country = {
    tag = POR

ai = "kaiserreich\Portugal.ai"
    policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 3
        political_left = 2
        free_market = 5
        freedom = 6
        professional_army = 6
        defense_lobby = 7
        interventionism = 8
    }

headofstate = { type = 9 id = 9001 }
headofgovernment = { type = 9 id = 9093 }

capital = 1560

ownedprovinces =      { 1372   }

controlledprovinces = { 1372  }

nationalprovinces =   { 1372 }

oil =	1000	
supplies = 5000

}

