
# list of spanish bases 

province = {
	id = 436 #tarragona
	anti_air = 2
	naval_base = {
		size = 6
		current_size = 6
	}
	air_base = {
		size = 6
		current_size = 6
	}
}

province = {
	id = 464 #valencia
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 2
		current_size = 2
	}
}

province = {
	id = 441 # coruña
	anti_air = 2
	naval_base = {
		size = 7
		current_size = 7
	}
	air_base = {
		size = 7
		current_size = 7
	}
}

province = {
	id = 475 #mallorca
	anti_air = 2
	naval_base = {
		size = 2
		current_size = 2
	}
	air_base = {
		size = 2
		current_size = 2
	}
}

province = {
	id = 474 #sevilla
	anti_air = 2
	naval_base = {
		size = 4
		current_size = 4
	}
	air_base = {
		size = 4
		current_size = 4
	}
}

province = {
	id = 460 #madrid
	anti_air = 3
	air_base = {
		size = 2
		current_size = 2
	}
}

province = { id = 444 #oviedo  
	     anti_air = 2 
	     air_base = { #a couple of small airfields were made during SCW, and later "scrapped"
		size = 1
		current_size = 1
		}
	} 
	
province = { id = 462 #almería
	     air_base = {
		size = 2
		current_size = 2
		}
	}	

province = { id = 436   #tarragona
	     anti_air = 2 
	      air_base = {
		size = 2
		current_size = 2
		}
		naval_base = {
		size = 4
		current_size = 4
		}
	     
	    } 
	    
	    
province = { id = 463 #murcia (cartagena)
	     anti_air = 2
	     naval_base = {
		size = 8
		current_size = 8
		}
	}
	
province = { id = 715 #ceuta
	     anti_air = 2 
	     air_base = {
		size = 1
		current_size = 1
		}
	} 	


province = { id =	473	naval_base = { size =	4	current_size = 	4	}  #huelva
				air_base = { size =	4	current_size = 	4	} }

province = { id =	440	naval_base = { size =	3	current_size = 	3	} #castellón
				air_base = { size =	3	current_size = 	3	} } 
				
province = { id =	441	naval_base = { size =	2	current_size = 	2	} 
				air_base = { size =	2	current_size = 	2	} } #menorca

province = { id =	475	naval_base = { size =	3	current_size = 	3	} 
				air_base = { size =	1	current_size = 	1	} } #ibiza



