province = { id = 436 points = 1 }
province = { id = 437 points = 1 }
province = { id = 438 points = 1 }
province = { id = 439 points = 1 }
province = { id = 440 points = 5 } #Barcelona
province = { id = 441 points = 1 }
province = { id = 442 points = 1 }
province = { id = 443 points = 2 } #Bilbao
province = { id = 444 points = 1 }
province = { id = 445 points = 1 }
province = { id = 446 points = 1 }
province = { id = 447 points = 1 }
province = { id = 448 points = 1 }
province = { id = 449 points = 1 }
province = { id = 450 points = 1 }
province = { id = 451 points = 5 } #Burgos
province = { id = 452 points = 1 }
province = { id = 453 points = 1 }
province = { id = 454 points = 1 }
province = { id = 455 points = 1 }
province = { id = 456 points = 1 }
province = { id = 457 points = 1 }
province = { id = 458 points = 1 }
province = { id = 459 points = 1 }
province = { id = 460 points = 10 } #Madrid
province = { id = 461 points = 1 }
province = { id = 462 points = 1 }
province = { id = 463 points = 1 }
province = { id = 464 points = 2 } #Valencia
province = { id = 465 points = 1 }
province = { id = 466 points = 1 }
province = { id = 467 points = 2 } #Cordoba
province = { id = 468 points = 1 }
province = { id = 469 points = 1 }
province = { id = 470 points = 1 }
province = { id = 471 points = 1 }
province = { id = 472 points = 1 }
province = { id = 473 points = 1 }
province = { id = 474 points = 5 } #Seville
province = { id = 475 points = 1 }
