  #.#.#   United Kingdom 

 province = { id = 23   #  Plymouth - West England - England
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 
 province = { id = 26   #  Dover - East England - England
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 3 
 } 
 
 province = { id = 27   #  Portsmouth - East England - England
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 2
 } 
 
 province = { id = 29   #  London - East England - England
   air_base = { size = 2 current_size = 2 } 
   ic = 3 
 } 

 #.#.#   France 
 
 province = { id = 37   #  Brest - Brittany - France
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 2
 } 
  
  province = { id = 38   #  Rennes - Brittany - France
	ic = -2
 }   
 
 province = { id = 41   #  Saint-Brieuc - Brittany - France
	ic = -2
 } 
 
 province = { id = 43   #  Cherbourg - Normandy - France
   naval_base = { size = 6 current_size = 6 } 
   #coastalfort = 2
 } 

 province = { id = 50   #  Amiens - ? - France
   air_base = { size = 1 current_size = 1 } 
 } 
 
 province = { id = 51   #  Dunkirk - Pas de Calais - France
   naval_base = { size = 3 current_size = 3 } 
   coastalfort = 4
 } 
 
 province = { id = 52   #  Lille - Pas de Calais - France
   air_base = { size = 2 current_size = 2 }
   landfort = 6   
   ic = -5
 } 
 
  province = { id = 54   #  Troyes - Paris - France
	ic = -2
 } 
 
 province = { id = 55   #  Paris - Paris - France
   air_base = { size = 4 current_size = 4 } 
   landfort = 4
   ic = -10
 }  
 
 province = { id = 56   #  Cheteau Thierry - Paris - France
   air_base = { size = 4 current_size = 4 } 
   landfort = 4
   ic = -7
 } 


 province = { id = 64   #  Le Creusot- ? - France
   air_base = { size = 1 current_size = 1 } 
 } 

 province = { id = 65   #  Bourges - ? - France
   air_base = { size = 1 current_size = 1 } 
 } 
 
 province = { id = 68   #  Bordeaux - Aquitaine - France
   naval_base = { size = 6 current_size = 6 } 
   ic = -4
 }  
 
 province = { id = 77   #  Toulouse - Pyreenes - France
   ic = -5
 }  
 
 province = { id = 83   #  Pau - ? - France
   air_base = { size = 1 current_size = 1 } 
 } 
 
 province = { id = 85   #  Lyon - ? - France
   air_base = { size = 1 current_size = 1 }
   landfort = 3
   ic = -5
 } 

 province = { id = 86   #  Toulon - Alpes_Provence - France
   naval_base = { size = 10 current_size = 10 }
 } 
 
 province = { id = 87   #  Nice - Alpes_Provence - France
   landfort = 5
   #coastalfort = 2
 } 
 
 province = { id = 90   #  Grenoble - Alpes_Provence - France
   landfort = 3 
 } 
 
 #province = { id = 96   #  Longwy - Bourgogne_Champagne - France
   #landfort = 4  } 

 province = { id = 97   #  Belfort - Bourgogne_Champagne - France
   ic = -1
   landfort = 8
   air_base = { size = 1 current_size = 1 }   } 

 province = { id = 99   #  Reims - Bourgogne_Champagne - France
   air_base = { size = 2 current_size = 2 } 
   #landfort = 4
 } 
 
 province = { id = 100   #  Verdun - Bourgogne_Champagne - France
   landfort = 8 
   air_base = { size = 1 current_size = 1 } 
 } 
 
  province = { id = 101   #  Laon - Bourgogne_Champagne - France
   landfort = 6
  }
 
  province = { id = 102   #  Sedan - Bourgogne_Champagne - France
   landfort = 5
  } 
  
   province = { id = 103   #  Hirson - Bourgogne_Champagne - France
   landfort = 5
  } 
  
  province = { id = 105   #  Colmar - Lorraine - France
   landfort = 8
  } 
 
 province = { id = 106   #  Nancy - ? - France
   landfort = 8
   air_base = { size = 2 current_size = 2 }   } 

 province = { id = 727   #  Algiers - Oran - Algeria
   naval_base = { size = 5 current_size = 5 } 
 } 
 
 province = { 
	id = 728 #Oran
	supplypool = 20
}
 
   #.#.#   Germany 

 
 province = { id = 104   #  Metz - Lorraine_Alsace - France
   landfort = 10 
 } 

 province = { id = 107   #  Strasbourg - Lorraine_Alsace - France
   landfort = 6  } 
   
 province = { id = 131   #  Cologne - Etappen-Flugzeug-Park 4
   air_base = { size = 1 current_size = 1 } 
   landfort = 6
 } 
