############################
#Victory points distribution
############################

#GERMAN OCCUPATION
province = { id = 49 points = 2 } #Calais
province = { id = 53 points = 1 } #Dieppe
province = { id = 55 points = 15 } #Paris
province = { id = 56 points = 1 } #Cheteau Thierry
province = { id = 99 points = 1 } #Reims
province = { id = 106 points = 2 } #Nancy
province = { id = 107 points = 2 } #Strassbourg
province = { id = 109 points = 1 } #Luxembourg
province = { id = 116 points = 5 } #Brussels
province = { id = 131 points = 5 } #Cologne

#FRANCE
province = { id = 37 points = 5 } #Brest 
province = { id = 38 points = 2 } #Rennes 
province = { id = 41 points = 2 } #Saint-Brieuc
province = { id = 43 points = 1 } #Cherbourg
province = { id = 44 points = 5 } #Caen
province = { id = 45 points = 1 } #Le Havre
province = { id = 46 points = 1 } #Bayeux
province = { id = 57 points = 2 } #Nantes
province = { id = 59 points = 1 } #Angers
province = { id = 62 points = 1 } #Poitiers
province = { id = 65 points = 1 } #Bourges
province = { id = 66 points = 5 } #Orleans
province = { id = 68 points = 5 } #Bordeaux
province = { id = 69 points = 2 } #La Rochelle
province = { id = 71 points = 2 } #Clermont Ferrand
province = { id = 73 points = 2 } #Limoges
province = { id = 74 points = 2 } #Vichy
province = { id = 77 points = 2 } #Toulouse
province = { id = 82 points = 1 } #Montpellier
province = { id = 85 points = 5 } #Lyon
province = { id = 87 points = 2 } #Nice
province = { id = 88 points = 5 } #Bourg-en-Bresse
province = { id = 89 points = 5 } #Marseille
province = { id = 90 points = 1 } #Grenoble
province = { id = 92 points = 2 } #Valence
province = { id = 94 points = 2 } #Corsica

province = { id = 727 points = 5 } #Algiers