############################
#Victory points distribution
############################

province = { id = 880 points = 20 } #Cape Town
province = { id = 883 points = 10 } #Luderitz
province = { id = 884 points = 10 } #Windhoek
province = { id = 882 points = 5 } #Swakopmund
province = { id = 867 points = 5 } #Salisbury
province = { id = 859 points = 5 } #Livingstone
province = { id = 863 points = 5 } #Lusaka
province = { id = 850 points = 20 } #Darussalam
province = { id = 852 points = 5 } #Zanzibar
province = { id = 841 points = 5 } #Mombasa
province = { id = 842 points = 5 } #Nairobi
province = { id = 844 points = 2 } #Kampala
province = { id = 897 points = 2 } #Kolwezi
province = { id = 898 points = 2 } #Elisabethville
province = { id = 899 points = 10} #Leopoldville
province = { id = 907 points = 2 } #Brazzaville
province = { id = 911 points = 2 } #Douala
province = { id = 929 points = 10 } #Lagos
province = { id = 930 points = 2 } #Port Harcourt
province = { id = 937 points = 2 } #Sokoto
province = { id = 956 points = 2 } #Accra
province = { id = 964 points = 5 } #Freetown
province = { id = 966 points = 2 } #Conarky
province = { id = 978 points = 2 } #Dakar
province = { id = 1053 points = 5 } #Aden
province = { id = 1517 points = 5 } #Bombay
province = { id = 1522 points = 2 } #Rajkot
province = { id = 873 points = 5 } #Pretoria
province = { id = 875 points = 5 } #Bloemfontein
province = { id = 876 points = 5 } #Johannesburg
