############################
#Victory points distribution
############################
province = { id = 1179 points = 5 } 
province = { id = 1184 points = 5 }
province = { id = 1191 points = 5 }
province = { id = 1541 points = 5 }
province = { id = 1542 points = 5 }
province = { id = 1221 points = 5 }
province = { id = 1228 points = 5 }
province = { id = 1232 points = 5 }
province = { id = 1547 points = 5 }
province = { id = 1551 points = 5 }
province = { id = 1162 points = 10 }
province = { id = 1247 points = 5 }
province = { id = 1328 points = 5 }
province = { id = 1185 points = 5 }
province = { id = 1190 points = 5 } 
province = { id = 1194 points = 5 } 
province = { id = 1199 points = 5 } 
province = { id = 1208 points = 5 } 
province = { id = 1124 points = 5 } 
province = { id = 1186 points = 5 } 
province = { id = 1188 points = 5 } 
province = { id = 1187 points = 5 } 
province = { id = 1219 points = 5 } 
province = { id = 1218 points = 5 } 
province = { id = 1552 points = 10 } 