### AZB
province = { id = 713 ic = 3 landfort = 3 anti_air = 1 #Baku (previously ic = 7)
	air_base = { size = 4 current_size = 4 } }


### BLR
province = { id = 247 landfort = 2 } #Brest-Litovsk
province = { id = 248 manpower = 1 } #Pinsk
province = { id = 251 ic = 1 manpower = 1 } #Nowogrodek
province = { id = 256 ic = 1 } #Vilejka
province = { id = 257 landfort = 1 } #Glebokie
province = { id = 591 landfort = 2 manpower = 1 } #Orsha
province = { id = 592 landfort = 1 manpower = 1 } #Borisov
province = { id = 594 ic = 1 landfort = 1 manpower = 1 } #Bobruisk
province = { id = 598 landfort = 1 } #Rechytsa
province = { id = 599 ic = 3 anti_air = 3 #Minsk
	air_base = { size = 8 current_size = 8 } }


#Kaiserreich
province = { id = 163 anti_air = 2 #Berlin
	air_base = { size = 10 current_size = 10 } }	
province = { id = 164 ic = 4 } #Oppeln
province = { id = 167 ic = 6 landfort = 1 anti_air = 3 #Breslau
	air_base = { size = 10 current_size = 10 } }
province = { id = 181 ic = 2 anti_air = 2 #Gdynia
	naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 183 supplypool = 100 } #Elbing

province = { 
id = 184 
anti_air = 4 #Koeningsberg
naval_base = { size = 10 current_size = 10 } 
air_base = { size = 10 current_size = 10 } 
}

province = { 
id = 221 #Katowice 
ic = 2 
} 

province = { 
id = 222  #Torun
landfort = 3 
anti_air = 3 
} 

province = { 
id = 224  #Poznan
landfort = 3 
anti_air = 4 
} 

province = { 
id = 261 #Klaipeda
anti_air = 1 
naval_base = { size = 2 current_size = 2 } 
air_base = { size = 1 current_size = 1 } 
}

### LAT

#Estonia
province = { id = 272 ic = 1 } #Tartu
province = { id = 273 landfort = 1 } #Voru
province = { id = 274 ic = 1 landfort = 1 } #Narva
province = { id = 275 infra = { size = 0.20 current_size = 0.20 } } #Kuressaare
province = { id = 270 landfort = 1 #Tallinn
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }

#Latvia
province = { id = 264 landfort = 1 anti_air = 1 #Riga
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id = 266 ic = 1 landfort = 2 } #Daugavpils
province = { id = 268 ic = 2 landfort = 2 #Liepaja
	naval_base = { size = 7 current_size = 7 } }

### LIT
province = { id = 252 ic = 2 } #Suwalki
province = { id = 255 ic = 1 anti_air = 2 } #Grodno
province = { id = 258 ic = 4 anti_air = 5 #Wilno
	air_base = { size = 3 current_size = 3 } }
province = { id = 262 anti_air = 1 #Kaunas
	air_base = { size = 1 current_size = 1 } }

### POL
province = { id = 223 anti_air = 4 #Lodz
	air_base = { size = 4 current_size = 4 } }
province = { id = 232 landfort = 2 anti_air = 4 #Warsaw
	air_base = { size = 6 current_size = 6 } }

### RUS

#European Russia
province = { id = 535 anti_air = 4 #Murmansk
	naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }
province = { id = 539 ic = 1 } #Petrozavodsk
province = { id = 542 anti_air = 2 #Archangelsk
	naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } }
province = { id = 548 ic = -1 } #Volodga
province = { id = 553 landfort = 2 coastalfort = 5 anti_air = 3 #Leningrad
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 558 ic = 1 } #Rzhev
province = { id = 560 anti_air = 1 ic = 1 } #Novgorod
province = { id = 566 air_base = { size = 6 current_size = 6 } } #Pskov
province = { id = 569 ic = -8 } #Tver
province = { id = 572 landfort = 1 anti_air = 2 #Moscow
	air_base = { size = 10 current_size = 10 } }
province = { id = 576 anti_air = 1 } #Kaluga
province = { id = 581 air_base = { size = 5 current_size = 5 } } #Oryol
province = { id = 588 anti_air = 2 ic = 2 } #Bryansk
province = { id = 589 anti_air = 3 } #Smolensk
province = { id = 590 anti_air = 2 } #Vitebsk
province = { id = 600 anti_air = 1 #Mogilev
	air_base = { size = 5 current_size = 5 } }
province = { id = 663 air_base = { size = 2 current_size = 2 } } #Tsaritsyn

### UKR
province = { id = 245 landfort = 2 } #Lutsk
province = { id = 606 landfort = 1 infra = { size = 0.30 current_size = 0.30 } } #Sumy
province = { id = 605 landfort = 1 } #Konotop
province = { id = 607 landfort = 1 air_base = { size = 2 current_size = 2 } #Chernigov
	infra = { size = 0.40 current_size = 0.40 } }
province = { id = 612 ic = -1 } #Vinnitsa
province = { id = 618 ic = -2 infra = { size = 0.30 current_size = 0.30 } } #Kamenets-Podolsky
province = { id = 619 infra = { size = 0.20 current_size = 0.20 } } #Mogilev-Podolsky
province = { id = 617 anti_air = 3 #Kiev
air_base = { size = 8 current_size = 8 } }
province = { id = 622 ic = 2 naval_base = { size = 5 current_size = 5 } } #Nikolayev
province = { id = 625 infra = { size = 0.30 current_size = 0.30 } } #Ochakov
province = { id = 626 anti_air = 3 #Odessa
naval_base = { size = 3 current_size = 3 } }
province = { id = 627 infra = { size = 0.40 current_size = 0.40 } } #Krivoy Rog
province = { id = 628 infra = { size = 0.40 current_size = 0.40 } } #Yelisavetgrad
province = { id = 632 anti_air = 2 #Dnepropetrovsk
air_base = { size = 2 current_size = 2 } }
province = { id = 634 landfort = 1 } #Voroshilovgrad
province = { id = 635 landfort = 1 anti_air = 2 } #Stalino
province = { id = 636 ic = 2 landfort = 2 anti_air = 5 } #Kharkov
province = { id = 641 ic = 1 landfort = 3 coastalfort = 5 anti_air = 5 #Sevastopol
naval_base = { size = 10 current_size = 10 } air_base = { size = 6 current_size = 6 } }
province = { id = 644 anti_air = 2 #Rostov
naval_base = { size = 4 current_size = 4 } air_base = { size = 6 current_size = 6 } }
province = { id = 654 anti_air = 1 } #Voronezh

#More Supply Pools
 province = {  id = 371  oilpool = 100 supplypool = 500 }
 province = {  id = 1782  oilpool = 100 supplypool = 500 }
 province = {  id = 1771  oilpool = 100 supplypool = 500 }
 province = {  id = 1758  oilpool = 100 supplypool = 500 }
 province = {  id = 2000  oilpool = 100 supplypool = 500 }
 province = {  id = 1721  oilpool = 100 supplypool = 500 }
 province = {  id = 1607  oilpool = 100 supplypool = 500 }
 province = {  id = 991  oilpool = 100 supplypool = 500 }
 province = {  id = 988  oilpool = 100 supplypool = 500 }
 province = {  id = 475  oilpool = 100 supplypool = 500 }
 province = {  id = 715  oilpool = 100 supplypool = 500 }
 province = {  id = 892  oilpool = 100 supplypool = 500 }
 province = {  id = 963  oilpool = 100 supplypool = 500 }
 province = {  id = 855  oilpool = 100 supplypool = 500 }
 province = {  id = 1661  oilpool = 100 supplypool = 500 }
 province = {  id = 1662  oilpool = 100 supplypool = 500 }
 province = {  id = 1672  oilpool = 100 supplypool = 500 }
 province = {  id = 1562  oilpool = 100 supplypool = 500 }
 province = {  id = 1358  oilpool = 100 supplypool = 500 }
 province = {  id = 1346  oilpool = 100 supplypool = 500 }
 province = {  id = 381  oilpool = 100 supplypool = 500 }
 province = {  id = 379  oilpool = 100 supplypool = 500 }
 province = {  id = 388  oilpool = 100 supplypool = 500 }
 province = {  id = 718  oilpool = 100 supplypool = 500 }
 province = {  id = 833  oilpool = 100 supplypool = 500 }
 province = {  id = 900  oilpool = 100 supplypool = 500 }
 province = {  id = 1328  oilpool = 100 supplypool = 500 }