# Russia - initial VP = 200
province = { id = 626 points = 5 } # Odesa
province = { id = 617 points = 10 } # Kyiv
province = { id = 599 points = 5 } # Minsk
province = { id = 264 points = 5 } # Riga
province = { id = 270 points = 5 } # Tallin
province = { id = 258 points = 5 } # Vilnius
province = { id = 638 points = 10 } # Sevastopol
province = { id = 589 points = 5 } # Smolensk
province = { id = 553 points = 50 } # Petrograd
province = { id = 535 points = 10 } # Murmansk
province = { id = 636 points = 5 } # Kharkov
province = { id = 713 points = 5 } # Baku
province = { id = 644 points = 5 } # Rostov-Don
province = { id = 584 points = 5 } #Tula
province = { id = 572 points = 50 } # Moscow
province = { id = 542 points = 10 } # Archangielsk
province = { id = 663 points = 10 } # Tsaritin
province = { id = 668 points = 15 } # Wrangelsk


# Axis - initial VP = 50 (to motivate them to attack!)
province = { id = 184 points = 2 } # Koeningsberg
province = { id = 167 points = 5 } # Breslau
province = { id = 163 points = 20 } # Berlin
province = { id = 232 points = 2 } # Warsaw
province = { id = 181 points = 2 } # Danzig

province = { id = 525 points = 2 } # Helsinki
province = { id = 704 points = 2 } # Makhachkala
province = { id = 709 points = 3 } # Tbilisi
province = { id = 713 points = 2 } # Baku