####
#Organised by RainbowFire for DH Kaiserreich
####

### AFG
province = { id = 2171 air_base = { size = 1 current_size = 1 } } #Kabul

### ALB
province = { id = 359 anti_air = 1
naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } } #Tirana

### ARG

#Argentina
province = { id = 2048 anti_air = 2 #Bahia Blanca
naval_base = { size = 8 current_size = 8 } air_base = { size = 3 current_size = 3 } } 
province = { id = 2050 anti_air = 5 #Buenos aires
naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } }
province = { id = 2054 anti_air = 1 } #Cordoba

#Falklands
province = { id = 2045 anti_air = 2 oilpool = 100 supplypool = 200 #Falkland Islands
naval_base = { size = 5 current_size = 5 } air_base = { size = 2 current_size = 2 } }

#Paraguay
province = { id = 2046 anti_air = 1 #Villa Hayes
air_base = { size = 4 current_size = 4 } }
province = { id = 2047 infra = { size = 0.40 current_size = 0.40 } } #Nuestra Senora de la Asuncion

#Uruguay
province = { id = 2052 anti_air = 1 #Montevideo
naval_base = { size = 6 current_size = 6 } air_base = { size = 2 current_size = 2 } }

### ARM
province = { id = 711 landfort = 3 anti_air = 1 #Yerevan (Mar2020 increased infra)
	infra = { size = 0.30 current_size = 0.30 } }

### AST

#Australia
province = { id = 1690 anti_air = 5 #Perth
naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } }
province = { id = 1697 anti_air = 5 #Darwin
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1696 air_base = { size = 8 current_size = 8 } } #Katherine
province = { id = 1704 coastalfort = 1 anti_air = 1 #Brisbane
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1705 manpower = 2 anti_air = 7 #Sydney
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1707 anti_air = 2 #Canberra
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1708 anti_air = 3 coastalfort = 1 } #Melbourne
province = { id = 1712 anti_air = 2 } #Adelaide
province = { id = 1715 anti_air = 1 } #Port Augusta

#New Zealand
province = { id = 1719 infra = { size = 0.30 current_size = 0.30 } } #Hamilton
province = { id = 1720 infra = { size = 0.40 current_size = 0.40 } } #Auckland
province = { id = 1721 infra = { size = 0.40 current_size = 0.40 } anti_air = 2 #Wellington
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id = 1722 infra = { size = 0.30 current_size = 0.30 } anti_air = 3 #Christchurch
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }

#Papua New Guinea
province = { id = 1602 anti_air = 1 oilpool = 100 supplypool = 500 #Lae
naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } }
province = { id = 1607 anti_air = 1 #Port Moresby
naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }

### AUS

#Austria
province = { id = 187 air_base = { size = 4 current_size = 4 } } #Linz
province = { id = 189 anti_air = 2 #Innsbruck
	air_base = { size = 4 current_size = 4 } }
province = { id = 190 anti_air = 1 energy = 4 } #Graz
province = { id = 191 air_base = { size = 6 current_size = 6 } } #Klagenfurt
province = { id = 195 anti_air = 5 manpower = 3 #Vienna
	air_base = { size = 10 current_size = 10 } }

#Montenegro
province = { id = 332 #Cetinje
	naval_base = { size = 3 current_size = 3 } infra = { size = 0.20 current_size = 0.20 } }

#Slovene/Italian lands
province = { id = 400 anti_air = 2 #Venezia
	naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 404 anti_air = 1 #Trieste
	naval_base = { size = 5 current_size = 5 } }
province = { id = 406 manpower = 1 anti_air = 1 #Pola
	naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }

### AZB
province = { id = 713 landfort = 3 anti_air = 1 #Baku 
	air_base = { size = 4 current_size = 4 } }

### BEL
province = { id = 112 landfort = 2 anti_air = 1 } #Mons
province = { id = 114 landfort = 2 anti_air = 1 #Burges
	air_base = { size = 5 current_size = 5 } }
 province = { id = 114 manpower = 2 #Bruges
	air_base = { size = 6 current_size = 6 } naval_base = { size = 3 current_size = 3 } }
province = { id = 115 #Antwerpen
	naval_base = { size = 5 current_size = 5 } }
province = { id = 116 landfort = 2 anti_air = 1 manpower = 3 #Brussels
	air_base = { size = 6 current_size = 6 } }

### BLR
province = { id = 247 landfort = 2 } #Brest-Litovsk
province = { id = 248 manpower = 1 } #Pinsk
province = { id = 251 manpower = 1 } #Nowogrodek
province = { id = 257 landfort = 1 } #Glebokie
province = { id = 591 landfort = 2 manpower = 1 } #Orsha
province = { id = 592 landfort = 1 manpower = 1 } #Borisov
province = { id = 594 landfort = 1 manpower = 1 } #Bobruisk
province = { id = 598 landfort = 1 } #Rechytsa
province = { id = 599 anti_air = 3 #Minsk
	air_base = { size = 8 current_size = 8 } }

### BOL
province = { id = 2020 infra = { size = 0.40 current_size = 0.40 } #Nuestra Senora de La Paz
	air_base = { size = 4 current_size = 4 } anti_air = 1 }
province = { id = 2021 infra = { size = 0.40 current_size = 0.40 } } #Sucre

### BOS
province = { id = 353 infra = { size = 0.30 current_size = 0.30 } } #Banja Luka
province = { id = 355 anti_air = 2 #Sarajevo
	air_base = { size = 5 current_size = 5 } infra = { size = 0.30 current_size = 0.30 } }

### BRA
province = { id = 2058 anti_air = 2 #Porto Alegre
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 2059 anti_air = 1 #Sao Paulo
	naval_base = { size = 6 current_size = 6 } air_base = { size = 4 current_size = 4 } }
province = { id = 2067 anti_air = 2 #Belo Horizonte
	air_base = { size = 3 current_size = 3 } }
province = { id = 2074 anti_air = 1 } #Vitoria
province = { id = 2075 anti_air = 1 #Rio de Janeiro
	naval_base = { size = 6 current_size = 6 } air_base = { size = 4 current_size = 4 } }

### BUL
province = { id = 307 infra = { size = 0.20 current_size = 0.20 } } #Dobrich
province = { id = 317 infra = { size = 0.30 current_size = 0.30 } } #Vidin
province = { id = 318 infra = { size = 0.30 current_size = 0.30 } } #Ruse
province = { id = 319 infra = { size = 0.20 current_size = 0.20 } } #Haskovo
province = { id = 321 infra = { size = 0.40 current_size = 0.40 } #Sofia
	anti_air = 2 air_base = { size = 6 current_size = 6 } }
province = { id = 322 infra = { size = 0.20 current_size = 0.20 } } #Gabrovo
province = { id = 323 infra = { size = 0.30 current_size = 0.30 } } #Pleven
province = { id = 324 infra = { size = 0.30 current_size = 0.30 } } #Plovdiv
province = { id = 325 infra = { size = 0.30 current_size = 0.30 } } #Burgas
province = { id = 326 infra = { size = 0.30 current_size = 0.30 } anti_air = 1 #Varna
	naval_base = { size = 4 current_size = 4 } air_base = { size = 3 current_size = 3 } }
province = { id = 328 infra = { size = 0.30 current_size = 0.30 } } #Kumanovo
province = { id = 331 infra = { size = 0.30 current_size = 0.30 } } #Pirot
province = { id = 363 anti_air = 1 infra = { size = 0.20 current_size = 0.20 } #Xanthi
	naval_base = { size = 2 current_size = 2 } air_base = { size = 3 current_size = 3 } }
province = { id = 364 infra = { size = 0.20 current_size = 0.20 } } #Kavala
province = { id = 365 naval_base = { size = 6 current_size = 6 } } #Thessaloniki
province = { id = 366 infra = { size = 0.30 current_size = 0.30 } } #Kozani
province = { id = 370 infra = { size = 0.20 current_size = 0.20 } } #Alexandroupoli

### BUR
province = { id = 1410 anti_air = 1 #Mandalay
	air_base = { size = 4 current_size = 4 } }
province = { id = 1415 anti_air = 2 #Rangoon
	naval_base = { size = 6 current_size = 6 } air_base = { size = 4 current_size = 4 } }

### CAN
province = { id = 2089 manpower = 1 anti_air = 1 #Vancouver
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 2090 infra = { size = 0.50 current_size = 0.50 } #Victoria
	naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }
province = { id = 2101 manpower = 1 } #Regina
province = { id = 2102 infra = { size = 0.20 current_size = 0.20 } } #Prince Albert
province = { id = 2103 manpower = 1 air_base = { size = 4 current_size = 4 } } #Edmonton
province = { id = 2104 oil = 5 } #Calgary
province = { id = 2105 infra = { size = 0.20 current_size = 0.20 } } #Grande Prairie
province = { id = 2106 manpower = 1 anti_air = 1 #Winnipeg
	air_base = { size = 4 current_size = 4 } }
province = { id = 2108 manpower = 1 anti_air = 3 #Ottawa
	air_base = { size = 4 current_size = 4 } }
province = { id = 2109 manpower = 1 infra = { size = 0.70 current_size = 0.70 } } #Kingston
province = { id = 2111 manpower = 3 anti_air = 3 #Toronto
	air_base = { size = 10 current_size = 10 } infra = { size = 0.80 current_size = 0.80 } }
province = { id = 2112 infra = { size = 0.20 current_size = 0.20 } } #Thunder Bay
province = { id = 2113 manpower = 1 infra = { size = 0.60 current_size = 0.60 } } #Windsor
province = { id = 2117 manpower = 1 anti_air = 4 #Québec
	naval_base = { size = 10 current_size = 10 } air_base = { size = 6 current_size = 6 } }
province = { id = 2118 manpower = 1 infra = { size = 0.60 current_size = 0.60 } } #Sherbrooke
province = { id = 2119 manpower = 3 anti_air = 2 #Montreal
	air_base = { size = 4 current_size = 4 } }
province = { id = 2120 infra = { size = 0.20 current_size = 0.20 } } #Sept-Iles
province = { id = 2121 infra = { size = 0.30 current_size = 0.30 } } #Chicoutimi
province = { id = 2126 infra = { size = 0.50 current_size = 0.50 } } #Riviere-du-Loup
province = { id = 2128 infra = { size = 0.50 current_size = 0.50 } } #Fredericton
province = { id = 2130 manpower = 1 #Saint John
	infra = { size = 0.50 current_size = 0.50 } }
province = { id = 2131 infra = { size = 0.50 current_size = 0.50 } } #Moncton
province = { id = 2132 manpower = 1 coastalfort = 2 anti_air = 3 #Halifax
	naval_base = { size = 6 current_size = 6 } air_base = { size = 4 current_size = 4 } }
province = { id = 2134 anti_air = 2 infra = { size = 0.50 current_size = 0.50 } #Glace Bay
	naval_base = { size = 4 current_size = 4 } air_base = { size = 6 current_size = 6 } energy = 2 }
province = { id = 2136 infra = { size = 0.20 current_size = 0.20 } } #Goose Bay
province = { id = 2137 anti_air = 2 #St. Johns
	naval_base = { size = 10 current_size = 10 } air_base = { size = 6 current_size = 6 } }
province = { id = 2138 infra = { size = 0.10 current_size = 0.10 } } #Nain

### CGX
province = { id = 1351 anti_air = 1 #Shangrao
 	air_base = { size = 2 current_size = 2 } }
province = { id = 1369 naval_base = { size = 4 current_size = 4 } air_base = { size = 5 current_size = 5 } } #Guangzhou
province = { id = 1376 infra = { size = 0.20 current_size = 0.20 } } #Debao
province = { id = 1378 anti_air = 2 #Guilin
	air_base = { size = 4 current_size = 4 } }

### CHC
province = { id = 1253 infra = { size = 0.40 current_size = 0.40 } } #Linfen
province = { id = 1255 landfort = 3 } #Pingliang
province = { id = 1256 landfort = 1 } #Baoji
province = { id = 1257 landfort = 1 } #Tongguan
province = { id = 1258 landfort = 1 } #Xi'an
province = { id = 1259 landfort = 4 infra = { size = 0.20 current_size = 0.20 } } #Yan'an
province = { id = 1260 landfort = 1 } #Yulin
province = { id = 1263 landfort = 1 } #Tianshoui
province = { id = 1269 landfort = 2 } #Uqai
province = { id = 1271 landfort = 1 } #Wuzhong

### CHL
province = { id = 2023 anti_air = 2 #Santiago de Chile
	naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }

### COL
province = { id = 1986 anti_air = 1
	naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } }
province = { id = 1990 anti_air = 1 } #Cartagena
province = { id = 1991 anti_air = 2 } #Bogota

### CON
province = { id = 842 anti_air = 1 #Mombasa
air_base = { size = 4 current_size = 4 } }
province = { id = 850 anti_air = 4 #Dar es Salaam
naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 882 anti_air = 2 #Swakopmund
naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }
province = { id = 894 anti_air = 2 #Matadi
naval_base = { size = 3 current_size = 3 } air_base = { size = 2 current_size = 2 } }
province = { id = 929 anti_air = 1 #Lagos
air_base = { size = 4 current_size = 4 } }
province = { id = 956 anti_air = 2 #Accra
naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }
province = { id = 863 air_base = { size = 2 current_size = 2 } } #Lusaka


### CRO
province = { id = 337 infra = { size = 0.30 current_size = 0.30 } } #Ruma
province = { id = 343 anti_air = 2 #Dubrovnik
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 344 anti_air = 1 #Osijek
	infra = { size = 0.40 current_size = 0.40 } }
province = { id = 345 infra = { size = 0.40 current_size = 0.40 } } #Bjelovar
province = { id = 347 naval_base = { size = 5 current_size = 5 } #Karlovac
	 air_base = { size = 5 current_size = 5 } }
province = { id = 350 anti_air = 2 #Split
	air_base = { size = 2 current_size = 2 } }
province = { id = 352 anti_air = 2 } #Zagreb

### CSX
province = { id = 1247 anti_air = 4 #Beijing
	air_base = { size = 6 current_size = 6 } }
province = { id = 1321 infra = { size = 0.40 current_size = 0.40 } } #Xinxiang
province = { id = 1327 infra = { size = 0.30 current_size = 0.30 } } #Heze
province = { id = 1330 anti_air = 2 #Qing Jinan
	air_base = { size = 4 current_size = 4 } }
province = { id = 1331 infra = { size = 0.20 current_size = 0.20 } } #Yantai
province = { id = 1332 infra = { size = 0.20 current_size = 0.20 } } #Zaozhuang
province = { id = 1334 anti_air = 2 #Nantong
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }

### CUB
province = { id = 1775 infra = { size = 0.30 current_size = 0.30 } } #Camaguey
province = { id = 1776 anti_air = 1 infra = { size = 0.40 current_size = 0.40 } #Havana
	naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } }
province = { id = 1777 infra = { size = 0.40 current_size = 0.40 } } #Santiago de Cuba
province = { id = 1779 infra = { size = 0.40 current_size = 0.40 } } #Santa Clara

### CXB
province = { id = 1265 infra = { size = 0.20 current_size = 0.20 } } #Zhangye
province = { id = 1266 infra = { size = 0.20 current_size = 0.20 } } #Yumen
province = { id = 1277 infra = { size = 0.20 current_size = 0.20 } } #Qumul
province = { id = 1281  infra = { size = 0.20 current_size = 0.20 } } #Urumqi
province = { id = 1284 air_base = { size = 6 current_size = 6 } } #Xining

### CZE
province = { id = 196 anti_air = 2 #Brno
	air_base = { size = 3 current_size = 3 } manpower = 2 }
province = { id = 198 air_base = { size = 6 current_size = 6 } } #Hradec Kralove
province = { id = 199 anti_air = 2 #Plzen
	air_base = { size = 7 current_size = 7 } manpower = 2 }
province = { id = 201 manpower = 2 } #Ostrava
province = { id = 205 air_base = { size = 4 current_size = 4 } } #Karlovy Vary
province = { id = 207 anti_air = 3 #Prague
	air_base = { size = 6 current_size = 6 } manpower = 2 }

### DEN
province = { id = 219 manpower = 1 } #Odense

#Iceland
province = { id = 1 anti_air = 1 #Reykjavik
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }

#Denmark
province = { id = 217 anti_air = 1 #Aalborg
	naval_base = { size = 1 current_size = 1 } air_base = { size = 4 current_size = 4 } }
province = { id = 220 naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } } #Aarhus
province = { id = 294 anti_air = 2 #Copenhagen
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }

### DOM
province = { id = 1780 naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } } #Ciudad Trujillo

### EAF
province = { id = 1338 anti_air = 2 #Shanghai
	naval_base = { size = 10 current_size = 10 } air_base = { size = 6 current_size = 6 } }
province = { id = 1346 naval_base = { size = 8 current_size = 8 } } #Ningbo
province = { id = 1358 #Fuzhou naval_base = { size = 3 current_size = 3 } 
	air_base = { size = 3 current_size = 3 } }
province = { id = 1371 landfort = 1 coastalfort = 1 anti_air = 4 oilpool = 100 supplypool = 500 #Hong Kong
	naval_base = { size = 8 current_size = 8 } air_base = { size = 4 current_size = 4 } }
 
### ECU
province = { id = 2040 naval_base = { size = 3 current_size = 3 } } #Santiago de Guayaquil
province = { id = 2042 anti_air = 2 #San Francisco de Quito 
	air_base = { size = 1 current_size = 1 } }

### EGY

#Egypt
province = { id = 787 anti_air = 2 #Cario (Mar2020 increased airbase)
	air_base = { size = 7 current_size = 7 } }
province = { id = 789 anti_air = 3 #Alexandria 
	naval_base = { size = 8 current_size = 8 } air_base = { size = 7 current_size = 7 } }
#province = { id = 790 air_base = { size = 4 current_size = 4 } } #Tanta
#province = { id = 1007 anti_air = 2 #Suez
#	naval_base = { size = 4 current_size = 4 } }

#Sudan
province = { id = 810 anti_air = 1 #Khartoum
	air_base = { size = 4 current_size = 4 } }
province = { id = 813 naval_base = { size = 3 current_size = 3 } } #Port Sudan 

### ENG
province = { id = 5 anti_air = 4 #Scapa Flow
	naval_base = { size = 10 current_size = 10 } air_base = { size = 4 current_size = 4 } }
province = { id = 11 anti_air = 2 #Glasgow
	air_base = { size = 4 current_size = 4 } }
province = { id = 12 anti_air = 2 #Edinburgh
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 13 naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } } #Sunderland
province = { id = 15 anti_air = 2 #Hull
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 16 manpower = 2 } #Lincoln
province = { id = 17 anti_air = 3 #Manchester
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 18 manpower = 3 } #Sheffield
province = { id = 19 anti_air = 4 #Bristol
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 21 manpower = 1 anti_air = 2 #Caernarfon
	air_base = { size = 4 current_size = 4 } }
province = { id = 22 naval_base = { size = 3 current_size = 3 } } #Cardiff
province = { id = 23 anti_air = 6 #Plymouth
	naval_base = { size = 5 current_size = 5 } air_base = { size = 4 current_size = 4 } }
province = { id = 24 anti_air = 2 manpower = 5 } #Birmingham
province = { id = 25 anti_air = 4 #Norwich
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 26 coastalfort = 3 anti_air = 5 #Dover
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 27 anti_air = 6 #Portsmouth
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 28 manpower = 2 } #Oxford
province = { id = 29 anti_air = 3 #London
	air_base = { size = 10 current_size = 10 } }

### ETH
province = { id = 815 anti_air = 1 infra = { size = 0.20 current_size = 0.20 } #Massawa
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 817 infra = { size = 0.20 current_size = 0.20 } } #Asmara
province = { id = 825 anti_air = 2 #Addis Abeba
	air_base = { size = 6 current_size = 6 } }
province = { id = 836 naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } } #Mogadishu

### FIN
province = { id = 517 #Petsamo
	naval_base = { size = 4 current_size = 4 } air_base = { size = 3 current_size = 3 } }
#province = { id = 523 energy = 2 } #Kajaani
province = { id = 520 #Oulu
	air_base = { size = 4 current_size = 4 } }
province = { id = 524 coastalfort = 1 anti_air = 2 #Turku
	naval_base = { size = 5 current_size = 5 } air_base = { size = 2 current_size = 2 } }
province = { id = 525 coastalfort = 1 anti_air = 3 #Helsinki
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id = 527 anti_air = 2 #Tampere
	air_base = { size = 2 current_size = 2 } }
province = { id = 531 landfort = 2 anti_air = 3 manpower = 1 #Viipuri
	naval_base = { size = 1 current_size = 1 } air_base = { size = 4 current_size = 4 } }
province = { id = 532 landfort = 2 } #Sortavala

### FRA
province = { id = 37 anti_air = 2 #Brest
	naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 39 air_base = { size = 10 current_size = 10 } } #Lorient
province = { id = 40 manpower = 1 } #Saint-Nazaire
province = { id = 43 anti_air = 3 #Cherbourg
	naval_base = { size = 6 current_size = 6 } air_base = { size = 5 current_size = 5 } }
province = { id = 44 anti_air = 1 } #Caen
province = { id = 45 naval_base = { size = 5 current_size = 5 } #Le Havre
	air_base = { size = 5 current_size = 5 } }
province = { id = 49 naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } } #Calais
province = { id = 50 manpower = 2 } #Amiens
province = { id = 51 landfort = 4 anti_air = 2 manpower = 1 } #Dunkirk
province = { id = 52 landfort = 4 anti_air = 3 #Lille
	air_base = { size = 10 current_size = 10 } }
province = { id = 55 anti_air = 8 #Paris
	air_base = { size = 10 current_size = 10 } }
province = { id = 57 anti_air = 2 } #Nantes
province = { id = 63 air_base = { size = 10 current_size = 10 } } #Auxerre
province = { id = 67 landfort = 2 } #Mont-de-Marsan
province = { id = 68 anti_air = 4 manpower = 2 #Bordeaux
	naval_base = { size = 10 current_size = 10 } air_base = { size = 4 current_size = 4 } }
province = { id = 74 anti_air = 1 } #Vichy
province = { id = 77 air_base = { size = 10 current_size = 10 } } #Toulouse
province = { id = 80 landfort = 2 anti_air = 1 #Perpignan
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 83 landfort = 2 } #Pau
province = { id = 86 landfort = 3 anti_air = 3 #Toulon
	naval_base = { size = 10 current_size = 10 } air_base = { size = 2 current_size = 2 } }
province = { id = 88 landfort = 3 anti_air = 1 } #Bourg-en-Bresse
province = { id = 89 anti_air = 5 manpower = 2 #Marseille
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 90 landfort = 3 anti_air = 1 manpower = 1 } #Grenoble
province = { id = 92 landfort = 3 anti_air = 1 } #Valence
province = { id = 95 landfort = 4 anti_air = 3 } #Chaumont
province = { id = 97 landfort = 3 anti_air = 1 } #Belfort
province = { id = 98 landfort = 3 anti_air = 1 } #Pontarlier
province = { id = 100 landfort = 6 anti_air = 2 } #Verdun
province = { id = 102 landfort = 4 anti_air = 2 } #Sedan
province = { id = 103 landfort = 4 anti_air = 2 } #Hirson
province = { id = 104 anti_air = 3 #Metz
	air_base = { size = 10 current_size = 10 } }

### GUA
province = { id = 2086 naval_base = { size = 2 current_size = 2 } } #Belize City

### GEO
province = { id = 708 anti_air = 2 #Kutaisi
	naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }
province = { id = 709 landfort = 3 anti_air = 1 } #Tbilisi

### GER

#African colonies
province = { id = 718 anti_air = 3 #Casablanca
naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 900 anti_air = 2 naval_base = { size = 7 current_size = 7 } #Suez (Mar2020 - increased navalbase, added anti_air)
	air_base = { size = 3 current_size = 3 } }
province = { id = 964 anti_air = 2 #Freetown
naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }
province = { id = 833 anti_air = 2 #Djibouti
naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }

#Arabia/Indian Ocean colonies
province = { id = 996 naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 } } #Saint Denis de la Reunion
province = { id = 1001 naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } } #Tananarive
province = { id = 1053 coastalfort = 1 anti_air = 4 #Aden
naval_base = { size = 6 current_size = 6 } air_base = { size = 4 current_size = 4 } }
province = { id = 1511 coastalfort = 1 anti_air = 2 oilpool = 1000 supplypool = 2000 #Colombo
naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 1611 naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } } #Male

#Asian colonies
province = { id = 1241 naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } } #Tianjin
province = { id = 1328 landfort = 1 coastalfort = 1 anti_air = 2 #Qingdao
	naval_base = { size = 10 current_size = 10 } air_base = { size = 7 current_size = 7 } }
province = { id = 1365 #Haikou
	naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 } }
province = { id = 1367 coastalfort = 1 anti_air = 2 #Zhanjiang
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 1395 anti_air = 2 infra = { size = 0.40 current_size = 0.40 } oilpool = 100 supplypool = 500 #Hanoi
	naval_base = { size = 1 current_size = 1 } air_base = { size = 4 current_size = 4 } }
province = { id = 1392 anti_air = 2 #Haiphong
	naval_base = { size = 4 current_size = 4 } }
province = { id = 1397 naval_base = { size = 2 current_size = 2 } } #Da Nang
province = { id = 1399 anti_air = 3 oilpool = 100 supplypool = 500 #Saigon
	naval_base = { size = 6 current_size = 6 } air_base = { size = 10 current_size = 10 } }
province = { id = 1432 landfort = 3 coastalfort = 4 anti_air = 4 oilpool = 2000 supplypool = 10000 #Singapore
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1438 anti_air = 1 #Kuala Lumpur
	naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } }
province = { id = 1624 naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } } #Kuching

#Kaiserreich
province = { id = 127 anti_air = 2 } #Saarbrücken
province = { id = 129 anti_air = 2 } #Köln
province = { id = 130 anti_air = 2 } #Mannheim
province = { id = 134 anti_air = 2 #Stuttgart
	air_base = { size = 4 current_size = 4 } }
province = { id = 137 anti_air = 2 #Kassel
	air_base = { size = 4 current_size = 4 } }
province = { id = 138 anti_air = 1 #Frankfurt/Main
	air_base = { size = 4 current_size = 4 } }
province = { id = 141 anti_air = 3 } #Muenster
province = { id = 142 anti_air = 2 #Duesseldorf
	air_base = { size = 10 current_size = 10 } }
province = { id = 145 anti_air = 3 #Essen
	air_base = { size = 4 current_size = 4 } }
province = { id = 147 naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } } #Wilhelmshaven
province = { id = 148 naval_base = { size = 10 current_size = 10 } } #Bremen
province = { id = 151 anti_air = 1 #Lubeck
	naval_base = { size = 3 current_size = 3 } air_base = { size = 10 current_size = 10 } }
province = { id = 152 anti_air = 1 #Kiel
	naval_base = { size = 10 current_size = 10 } air_base = { size = 4 current_size = 4 } }
province = { id = 153 anti_air = 2 #Rostock
	naval_base = { size = 10 current_size = 10 } air_base = { size = 4 current_size = 4 } }
province = { id = 154 anti_air = 2 #Hamburg
	naval_base = { size = 10 current_size = 10 } }
province = { id = 163 anti_air = 2 #Berlin
	air_base = { size = 10 current_size = 10 } }	
province = { id = 167 landfort = 1 anti_air = 3 #Breslau
	air_base = { size = 10 current_size = 10 } }
province = { id = 168 manpower = 1 } #Gleitwitz
province = { id = 169 anti_air = 2 } #Magdeburg
province = { id = 170 anti_air = 1 } #Leipzig
province = { id = 173 air_base = { size = 10 current_size = 10 } } #Dresden
province = { id = 177 anti_air = 1 } #Nuremberg
province = { id = 179 anti_air = 2 #Munich
	air_base = { size = 10 current_size = 10 } }
province = { id = 181 anti_air = 2 #Gdansk
	naval_base = { size = 5 current_size = 5 } }
province = { id = 183 supplypool = 100 } #Elbing
province = { id = 184 anti_air = 4 #Koeningsberg
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 222 landfort = 3 anti_air = 3 } #Torun
province = { id = 224 landfort = 3 anti_air = 4 } #Poznan
province = { id = 226 anti_air = 1 #Gdynia
	naval_base = { size = 3 current_size = 3 } air_base = { size = 5 current_size = 5 } }
province = { id = 261 anti_air = 1 #Klaipeda
	naval_base = { size = 2 current_size = 2 } air_base = { size = 1 current_size = 1 } }
	
#Oceaninic colonies
province = { id = 1582 naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } } #Espiritu Santo
province = { id = 1586 naval_base = { size = 7 current_size = 7 } air_base = { size = 7 current_size = 7 } } #Nouvelle-Caledonia
province = { id = 1587 anti_air = 3 #Bougainville #North Solomon Islands
	naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } }
province = { id = 1590 naval_base = { size = 4 current_size = 4 } } #Lunga
province = { id = 1593 air_base = { size = 4 current_size = 4 } } #Guadalcanal
province = { id = 1686 anti_air = 3 #Pagan
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id = 1725 naval_base = { size = 7 current_size = 7 } air_base = { size = 7 current_size = 7 } } #Kavieng
province = { id = 1726 anti_air = 2 #Rabaul
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 1727 anti_air = 2 #Kimbe #Previously New britian
	naval_base = { size = 7 current_size = 7 } air_base = { size = 7 current_size = 7 } }

#Post 1870 European gains
province = { id = 96 landfort = 4 anti_air = 2 } #Longwy
province = { id = 105 landfort = 4 anti_air = 2 } #Colmar
province = { id = 106 landfort = 4 anti_air = 2 } #Nancy
province = { id = 108 landfort = 4 anti_air = 2 } #Liege
province = { id = 111 landfort = 4 anti_air = 2 } #Arlon
province = { id = 429 landfort = 3 coastalfort = 2 anti_air = 2 oilpool = 100 supplypool = 500 #Malta
	naval_base = { size = 5 current_size = 5 } air_base = { size = 4 current_size = 4 } }

### GLD
province = { id = 239 landfort = 2 anti_air = 1 } #Pryzemysl
province = { id = 241 oil = 2 } #Stryj
province = { id = 242 anti_air = 2 #Lwow
	air_base = { size = 5 current_size = 5 } }

### GRE
province = { id = 367 naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 } } #Ioannina
province = { id = 368 landfort = 2 anti_air = 1 } #Larissa
province = { id = 369 landfort = 2 anti_air = 1 } #Metsovo
province = { id = 372 manpower = 1 infra = { size = 0.40 current_size = 0.40 } } #Patra
province = { id = 373 naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } } #Corinith
province = { id = 374 infra = { size = 0.20 current_size = 0.20 } } #Chalcis
province = { id = 375 infra = { size = 0.40 current_size = 0.40 } } #Levadhia
province = { id = 377 anti_air = 1 manpower = 3 infra = { size = 0.50 current_size = 0.50 } #Athens
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 388 naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } } #Nicosia

### GUA
province = { id = 2079 naval_base = { size = 1 current_size = 1 } #San Salvador
	air_base = { size = 1 current_size = 1 } } 
province = { id = 2087 manpower = 1 } #Puerto Barrios
province = { id = 2088 anti_air = 1  manpower = 3 #Cuidad de Guatemala
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }

### GUY
province = { id = 1758 anti_air = 1 #Trinidad
	air_base = { size = 4 current_size = 4 } infra = { size = 0.40 current_size = 0.40 } }
province = { id = 1773 anti_air = 1 oilpool = 100 infra = { size = 0.40 current_size = 0.40 } #Bermudas
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } supplypool = 500 }
province = { id = 1782 infra = { size = 0.40 current_size = 0.40 } #Jamaica
	air_base = { size = 2 current_size = 2 } }
province = { id = 1997 anti_air = 1 #Georgetown
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }

### HAI
province = { id = 1781 anti_air = 1 #Port-au-Prince
	naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }

### HOL

#Indonesia
province = { id = 1615 air_base = { size = 4 current_size = 4 } } #Flores
province = { id = 1632 infra = { size = 0.20 current_size = 0.20 } #Balikpapan
	naval_base = { size = 4 current_size = 4 } air_base = { size = 3 current_size = 3 } }
province = { id = 1636 anti_air = 2 infra = { size = 0.30 current_size = 0.30 } #Palembang
	naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }
province = { id = 1640 infra = { size = 0.20 current_size = 0.20 } } #Koeta-Radja
province = { id = 1641 infra = { size = 0.30 current_size = 0.30 } } #Oosthaven
province = { id = 1642 anti_air = 2 #Medan
	naval_base = { size = 3 current_size = 3 } air_base = { size = 2 current_size = 2 } }
province = { id = 1646 infra = { size = 0.40 current_size = 0.40 } } #Tjilatjap
province = { id = 1647 anti_air = 2 infra = { size = 0.50 current_size = 0.50 } #Batavia
  naval_base = { size = 6 current_size = 6 } oilpool = 100 supplypool = 500 air_base = { size = 6 current_size = 6 } }
province = { id = 1648 infra = { size = 0.40 current_size = 0.40 } } #Tjilegon
province = { id = 1649 infra = { size = 0.40 current_size = 0.40 } } #Tjirebon
province = { id = 1650 infra = { size = 0.40 current_size = 0.40 } } #Semarang
province = { id = 1651 infra = { size = 0.40 current_size = 0.40 } } #Bandoeng
province = { id = 1652 infra = { size = 0.40 current_size = 0.40 } } #Rembang
province = { id = 1653 infra = { size = 0.50 current_size = 0.50 } anti_air = 2 #Soerabaja
	naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }
province = { id = 1654 infra = { size = 0.40 current_size = 0.40 } } #Jogjakarta
province = { id = 1655 infra = { size = 0.40 current_size = 0.40 } } #Malang
province = { id = 1656 infra = { size = 0.30 current_size = 0.30 } } #Madura
province = { id = 1658 naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } } #Kendari
province = { id = 1698 naval_base = { size = 8 current_size = 8 } } #Broome
province = { id = 1699 naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } } #Townsville
province = { id = 1701 naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } } #Cairns
province = { id = 1710 naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } } #Hobart

#Netherlands
province = { id = 118 anti_air = 2 air_base = { size = 4 current_size = 4 } } #Eindhoven
province = { id = 119 anti_air = 1 landfort = 2 #Arnhem
	air_base = { size = 4 current_size = 4 } }
province = { id = 120 landfort = 1 } #Nijmegen
province = { id = 122 anti_air = 3 manpower = 2 coastalfort = 3 #Amsterdam
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 123 landfort = 1 anti_air = 1 #Middelburg
	naval_base = { size = 3 current_size = 3 } }
province = { id = 125 manpower = 3 anti_air = 3 coastalfort = 2 #Rotterdam
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }

### HON
province = { id = 2085 anti_air = 1 manpower = 2 #Tegucigalpa
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }

### HUN

#Hungary
province = { id = 284 anti_air = 2 #Budapest
	air_base = { size = 8 current_size = 8 } }
province = { id = 286 infra = { size = 0.50 current_size = 0.50 } } #Arad
province = { id = 287 infra = { size = 0.40 current_size = 0.40 } } #Turda
province = { id = 288 infra = { size = 0.50 current_size = 0.50 } #Cluj
	anti_air = 2 air_base = { size = 5 current_size = 5 } }
province = { id = 291 infra = { size = 0.50 current_size = 0.50 } } #Sibiu
province = { id = 295 infra = { size = 0.40 current_size = 0.40 } } #Resita
province = { id = 336 infra = { size = 0.40 current_size = 0.40 } } #Petrovgrad

#Slovakia
province = { id = 208 anti_air = 2 #Bratislava
	air_base = { size = 3 current_size = 3 } }

### IND
province = { id = 1487 anti_air = 1 #Hyderbad
	air_base = { size = 4 current_size = 4 } }
province = { id = 1517 anti_air = 3 #Bombay
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }

### ITA
province = { id = 94 naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } } #Corsica
province = { id = 379 naval_base = { size = 2 current_size = 2 } #Rodos
	air_base = { size = 4 current_size = 4 } infra = { size = 0.30 current_size = 0.30 } }
province = { id = 396 landfort = 2 anti_air = 2 #Genoa
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 398 landfort = 2 anti_air = 3 } #Turin
province = { id = 407 anti_air = 3 #Milano
	air_base = { size = 10 current_size = 10 } }
province = { id = 410 anti_air = 3 #Florence
	naval_base = { size = 5 current_size = 5 } }
province = { id = 411 anti_air = 1 } #Bologna
province = { id = 414 anti_air = 1 } #Firenze
province = { id = 419 anti_air = 1 #Rome
	air_base = { size = 10 current_size = 10 } }
province = { id = 434 anti_air = 1 #Cagliari
	naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }

### IRE
province = { id = 31 anti_air = 1 #Cork
	naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }
province = { id = 34 anti_air = 2 #Dublin
	naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }
province = { id = 36 anti_air = 2 coastalfort = 1 #Belfast
	naval_base = { size = 6 current_size = 6 } air_base = { size = 3 current_size = 3 } }

### JAP

#Korea/Port Arthur/Sakhalin
province = { id = 1219 anti_air = 2 infra = { size = 0.50 current_size = 0.50 } #Port Arthur
naval_base = { size = 8 current_size = 8 } air_base = { size = 7 current_size = 7 } }
province = { id = 1221 anti_air = 2 #Pyongyang
air_base = { size = 4 current_size = 4 } }
province = { id = 1228 naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } } #Seoul
province = { id = 1230 naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } } #Gwuangju
province = { id = 1232 anti_air = 2 #Busan
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1541 anti_air = 2 oilpool = 100 supplypool = 500 #Okha
naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } }
province = { id = 1542 oilpool = 100 supplypool = 500 #Toyohara
naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } }

#Japan
province = { id = 1544 naval_base = { size = 6 current_size = 6 } air_base = { size = 5 current_size = 5 } } #Kushrio
province = { id = 1545 naval_base = { size = 5 current_size = 5 } air_base = { size = 6 current_size = 6 } } #Sapporo
province = { id = 1547 anti_air = 2 #Akita
air_base = { size = 10 current_size = 10 } }
province = { id = 1549
naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } } #Sendai
province = { id = 1551 anti_air = 2 #Niigata
naval_base = { size = 6 current_size = 6 } air_base = { size = 10 current_size = 10 } }
province = { id = 1552 anti_air = 2
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } } #Tokyo
province = { id = 1553 anti_air = 2 #Osaka
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1554 anti_air = 2 #Hiroshima
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1556 anti_air = 2 #Kanazawa
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1557 anti_air = 2 #Nagoya
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1559 anti_air = 2 #Matsuyama
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1560 naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } } #Nagasaki
province = { id = 1562 naval_base = { size = 2 current_size = 2 } air_base = { size = 3 current_size = 3 } } #Amami
province = { id = 1561 anti_air = 2 #Kagoshima
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1563 anti_air = 2 oilpool = 100 supplypool = 500 #Southern Okinawa
	naval_base = { size = 10 current_size = 3 } air_base = { size = 10 current_size = 3 } }
province = { id = 1564 anti_air = 2 oilpool = 100 supplypool = 500 #Northern Okinawa
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id = 1663 anti_air = 2 #Motoyama
	air_base = { size = 4 current_size = 4 } } 
province = { id = 1667 anti_air = 3 #Minami Torishima
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 1672  anti_air = 5 oilpool = 200 supplypool = 1000 #Truk
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1675 anti_air = 5 #Eniwetok
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 1676 anti_air = 5 #Kwajalein
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id =	1558	naval_base = { size =	8	current_size = 	8	} } #Maizuru
province = { id =	1558	air_base = { size =	4	current_size = 	4	} }

province = { id =	1559	naval_base = { size =	4	current_size = 	4	} } #Matsuyama
province = { id =	1559	air_base = { size =	2	current_size = 	2	} }

province = { id =	1560	naval_base = { size =	10	current_size = 	10	} } #Sasebo
province = { id =	1560	air_base = { size =	4	current_size = 	4	} }	

#Islands
province = { id = 1661 naval_base = { size = 4 current_size = 4 } } #Iwo Jima

#Taiwan
province = { id = 1361 oilpool = 100 supplypool = 500 #Gaoxiong
	naval_base = { size = 6 current_size = 6 } }
province = { id = 1362 anti_air = 4 oilpool = 100 supplypool = 500 #Taipei
	naval_base = { size = 8 current_size = 8 } air_base = { size = 10 current_size = 10 } }
province = { id = 1363 oilpool = 100 supplypool = 500 } #Taizhong

### KAZ
province = { id = 500 infra = { size = 0.30 current_size = 0.30 } } #Balkhash
province = { id = 501 infra = { size = 0.30 current_size = 0.30 } } #Kokchetav
province = { id = 502 infra = { size = 0.40 current_size = 0.40 } } #Akmolinsk
province = { id = 503 infra = { size = 0.30 current_size = 0.30 } #Karaganda
	air_base = { size = 1 current_size = 1 } }
province = { id = 504 infra = { size = 0.40 current_size = 0.40 } #Alma-ata
	air_base = { size = 2 current_size = 2 } }
province = { id = 505 infra = { size = 0.30 current_size = 0.30 } } #Sar
province = { id = 506 infra = { size = 0.30 current_size = 0.30 } } #Taldy-Kurgan
province = { id = 706 anti_air = 3 #Astrakhan
	air_base = { size = 4 current_size = 4 } }
province = { id = 1108 infra = { size = 0.30 current_size = 0.30 } } #Dzambul
province = { id = 1109 infra = { size = 0.30 current_size = 0.30 } } #Chimkent
province = { id = 1110 infra = { size = 0.30 current_size = 0.30 } } #Kzyl-Orda
province = { id = 1117 infra = { size = 0.30 current_size = 0.30 } } #Chelkar

 ### KYG
province = { id = 1097 anti_air = 1 } #Ashkhabad
province = { id = 1098 infra = { size = 0.30 current_size = 0.30 } } #Merv
province = { id = 1099 manpower = 3 #Samarkand
	infra = { size = 0.40 current_size = 0.40 } air_base = { size = 2 current_size = 2 } }
province = { id = 1100 infra = { size = 0.30 current_size = 0.30 } } #Bukhara
province = { id = 1103 manpower = 4 #Tashkent
	infra = { size = 0.40 current_size = 0.40 } }

### LAT

#Estonia
province = { id = 273 landfort = 1 } #Voru
province = { id = 274 landfort = 1 } #Narva
province = { id = 275 infra = { size = 0.20 current_size = 0.20 } } #Kuressaare
province = { id = 270 landfort = 1 #Tallinn
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }

#Latvia
province = { id = 264 manpower = 2 landfort = 1 anti_air = 1 #Riga
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id = 266 landfort = 2 } #Daugavpils
province = { id = 268 landfort = 2 #Liepaja
	naval_base = { size = 7 current_size = 7 } }

### LBY
province = { id = 750 anti_air = 1 manpower = 2 #Tripoli
	naval_base = { size = 8 current_size = 8 } air_base = { size = 6 current_size = 6 } }
province = { id = 756 infra = { size = 0.20 current_size = 0.20 } } #Sirt
province = { id = 757 infra = { size = 0.20 current_size = 0.20 } } #Misratah
province = { id = 759 infra = { size = 0.20 current_size = 0.20 } } #El Agheila
province = { id = 761 anti_air = 1 infra = { size = 0.30 current_size = 0.30 } #Benghazi
	manpower = 1 naval_base = { size = 5 current_size = 5 } air_base = { size = 6 current_size = 6 } }
province = { id = 762 infra = { size = 0.20 current_size = 0.20 } } #Agedabia
province = { id = 765 landfort = 3 infra = { size = 0.20 current_size = 0.20 } anti_air = 2 #Tobruk
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 767 infra = { size = 0.20 current_size = 0.20 } } #Gazala
province = { id = 768 infra = { size = 0.20 current_size = 0.20 } } #Darnah
province = { id = 771 infra = { size = 0.20 current_size = 0.20 } } #Bardia

### LIB
province = { id = 969 anti_air = 1 #Monrovia
	naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }

### LIT
province = { id = 255 anti_air = 2 } #Grodno
province = { id = 258 anti_air = 5 #Wilno
	air_base = { size = 3 current_size = 3 } }
province = { id = 262 anti_air = 1 #Kaunas
	air_base = { size = 1 current_size = 1 } }

### MAN
province = { id = 1198 infra = { size = 0.30 current_size = 0.30 } } #Butehaqi
province = { id = 1199 infra = { size = 0.50 current_size = 0.50 } #Harbin
	air_base = { size = 2 current_size = 2 } anti_air = 2 }
province = { id = 1203 anti_air = 2 #Qiqihaer
	air_base = { size = 4 current_size = 4 } }
province = { id = 1202 anti_air = 2 #Jiamisu
	air_base = { size = 2 current_size = 2 } }		
province = { id = 1205 infra = { size = 0.40 current_size = 0.40 } #Mudanjiang
	air_base = { size = 3 current_size = 3 } }
province = { id = 1206 air_base = { size = 4 current_size = 4 } } #Haila'er
province = { id = 1208 anti_air = 3 #Changchun
	air_base = { size = 6 current_size = 6 } }
province = { id = 1210 infra = { size = 0.20 current_size = 0.20 } } #Tongliyao Hot
province = { id = 1212 infra = { size = 0.20 current_size = 0.20 } } #Yanji
province = { id = 1214 anti_air = 3 } #Shenyang
province = { id = 1216 infra = { size = 0.40 current_size = 0.40 } } #Jinzhou
province = { id = 1217 infra = { size = 0.40 current_size = 0.40 } } #Anshan
province = { id = 1218 anti_air = 2 #Panjin
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id = 1220 infra = { size = 0.30 current_size = 0.30 } } #Dandong
province = { id = 1235 infra = { size = 0.20 current_size = 0.20 } } #Fuxin
province = { id = 1236 infra = { size = 0.30 current_size = 0.30 } #Chengde
	anti_air = 2 air_base = { size = 6 current_size = 6 } }

### MEX
province = { id = 1968 naval_base = { size = 2 current_size = 2 } } #Veracruz
province = { id = 1972 anti_air = 2 #Acapulco
	naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }
province = { id = 1974 anti_air = 4 #Mexico City
	air_base = { size = 2 current_size = 2 } }
province = { id = 1975 anti_air = 1 } #Monterey
province = { id = 1977 anti_air = 2 } #Ciudad de México

### MON

#Outer Mongolia
province = { id = 1120 infra = { size = 0.30 current_size = 0.30 } } #Bayan Tumen
province = { id = 1124 infra = { size = 0.40 current_size = 0.40 } #Ulaanbaatar
	air_base = { size = 1 current_size = 1 } }

### NEP

### NIC
province = { id = 2080 infra = { size = 0.40 current_size = 0.40 } #Managua
	naval_base = { size = 2 current_size = 2 } air_base = { size = 1 current_size = 1 } }
province = { id = 2081 anti_air = 1 #San Jose
	air_base = { size = 4 current_size = 4 } }

### NOR
province = { id = 483 coastalfort = 3 anti_air = 2 #Oslo
	naval_base = { size = 10 current_size = 10 } air_base = { size = 6 current_size = 6 } }
province = { id = 485 coastalfort = 3 } #Kristinsand
province = { id = 488 anti_air = 2 #Bergen
	naval_base = { size = 10 current_size = 10 } air_base = { size = 5 current_size = 5 } }
province = { id = 493 coastalfort = 2 manpower = 1 #Trondheim
	naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } }
province = { id = 495 anti_air = 1 #Narvik
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }

### YEM
province = { id = 1050 infra = { size = 0.20 current_size = 0.20 } } #Sanaa (Mar2020 - increased infra)

### OMN
province = { id = 1051 naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 } } #El Mukalla
province = { id = 1052 anti_air = 2 infra = { size = 0.20 current_size = 0.20 } #Masqat (Mar2020 - increased infra)
	naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } }

### OTT

#Arabian territories
#province = { id = 1008 anti_air = 1 #Tel Aviv
#	naval_base = { size = 2 current_size = 2 } air_base = { size = 4 current_size = 4 } }
#province = { id = 1010 air_base = { size = 2 current_size = 2 } } #Eilat
province = { id = 1011 naval_base = { size = 3 current_size = 3 } } #Haifa
province = { id = 1015 infra = { size = 0.20 current_size = 0.20 } } #El Qamisli
province = { id = 1172 air_base = { size = 3 current_size = 3 } } #Jerusalem
province = { id = 1019 anti_air = 2 #Beirut
	naval_base = { size = 5 current_size = 5 } air_base = { size = 4 current_size = 4 } }
province = { id = 1021 #Aleppo (Mar2020 - added navalbase, increased airbase)
	air_base = { size = 3 current_size = 3 } naval_base = { size = 2 current_size = 2 } }
province = { id = 1032 naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } } #Basrah
province = { id = 1033 infra = { size = 0.20 current_size = 0.20 } } #El Hillah
province = { id = 1034 air_base = { size = 4 current_size = 4 } } #Baghdad
#province = { id = 1041 naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } } #Kuwait
province = { id = 1048 anti_air = 2 #Medina
	naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } }

#Tibet

#Turkey
province = { id = 385 infra = { size = 0.30 current_size = 0.30 } } #Adrianople
province = { id = 409 naval_base = { size = 10 current_size = 10 }#Istanbul 
	air_base = { size = 10 current_size = 10 } }
province = { id = 1056 naval_base = { size = 2 current_size = 2 } #Gaziantep
	infra = { size = 0.20 current_size = 0.20 } }
province = { id = 1058 infra = { size = 0.20 current_size = 0.20 } #Tarsus
	naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }
province = { id = 1060 infra = { size = 0.20 current_size = 0.20 } } #Diyarbakir
province = { id = 1065  air_base = { size = 4 current_size = 4 } #Karabuk
	naval_base = { size = 4 current_size = 4 } infra = { size = 0.30 current_size = 0.30 } }
province = { id = 1067 infra = { size = 0.30 current_size = 0.30 } #Trabzon
	naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }
province = { id = 1075 anti_air = 4 #Ankara
	air_base = { size = 6 current_size = 6 } }
province = { id = 1076 anti_air = 4 infra = { size = 0.30 current_size = 0.30 } #Izmit
	naval_base = { size = 10 current_size = 10 } air_base = { size = 6 current_size = 6 } }
province = { id = 1077 naval_base = { size = 5 current_size = 5 } #Smyrna 
	air_base = { size = 4 current_size = 4 } }

### PAK
province = { id = 1459 anti_air = 2 #Delhi
	air_base = { size = 4 current_size = 4 } }
province = { id = 1522 anti_air = 1 #Rajkot
	air_base = { size = 4 current_size = 4 } }
province = { id = 1533 anti_air = 1 #Karachi
	naval_base = { size = 8 current_size = 8 } air_base = { size = 8 current_size = 8 } }
province = { id = 1481 anti_air = 1 #Indhur
	air_base = { size = 4 current_size = 4 } }

### PAN
province = { id = 2078 anti_air = 2 infra = { size = 0.40 current_size = 0.40 } #Cuidad de Panama
	naval_base = { size = 5 current_size = 5 } air_base = { size = 1 current_size = 1 } }

### PER
province = { id = 1081 anti_air = 1 #Rast
	air_base = { size = 2 current_size = 2 } }
province = { id = 1085 anti_air = 2 #Tehran
	air_base = { size = 3 current_size = 3 } }
province = { id = 1089 air_base = { size = 3 current_size = 3 } } #Abadan
province = { id = 1091 anti_air = 2 #Gameroon
	naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } }

### PHI
province = { id = 1565 coastalfort = 3 anti_air = 2 #Manila
	naval_base = { size = 10 current_size = 10 } air_base = { size = 6 current_size = 6 } }
province = { id = 1567 anti_air = 4 #Baguio
	naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } }

### POL
province = { id = 223 anti_air = 4 #Lodz
	air_base = { size = 4 current_size = 4 } }
province = { id = 227 manpower = 2 } #Czestochowa
province = { id = 232 landfort = 2 anti_air = 4 #Warsaw
	air_base = { size = 6 current_size = 6 } }
province = { id = 235 anti_air = 4 #Krakow
	air_base = { size = 5 current_size = 5 } }

### POR

#African colonies
province = { id = 854 naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } } #Nampula
province = { id = 892 naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } } #Lobito
province = { id = 893 naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 } } #Cabinda
province = { id = 912 anti_air = 2 #Sao Tome
	naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 } }
province = { id = 992 naval_base = { size = 3 current_size = 3  } air_base = { size = 1 current_size = 1 } } #Cape Verde

#Asian/Oceanic colonies
province = { id = 1372 #Macao
	naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } }
province = { id = 1617 naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 } } #Dili

#Portugal
province = { id = 476 anti_air = 4 #Lisbon
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 481 anti_air = 1 } #Porto
province = { id = 995 anti_air = 2 #The Azores
	naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }

### PRI	
province = { id = 1185 landfort = 2 } #Gavan
province = { id = 1190 landfort = 2 #Khabarovsk
	air_base = { size = 3 current_size = 3 } }
province = { id = 1191 manpower = 1 landfort = 1 coastalfort = 3 anti_air = 5 #Vladivostok
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }

### PRK
province = { id = 1445 infra = { size = 0.30 current_size = 0.30 } } #Dhaka
province = { id = 1447 anti_air = 2 #Calcutta 
	naval_base = { size = 8 current_size = 8 } air_base = { size = 8 current_size = 8 } }
province = { id = 1449 infra = { size = 0.40 current_size = 0.40 } } #Rajshahi

### PRU
province = { id = 2016 naval_base = { size = 3 current_size = 3 } } #Lima

### ROM
province = { id = 297 anti_air = 1 #Iasi
	air_base = { size = 3 current_size = 3 } }
province = { id = 302 infra = { size = 0.30 current_size = 0.30 } } #Hotin
province = { id = 303 infra = { size = 0.30 current_size = 0.30 } } #Balti
province = { id = 304 anti_air = 1 infra = { size = 0.40 current_size = 0.40 } } #Chisinau
province = { id = 305 infra = { size = 0.30 current_size = 0.30 } } #Cahul
province = { id = 310 anti_air = 2 #Constantza
	naval_base = { size = 6 current_size = 6 } air_base = { size = 3 current_size = 3 } }
province = { id = 311 anti_air = 3 } #Ploiesti
province = { id = 315 infra = { size = 0.40 current_size = 0.40 } } #Craiova
province = { id = 316 anti_air = 2 #Bucharest
	air_base = { size = 5 current_size = 5 } }
	
### RSI
province = { id = 415 landfort = 2 } #Pescara
province = { id = 417 landfort = 1 } #Cassino
province = { id = 418 landfort = 2 } #Gaeta
province = { id = 421 naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } } #Naples
province = { id = 422 anti_air = 1 #Taranto
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 430 naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } } #Palermo
province = { id = 432 anti_air = 2 #Catania
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }

### RUS

#European Russia
province = { id = 535 anti_air = 4 #Murmansk
	naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }
province = { id = 542 anti_air = 2 #Archangelsk
	naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } }
province = { id = 553 landfort = 2 coastalfort = 5 anti_air = 3 #Leningrad
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 560 anti_air = 1 } #Novgorod
province = { id = 566 air_base = { size = 6 current_size = 6 } } #Pskov
province = { id = 572 landfort = 1 anti_air = 2 #Moscow
	air_base = { size = 10 current_size = 10 } }
province = { id = 576 anti_air = 1 } #Kaluga
province = { id = 581 air_base = { size = 5 current_size = 5 } } #Oryol
province = { id = 588 anti_air = 2 } #Bryansk
province = { id = 589 anti_air = 3 } #Smolensk
province = { id = 590 anti_air = 2 } #Vitebsk
province = { id = 600 anti_air = 1 #Mogilev
	air_base = { size = 5 current_size = 5 } }
province = { id = 663 air_base = { size = 2 current_size = 2 } } #Tsaritsyn
province = { id = 664 air_base = { size = 2 current_size = 2 } } #Naberezhnye Chelny
province = { id = 667 air_base = { size = 2 current_size = 2 } } #Tolyatti

#Siberia
province = { id = 1138 air_base = { size = 1 current_size = 1 } } #Omsk
province = { id = 1140 air_base = { size = 5 current_size = 5 } } #Barnaul
province = { id = 1148 air_base = { size = 2 current_size = 2 } } #Tomsk
province = { id = 1165 air_base = { size = 1 current_size = 1 } } #Bratsk
province = { id = 1171 infra = { size = 0.20 current_size = 0.20 } } #Ekimchan
province = { id = 1179 air_base = { size = 1 current_size = 1 } } #Yakutsk
province = { id = 1189 anti_air = 2 air_base = { size = 4 current_size = 4 } #Nikolayevsk-on-Amur
	naval_base = { size = 2 current_size = 2 } }

### SAF
province = { id = 872 naval_base = { size = 3 current_size = 3 } } #Duban
province = { id = 873 anti_air = 1 } #Port Elizabeth
province = { id = 876 anti_air = 5 #Johannesberg
air_base = { size = 1 current_size = 1 } }
province = { id = 880 anti_air = 4 #Cape Town
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 881 anti_air = 3 #Durban
naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } }
province = { id = 964 oilpool = 1000 supplypool = 2000 } #Freetown

### SAU
province = { id = 1038 naval_base = { size = 2 current_size = 2 } } #Doha
province = { id = 1040 } #Dammam (Mar2020 - removed navalbase)
province = { id = 1045 infra = { size = 0.30 current_size = 0.30 } } #Riyadh
province = { id = 1049 air_base = { size = 2 current_size = 2 } infra = { size = 0.20 current_size = 0.20 } } #Mecca

### SCH
province = { id = 389 landfort = 5 anti_air = 3 } #Zurich
province = { id = 390 landfort = 5 anti_air = 3 } #Lugano
province = { id = 391 landfort = 5 anti_air = 3 } #Geneva
province = { id = 392 landfort = 5 anti_air = 5 #Bern
air_base = { size = 4 current_size = 4 } }

### SER
province = { id = 327 landfort = 2 infra = { size = 0.40 current_size = 0.40 } } #Krusevac
province = { id = 330 landfort = 1 } #Nis
province = { id = 338 landfort = 2 anti_air = 2 #Beograd
air_base = { size = 6 current_size = 6 } }
province = { id = 339 landfort = 2 } #Bor
province = { id = 340 landfort = 2 infra = { size = 0.30 current_size = 0.30 } } #Sabac
province = { id = 342 landfort = 2 } #Uzice

### SIA
province = { id = 1422 anti_air = 2 air_base = { size = 2 current_size = 2 } } #Chon Buri
province = { id = 1423 anti_air = 2 #Bangkok
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id = 1426 air_base = { size = 4 current_size = 4 } } #Phitsanulok
province = { id = 1431 naval_base = { size = 2 current_size = 2 } air_base = { size = 1 current_size = 1 } } #Songkhla
province = { id = 1435 naval_base = { size = 2 current_size = 2 } } #Kuala Lumpur

### SPA

#Africa colonies
province = { id = 461 naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } } #Castellon de la Plana
province = { id = 473 naval_base = { size = 4 current_size = 4 } } #Cadiz
province = { id = 715 anti_air = 3 #Tanger
naval_base = { size = 6 current_size = 6 } air_base = { size = 2 current_size = 2 } }
province = { id = 988 anti_air = 2 #Villa Cisneros
naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } }
province = { id = 990 naval_base = { size = 1 current_size = 1 } air_base = { size = 2 current_size = 2 } } #Las Palmas de Gran Canaria
province = { id = 991 anti_air = 2 #Santa Cruz de Tenerife
naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }

#Spain
province = { id = 348 anti_air = 4 oilpool = 200 supplypool = 500 #Gibraltar
naval_base = { size = 6 current_size = 6 } air_base = { size = 4 current_size = 4 } }
province = { id = 436 anti_air = 2 #Tarragona
naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }
province = { id = 437 landfort = 3 } #Gerona
province = { id = 438 landfort = 3 } #Huesca
province = { id = 439 landfort = 3 } #Lerida
province = { id = 440 naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } } #Barcelona
province = { id = 441 anti_air = 2 #Coruna
naval_base = { size = 7 current_size = 7 } air_base = { size = 7 current_size = 7 } }
province = { id = 443 landfort = 3 } #Bilbao
province = { id = 446 landfort = 2 } #Pamplona
province = { id = 460 anti_air = 3 #Madrid
air_base = { size = 10 current_size = 10 } }
province = { id = 464 anti_air = 2 #Valencia
naval_base = { size = 3 current_size = 3 } air_base = { size = 2 current_size = 2 } }
province = { id = 472 naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } } #Huevla
province = { id = 474 anti_air = 2 #Sevilla
naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }
province = { id = 475 anti_air = 2 #Palma de Mallorca
naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }

### SWE
province = { id = 2152 coastalfort = 3 manpower = 2 #Malmo
naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id = 2153 coastalfort = 1 anti_air = 2 manpower = 2 #Gothenburg
naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }
province = { id = 2156 anti_air = 2 #Visby
naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }
province = { id = 2158 landfort = 1 coastalfort = 1 } #Uppsala
province = { id = 2159 coastalfort = 3 anti_air = 2 manpower = 2 #Stockholm
naval_base = { size = 8 current_size = 8 } air_base = { size = 8 current_size = 8 } }
province = { id = 2162 landfort = 1 coastalfort = 1 } #Gaevla
province = { id = 2166 landfort = 3 anti_air = 2 #Lulea
naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }

### TRA
province = { id = 694 anti_air = 2 #Novorossiysk
naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } }
province = { id = 702 air_base = { size = 2 current_size = 2 } } #Gronzy

### U02
province = { id = 382 anti_air = 1 infra = { size = 0.30 current_size = 0.30 } #Irakleio
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }

### U35
province = { id = 1500 naval_base = { size = 4 current_size = 4 } #Madras
	air_base = { size = 2 current_size = 2 } }

### UKR
province = { id = 245 landfort = 2 } #Lutsk
province = { id = 606 landfort = 1 infra = { size = 0.30 current_size = 0.30 } } #Sumy
province = { id = 605 landfort = 1 } #Konotop
province = { id = 607 landfort = 1 air_base = { size = 2 current_size = 2 } #Chernigov
	infra = { size = 0.40 current_size = 0.40 } }
province = { id = 618 infra = { size = 0.30 current_size = 0.30 } } #Kamenets-Podolsky
province = { id = 619 infra = { size = 0.20 current_size = 0.20 } } #Mogilev-Podolsky
province = { id = 617 anti_air = 3 #Kiev
air_base = { size = 8 current_size = 8 } }
province = { id = 622 naval_base = { size = 5 current_size = 5 } } #Nikolayev
province = { id = 625 infra = { size = 0.30 current_size = 0.30 } } #Ochakov
province = { id = 626 anti_air = 3 #Odessa
naval_base = { size = 3 current_size = 3 } }
province = { id = 627 infra = { size = 0.40 current_size = 0.40 } } #Krivoy Rog
province = { id = 628 infra = { size = 0.40 current_size = 0.40 } } #Yelisavetgrad
province = { id = 632 anti_air = 2 #Dnepropetrovsk
air_base = { size = 2 current_size = 2 } }
province = { id = 634 landfort = 1 } #Voroshilovgrad
province = { id = 635 landfort = 1 anti_air = 2 } #Stalino
province = { id = 636 landfort = 2 anti_air = 5 } #Kharkov
province = { id = 641 landfort = 3 coastalfort = 5 anti_air = 5 #Sevastopol
naval_base = { size = 10 current_size = 10 } air_base = { size = 6 current_size = 6 } }
province = { id = 644 anti_air = 2 #Rostov
naval_base = { size = 4 current_size = 4 } }
province = { id = 654 anti_air = 1 } #Voronezh

### USA

#Atlantic territories
province = { id = 889 anti_air = 3 supplypool = 100 infra = { size = 0.40 current_size = 0.40 } #Balbo
	naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 1765 supplypool = 100 } #Puerto Rico
province = { id = 1778 naval_base = { size = 4 current_size = 4 } } #Guantanamo Bay Naval Base

#AUS
province = { id = 1812 anti_air = 4 #Norfolk
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1819 anti_air = 1 #Louisville
air_base = { size = 4 current_size = 4 } }
province = { id = 1918 anti_air = 1 #Little Rock
air_base = { size = 4 current_size = 4 } }
province = { id = 1931 naval_base = { size = 10 current_size = 10 } } #New Oreleans
province = { id = 1922 anti_air = 1 #Corpus Christi
naval_base = { size = 8 current_size = 8 } air_base = { size = 6 current_size = 6 } }
province = { id = 1940 anti_air = 1 #Memphis
air_base = { size = 4 current_size = 4 } }
province = { id = 1944 naval_base = { size = 6 current_size = 6 } 
	air_base = { size = 6 current_size = 6 } } #Mobile
province = { id = 1952 anti_air = 1 #Jacksonville
naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 1953 anti_air = 1 #Miami
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1955 anti_air = 1 #Atlanta
air_base = { size = 4 current_size = 4 } }
province = { id = 1959 air_base = { size = 10 current_size = 10 } } #Augusta
province = { id = 1960 anti_air = 1 #Charleston
naval_base = { size = 8 current_size = 8 } air_base = { size = 8 current_size = 8 } }
province = { id = 1962 anti_air = 1 #Charlotte
air_base = { size = 4 current_size = 4 } }
province = { id = 1963 naval_base = { size = 8 current_size = 8 } 
	air_base = { size = 8 current_size = 8 } } #Wilimington

#CSA
province = { id = 1795 anti_air = 4 #New York
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1805 anti_air = 2 } #Philadelphia
province = { id = 1806 anti_air = 1 #Pittsburgh
air_base = { size = 4 current_size = 4 } }
province = { id = 1831 anti_air = 1 #Belleville
air_base = { size = 4 current_size = 4 } }
province = { id = 1832  anti_air = 3 #Chicago
air_base = { size = 10 current_size = 10 } }
province = { id = 1833 anti_air = 1 #Saint Louis
air_base = { size = 4 current_size = 4 } }
province = { id = 1838 anti_air = 1 #Des Moines
air_base = { size = 4 current_size = 4 } }
province = { id = 1839 anti_air = 1 #Milwaukee
air_base = { size = 4 current_size = 4 } }
province = { id = 1845 anti_air = 1 #Detroit
air_base = { size = 4 current_size = 4 } }
province = { id = 1847 anti_air = 1 #Minneapolis
air_base = { size = 4 current_size = 4 } }

#'Loyal' mainland
province = { id = 1797 naval_base = { size = 10 current_size = 10 } #Newark
	air_base = { size = 10 current_size = 10 } }
province = { id = 1809 anti_air = 4 #Washington D.C.
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1856 anti_air = 1 #Bismarck
air_base = { size = 4 current_size = 4 } }
province = { id = 1860 anti_air = 1 #Omaha
air_base = { size = 4 current_size = 4 } }
province = { id = 1896 anti_air = 1 #Salt Lake City
air_base = { size = 10 current_size = 10 } }
province = { id = 1900 anti_air = 1 #Phoenix
air_base = { size = 4 current_size = 4 } }
province = { id = 1908 anti_air = 1 #Denver
air_base = { size = 4 current_size = 4 } }
province = { id = 1912 anti_air = 1 #Tulsa
air_base = { size = 4 current_size = 4 } }
province = { id = 1913 anti_air = 1 #Oklahoma City
air_base = { size = 4 current_size = 4 } }
province = { id = 1926 anti_air = 1 #San Antonio
air_base = { size = 4 current_size = 4 } }
province = { id = 1928 anti_air = 1 #Houston
air_base = { size = 4 current_size = 4 } }

#New England
province = { id = 1787 anti_air = 1 #Concord
air_base = { size = 4 current_size = 4 } }
province = { id = 1789 anti_air = 3 #Boston
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1793 anti_air = 1 #Albany
air_base = { size = 4 current_size = 4 } }
	
#Pacific territories
province = { id = 1673 anti_air = 3 supplypool = 100 #Wake
naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 1683 anti_air = 3 supplypool = 100 #Guam
naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 1733 supplypool = 50 #Pago Pago
naval_base = { size = 2 current_size = 2 } }
province = { id = 1734 anti_air = 5 supplypool = 1000 #Pearl Harbour
naval_base = { size = 10 current_size = 10 } air_base = { size = 6 current_size = 6 } }
province = { id = 1738 supplypool = 1 } #Port Johnston
province = { id = 1739 supplypool = 100 #Midway
naval_base = { size = 3 current_size = 3 } }
province = { id = 1747 supplypool = 50 #Palmyra
naval_base = { size = 8 current_size = 8 } air_base = { size = 8 current_size = 8 } }
province = { id = 1887 anti_air = 3 #Los Angeles
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }

#West Coast
province = { id = 1874 anti_air = 1 #Seattle
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1878 anti_air = 1 #Portland
naval_base = { size = 6 current_size = 6 } air_base = { size = 4 current_size = 4 } }
province = { id = 1886 anti_air = 1 #San Diego
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1888 anti_air = 1 #Sacramento
air_base = { size = 4 current_size = 4 } }
province = { id = 1889 anti_air = 3 #San Francisco
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 2141 supplypool = 1000 } #Juneau
province = { id = 2142 anti_air = 1 #Anchorage
naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 2150 supplypool = 500 #Adak
naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }

### VEN
province = { id = 1988 anti_air = 2 #Maracaibo
	naval_base = { size = 6 current_size = 6 } air_base = { size = 1 current_size = 1 } }
province = { id = 1993 anti_air = 2 #Caracas
	naval_base = { size = 4 current_size = 4 } }

### VIC
province = { id = 728 anti_air = 2 #Oran
naval_base = { size = 2 current_size = 2 } air_base = { size = 4 current_size = 4 } }
province = { id = 727 anti_air = 4 #Algiers
naval_base = { size = 5 current_size = 5 } air_base = { size = 4 current_size = 4 } }
province = { id = 736 naval_base = { size = 5 current_size = 5 } #Bougie
	air_base = { size = 5 current_size = 5 } }
province = { id = 747 anti_air = 4 #Tunis
naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 962 anti_air = 2 #Abidjan
air_base = { size = 4 current_size = 4 } }
province = { id = 978 anti_air = 3 #Dakar
naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }

### YUN
province = { id = 1390 anti_air = 1 #Kunming
air_base = { size = 3 current_size = 3 } }


#More Supply Pools
 province = {  id = 371  oilpool = 100 supplypool = 500 }
 province = {  id = 1782  oilpool = 100 supplypool = 500 }
 province = {  id = 1771  oilpool = 100 supplypool = 500 }
 province = {  id = 1758  oilpool = 100 supplypool = 500 }
 province = {  id = 2000  oilpool = 100 supplypool = 500 }
 province = {  id = 1721  oilpool = 100 supplypool = 500 }
 province = {  id = 1607  oilpool = 100 supplypool = 500 }
 province = {  id = 991  oilpool = 100 supplypool = 500 }
 province = {  id = 988  oilpool = 100 supplypool = 500 }
 province = {  id = 475  oilpool = 100 supplypool = 500 }
 province = {  id = 715  oilpool = 100 supplypool = 500 }
 province = {  id = 892  oilpool = 100 supplypool = 500 }
 province = {  id = 963  oilpool = 100 supplypool = 500 }
 province = {  id = 855  oilpool = 100 supplypool = 500 }
 province = {  id = 1661  oilpool = 100 supplypool = 500 }
 province = {  id = 1662  oilpool = 100 supplypool = 500 }
 province = {  id = 1672  oilpool = 100 supplypool = 500 }
 province = {  id = 1562  oilpool = 100 supplypool = 500 }
 province = {  id = 1358  oilpool = 100 supplypool = 500 }
 province = {  id = 1346  oilpool = 100 supplypool = 500 }
 province = {  id = 381  oilpool = 100 supplypool = 500 }
 province = {  id = 379  oilpool = 100 supplypool = 500 }
 province = {  id = 388  oilpool = 100 supplypool = 500 }
 province = {  id = 718  oilpool = 100 supplypool = 500 }
 province = {  id = 833  oilpool = 100 supplypool = 500 }
 province = {  id = 900  oilpool = 100 supplypool = 500 }
 province = {  id = 1328  oilpool = 100 supplypool = 500 }