####
#Organised by RainbowFire for DH Kaiserreich
####

### AFG
province = { id = 1537 ic = 1 } #Peshawar
province = { id = 2168 ic = -1 } #Kondoz
province = { id = 2169 ic = -2 } #Kandahar
province = { id = 2171 energy = 4 metal = 3 rare_materials = 2 } #Bamyan coal, Hajigak & Logar iron/copper/chromite mines
province = { id = 2171 ic = 2 #Kabul
	infra = { size = 0.30 current_size = 0.30 } air_base = { size = 1 current_size = 1 } }

### ALB
province = { id = 359 anti_air = 1
naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } } #Tirana

### ARG

#Argentina
province = { id = 2048 anti_air = 2 #Bahia Blanca
naval_base = { size = 8 current_size = 8 } air_base = { size = 3 current_size = 3 } } 
province = { id = 2050 anti_air = 5 #Buenos aires
naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } }
province = { id = 2054 anti_air = 1 } #Cordoba

#Falklands
province = { id = 2045 anti_air = 2 oilpool = 100 supplypool = 200 #Falkland Islands
naval_base = { size = 5 current_size = 5 } air_base = { size = 2 current_size = 2 } }

#Paraguay
province = { id = 2046 anti_air = 1 #Villa Hayes
air_base = { size = 4 current_size = 4 } }
province = { id = 2047 infra = { size = 0.40 current_size = 0.40 } } #Nuestra Senora de la Asuncion

#Uruguay
province = { id = 2052 anti_air = 1 #Montevideo
naval_base = { size = 6 current_size = 6 } air_base = { size = 2 current_size = 2 } }

### ARM
province = { id = 711 ic = 1 landfort = 3 anti_air = 1 #Yerevan (Mar2020 - previously ic = 5, increased infra)
	infra = { size = 0.30 current_size = 0.30 } }

### AST

#Australia
province = { id = 1690 ic = 2 anti_air = 4 #Perth
	naval_base = { size = 4 current_size = 4 } air_base = { size = 6 current_size = 6 } }
province = { id = 1697 anti_air = 2 #Darwin
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 1696 air_base = { size = 2 current_size = 2 } } #Katherine
province = { id = 1698 naval_base = { size = 1 current_size = 1 } } #Broome
province = { id = 1699 ic = 1 #Townsville
	naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 1701 naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } } #Cairns
province = { id = 1703 ic = 1 } #Newcastle
province = { id = 1704 coastalfort = 1 anti_air = 1 #Brisbane
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1705 ic = 5 manpower = 2 anti_air = 7 #Sydney
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1706 ic = 1 } #Wollongong
province = { id = 1707 ic = -1 anti_air = 2 #Canberra
	air_base = { size = 2 current_size = 2 } }
province = { id = 1708 ic = 6 anti_air = 3 coastalfort = 1 #Melbourne
	naval_base = { size = 6 current_size = 6 } air_base = { size = 8 current_size = 8 } }
province = { id = 1710 naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } } #Hobart
province = { id = 1711 ic = 1 } #Port Lincoln
province = { id = 1712 ic = 3 anti_air = 2 #Adelaide
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 1713 ic = -3 } #Robe
province = { id = 1715 anti_air = 1 } #Port Augusta

#New Zealand
province = { id = 1718 energy = 2 } #Napier
province = { id = 1719 infra = { size = 0.30 current_size = 0.30 } } #Hamilton
province = { id = 1720 infra = { size = 0.40 current_size = 0.40 } ic = 1 energy = 3 } #Auckland
province = { id = 1721 infra = { size = 0.40 current_size = 0.40 } ic = -2 anti_air = 2 #Wellington
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id = 1722 infra = { size = 0.40 current_size = 0.40 } ic = 2 manpower = 1 anti_air = 3 #Christchurch
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1723 infra = { size = 0.20 current_size = 0.20 } ic = 1 } #Dunedin

#Papua New Guinea
province = { id = 1234 anti_air = 1 oilpool = 100 supplypool = 500 #Lae/Buna
naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } }
province = { id = 1607 anti_air = 1 #Port Moresby
naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }

### AUS

#Austria
province = { id = 187 ic = 2 #Linz
	air_base = { size = 4 current_size = 4 } }
province = { id = 189 anti_air = 2 #Innsbruck
	air_base = { size = 4 current_size = 4 } }
province = { id = 190 ic = 4 anti_air = 1 } #Graz
province = { id = 191 ic = 1 air_base = { size = 6 current_size = 6 } } #Klagenfurt
province = { id = 192 ic = 2 } #Salzburg
province = { id = 193 ic = 1 } #Sankt Poelten
province = { id = 195 anti_air = 5 ic = 1 manpower = 3 #Vienna
	air_base = { size = 10 current_size = 10 } }

#Montenegro
province = { id = 332 #Cetinje
	naval_base = { size = 3 current_size = 3 } infra = { size = 0.20 current_size = 0.20 } }

#Slovene/Italian lands
province = { id = 346 ic = 3 } #Maribor
province = { id = 394 ic = -2 } #Belluno
province = { id = 400 anti_air = 2 ic = 3 #Venezia
	naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 404 anti_air = 1 #Trieste
	naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 405 ic = -1 } #Udine
province = { id = 406 manpower = 1 ic = 2 anti_air = 1 #Pola
	naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }

### AZB
province = { id = 713 ic = 3 landfort = 3 anti_air = 1 #Baku (previously ic = 7)
	air_base = { size = 4 current_size = 4 } }

### BEL
province = { id = 112 landfort = 2 anti_air = 1 } #Mons
province = { id = 114 landfort = 2 anti_air = 1 #Burges
	air_base = { size = 5 current_size = 5 } }
 province = { id = 114 manpower = 2 #Bruges
	air_base = { size = 6 current_size = 6 } naval_base = { size = 3 current_size = 3 } }
province = { id = 115 #Antwerpen
	naval_base = { size = 5 current_size = 5 } }
province = { id = 116 landfort = 2 anti_air = 1 manpower = 3 #Brussels
	air_base = { size = 6 current_size = 6 } }

### BLR
province = { id = 247 landfort = 2 } #Brest-Litovsk
province = { id = 248 manpower = 1 } #Pinsk
province = { id = 251 ic = 1 manpower = 1 } #Nowogrodek
province = { id = 256 ic = 1 } #Vilejka
province = { id = 257 landfort = 1 } #Glebokie
province = { id = 591 landfort = 2 manpower = 1 } #Orsha
province = { id = 592 landfort = 1 manpower = 1 } #Borisov
province = { id = 594 ic = 1 landfort = 1 manpower = 1 } #Bobruisk
province = { id = 598 landfort = 1 } #Rechytsa
province = { id = 599 ic = 3 anti_air = 3 #Minsk
	air_base = { size = 8 current_size = 8 } }

### BOL
province = { id = 2020 ic = 3 infra = { size = 0.40 current_size = 0.40 } #Nuestra Senora de La Paz
	air_base = { size = 4 current_size = 4 } anti_air = 1 }
province = { id = 2021 ic = -3 infra = { size = 0.40 current_size = 0.40 } } #Sucre

### BOS
province = { id = 353 ic = 2 infra = { size = 0.30 current_size = 0.30 } } #Banja Luka
province = { id = 355 anti_air = 2 #Sarajevo
	air_base = { size = 5 current_size = 5 } infra = { size = 0.30 current_size = 0.30 } }

### BRA
province = { id = 2058 anti_air = 2 #Porto Alegre
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 2059 anti_air = 1 #Sao Paulo
	naval_base = { size = 6 current_size = 6 } air_base = { size = 4 current_size = 4 } }
province = { id = 2060 ic = 1 } #Campo Grande
province = { id = 2067 anti_air = 2 #Belo Horizonte
	air_base = { size = 3 current_size = 3 } }
province = { id = 2074 anti_air = 1 } #Vitoria
province = { id = 2075 anti_air = 1 #Rio de Janeiro
	naval_base = { size = 6 current_size = 6 } air_base = { size = 4 current_size = 4 } }

### BUL
province = { id = 307 infra = { size = 0.20 current_size = 0.20 } } #Dobrich
province = { id = 317 infra = { size = 0.30 current_size = 0.30 } } #Vidin
province = { id = 318 infra = { size = 0.30 current_size = 0.30 } } #Ruse
province = { id = 319 infra = { size = 0.20 current_size = 0.20 } } #Haskovo
province = { id = 321 ic = 3 infra = { size = 0.40 current_size = 0.40 } #Sofia
	anti_air = 2 air_base = { size = 6 current_size = 6 } }
province = { id = 322 ic = -3 infra = { size = 0.20 current_size = 0.20 } } #Gabrovo
province = { id = 323 ic = 1 infra = { size = 0.30 current_size = 0.30 } } #Pleven
province = { id = 324 infra = { size = 0.30 current_size = 0.30 } } #Plovdiv
province = { id = 325 infra = { size = 0.30 current_size = 0.30 } } #Burgas
province = { id = 326 ic = 2 infra = { size = 0.30 current_size = 0.30 } anti_air = 1 #Varna
	naval_base = { size = 4 current_size = 4 } air_base = { size = 3 current_size = 3 } }
province = { id = 328 infra = { size = 0.30 current_size = 0.30 } } #Kumanovo
province = { id = 331 ic = 2 infra = { size = 0.30 current_size = 0.30 } } #Pirot
province = { id = 363 ic = 1 anti_air = 1 infra = { size = 0.20 current_size = 0.20 } #Xanthi
	naval_base = { size = 2 current_size = 2 } air_base = { size = 3 current_size = 3 } }
province = { id = 364 ic = 1 infra = { size = 0.20 current_size = 0.20 } } #Kavala
province = { id = 365 ic = 3 #Thessaloniki
	naval_base = { size = 6 current_size = 6 } }
province = { id = 366 infra = { size = 0.30 current_size = 0.30 } } #Kozani
province = { id = 370 infra = { size = 0.20 current_size = 0.20 } } #Alexandroupoli

### BUR
province = { id = 1410 ic = 3 anti_air = 1 #Mandalay
	air_base = { size = 4 current_size = 4 } }
province = { id = 1411 ic = 1 } #Pakokdu
province = { id = 1415 ic = 1 anti_air = 2 #Rangoon
	naval_base = { size = 6 current_size = 6 } air_base = { size = 4 current_size = 4 } }

### CAN
province = { id = 2089 ic = 1 manpower = 1 anti_air = 1 #Vancouver
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 2090 ic = 1 infra = { size = 0.50 current_size = 0.50 } #Victoria
	naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }
province = { id = 2092 ic = -2 } #Jasper
province = { id = 2101 ic = 1 manpower = 1 } #Regina
province = { id = 2102 ic = -1 infra = { size = 0.20 current_size = 0.20 } } #Prince Albert
province = { id = 2103 manpower = 1 air_base = { size = 4 current_size = 4 } } #Edmonton
province = { id = 2105 ic = -1 infra = { size = 0.20 current_size = 0.20 } } #Grande Prairie
province = { id = 2106 ic = 1 manpower = 1 anti_air = 1 #Winnipeg
	air_base = { size = 4 current_size = 4 } }
province = { id = 2108 manpower = 1 anti_air = 3 #Ottawa
	air_base = { size = 4 current_size = 4 } }
province = { id = 2109 ic = 1 manpower = 1 infra = { size = 0.70 current_size = 0.70 } } #Kingston
province = { id = 2110 ic = -2 } #Fort William
province = { id = 2111 ic = 4 manpower = 3 anti_air = 3 #Toronto
	air_base = { size = 10 current_size = 10 } infra = { size = 0.80 current_size = 0.80 } }
province = { id = 2112 ic = -1 infra = { size = 0.20 current_size = 0.20 } } #Thunder Bay
province = { id = 2113 ic = 3 manpower = 1 infra = { size = 0.60 current_size = 0.60 } } #Windsor
province = { id = 2117 manpower = 1 anti_air = 4 #Québec
	naval_base = { size = 10 current_size = 10 } air_base = { size = 6 current_size = 6 } }
province = { id = 2118 ic = 2 manpower = 1 infra = { size = 0.60 current_size = 0.60 } } #Sherbrooke
province = { id = 2119 ic = 4 manpower = 3 anti_air = 2 #Montreal
	air_base = { size = 4 current_size = 4 } }
province = { id = 2120 infra = { size = 0.20 current_size = 0.20 } } #Sept-Iles
province = { id = 2121 infra = { size = 0.30 current_size = 0.30 } } #Chicoutimi
province = { id = 2124 ic = -1 } #Gatineau
province = { id = 2126 ic = 1 infra = { size = 0.50 current_size = 0.50 } } #Riviere-du-Loup
province = { id = 2128 infra = { size = 0.50 current_size = 0.50 } } #Fredericton
province = { id = 2129 ic = 1 } #Sault Ste Marie
province = { id = 2130 ic = 2 manpower = 1 #Saint John
	infra = { size = 0.50 current_size = 0.50 } }
province = { id = 2131 ic = 1 infra = { size = 0.50 current_size = 0.50 } } #Moncton
province = { id = 2132 ic = 2 manpower = 1 coastalfort = 2 anti_air = 3 #Halifax
	naval_base = { size = 6 current_size = 6 } air_base = { size = 4 current_size = 4 } }
province = { id = 2133 ic = -1 } #Charlottetown
province = { id = 2134 anti_air = 2 infra = { size = 0.50 current_size = 0.50 } #Glace Bay
	naval_base = { size = 4 current_size = 4 } air_base = { size = 6 current_size = 6 } }
province = { id = 2136 infra = { size = 0.20 current_size = 0.20 } } #Goose Bay
province = { id = 2137 ic = 1 anti_air = 2 #St. Johns
	naval_base = { size = 10 current_size = 10 } air_base = { size = 6 current_size = 6 } }
province = { id = 2138 infra = { size = 0.10 current_size = 0.10 } } #Nain

### CGX
province = { id = 1308 ic = 1 anti_air = 1 } #Changsha
province = { id = 1309 ic = -2 } #Xiangtan
province = { id = 1311 ic = 1 } #Chenzhou
province = { id = 1312 ic = 1 anti_air = 1 #Henyang
	air_base = { size = 4 current_size = 4 } }
province = { id = 1313 ic = 1 } #Shashi
province = { id = 1351 anti_air = 1 #Shangrao
 	air_base = { size = 2 current_size = 2 } }
province = { id = 1352 ic = 1 } #Nanchang
province = { id = 1360 ic = 1 } #Xiamen
province = { id = 1368 ic = 1 } #Shaoguan
province = { id = 1369 ic = 1 #Guangzhou
	naval_base = { size = 4 current_size = 4 } air_base = { size = 5 current_size = 5 } }
province = { id = 1370 ic = 1 } #Lufeng
province = { id = 1373 ic = -4 } #Jiangmen
province = { id = 1375 ic = 1 } #Shantou
province = { id = 1376 infra = { size = 0.20 current_size = 0.20 } } #Debao
province = { id = 1379 ic = -1 } #Nanning
province = { id = 1380 ic = -1 } #Liuzhou

### CHL
province = { id = 2023 ic = 7 anti_air = 2 #Santiago de Chile
	naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }
province = { id = 2025 ic = -7 } #Antofagasta

### COL
province = { id = 1986 anti_air = 1
	naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } }
province = { id = 1990 anti_air = 1 } #Cartagena
province = { id = 1991 anti_air = 2 } #Bogota

### CON
province = { id = 842 ic = 1 anti_air = 1 #Mombasa
air_base = { size = 4 current_size = 4 } }
province = { id = 850 ic = 4 anti_air = 4 #Dar es Salaam
naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 882 anti_air = 2 #Swakopmund
naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }
province = { id = 894 anti_air = 2 #Matadi
naval_base = { size = 3 current_size = 3 } air_base = { size = 2 current_size = 2 } }
province = { id = 929 ic = 1 anti_air = 1 #Lagos
air_base = { size = 4 current_size = 4 } }
province = { id = 915 ic = 1 } #Libreville
province = { id = 956 ic = 1 anti_air = 2 #Accra
naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }
province = { id = 863 air_base = { size = 2 current_size = 2 } } #Lusaka


### CRO
province = { id = 337 ic = 1 infra = { size = 0.30 current_size = 0.30 } } #Ruma
province = { id = 343 ic = 1 anti_air = 2 #Dubrovnik
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 344 ic = 1 anti_air = 1 #Osijek
	infra = { size = 0.40 current_size = 0.40 } }
province = { id = 345 infra = { size = 0.40 current_size = 0.40 } } #Bjelovar
province = { id = 347 ic = 2 #Karlovac
	naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 350 ic = -1 anti_air = 2 #Split
	air_base = { size = 2 current_size = 2 } }
province = { id = 352 ic = 1 anti_air = 2 } #Zagreb

### CSX
province = { id = 1242 ic = 1 } #Shijazhuang
province = { id = 1243 ic = 1 } #Baoding
province = { id = 1245 ic = 3 } #Tangshen
province = { id = 1247 anti_air = 4 #Beijing
	air_base = { size = 6 current_size = 6 } }
province = { id = 1249 infra = { size = 0.30 current_size = 0.30 } } #Yangquan
province = { id = 1251 ic = 1 } #Datong
province = { id = 1252 ic = -3 } #Taiyuan
province = { id = 1253 ic = 1 infra = { size = 0.40 current_size = 0.40 } } #Linfen
province = { id = 1255 landfort = 3 } #Pingliang
province = { id = 1256 landfort = 1 } #Baoji
province = { id = 1257 ic = -1 landfort = 1 } #Tongguan
province = { id = 1258 ic = 1 landfort = 1 } #Xi'an
province = { id = 1259 landfort = 4 infra = { size = 0.20 current_size = 0.20 } } #Yan'an
province = { id = 1260 ic = -4 landfort = 1 } #Yulin
province = { id = 1263 landfort = 1 } #Tianshoui
province = { id = 1269 landfort = 2 } #Uqai
province = { id = 1271 landfort = 1 } #Wuzhong
province = { id = 1317 ic = 1 } #Wuhan
province = { id = 1319 ic = 1 } #Kaifeng
province = { id = 1321 infra = { size = 0.40 current_size = 0.40 } } #Xinxiang
province = { id = 1322 ic = 1 } #Luoyang
province = { id = 1323 ic = 1 } #Anyang
province = { id = 1324 ic = -2 } #Zhengzhou
province = { id = 1327 infra = { size = 0.30 current_size = 0.30 } } #Heze
province = { id = 1330 ic = 2 anti_air = 2 #Qing Jinan
	air_base = { size = 4 current_size = 4 } }
province = { id = 1331 infra = { size = 0.20 current_size = 0.20 } } #Yantai
province = { id = 1332 infra = { size = 0.20 current_size = 0.20 } } #Zaozhuang
province = { id = 1333 ic = 1 } #Huaiyan
province = { id = 1334 ic = 1 anti_air = 2 #Nantong
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id = 1336 ic = 1 } #Xuzhou
province = { id = 1337 ic = -7 } #Nanjing
province = { id = 1340 ic = -1 } #Hefei
province = { id = 1345 ic = -2 } #Hangzhou

### CUB
province = { id = 1775 infra = { size = 0.30 current_size = 0.30 } } #Camaguey
province = { id = 1776 anti_air = 1 infra = { size = 0.40 current_size = 0.40 } #Havana
	naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } }
province = { id = 1777 infra = { size = 0.40 current_size = 0.40 } } #Santiago de Cuba
province = { id = 1779 infra = { size = 0.40 current_size = 0.40 } } #Santa Clara

### CXB
province = { id = 1265 infra = { size = 0.20 current_size = 0.20 } } #Zhangye
province = { id = 1266 infra = { size = 0.20 current_size = 0.20 } } #Yumen
province = { id = 1272 ic = -1 } #Bayan Hot
province = { id = 1277 infra = { size = 0.20 current_size = 0.20 } } #Qumul
province = { id = 1281 ic = -3 infra = { size = 0.20 current_size = 0.20 } } #Urumqi
province = { id = 1283 ic = -4 } #Ge'ermu
province = { id = 1284 air_base = { size = 6 current_size = 6 } } #Xining

### CZE
province = { id = 196 ic = 3 anti_air = 2 #Brno
	air_base = { size = 3 current_size = 3 } manpower = 2 }
province = { id = 197 ic = -2 } #Znojmo
province = { id = 198 air_base = { size = 6 current_size = 6 } } #Hradec Kralove
province = { id = 199 ic = 7 anti_air = 2 #Plzen
	air_base = { size = 7 current_size = 7 } manpower = 2 }
province = { id = 201 ic = 2 manpower = 2 } #Ostrava
province = { id = 202 ic = 4 } #Ceske Budejovice
province = { id = 203 ic = 2 } #Tesin
province = { id = 205 air_base = { size = 4 current_size = 4 } } #Karlovy Vary
province = { id = 207 ic = 5 anti_air = 3 #Prague
	air_base = { size = 6 current_size = 6 } manpower = 2 }

### DEN
province = { id = 219 manpower = 1 } #Odense

#Iceland
province = { id = 1 ic = 4 anti_air = 1 #Reykjavik
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }

#Denmark
province = { id = 217 anti_air = 1 #Aalborg
	naval_base = { size = 1 current_size = 1 } air_base = { size = 4 current_size = 4 } }
province = { id = 220 naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } } #Aarhus
province = { id = 294 anti_air = 2 #Copenhagen
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }

### DOM
province = { id = 1780 naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } } #Ciudad Trujillo

### EAF
province = { id = 1338 ic = 5 anti_air = 2 #Shanghai
	naval_base = { size = 10 current_size = 10 } air_base = { size = 6 current_size = 6 } }
province = { id = 1346 ic = 1 #Ningbo
	naval_base = { size = 8 current_size = 8 } }
province = { id = 1358 ic = 1 #Fuzhou
	naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } }
province = { id = 1371 ic = 2 landfort = 1 coastalfort = 1 anti_air = 4 oilpool = 100 supplypool = 500 #Hong Kong
	naval_base = { size = 8 current_size = 8 } air_base = { size = 4 current_size = 4 } }
 
### ECU
province = { id = 2007 infra = { size = 0.20 current_size = 0.20 } } #Puyo
province = { id = 2008 infra = { size = 0.10 current_size = 0.10 } } #Iquitos
province = { id = 2010 infra = { size = 0.10 current_size = 0.10 } } #Nanta
province = { id = 2033 infra = { size = 0.20 current_size = 0.20 } } #Jaen
province = { id = 2040 naval_base = { size = 3 current_size = 3 } } #Santiago de Guayaquil
province = { id = 2042 anti_air = 2 #San Francisco de Quito 
	air_base = { size = 1 current_size = 1 } }

### EGY

#Egypt
province = { id = 787 ic = 7 anti_air = 2 #Cario (Mar2020 - previously ic = 8, increased airbase)
	air_base = { size = 7 current_size = 7 } }
province = { id = 789 ic = 5 anti_air = 3 #Alexandria (previously ic = 6)
	naval_base = { size = 8 current_size = 8 } air_base = { size = 7 current_size = 7 } }
#province = { id = 790 air_base = { size = 4 current_size = 4 } } #Tanta
#province = { id = 1007 anti_air = 2 #Suez
#	naval_base = { size = 4 current_size = 4 } }

#Sudan
province = { id = 810 ic = 1 anti_air = 1 #Khartoum
	air_base = { size = 4 current_size = 4 } }
province = { id = 813 ic = 1 #Port Sudan (previously ic = 4)
	naval_base = { size = 3 current_size = 3 } }

### ENG
province = { id = 5 anti_air = 4 #Scapa Flow
	naval_base = { size = 10 current_size = 10 } air_base = { size = 4 current_size = 4 } }
province = { id = 10 ic = -6 } #Dumfries
province = { id = 11 ic = 2 anti_air = 2 #Glasgow
	air_base = { size = 4 current_size = 4 } }
province = { id = 12 ic = 1 anti_air = 2 #Edinburgh
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 13 naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } } #Sunderland
province = { id = 14 ic = 3 } #Carlisle
province = { id = 15 anti_air = 2 #Hull
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 16 ic = 2 manpower = 2 } #Lincoln
province = { id = 17 ic = 5 anti_air = 3 #Manchester
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 18 ic = -5 manpower = 3 } #Sheffield
province = { id = 19 ic = 2 anti_air = 4 #Bristol
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 21 ic = 1 manpower = 1 anti_air = 2 #Caernarfon
	air_base = { size = 4 current_size = 4 } }
province = { id = 22 ic = -9 naval_base = { size = 3 current_size = 3 } } #Cardiff
province = { id = 23 anti_air = 6 #Plymouth
	naval_base = { size = 5 current_size = 5 } air_base = { size = 4 current_size = 4 } }
province = { id = 24 ic = 8 anti_air = 2 manpower = 5 } #Birmingham
province = { id = 25 anti_air = 4 #Norwich
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 26 coastalfort = 3 anti_air = 5 #Dover
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 27 ic = 2 anti_air = 6 #Portsmuth
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 28 ic = 2 manpower = 2 } #Oxford
province = { id = 29 anti_air = 3 #London
	air_base = { size = 10 current_size = 10 } }

### ETH
province = { id = 815 ic = 1 anti_air = 1 infra = { size = 0.20 current_size = 0.20 } #Massawa
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 817 infra = { size = 0.20 current_size = 0.20 } } #Asmara
province = { id = 818 ic = 1 } #Dire Dawa
province = { id = 820 ic = 1 } #Dessie
province = { id = 825 ic = 2 anti_air = 2 #Addis Abeba
	air_base = { size = 6 current_size = 6 } }
province = { id = 828 ic = 3 } #Harer
province = { id = 830 ic = -4 } #Arba Minch
province = { id = 836 ic = 3 #Mogadishu
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }

### FIN
province = { id = 517 #Petsamo
	naval_base = { size = 4 current_size = 4 } air_base = { size = 3 current_size = 3 } }
province = { id = 520 #Oulu
	air_base = { size = 4 current_size = 4 } }
province = { id = 524 coastalfort = 1 anti_air = 2 #Turku
	naval_base = { size = 5 current_size = 5 } air_base = { size = 2 current_size = 2 } }
province = { id = 525 coastalfort = 1 anti_air = 3 #Helsinki
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id = 527 anti_air = 2 #Tampere
	air_base = { size = 2 current_size = 2 } }
province = { id = 531 landfort = 2 anti_air = 3 manpower = 1 #Viipuri
	naval_base = { size = 1 current_size = 1 } air_base = { size = 4 current_size = 4 } }
province = { id = 532 landfort = 2 } #Sortavala

### FRA
province = { id = 37 ic = 1 anti_air = 2 #Brest
	naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 39 ic = 3 #Lorient
	air_base = { size = 10 current_size = 10 } }
province = { id = 40 ic = 2 manpower = 1 } #Saint-Nazaire
province = { id = 43 anti_air = 3 #Cherbourg
	naval_base = { size = 6 current_size = 6 } air_base = { size = 5 current_size = 5 } }
province = { id = 44 ic = 2 anti_air = 1 } #Caen
province = { id = 45 ic = 2 #Le Havre
	naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 49 naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } } #Calais
province = { id = 50 manpower = 2 } #Amiens
province = { id = 51 landfort = 4 anti_air = 2 manpower = 1 } #Dunkirk
province = { id = 52 landfort = 4 anti_air = 3 #Lille
	air_base = { size = 10 current_size = 10 } }
province = { id = 55 ic = 1 anti_air = 8 #Paris
	air_base = { size = 10 current_size = 10 } }
province = { id = 57 anti_air = 2 } #Nantes
province = { id = 66 ic = 2 } #Orleans
province = { id = 63 ic = 1 #Auxerre
	air_base = { size = 10 current_size = 10 } }
province = { id = 67 landfort = 2 } #Mont-de-Marsan
province = { id = 68 anti_air = 4 manpower = 2 #Bordeaux
	naval_base = { size = 10 current_size = 10 } air_base = { size = 4 current_size = 4 } }
province = { id = 74 ic = 2 anti_air = 1 } #Vichy
province = { id = 78 ic = 1 } #Leroges
province = { id = 71 ic = 1 } #Clermont-Ferrand
province = { id = 77 air_base = { size = 10 current_size = 10 } } #Toulouse
province = { id = 80 landfort = 2 anti_air = 1 #Perpignan
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 83 landfort = 2 } #Pau
province = { id = 85 ic = 1 } #Lyon
province = { id = 86 landfort = 3 anti_air = 3 #Toulon
	naval_base = { size = 10 current_size = 10 } air_base = { size = 2 current_size = 2 } }
province = { id = 88 landfort = 3 anti_air = 1 } #Bourg-en-Bresse
province = { id = 89 ic = 1 anti_air = 5 manpower = 2 #Marseille
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 90 landfort = 3 anti_air = 1 manpower = 1 } #Grenoble
province = { id = 92 landfort = 3 anti_air = 1 } #Valence
province = { id = 95 landfort = 4 anti_air = 3 } #Chaumont
province = { id = 97 landfort = 3 anti_air = 1 } #Belfort
province = { id = 98 landfort = 3 anti_air = 1 } #Pontarlier
province = { id = 100 landfort = 6 anti_air = 2 } #Verdun
province = { id = 102 landfort = 4 anti_air = 2 } #Sedan
province = { id = 103 landfort = 4 anti_air = 2 } #Hirson
province = { id = 104 ic = 3 anti_air = 3 #Metz
	air_base = { size = 10 current_size = 10 } }

### GUA
province = { id = 2086 naval_base = { size = 2 current_size = 2 } } #Belize City

### GEO
province = { id = 708 ic = 2 anti_air = 2 #Kutaisi
	naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }
province = { id = 709 ic = 4 landfort = 3 anti_air = 1 } #Tbilisi
province = { id = 710 ic = 1 } #Sukhumi

### GER

#African colonies
province = { id = 718 anti_air = 3 #Casablanca
naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 900 anti_air = 2 naval_base = { size = 7 current_size = 7 } #Suez (Mar2020 - increased navalbase, added anti_air)
	air_base = { size = 3 current_size = 3 } }
province = { id = 964 anti_air = 2 #Freetown
naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }
province = { id = 833 anti_air = 2 #Djibouti
naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }

#Arabia/Indian Ocean colonies
province = { id = 996 naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 } } #Saint Denis de la Reunion
province = { id = 1001 naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } } #Tananarive
province = { id = 1053 coastalfort = 1 anti_air = 4 #Aden
naval_base = { size = 6 current_size = 6 } air_base = { size = 4 current_size = 4 } }
province = { id = 1511 coastalfort = 1 anti_air = 2 oilpool = 1000 supplypool = 2000 #Colombo
naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 1611 naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } } #Male

#Asian colonies
province = { id = 1241 ic = 3 #Tianjin
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id = 1328 ic = 2 landfort = 1 coastalfort = 1 anti_air = 2 #Qingdao
	naval_base = { size = 10 current_size = 10 } air_base = { size = 7 current_size = 7 } }
province = { id = 1365 #Haikou
	naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 } }
province = { id = 1367 coastalfort = 1 anti_air = 2 #Zhanjiang
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 1395 anti_air = 2 infra = { size = 0.40 current_size = 0.40 } oilpool = 100 supplypool = 500 #Hanoi
	naval_base = { size = 1 current_size = 1 } air_base = { size = 4 current_size = 4 } }
province = { id = 1392 anti_air = 2 #Haiphong
	naval_base = { size = 4 current_size = 4 } }
province = { id = 1397 naval_base = { size = 2 current_size = 2 } } #Da Nang
province = { id = 1399 anti_air = 3 oilpool = 100 supplypool = 500 #Saigon
	naval_base = { size = 6 current_size = 6 } air_base = { size = 10 current_size = 10 } }
province = { id = 1432 landfort = 3 coastalfort = 4 anti_air = 4 ic = 2 oilpool = 500 supplypool = 5000 #Singapore
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1438 anti_air = 1 #Kuala Lumpur
	naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } }
province = { id = 1624 naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } } #Kuching

#Kaiserreich
province = { id = 126 ic = -2 } #Aachen
province = { id = 127 anti_air = 2 } #Saarbrücken
province = { id = 128 ic = 1 } #Trier
province = { id = 129 ic = 2 anti_air = 2 } #Köln
province = { id = 130 ic = 1 anti_air = 2 } #Mannheim
province = { id = 134 anti_air = 2 #Stuttgart
	air_base = { size = 4 current_size = 4 } }
province = { id = 137 anti_air = 2 #Kassel
	air_base = { size = 4 current_size = 4 } }
province = { id = 138 anti_air = 1 #Frankfurt/Main
	air_base = { size = 4 current_size = 4 } }
province = { id = 141 ic = -5 anti_air = 3 } #Muenster
province = { id = 142 anti_air = 2 #Duesseldorf
	air_base = { size = 10 current_size = 10 } }
province = { id = 145 ic = 7 anti_air = 3 #Essen
	air_base = { size = 4 current_size = 4 } }
province = { id = 147 naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } } #Wilhelmshaven
province = { id = 148 naval_base = { size = 10 current_size = 10 } } #Bremen
province = { id = 151 anti_air = 1 #Lubeck
	naval_base = { size = 3 current_size = 3 } air_base = { size = 10 current_size = 10 } }
province = { id = 152 anti_air = 1 #Kiel
	naval_base = { size = 10 current_size = 10 } air_base = { size = 4 current_size = 4 } }
province = { id = 153 anti_air = 2 #Rostock
	naval_base = { size = 10 current_size = 10 } air_base = { size = 4 current_size = 4 } }
province = { id = 154 anti_air = 2 #Hamburg
	naval_base = { size = 10 current_size = 10 } }
province = { id = 163 anti_air = 2 #Berlin
	air_base = { size = 10 current_size = 10 } }	
province = { id = 164 ic = 2 } #Oppeln
province = { id = 167 ic = 6 landfort = 1 anti_air = 3 #Breslau
	air_base = { size = 10 current_size = 10 } }
province = { id = 168 ic = 2 manpower = 1 } #Gleitwitz
province = { id = 169 anti_air = 2 } #Magdeburg
province = { id = 170 anti_air = 1 } #Leipzig
province = { id = 173 ic = -8 air_base = { size = 10 current_size = 10 } } #Dresden
province = { id = 177 anti_air = 1 } #Nuremberg
province = { id = 179 anti_air = 2 #Munich
	air_base = { size = 10 current_size = 10 } }
province = { id = 181 ic = 2 anti_air = 2 #Gdansk
	naval_base = { size = 5 current_size = 5 } }
province = { id = 183 supplypool = 100 } #Elbing
province = { id = 184 anti_air = 4 #Koeningsberg
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 221 ic = 2 } #Katowice
province = { id = 222 landfort = 3 anti_air = 3 } #Torun
province = { id = 224 landfort = 3 anti_air = 4 } #Poznan
province = { id = 226 anti_air = 1 #Gdynia
	naval_base = { size = 3 current_size = 3 } air_base = { size = 5 current_size = 5 } }
province = { id = 261 anti_air = 1 #Klaipeda
	naval_base = { size = 2 current_size = 2 } air_base = { size = 1 current_size = 1 } }
	
#Oceaninic colonies
#province = { id = 1582 naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } } #Espiritu Santo
province = { id = 1586 naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } } #Nouvelle-Caledonia
#province = { id = 1587 anti_air = 3 #Bougainville #North Solomon Islands
#	naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } }
#province = { id = 1590 naval_base = { size = 4 current_size = 4 } } #Lunga
#province = { id = 1593 air_base = { size = 4 current_size = 4 } } #Guadalcanal
province = { id = 1667 anti_air = 5 infra = { size = 0.30 current_size = 0.30 } oilpool = 200 supplypool = 1000 #Truk
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1686 anti_air = 1 #Pagan
	naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 } }
#province = { id = 1725 naval_base = { size = 7 current_size = 7 } air_base = { size = 7 current_size = 7 } } #Kavieng
province = { id = 1726 anti_air = 2 #Rabaul
	naval_base = { size = 7 current_size = 7 } air_base = { size = 7 current_size = 7 } }
#province = { id = 1727 anti_air = 2 #Kimbe #Previously New britian
#	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 1728 infra = { size = 0.20 current_size = 0.20 } #Suva
	naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 } }

#Post 1870 European gains
province = { id = 96 ic = 2 landfort = 4 anti_air = 2 } #Longwy
province = { id = 105 landfort = 4 anti_air = 2 } #Colmar
province = { id = 106 landfort = 4 anti_air = 2 } #Nancy
province = { id = 108 landfort = 4 anti_air = 2 } #Liege
province = { id = 111 landfort = 4 anti_air = 2 } #Arlon
province = { id = 429 landfort = 3 coastalfort = 2 anti_air = 2 oilpool = 100 supplypool = 500 #Malta
	naval_base = { size = 5 current_size = 5 } air_base = { size = 4 current_size = 4 } }

### GLD
province = { id = 237 ic = -1 } #Tarnow
province = { id = 239 landfort = 2 anti_air = 1 } #Pryzemysl
province = { id = 240 ic = -1 } #Tarnopol
province = { id = 242 anti_air = 2 #Lwow
	air_base = { size = 5 current_size = 5 } }

### GRE
province = { id = 367 naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 } } #Ioannina
province = { id = 368 landfort = 2 anti_air = 1 } #Larissa
province = { id = 369 landfort = 2 anti_air = 1 } #Metsovo
province = { id = 372 manpower = 1 ic = 1 infra = { size = 0.40 current_size = 0.40 } } #Patra
province = { id = 373 naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } } #Corinith
province = { id = 374 ic = -4 infra = { size = 0.20 current_size = 0.20 } } #Chalcis
province = { id = 375 ic = 1 infra = { size = 0.40 current_size = 0.40 } } #Levadhia
province = { id = 377 anti_air = 1 ic = 3 manpower = 3 infra = { size = 0.50 current_size = 0.50 } #Athens
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 388 naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } } #Nicosia

### GUA
province = { id = 2079 ic = -2 #San Salvador
	naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 } }
province = { id = 2087 ic = -4 manpower = 1 } #Puerto Barrios
province = { id = 2088 anti_air = 1 ic = -2 manpower = 3 #Cuidad de Guatemala
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }

### GUY
province = { id = 1758 ic = 1 anti_air = 1 #Trinidad
	air_base = { size = 4 current_size = 4 } infra = { size = 0.40 current_size = 0.40 } }
province = { id = 1773 anti_air = 1 oilpool = 100 infra = { size = 0.40 current_size = 0.40 } #Bermudas
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } supplypool = 500 }
province = { id = 1782 ic = 2 infra = { size = 0.40 current_size = 0.40 } #Jamaica
	air_base = { size = 2 current_size = 2 } }
province = { id = 1997 ic = 2 anti_air = 1 #Georgetown
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 2000 ic = 2 } #Cayenne

### HAI
province = { id = 1781 anti_air = 1 #Port-au-Prince
	naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }

### HOL

#Indonesia
province = { id = 1615 air_base = { size = 4 current_size = 4 } } #Flores
province = { id = 1632 ic = 1 infra = { size = 0.20 current_size = 0.20 } #Balikpapan
	naval_base = { size = 4 current_size = 4 } air_base = { size = 3 current_size = 3 } }
province = { id = 1636 anti_air = 2 infra = { size = 0.30 current_size = 0.30 } #Palembang
	naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }
province = { id = 1637 ic = 1 } #Padang
province = { id = 1640 infra = { size = 0.20 current_size = 0.20 } } #Koeta-Radja
province = { id = 1641 infra = { size = 0.30 current_size = 0.30 } } #Oosthaven
province = { id = 1642 anti_air = 2 #Medan
	naval_base = { size = 3 current_size = 3 } air_base = { size = 2 current_size = 2 } }
province = { id = 1646 ic = 1 infra = { size = 0.40 current_size = 0.40 } } #Tjilatjap
province = { id = 1647 ic = 2 anti_air = 2 infra = { size = 0.50 current_size = 0.50 } #Batavia
  naval_base = { size = 6 current_size = 6 } oilpool = 100 supplypool = 500 air_base = { size = 6 current_size = 6 } }
province = { id = 1648 infra = { size = 0.40 current_size = 0.40 } } #Tjilegon
province = { id = 1649 ic = 1 infra = { size = 0.40 current_size = 0.40 } } #Tjirebon
province = { id = 1650 ic = -1 infra = { size = 0.40 current_size = 0.40 } } #Semarang
province = { id = 1651 infra = { size = 0.40 current_size = 0.40 } } #Bandoeng
province = { id = 1652 infra = { size = 0.40 current_size = 0.40 } } #Rembang
province = { id = 1653 infra = { size = 0.50 current_size = 0.50 } anti_air = 2 #Soerabaja
	ic = 2 naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }
province = { id = 1654 ic = 1 infra = { size = 0.40 current_size = 0.40 } } #Jogjakarta
province = { id = 1655 infra = { size = 0.40 current_size = 0.40 } } #Malang
province = { id = 1656 infra = { size = 0.30 current_size = 0.30 } } #Madura
province = { id = 1658 naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } } #Kendari

#Netherlands
province = { id = 118 anti_air = 2 air_base = { size = 4 current_size = 4 } } #Eindhoven
province = { id = 119 anti_air = 1 landfort = 2 #Arnhem
	air_base = { size = 4 current_size = 4 } }
province = { id = 120 landfort = 1 } #Nijmegen
province = { id = 121 ic = 1 } #Maastricht
province = { id = 122 anti_air = 3 manpower = 2 coastalfort = 3 #Amsterdam
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 123 landfort = 1 anti_air = 1 #Middelburg
	naval_base = { size = 3 current_size = 3 } }
province = { id = 125 manpower = 3 anti_air = 3 coastalfort = 2 #Rotterdam
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }

### HON
province = { id = 2085 anti_air = 1 ic = -2 manpower = 2 #Tegucigalpa
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }

### HUN

#Hungary
province = { id = 278 ic = -9 } #Szekesfehervar
province = { id = 281 ic = 2 } #Debrecen
province = { id = 282 ic = 1 } #Miskolc
province = { id = 284 ic = 5 anti_air = 2 #Budapest
	air_base = { size = 8 current_size = 8 } }
province = { id = 286 infra = { size = 0.50 current_size = 0.50 } } #Arad
province = { id = 287 infra = { size = 0.40 current_size = 0.40 } } #Turda
province = { id = 288 infra = { size = 0.50 current_size = 0.50 } #Cluj
	anti_air = 2 air_base = { size = 5 current_size = 5 } }
province = { id = 291 infra = { size = 0.50 current_size = 0.50 } } #Sibiu
province = { id = 295 ic = 2 infra = { size = 0.40 current_size = 0.40 } } #Resita
province = { id = 336 infra = { size = 0.40 current_size = 0.40 } } #Petrovgrad

#Slovakia
province = { id = 208 ic = -4 anti_air = 2 #Bratislava
	air_base = { size = 3 current_size = 3 } }
province = { id = 209 ic = -1 } #Kosice
province = { id = 211 ic = -1 } #Banska Bystrica
province = { id = 212 ic = 3 } #Zilina
province = { id = 214 ic = -4 } #Presov

### IND
province = { id = 1487 anti_air = 1 #Hyderbad
	air_base = { size = 4 current_size = 4 } }
province = { id = 1494 ic = -2 } #Nellore
province = { id = 1502 ic = -2 } #Bangalore
province = { id = 1504 ic = -1 } #Madurai
province = { id = 1512 ic = -2 } #Kohlapur
province = { id = 1515 ic = -2 } #Hubli
province = { id = 1516 ic = 2 } #Poona
province = { id = 1517 ic = -2 anti_air = 3 #Bombay
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }

### ITA
province = { id = 87 ic = -3 } #Nice
province = { id = 91 ic = 2 } #Chambery
province = { id = 94 naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } } #Corsica
province = { id = 379 naval_base = { size = 2 current_size = 2 } #Rodos
	air_base = { size = 4 current_size = 4 } infra = { size = 0.30 current_size = 0.30 } }
province = { id = 395 ic = -2 } #Bergamo
province = { id = 396 landfort = 2 anti_air = 2 ic = 4 #Genoa
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 398 landfort = 2 anti_air = 3 ic = 2 #Turin
	air_base = { size = 4 current_size = 4 } }
province = { id = 399 ic = 1 } #Alessandria
province = { id = 407 anti_air = 3 ic = 1 #Milano
	air_base = { size = 10 current_size = 10 } }
province = { id = 408 ic = 1 } #Parma
province = { id = 410 anti_air = 3 ic = -1 #Florence
	naval_base = { size = 3 current_size = 3 } }
province = { id = 411 anti_air = 1 ic = -1 } #Bologna
province = { id = 412 ic = 1 #Ancona
	air_base = { size = 3 current_size = 3 } naval_base = { size = 3 current_size = 3 } }
province = { id = 413 anti_air = 2 ic = 2 #Livorno
	air_base = { size = 5 current_size = 5 } naval_base = { size = 5 current_size = 5 } }
province = { id = 414 anti_air = 1 } #Perugia
province = { id = 416 ic = -1 } #Anzio
province = { id = 419 anti_air = 1 #Rome
	air_base = { size = 10 current_size = 10 } }
province = { id = 434 anti_air = 1 #Cagliari
	naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }

### IRE
province = { id = 31 anti_air = 1 #Cork
	naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }
province = { id = 34 anti_air = 2 #Dublin
	naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }
province = { id = 36 anti_air = 2 coastalfort = 1 #Belfast
	naval_base = { size = 6 current_size = 6 } air_base = { size = 3 current_size = 3 } }

### JAP

#Korea/Port Arthur/Sakhalin
province = { id = 1219 ic = 2 anti_air = 2 infra = { size = 0.50 current_size = 0.50 } #Port Arthur
naval_base = { size = 8 current_size = 8 } air_base = { size = 7 current_size = 7 } }
province = { id = 1221 anti_air = 2 #Pyongyang
air_base = { size = 4 current_size = 4 } }
province = { id = 1228 naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } } #Seoul
province = { id = 1230 naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } } #Gwuangju
province = { id = 1232 anti_air = 2 #Busan
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1541 oilpool = 100 supplypool = 500 } #Okha
province = { id = 1542 anti_air = 2 infra = { size = 0.20 current_size = 0.20 } #Toyohara
naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } oilpool = 100 supplypool = 500 }

#Japan
province = { id = 1544 ic = -1 naval_base = { size = 6 current_size = 6 } } #Kushrio
province = { id = 1545 ic = 1 infra = { size = 0.40 current_size = 0.40 } #Sapporo
	naval_base = { size = 5 current_size = 5 } air_base = { size = 6 current_size = 6 } }
province = { id = 1546 ic = 1 } #Shizuoka
province = { id = 1547 ic = 1 anti_air = 2 #Akita
	air_base = { size = 6 current_size = 6 } }
province = { id = 1548 ic = 1 } #Nagano
province = { id = 1549 ic = 2 #Sendai
	naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 1550 anti_air = 2 #Yokohama
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1551 anti_air = 2 #Niigata
	naval_base = { size = 6 current_size = 6 } air_base = { size = 4 current_size = 4 } }
province = { id = 1552 ic = 7 anti_air = 2 #Tokyo
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1553 ic = 2 anti_air = 2 infra = { size = 0.50 current_size = 0.50 } #Osaka
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1554 anti_air = 2 #Hiroshima
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1555 anti_air = 2 #Kobe
	naval_base = { size = 10 current_size = 10 } }
province = { id = 1556 anti_air = 2 infra = { size = 0.40 current_size = 0.40 } #Kanazawa
	naval_base = { size = 5 current_size = 5 } air_base = { size = 3 current_size = 3 } }
province = { id = 1557 ic = 3 anti_air = 2 #Nagoya
	naval_base = { size = 8 current_size = 8 } air_base = { size = 10 current_size = 10 } }
province = { id = 1558 anti_air = 2 #Kyoto
	naval_base = { size = 8 current_size = 8 } air_base = { size = 4 current_size = 4 } }
province = { id = 1559 #Matsuyama
	naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }
province = { id = 1560 infra = { size = 0.50 current_size = 0.50 } #Nagasaki
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
#province = { id = 1562 naval_base = { size = 2 current_size = 2 } air_base = { size = 3 current_size = 3 } } #Amami
province = { id = 1561 ic = -1 #Kagoshima
	naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } }
#province = { id = 1675 anti_air = 5 #Eniwetok
#	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
#province = { id = 1676 anti_air = 5 #Kwajalein
#	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }

#Islands
province = { id = 1563 anti_air = 1 oilpool = 100 supplypool = 500 #Southern Okinawa
	naval_base = { size = 4 current_size = 4 } air_base = { size = 3 current_size = 3 } }
province = { id = 1564 oilpool = 100 supplypool = 500 } #Northern Okinawa
#province = { id = 1661 naval_base = { size = 4 current_size = 4 } } #Iwo Jima
#province = { id = 1663 anti_air = 2 air_base = { size = 4 current_size = 4 } } #Motoyama
province = { id = 1672 air_base = { size = 1 current_size = 1 } } #Minami Torishima

#Taiwan
province = { id = 1361 oilpool = 100 supplypool = 500 #Gaoxiong
	naval_base = { size = 6 current_size = 6 } }
province = { id = 1362 anti_air = 4 oilpool = 100 supplypool = 500 #Taipei
	naval_base = { size = 8 current_size = 8 } air_base = { size = 10 current_size = 10 } }
province = { id = 1363 oilpool = 100 supplypool = 500 } #Taizhong

### KAZ
province = { id = 500 ic = 2 infra = { size = 0.30 current_size = 0.30 } } #Balkhash
province = { id = 501 infra = { size = 0.30 current_size = 0.30 } } #Kokchetav
province = { id = 502 infra = { size = 0.40 current_size = 0.40 } } #Akmolinsk
province = { id = 503 ic = 1 #Karaganda
	infra = { size = 0.30 current_size = 0.30 } air_base = { size = 1 current_size = 1 } }
province = { id = 504 ic = 5 #Alma-ata
	infra = { size = 0.40 current_size = 0.40 } air_base = { size = 2 current_size = 2 } }
province = { id = 505 infra = { size = 0.30 current_size = 0.30 } } #Sar
province = { id = 506 infra = { size = 0.30 current_size = 0.30 } } #Taldy-Kurgan
province = { id = 507 ic = 1 } #Ust-Kamenogorsk
province = { id = 706 ic = 3 anti_air = 3 #Astrakhan
	air_base = { size = 4 current_size = 4 } }
province = { id = 1108 infra = { size = 0.30 current_size = 0.30 } } #Dzambul
province = { id = 1109 infra = { size = 0.30 current_size = 0.30 } } #Chimkent
province = { id = 1110 ic = 1 infra = { size = 0.30 current_size = 0.30 } } #Kzyl-Orda
province = { id = 1113 ic = 1 } #Uralsk
province = { id = 1114 ic = 1 } #Aktyubinsk
province = { id = 1116 ic = 1 } #Derzhavinsk
province = { id = 1117 ic = 1 infra = { size = 0.30 current_size = 0.30 } } #Chelkar
province = { id = 1118 ic = 1 } #Fort Alexandrovsky

 ### KYG
province = { id = 1097 ic = -1 anti_air = 1 } #Ashkhabad
province = { id = 1098 ic = 1 infra = { size = 0.30 current_size = 0.30 } } #Merv
province = { id = 1099 ic = 7 manpower = 3 #Samarkand
	infra = { size = 0.40 current_size = 0.40 } air_base = { size = 2 current_size = 2 } }
province = { id = 1100 ic = 2 infra = { size = 0.30 current_size = 0.30 } } #Bukhara
province = { id = 1103 ic = 6 manpower = 4 #Tashkent
	infra = { size = 0.40 current_size = 0.40 } }
province = { id = 1106 ic = 1 } #Osh

### LAT

#Estonia
province = { id = 272 ic = 1 } #Tartu
province = { id = 273 landfort = 1 } #Voru
province = { id = 274 ic = 1 landfort = 1 } #Narva
province = { id = 275 infra = { size = 0.20 current_size = 0.20 } } #Kuressaare
province = { id = 270 manpower = 2 landfort = 1 #Tallinn
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }

#Latvia
province = { id = 264 manpower = 2 landfort = 1 anti_air = 1 #Riga
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id = 266 ic = 1 landfort = 2 } #Daugavpils
province = { id = 268 ic = 2 landfort = 2 #Liepaja
	naval_base = { size = 7 current_size = 7 } }
province = { id = 269 manpower = 1 } #Jelgave

### LBY
province = { id = 750 ic = 4 anti_air = 1 manpower = 2 #Tripoli
	naval_base = { size = 8 current_size = 8 } air_base = { size = 6 current_size = 6 } }
province = { id = 756 infra = { size = 0.20 current_size = 0.20 } } #Sirt
province = { id = 757 infra = { size = 0.20 current_size = 0.20 } } #Misratah
province = { id = 759 infra = { size = 0.20 current_size = 0.20 } } #El Agheila
province = { id = 761 ic = 2 anti_air = 1 infra = { size = 0.30 current_size = 0.30 } #Benghazi
	manpower = 1 naval_base = { size = 5 current_size = 5 } air_base = { size = 6 current_size = 6 } }
province = { id = 762 infra = { size = 0.20 current_size = 0.20 } } #Agedabia
province = { id = 765 ic = 1 landfort = 3 infra = { size = 0.20 current_size = 0.20 } anti_air = 2 #Tobruk
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 767 infra = { size = 0.20 current_size = 0.20 } } #Gazala
province = { id = 768 infra = { size = 0.20 current_size = 0.20 } } #Darnah
province = { id = 771 infra = { size = 0.20 current_size = 0.20 } } #Bardia

### LIB
province = { id = 969 anti_air = 1 #Monrovia
	naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }

### LIT
province = { id = 252 ic = 2 } #Suwalki
province = { id = 255 ic = 1 anti_air = 2 } #Grodno
province = { id = 258 ic = 4 manpower = 2 anti_air = 5 #Wilno
	air_base = { size = 3 current_size = 3 } }
province = { id = 262 anti_air = 1 #Kaunas
	air_base = { size = 1 current_size = 1 } }

### MAN
province = { id = 1198 infra = { size = 0.30 current_size = 0.30 } } #Butehaqi
province = { id = 1199 infra = { size = 0.50 current_size = 0.50 } #Harbin
	air_base = { size = 2 current_size = 2 } anti_air = 2 ic = 3 }
province = { id = 1203 ic = 1 anti_air = 2 #Qiqihaer
	air_base = { size = 4 current_size = 4 } }
province = { id = 1202 anti_air = 2 #Jiamisu
	air_base = { size = 2 current_size = 2 } }		
province = { id = 1205 infra = { size = 0.40 current_size = 0.40 } #Mudanjiang
	air_base = { size = 3 current_size = 3 } }
province = { id = 1206 air_base = { size = 4 current_size = 4 } } #Haila'er
province = { id = 1207 ic = -4 } #Jilin
province = { id = 1208 ic = 2 anti_air = 3 #Changchun
	air_base = { size = 6 current_size = 6 } }
province = { id = 1210 infra = { size = 0.20 current_size = 0.20 } } #Tongliyao Hot
province = { id = 1212 ic = -1 infra = { size = 0.20 current_size = 0.20 } } #Yanji
province = { id = 1214 anti_air = 3 ic = 5 } #Shenyang
province = { id = 1215 ic = -2 } #Fushun
province = { id = 1216 ic = 1 infra = { size = 0.40 current_size = 0.40 } } #Jinzhou
province = { id = 1217 ic = 2 #Anshan
	infra = { size = 0.40 current_size = 0.40 } }
province = { id = 1218 ic = -3 anti_air = 2 #Panjin
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id = 1220 ic = -2 infra = { size = 0.30 current_size = 0.30 } } #Dandong
province = { id = 1235 infra = { size = 0.20 current_size = 0.20 } } #Fuxin
province = { id = 1236 infra = { size = 0.30 current_size = 0.30 } #Chengde
	anti_air = 2 air_base = { size = 6 current_size = 6 } }

### MEX
province = { id = 1967 ic = 3 } #La Paz
province = { id = 1968 naval_base = { size = 2 current_size = 2 } } #Veracruz
province = { id = 1971 ic = 2 } #Mexicali
province = { id = 1972 ic = 3 anti_air = 2 #Acapulco
	naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }
province = { id = 1974 anti_air = 4 #Mexico City
	air_base = { size = 2 current_size = 2 } }
province = { id = 1975 anti_air = 1 } #Monterey
province = { id = 1977 anti_air = 2 } #Ciudad de México

### MON

#Outer Mongolia
province = { id = 1119 ic = -2 } #Kyzyl
province = { id = 1120 infra = { size = 0.30 current_size = 0.30 } } #Bayan Tumen
province = { id = 1124 ic = 2 #Ulaanbaatar
	infra = { size = 0.40 current_size = 0.40 } air_base = { size = 1 current_size = 1 } }

#Trans-Siberian Railway
province = { id = 1146 ic = 2 } #Oyrot-Tura
province = { id = 1147 ic = 1 } #Abakan (was 3)
province = { id = 1158 ic = 1 } #Minusinsk (was 2)
province = { id = 1167 ic = 2 } #Ulan Ude
province = { id = 1168 ic = 1 } #Borzya (was 2)
province = { id = 1169 ic = 1 } #Chita

### NEP
province = { id = 1467 ic = 4 } #Gorakhpur

### NIC
province = { id = 2080 infra = { size = 0.40 current_size = 0.40 } ic = -2 #Managua
	naval_base = { size = 2 current_size = 2 } air_base = { size = 1 current_size = 1 } }
province = { id = 2081 anti_air = 1 ic = -2 #San Jose
	air_base = { size = 4 current_size = 4 } }

### NOR
province = { id = 483 coastalfort = 3 anti_air = 2 #Oslo
	naval_base = { size = 10 current_size = 10 } air_base = { size = 6 current_size = 6 } }
province = { id = 485 coastalfort = 3 } #Kristinsand
province = { id = 488 anti_air = 2 #Bergen
	naval_base = { size = 10 current_size = 10 } air_base = { size = 5 current_size = 5 } }
province = { id = 493 coastalfort = 2 manpower = 1 #Trondheim
	naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } }
province = { id = 495 anti_air = 1 #Narvik
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }

### YEM
province = { id = 1050 ic = -2 infra = { size = 0.20 current_size = 0.20 } } #Sanaa (Mar2020 - increased infra, reduced IC)

### OMN
province = { id = 1051 naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 } } #El Mukalla
province = { id = 1052 anti_air = 2 ic = -2 infra = { size = 0.20 current_size = 0.20 } #Masqat (Mar2020 - increased infra, reduced IC)
	naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } }

### OTT

#Arabian territories
#province = { id = 1008 anti_air = 1 #Tel Aviv
#	naval_base = { size = 2 current_size = 2 } air_base = { size = 4 current_size = 4 } }
#province = { id = 1010 air_base = { size = 2 current_size = 2 } } #Eilat
province = { id = 1011 naval_base = { size = 3 current_size = 3 } } #Haifa
province = { id = 1015 infra = { size = 0.20 current_size = 0.20 } } #El Qamisli
province = { id = 1172 air_base = { size = 3 current_size = 3 } } #Jerusalem
province = { id = 1016 ic = 1 } #Damascus
province = { id = 1019 ic = 2 anti_air = 2 #Beirut
	naval_base = { size = 5 current_size = 5 } air_base = { size = 4 current_size = 4 } }
province = { id = 1021 ic = 2 #Aleppo (Mar2020 - added navalbase, increased airbase)
	air_base = { size = 3 current_size = 3 } naval_base = { size = 2 current_size = 2 } }
province = { id = 1032 naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } } #Basrah
province = { id = 1033 infra = { size = 0.20 current_size = 0.20 } } #El Hillah
province = { id = 1034 air_base = { size = 4 current_size = 4 } } #Baghdad
#province = { id = 1041 naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } } #Kuwait
province = { id = 1048 anti_air = 2 infra = { size = 0.20 current_size = 0.20 } #Medina
	naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } }

#Tibet
province = { id = 1289 ic = -4 } #Lhasa

#Turkey
province = { id = 385 infra = { size = 0.30 current_size = 0.30 } } #Adrianople
province = { id = 387 ic = 1 } #Famagusta
province = { id = 409 ic = 6 #Istanbul
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1056 naval_base = { size = 2 current_size = 2 } #Gaziantep
	infra = { size = 0.20 current_size = 0.20 } }
province = { id = 1057 ic = -2 } #Antalya
province = { id = 1058 ic = 2 infra = { size = 0.20 current_size = 0.20 } #Tarsus
	naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }
province = { id = 1060 infra = { size = 0.20 current_size = 0.20 } } #Diyarbakir
province = { id = 1065  air_base = { size = 4 current_size = 4 } #Karabuk
	naval_base = { size = 4 current_size = 4 } infra = { size = 0.30 current_size = 0.30 } ic = 2 }
province = { id = 1067 ic = 2 infra = { size = 0.30 current_size = 0.30 } #Trazbon
	naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }
province = { id = 1072 ic = 1 } #Kirikkale
province = { id = 1074 ic = 1 } #Konya
province = { id = 1075 anti_air = 4 #Ankara
	air_base = { size = 6 current_size = 6 } }
province = { id = 1076 anti_air = 4 infra = { size = 0.30 current_size = 0.30 } #Izmit
	naval_base = { size = 10 current_size = 10 } air_base = { size = 6 current_size = 6 } }
province = { id = 1077 ic = 3 #Smyrna
	naval_base = { size = 5 current_size = 5 } air_base = { size = 4 current_size = 4 } }
province = { id = 1078 ic = 4 } #Bursa

### PAK
province = { id = 1459 anti_air = 2 #Delhi
	air_base = { size = 4 current_size = 4 } }
province = { id = 1522 anti_air = 1 #Rajkot
	air_base = { size = 4 current_size = 4 } }
province = { id = 1524 ic = -2 } #Jaypur
province = { id = 1525 ic = -1 } #Jodhpur
province = { id = 1531 ic = -1 } #Ludhiana
province = { id = 1533 anti_air = 1 #Karachi
	naval_base = { size = 8 current_size = 8 } air_base = { size = 8 current_size = 8 } }
province = { id = 1535 ic = -1 } #Amritstar
province = { id = 1538 infra = { size = 0.30 current_size = 0.30 } } #Gwadar
province = { id = 1466 ic = -1 } #Arrah
province = { id = 1483 ic = -1 } #Rewa
province = { id = 1460 ic = -1 } #Merath
province = { id = 1468 ic = -4 } #Cawnpore
province = { id = 1481 anti_air = 1 #Indhur
	air_base = { size = 4 current_size = 4 } }
province = { id = 1532 ic = -2 } #Nawabshah
province = { id = 1518 ic = -1 } #Ahmedabad

### PAN
province = { id = 2078 anti_air = 2 infra = { size = 0.40 current_size = 0.40 } #Cuidad de Panama
	naval_base = { size = 5 current_size = 5 } air_base = { size = 1 current_size = 1 } ic = -2 }

### PER
province = { id = 1081 anti_air = 1 #Rast
	air_base = { size = 2 current_size = 2 } }
province = { id = 1083 ic = 2 } #Tabriz
province = { id = 1084 infra = { size = 0.20 current_size = 0.20 } } #Kermanshah
province = { id = 1085 ic = 3 anti_air = 2 #Tehran
	air_base = { size = 3 current_size = 3 } }
province = { id = 1086 ic = 2 infra = { size = 0.30 current_size = 0.30 } } #Eshfahan
province = { id = 1088 infra = { size = 0.20 current_size = 0.20 } } #Shiraz
province = { id = 1089 ic = 3 infra = { size = 0.40 current_size = 0.40 } #Abadan
	air_base = { size = 3 current_size = 3 } }
province = { id = 1090 infra = { size = 0.20 current_size = 0.20 } } #Busehr
province = { id = 1091 anti_air = 2 #Gameroon
	naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } }
province = { id = 1093 infra = { size = 0.20 current_size = 0.20 } } #Zahedan
province = { id = 1094 infra = { size = 0.10 current_size = 0.10 } } #Kerman
province = { id = 1095 infra = { size = 0.20 current_size = 0.20 } } #Birjand

### PHI
province = { id = 1565 coastalfort = 3 anti_air = 2 #Manila
	naval_base = { size = 10 current_size = 10 } air_base = { size = 6 current_size = 6 } }
province = { id = 1567 anti_air = 4 #Baguio
	naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } }

### POL
province = { id = 223 anti_air = 4 ic = -2 #Lodz
	air_base = { size = 4 current_size = 4 } }
province = { id = 227 ic = 1 manpower = 2 } #Czestochowa
province = { id = 228 ic = 1 } #Siedlce
province = { id = 232 landfort = 2 anti_air = 4 #Warsaw
	air_base = { size = 6 current_size = 6 } }
province = { id = 235 ic = -1 anti_air = 4 #Krakow
	air_base = { size = 5 current_size = 5 } }
province = { id = 246 ic = 1 } #Chelm

### POR

#African colonies
province = { id = 854 naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } } #Nampula
province = { id = 892 naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } } #Lobito
province = { id = 893 naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 } } #Cabinda
province = { id = 912 anti_air = 2 #Sao Tome
	naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 } }
province = { id = 992 naval_base = { size = 3 current_size = 3  } air_base = { size = 1 current_size = 1 } } #Cape Verde

#Asian/Oceanic colonies
province = { id = 1372 #Macao
	naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } }
province = { id = 1617 naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 } } #Dili

#Portugal
province = { id = 476 anti_air = 4 #Lisbon
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 481 anti_air = 1 } #Porto
province = { id = 995 anti_air = 2 #The Azores
	naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }

### PRI	
province = { id = 1185 landfort = 2 } #Gavan
province = { id = 1190 ic = 1 landfort = 2 #Khabarovsk
	air_base = { size = 3 current_size = 3 } }
province = { id = 1191 ic = 7 manpower = 1 landfort = 1 coastalfort = 3 anti_air = 5 #Vladivostok
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1192 infra = { size = 0.10 current_size = 0.10 } } #Semyonovka
province = { id = 1193 ic = 1 infra = { size = 0.30 current_size = 0.30 } } #Nakhodka
province = { id = 1194 ic = 1 } #Lesozavodsk
province = { id = 1195 infra = { size = 0.30 current_size = 0.30 } } #Tetyukhe
province = { id = 1196 ic = 3 } #Nikolsk-Ussuriysky

### PRK
province = { id = 1445 infra = { size = 0.30 current_size = 0.30 } } #Dhaka
province = { id = 1446 ic = -1 } #Siliguri
province = { id = 1447 ic = 4 anti_air = 2 #Calcutta -5
	naval_base = { size = 8 current_size = 8 } air_base = { size = 8 current_size = 8 } }
province = { id = 1449 ic = -1 infra = { size = 0.40 current_size = 0.40 } } #Rajshahi
province = { id = 1450 ic = -1 } #Cattagram
province = { id = 1470 ic = -1 } #Balangir
province = { id = 1471 ic = -3 } #Bhubanesbar
province = { id = 1493 ic = 2 } #Vizagapatam

### PRU
province = { id = 2012 infra = { size = 0.20 current_size = 0.20 } } #Requena
province = { id = 2013 infra = { size = 0.10 current_size = 0.10 } } #Puerto Maldonado
province = { id = 2014 infra = { size = 0.40 current_size = 0.40 } } #Trujillo
province = { id = 2015 infra = { size = 0.40 current_size = 0.40 } } #Cuzco
province = { id = 2016 naval_base = { size = 3 current_size = 3 } air_base = { size = 2 current_size = 2 } } #Lima
province = { id = 2017 infra = { size = 0.40 current_size = 0.40 } } #Arequipa

### ROM
province = { id = 297 anti_air = 1 #Iasi
	air_base = { size = 3 current_size = 3 } }
province = { id = 302 infra = { size = 0.30 current_size = 0.30 } } #Hotin
province = { id = 303 ic = -2 infra = { size = 0.30 current_size = 0.30 } } #Balti
province = { id = 304 anti_air = 1 infra = { size = 0.40 current_size = 0.40 } } #Chisinau
province = { id = 305 infra = { size = 0.30 current_size = 0.30 } } #Cahul
province = { id = 306 ic = -2 } #Ismail
province = { id = 310 ic = 2 anti_air = 2 #Constantza
	naval_base = { size = 6 current_size = 6 } air_base = { size = 3 current_size = 3 } }
province = { id = 311 ic = 1 anti_air = 3 } #Ploiesti
province = { id = 315 infra = { size = 0.40 current_size = 0.40 } } #Craiova
province = { id = 316 anti_air = 2 #Bucharest
	air_base = { size = 5 current_size = 5 } }
	
### RSI
province = { id = 415 landfort = 2 ic = -1 #Pescara
	air_base = { size = 4 current_size = 4 } }
province = { id = 417 landfort = 1 } #Cassino
province = { id = 418 landfort = 2 } #Gaeta
province = { id = 420 ic = -1 } #Foggia
province = { id = 421 anti_air = 2 ic = 5 #Naples
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 422 ic = 3 anti_air = 1 #Taranto
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 426 ic = 1 } #Bari
province = { id = 427 ic = 1 } #Salerno
province = { id = 428 ic = 1 } #Cosenza
province = { id = 430 naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } } #Palermo
province = { id = 432 anti_air = 2 ic = 1 #Catania
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }

### RUS

#European Russia
province = { id = 535 anti_air = 4 #Murmansk
	naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }
province = { id = 539 ic = 1 } #Petrozavodsk
province = { id = 542 anti_air = 2 #Archangelsk
	naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } }
province = { id = 548 ic = -1 } #Volodga
province = { id = 553 landfort = 2 coastalfort = 5 anti_air = 3 #Leningrad
	naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 558 ic = 1 } #Rzhev
province = { id = 560 anti_air = 1 ic = 1 } #Novgorod
province = { id = 566 air_base = { size = 6 current_size = 6 } } #Pskov
province = { id = 569 ic = -8 } #Tver
province = { id = 572 landfort = 1 anti_air = 2 #Moscow
	air_base = { size = 10 current_size = 10 } }
province = { id = 576 anti_air = 1 } #Kaluga
province = { id = 581 air_base = { size = 5 current_size = 5 } } #Oryol
province = { id = 588 anti_air = 2 ic = 2 } #Bryansk
province = { id = 589 anti_air = 3 } #Smolensk
province = { id = 590 anti_air = 2 } #Vitebsk
province = { id = 600 anti_air = 1 #Mogilev
	air_base = { size = 5 current_size = 5 } }
province = { id = 663 air_base = { size = 2 current_size = 2 } } #Tsaritsyn
province = { id = 664 air_base = { size = 2 current_size = 2 } } #Naberezhnye Chelny
province = { id = 667 air_base = { size = 2 current_size = 2 } } #Tolyatti
province = { id = 671 ic = 2 } #Izhevsk
province = { id = 681 ic = -1 } #Kostrama
province = { id = 1126 ic = -1 } #Kungur

#Siberia
province = { id = 1135 ic = 1 infra = { size = 0.30 current_size = 0.30 } } #Tobolsk
province = { id = 1138 air_base = { size = 1 current_size = 1 } } #Omsk
province = { id = 1140 air_base = { size = 5 current_size = 5 } } #Barnaul
province = { id = 1142 ic = 1 } #Novosibirsk
province = { id = 1144 ic = -1 } #Kemerovo
province = { id = 1145 ic = -1 } #Kusnezk
province = { id = 1148 air_base = { size = 2 current_size = 2 } } #Tomsk
province = { id = 1151 ic = -1 } #Sverdlovsk
province = { id = 1152 ic = -1 } #Salekhard
province = { id = 1154 ic = -1 } #Surgut
province = { id = 1156 ic = 1 } #Krasnoyarsk
province = { id = 1162 ic = 2 } #Irkutsk
province = { id = 1164 ic = -1 } #Ust-Kut
province = { id = 1165 air_base = { size = 1 current_size = 1 } } #Bratsk
province = { id = 1171 infra = { size = 0.20 current_size = 0.20 } } #Ekimchan
province = { id = 1176 ic = 1 } #Blagoveshchensk
province = { id = 1179 ic = 1 #Yakutsk
air_base = { size = 1 current_size = 1 } }
province = { id = 1189 anti_air = 2 air_base = { size = 4 current_size = 4 } #Nikolayevsk-on-Amur
	naval_base = { size = 2 current_size = 2 } }

### SAF
province = { id = 872 naval_base = { size = 3 current_size = 3 } } #Duban
province = { id = 873 anti_air = 1 } #Port Elizabeth
province = { id = 876 anti_air = 5 infra = { size = 0.40 current_size = 0.40 } #Johannesberg
air_base = { size = 1 current_size = 1 } }
province = { id = 880 anti_air = 4 #Cape Town
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 881 anti_air = 3 #Durban
naval_base = { size = 3 current_size = 3 } air_base = { size = 1 current_size = 1 } }
province = { id = 964 oilpool = 1000 supplypool = 2000 } #Freetown

### SAU
province = { id = 1038 naval_base = { size = 2 current_size = 2 } } #Doha
province = { id = 1040 } #Dammam (Mar2020 - removed navalbase)
province = { id = 1045 infra = { size = 0.30 current_size = 0.30 } } #Riyadh
province = { id = 1049 air_base = { size = 2 current_size = 2 } infra = { size = 0.20 current_size = 0.20 } } #Mecca

### SCH
province = { id = 389 landfort = 5 anti_air = 3 } #Zurich
province = { id = 390 landfort = 5 anti_air = 3 } #Lugano
province = { id = 391 landfort = 5 anti_air = 3 } #Geneva
province = { id = 392 landfort = 5 anti_air = 5 #Bern
air_base = { size = 4 current_size = 4 } }

### SER
province = { id = 327 landfort = 2 infra = { size = 0.40 current_size = 0.40 } } #Krusevac
province = { id = 330 ic = 1 landfort = 1 } #
province = { id = 338 landfort = 2 anti_air = 2 #Beograd
air_base = { size = 6 current_size = 6 } }
province = { id = 339 ic = 1 landfort = 2 } #Bor
province = { id = 340 landfort = 2 infra = { size = 0.30 current_size = 0.30 } } #Sabac
province = { id = 342 landfort = 2 } #Uzice

### SIA
province = { id = 1422 anti_air = 2 air_base = { size = 2 current_size = 2 } } #Chon Buri
province = { id = 1423 anti_air = 2 #Bangkok
	naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id = 1426 air_base = { size = 4 current_size = 4 } } #Phitsanulok
province = { id = 1431 naval_base = { size = 2 current_size = 2 } air_base = { size = 1 current_size = 1 } } #Songkhla
province = { id = 1435 naval_base = { size = 2 current_size = 2 } } #Kuala Lumpur

### SPA

#Africa colonies
province = { id = 461 naval_base = { size = 3 current_size = 3 } air_base = { size = 3 current_size = 3 } } #Castellon de la Plana
province = { id = 473 naval_base = { size = 4 current_size = 4 } } #Cadiz
province = { id = 715 anti_air = 3 #Tanger
naval_base = { size = 6 current_size = 6 } air_base = { size = 2 current_size = 2 } }
province = { id = 988 anti_air = 2 #Villa Cisneros
naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } }
province = { id = 990 naval_base = { size = 1 current_size = 1 } air_base = { size = 2 current_size = 2 } } #Las Palmas de Gran Canaria
province = { id = 991 anti_air = 2 #Santa Cruz de Tenerife
naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }

#Spain
province = { id = 348 anti_air = 4 oilpool = 200 supplypool = 500 #Gibraltar
naval_base = { size = 6 current_size = 6 } air_base = { size = 4 current_size = 4 } }
province = { id = 436 anti_air = 2 #Tarragona
naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }
province = { id = 437 landfort = 3 } #Gerona
province = { id = 438 landfort = 3 } #Huesca
province = { id = 439 landfort = 3 } #Lerida
province = { id = 440 naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } } #Barcelona
province = { id = 441 anti_air = 2 #Coruna
naval_base = { size = 7 current_size = 7 } air_base = { size = 7 current_size = 7 } }
province = { id = 443 landfort = 3 } #Bilbao
province = { id = 446 landfort = 2 } #Pamplona
province = { id = 460 anti_air = 3 #Madrid
air_base = { size = 10 current_size = 10 } }
province = { id = 464 anti_air = 2 #Valencia
naval_base = { size = 3 current_size = 3 } air_base = { size = 2 current_size = 2 } }
province = { id = 472 naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } } #Huevla
province = { id = 474 anti_air = 2 #Sevilla
naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }
province = { id = 475 anti_air = 2 #Palma de Mallorca
naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }

### SWE
province = { id = 2152 coastalfort = 3 manpower = 2 #Malmo
naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } }
province = { id = 2153 coastalfort = 1 anti_air = 2 manpower = 2 #Gothenburg
naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }
province = { id = 2156 anti_air = 2 #Visby
naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 } }
province = { id = 2158 landfort = 1 coastalfort = 1 } #Uppsala
province = { id = 2159 coastalfort = 3 anti_air = 2 manpower = 2 #Stockholm
naval_base = { size = 8 current_size = 8 } air_base = { size = 8 current_size = 8 } }
province = { id = 2162 landfort = 1 coastalfort = 1 } #Gaevla
province = { id = 2163 ic = -1 } #Vilhelmina
province = { id = 2166 ic = 1 landfort = 3 anti_air = 2 #Lulea
naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 } }

### TRA
province = { id = 691 ic = 4 } #Krasnodar
province = { id = 694 ic = 2 anti_air = 2 #Novorossiysk
naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 } }
province = { id = 702 ic = 2 #Gronzy
air_base = { size = 2 current_size = 2 } } 
province = { id = 703 ic = 2 } #Vladikavkaz

### U02
province = { id = 382 anti_air = 1 infra = { size = 0.30 current_size = 0.30 } #Irakleio
	naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }

### U35
province = { id = 1500 ic = 2 #Madras
	naval_base = { size = 4 current_size = 4 } air_base = { size = 2 current_size = 2 } }

### UKR
province = { id = 245 landfort = 2 } #Lutsk
province = { id = 606 landfort = 1 infra = { size = 0.30 current_size = 0.30 } } #Sumy
province = { id = 605 landfort = 1 } #Konotop
province = { id = 607 landfort = 1 air_base = { size = 2 current_size = 2 } #Chernigov
	infra = { size = 0.40 current_size = 0.40 } }
province = { id = 612 ic = -1 } #Vinnitsa
province = { id = 618 ic = -2 infra = { size = 0.30 current_size = 0.30 } } #Kamenets-Podolsky
province = { id = 619 infra = { size = 0.20 current_size = 0.20 } } #Mogilev-Podolsky
province = { id = 617 anti_air = 3 #Kiev
air_base = { size = 8 current_size = 8 } }
province = { id = 622 ic = 2 naval_base = { size = 5 current_size = 5 } } #Nikolayev
province = { id = 625 infra = { size = 0.30 current_size = 0.30 } } #Ochakov
province = { id = 626 anti_air = 3 #Odessa
naval_base = { size = 3 current_size = 3 } }
province = { id = 627 infra = { size = 0.40 current_size = 0.40 } } #Krivoy Rog
province = { id = 628 infra = { size = 0.40 current_size = 0.40 } } #Yelisavetgrad
province = { id = 632 anti_air = 2 #Dnepropetrovsk
air_base = { size = 2 current_size = 2 } }
province = { id = 634 landfort = 1 } #Voroshilovgrad
province = { id = 635 landfort = 1 anti_air = 2 } #Stalino
province = { id = 636 ic = 2 landfort = 2 anti_air = 5 } #Kharkov
province = { id = 641 ic = 1 landfort = 3 coastalfort = 5 anti_air = 5 #Sevastopol
naval_base = { size = 10 current_size = 10 } air_base = { size = 6 current_size = 6 } }
province = { id = 644 anti_air = 2 #Rostov
naval_base = { size = 4 current_size = 4 } }
province = { id = 654 anti_air = 1 } #Voronezh

### USA

#Atlantic territories
province = { id = 889 anti_air = 3 supplypool = 100 infra = { size = 0.40 current_size = 0.40 } #Balbo
	naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 1765 supplypool = 100 } #Puerto Rico
province = { id = 1778 naval_base = { size = 4 current_size = 4 } } #Guantanamo Bay Naval Base

#AUS
province = { id = 1812 ic = -2 anti_air = 4 #Norfolk
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1813 ic = -2 } #Richmond
province = { id = 1819 anti_air = 1 #Louisville
air_base = { size = 4 current_size = 4 } }
province = { id = 1915 ic = -2 } #Jonesboro
province = { id = 1918 anti_air = 1 #Little Rock
air_base = { size = 4 current_size = 4 } }
province = { id = 1930 ic = -1 } #Shreveport
province = { id = 1931 naval_base = { size = 10 current_size = 10 } } #New Oreleans
province = { id = 1922 ic = -2 anti_air = 1 #Corpus Christi
naval_base = { size = 8 current_size = 8 } air_base = { size = 6 current_size = 6 } }
province = { id = 1940 anti_air = 1 #Memphis
air_base = { size = 4 current_size = 4 } }
province = { id = 1944 naval_base = { size = 6 current_size = 6 } air_base = { size = 6 current_size = 6 } } #Mobile
province = { id = 1947 ic = -4 } #Montgomery
province = { id = 1949 ic = -2 } #Orlando
province = { id = 1950 ic = -1 } #Pensacola
province = { id = 1951 ic = -1 } #Tallahasse
province = { id = 1952 anti_air = 1 #Jacksonville
naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 1953 anti_air = 1 #Miami
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1954 ic = -2 } #Macon
province = { id = 1955 anti_air = 1 #Atlanta
air_base = { size = 4 current_size = 4 } }
province = { id = 1959 ic = 1 air_base = { size = 10 current_size = 10 } } #Augusta
province = { id = 1960 anti_air = 1 #Charleston
naval_base = { size = 8 current_size = 8 } air_base = { size = 8 current_size = 8 } }
province = { id = 1962 anti_air = 1 #Charlotte
air_base = { size = 4 current_size = 4 } }
province = { id = 1963 naval_base = { size = 8 current_size = 8 } air_base = { size = 8 current_size = 8 } } #Wilimington
province = { id = 1964 ic = -2 } #Asheville

#CSA
province = { id = 1792 ic = -2 } #Syracuse
province = { id = 1795 ic = -13 anti_air = 4 #New York
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1803 ic = -4 } #Williamsport
province = { id = 1805 ic = -13 anti_air = 2 } #Philadelphia
province = { id = 1806 ic = -3 anti_air = 1 #Pittsburgh
air_base = { size = 4 current_size = 4 } }
province = { id = 1821 ic = -8 } #Columbus
province = { id = 1825 ic = -8 } #Cleveland
province = { id = 1826 ic = -4 } #Fort Wayne
province = { id = 1828 ic = -4 } #Indianapolis
province = { id = 1829 ic = -3 } #Peoria
province = { id = 1830 ic = -3 } #Decatur
province = { id = 1831 anti_air = 1 #Belleville
air_base = { size = 4 current_size = 4 } }
province = { id = 1832 ic = -5 anti_air = 3 #Chicago
air_base = { size = 10 current_size = 10 } }
province = { id = 1833 ic = -2 anti_air = 1 #Saint Louis
air_base = { size = 4 current_size = 4 } }
province = { id = 1838 ic = -2 anti_air = 1 #Des Moines
air_base = { size = 4 current_size = 4 } }
province = { id = 1839 ic = -7 anti_air = 1 #Milwaukee
air_base = { size = 4 current_size = 4 } }
province = { id = 1845 ic = -3 anti_air = 1 #Detroit
air_base = { size = 4 current_size = 4 } }
province = { id = 1846 ic = -7 } #Rochester
province = { id = 1847 anti_air = 1 #Minneapolis
air_base = { size = 4 current_size = 4 } }

#'Loyal' mainland
province = { id = 1797 ic = -28 #Newark
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1801 ic = -14 } #Harrisburg
province = { id = 1807 ic = -2 } #Cape Charles
province = { id = 1808 ic = -5 } #Baltimore
province = { id = 1809 anti_air = 4 #Washington D.C.
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1810 ic = -5 } #Clarksburg
province = { id = 1820 ic = -7 } #Lexington
province = { id = 1834 ic = -7 } #Saint Joseph
province = { id = 1837 ic = -2 } #Cedar Rapids
province = { id = 1836 ic = -2 } #Springfield
province = { id = 1856 anti_air = 1 #Bismarck
air_base = { size = 4 current_size = 4 } }
province = { id = 1857 ic = -2 } #Sioux Falls
province = { id = 1858 ic = -1 } #Rapid City
province = { id = 1859 ic = -6 } #Lincoln
province = { id = 1860 anti_air = 1 #Omaha
air_base = { size = 4 current_size = 4 } }
province = { id = 1862 ic = -2 } #Bozeman
province = { id = 1864 ic = -2 } #Great Falls
province = { id = 1865 ic = -2 } #Missoula
province = { id = 1896 anti_air = 1 #Salt Lake City
air_base = { size = 10 current_size = 10 } }
province = { id = 1898 ic = -1 } #Spring Rocks
province = { id = 1900 anti_air = 1 #Phoenix
air_base = { size = 4 current_size = 4 } }
province = { id = 1908 anti_air = 1 #Denver
air_base = { size = 4 current_size = 4 } }
province = { id = 1912 anti_air = 1 #Tulsa
air_base = { size = 4 current_size = 4 } }
province = { id = 1913 anti_air = 1 #Oklahoma City
air_base = { size = 4 current_size = 4 } }
province = { id = 1914 ic = -2 } #Kansas City
province = { id = 1923 ic = -1 } #El Paso
province = { id = 1924 ic = -7 } #Dallas
province = { id = 1926 anti_air = 1 #San Antonio
air_base = { size = 4 current_size = 4 } }
province = { id = 1928 ic = -6 anti_air = 1 #Houston
air_base = { size = 4 current_size = 4 } }
province = { id = 1939 ic = -2 } #Jackson

#New England
province = { id = 1787 anti_air = 1 #Concord
air_base = { size = 4 current_size = 4 } }
province = { id = 1785 ic = -2 } #Lewiston
province = { id = 1788 ic = -3 } #Hartford
province = { id = 1789 anti_air = 3 #Boston
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1793 ic = -2 anti_air = 1 #Albany
air_base = { size = 4 current_size = 4 } }
province = { id = 1796 ic = -6 } #Providence
	
#Pacific territories
province = { id = 1673 anti_air = 3 supplypool = 100 #Wake
naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }
province = { id = 1683 anti_air = 3 supplypool = 100 #Guam
naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 1733 supplypool = 50 naval_base = { size = 2 current_size = 2 } } #Pago Pago
province = { id = 1734 manpower = 1 anti_air = 5 supplypool = 1000 #Pearl Harbour
naval_base = { size = 10 current_size = 10 } air_base = { size = 6 current_size = 6 } }
province = { id = 1738 supplypool = 1 } #Port Johnston
province = { id = 1739 supplypool = 100 #Midway
naval_base = { size = 3 current_size = 3 } }
#province = { id = 1747 supplypool = 50 #Palmyra
#naval_base = { size = 8 current_size = 8 } air_base = { size = 8 current_size = 8 } }
province = { id = 1887 ic = -4 anti_air = 3 #Los Angeles
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }

#West Coast
province = { id = 1874 anti_air = 1 #Seattle
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1877 ic = -6 } #Tacoma
province = { id = 1878 anti_air = 1 #Portland
naval_base = { size = 6 current_size = 6 } air_base = { size = 4 current_size = 4 } }
province = { id = 1883 ic = -2 } #Fresno
province = { id = 1886 ic = -2 anti_air = 1 #San Diego
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 1888 anti_air = 1 #Sacramento
air_base = { size = 4 current_size = 4 } }
province = { id = 1889 ic = -4 anti_air = 3 #San Francisco
naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } }
province = { id = 2141 supplypool = 1000 } #Juneau
province = { id = 2142 anti_air = 1 #Anchorage
naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
#province = { id = 2150 supplypool = 500 #Adak
#naval_base = { size = 4 current_size = 4 } air_base = { size = 4 current_size = 4 } }

### VEN
province = { id = 1988 anti_air = 2 #Maracaibo
	naval_base = { size = 6 current_size = 6 } air_base = { size = 1 current_size = 1 } }
province = { id = 1989 ic = 1 } #Barquisimeto
province = { id = 1993 anti_air = 2 ic = 4 #Caracas
	naval_base = { size = 4 current_size = 4 } }
province = { id = 1996 ic = -5 } #Barinas

### VIC
province = { id = 728 ic = 3 anti_air = 2 #Oran
	naval_base = { size = 2 current_size = 2 } air_base = { size = 4 current_size = 4 } }
province = { id = 727 ic = 8 anti_air = 4 #Algiers
	naval_base = { size = 5 current_size = 5 } air_base = { size = 4 current_size = 4 } }
province = { id = 729 ic = 2 } #Tlemcen
province = { id = 731 ic = 1 } #Batna
province = { id = 734 ic = 1 } #Constantine
province = { id = 735 ic = 1 } #Bona
province = { id = 736 ic = 3 #Bougie
	naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 747 ic = 4 anti_air = 4 #Tunis
	naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }
province = { id = 748 ic = 2 anti_air = 3 infra = { size = 0.40 current_size = 0.40 } #Bizerte
	naval_base = { size = 8 current_size = 8 } air_base = { size = 8 current_size = 8 } }
province = { id = 749 ic = 1 } #Beja
province = { id = 957 ic = 1 } #Ouagadougou
province = { id = 962 ic = 2 anti_air = 2 #Abidjan
	air_base = { size = 4 current_size = 4 } }
province = { id = 966 ic = 2 } #Conarky
province = { id = 978 ic = 3 anti_air = 3 #Dakar
	naval_base = { size = 5 current_size = 5 } air_base = { size = 5 current_size = 5 } }

### YUN
province = { id = 1297 ic = -3 } #Chengdu
province = { id = 1299 ic = 1 } #Chongqing
province = { id = 1390 ic = -3 anti_air = 1 #Kunming
	air_base = { size = 3 current_size = 3 } }

#Industries in Japan Mainland (81 IC )
province = { id = 1543 ic = -1 } #Shana
province = { id = 1550 ic = 6 } #Yokohama
province = { id = 1551 ic = 1 } #Niigata
province = { id = 1552 ic = 1 } #Tokyo
province = { id = 1553 ic = -4 } #Osaka
province = { id = 1554 ic = 3 } #Hiroshima
province = { id = 1555 ic = 6 } #Kobe
province = { id = 1556 ic = -2 } #Kanazawa
province = { id = 1557 ic = -5 } #Nagoya
province = { id = 1558 ic = 3 } #Kyoto
province = { id = 1559 ic = -3 } #Matsuyama
province = { id = 1560 ic = 5 } #Nagasaki

#Industries in Korea (16 IC)
province = { id = 1221 ic = 1 } #Pyeongyang
province = { id = 1222 ic = 2 } #Sariwon
province = { id = 1223 ic = 2 } #Wonsan
province = { id = 1226 ic = -1 } #Ganggye
province = { id = 1227 ic = 1 } #Hamheung
province = { id = 1228 ic = -1 } #Seoul
province = { id = 1233 ic = -1 } #Chuncheon
province = { id = 1231 ic = -1 } #Daegu
province = { id = 1230 ic = -2 } #Gwangju

#More Supply Pools
 province = {  id = 371  oilpool = 100 supplypool = 500 }
 province = {  id = 1782  oilpool = 100 supplypool = 500 }
 province = {  id = 1771  oilpool = 100 supplypool = 500 }
 province = {  id = 1758  oilpool = 100 supplypool = 500 }
 province = {  id = 2000  oilpool = 100 supplypool = 500 }
 province = {  id = 1721  oilpool = 100 supplypool = 500 }
 province = {  id = 1607  oilpool = 100 supplypool = 500 }
 province = {  id = 991  oilpool = 100 supplypool = 500 }
 province = {  id = 988  oilpool = 100 supplypool = 500 }
 province = {  id = 475  oilpool = 100 supplypool = 500 }
 province = {  id = 715  oilpool = 100 supplypool = 500 }
 province = {  id = 892  oilpool = 100 supplypool = 500 }
 province = {  id = 963  oilpool = 100 supplypool = 500 }
 province = {  id = 855  oilpool = 100 supplypool = 500 }
 province = {  id = 1661  oilpool = 100 supplypool = 500 }
 province = {  id = 1662  oilpool = 100 supplypool = 500 }
 province = {  id = 1672  oilpool = 100 supplypool = 500 }
 province = {  id = 1562  oilpool = 100 supplypool = 500 }
 province = {  id = 1358  oilpool = 100 supplypool = 500 }
 province = {  id = 1346  oilpool = 100 supplypool = 500 }
 province = {  id = 381  oilpool = 100 supplypool = 500 }
 province = {  id = 379  oilpool = 100 supplypool = 500 }
 province = {  id = 388  oilpool = 100 supplypool = 500 }
 province = {  id = 718  oilpool = 100 supplypool = 500 }
 province = {  id = 833  oilpool = 100 supplypool = 500 }
 province = {  id = 900  oilpool = 100 supplypool = 500 }
 province = {  id = 1328  oilpool = 100 supplypool = 500 }