


country = {
    tag = BHU  

   policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 3
        political_left = 4
        free_market = 8
        freedom = 9
        professional_army = 1
        defense_lobby = 3
        interventionism = 3
    }

#### cabinet

#### Resource Reserves


	manpower = 5
	energy	=	200   metal	=	200	rare_materials =	100	oil =	200	supplies =	200
	money = 10

	capital = 	1456


    ownedprovinces =      {
		1455 1456  
	 }
    controlledprovinces = {
		1455 1456 
	  }
    nationalprovinces =   {
		1455 1456 
	}

diplomacy = {

}


	
	techapps = {

#Aircraft
4500 4510 4520 4530 4540 4550 #up to 1918 interceptor

#Armour and artillery
2860 2870 #Armd Cars up to ww1 armd car
2290 #Artillery
5810 5820

#Infantry
1010 1020 1030 1040 #Infantry divisions just stoped in 1914 inf div
13060 13070 13080 1310 #Cavalry, just stoped in 1914 cavalry division

#Land Doctrines
6500 6510 6530 6590 #Up to pre ww1 tech
6600 6610 6620 6650 6670 6680 6690 6700 6710 6550 6910 #ww1 offensive doctrines
14000 14010 #Hospitals
6570 6300 # Human Wave
	}

#########  OOB (...)
	landunit = {
	location = 1456
        id = { type = 16000 id = 1 }
	name = "Royal Bhutanese Army"

		division = {
	        id = { type = 16000 id = 2 }
		name = "Household Division"
		type = infantry
		model = 5
		strength  = 100
		}

		division = {
	        id = { type = 16000 id = 3 }
		name = "Royal Division"
		type = infantry
                model = 5
		strength  = 100
		}
		}

}  