


country = {
    tag = PAK

ai = "kaiserreich\Delhi.ai"

	policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 4
        political_left = 3
        freedom = 5
        free_market = 7
        professional_army = 5
        defense_lobby = 5
        interventionism = 4
    }


     
	headofstate = { type = 9 id = 564001 }
	headofgovernment = { type = 9 id = 564002 }
 	foreignminister = { type = 9 id = 564003 }
 	armamentminister = { type = 9 id = 564004 }
 	ministerofsecurity = { type = 9 id = 564005 }
 	ministerofintelligence = { type = 9 id = 564006 }
 	chiefofstaff = { type = 9 id = 564007 }
 	chiefofarmy = { type = 9 id = 564008 }
 	chiefofnavy = { type = 9 id = 564009 }        
 	chiefofair = { type = 9 id = 564010 }


#### Resource Reserves

	capital = 1459
	manpower = 120
	energy	=	1000   metal	= 1000		rare_materials =	500	oil =	500	supplies =	500
	money = 100

	transports = 40

    ownedprovinces =      {
1459 1533 1538 1532 1519 1522 1479 1480 1481 1483 1466 1453 1454 1463 1460 1464 1461 1468
1518 1521 1523 1524 1525 1526 1527 1528 1530 1531 1534 1535 1536 1539 1540 
  
  
   
  
  
	 }
    controlledprovinces = {
1459 1533 1538 1532 1519 1522 1479 1480 1481 1483 1466 1453 1454 1463 1460 1464 1461 1468
1518 1521 1523 1524 1525 1526 1527 1528 1530 1531 1534 1535 1536 1539 1540 


 
  
	  }
    nationalprovinces =   {
1459 1533 1538 1532 1519 1522 1479 1480 1481 1483 1466 1453 1454 1463 1460 1464 1461 1468
1518 1521 1523 1524 1525 1526 1527 1528 1530 1531 1534 1535 1536 1539 1540 
	}
diplomacy = {
relation = {   tag =  	GER	value =		         -100	   }  
relation = {   tag =  	AUS	value = 		-20	   }  
relation = {   tag =  	HUN	 value =		-20	   }  
relation = {   tag =  	IND	value = 		-175	   }  
relation = {   tag =  	PRK	value = 		-175	   }  
relation = {   tag =  	ENG	value = 		-100	   }  
relation = {   tag =  	FRA	value = 		-80	   }  
relation = {   tag =  	RSI	 value =		-80	   }  
relation = {   tag =  	CAN	value = 		175	   }  
relation = {   tag =  	VIC	value = 		150	   }  
relation = {   tag =  	RUS	 value =		50	   }  
relation = {   tag =  	CON	value = 		-20	   }  
relation = {   tag =   	USA	value = 		60	   }
relation = {   tag =  	JAP	value = 		75	   } 
relation = {   tag =  	PER	value = 		50	   } 
relation = {   tag =  	AFG	value = 		-150	   } 
relation = {   tag =  	AST	value = 		150	   } 
relation = {   tag =  	GUY	value = 		150	   }
relation = {   tag =  	NEP	value = 		-150	   } 


	
}



	
	techapps = {

#Infantry
1010  1020 1030 1040 1050 1060 1070 #1921 Infantry Division
1160  1170 1180 1190 1200 1210 1220 1230 1240 #Early Mountain Division
1560 #Naval Infantry
1910 1920 1930 1940 1950 1960 1970 1980 #Interbellum 1930 Supply 
13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 #1930 Cavalry Division 
1830 1840 1850 1860 #Engineers

#Armour & Artillery
2860 2870 2880 2020 #Basic Armoured Car 
2290 2300 2310 #Great War Heavy Field Artillery 
7600 7610 2620 2010 #SW Tank
2800 2450 #Early Static Anti-Air Artillery 

#Naval
3010 3020 3030 3040 #Great War Destroyer
3610 #SS
3720 3730 3736 3740 3750 3900 #Torpedo & ASW 18
3810 #Troopships

#Aircraft
4500 4510 4520 4530 4540 4550 4010 #Interwar Fighter 
4600 4610 4620 4630 4120 #Interwar Bomber 
4700 4710 #Naval Bomber

#Air Doctrines 
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010

#Industrial
5600 #Medicine
5310 54010 54020 54030 5316 5326 #Computers & cryptografi
5810 5820 5050 5830 #Manufactoring
5800 5080 5090 #Improved Construction Engineering 

#Land Doctrines (entente)
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6680 6540 6910
6010 6020 # Superior Firepower
14000 14010 #Hospitals

#Naval Doctrines
8010 8020 8030 8040 8050 8060 8070 8080 # Theories
8100 8110 8120 8150 8160 #Convoy Navigation
8900 8910 8920 8930 #Focused fire 
8500 8510 8520 #Distraction Action
8550 8560 #Commerce Raiders
82300 # Amphib
82500 # Logistic Support
}

dormant_ministers = { 564100 564101 564102 #U44
					  564103 564104 564105 564106 #Ganga Singh
					  #IND
					  564107 564108 564109 564110 564199 564200 564201 564202 564203 564204 564205 564206 564207 564208 564209 564210 564211 564212 564213 564214 564215 564216
					  564217 564218 564219 564220 564221 564222 564223 564224 564225
					  #PRK
					  564226 564227 564228 564229 564230 564231 564232 564233 564234 564235 564236 564237 564238 564239 564240 564241 564242
					  564113 564114 564115 564116
					  }

dormant_teams = { 12505 12506 12524 }

dormant_leaders = { #IND leaders 564215-564274
					564216 564217 564219 564221 564222 564223 564224 564225 564226 564227 564229 564231 564232 564234 564235 564236 564237 564238 564239 564240 564241 564242
					564243 564244 564245 564247 564248 564249 564250 564251 564252 564253 564254 564255 564256 564258 564262 564263 564265 564266 564267 564269 564270 564271
					564273 564274
					#PRK leaders 564275-564305
					564276 564277 564279 564282 564283 564284 564285 564287 564288 564289 564291 564294 564295 564296 564297 564298 564299 564302 564303 564304
					#OTL Pakistan leaders post-partition
					#564008 564017 564027 564032 564040 564041 564042 564043 564046 564056 564073 564088 564096 564105 564111 564114 564117 564118 564121 564122 564123 564124
					#564125 564126 564128 564129 564130 564132 564133 564134 564135 564144 564145 564146 564164 564166 564169 564171 564175 564215 564259 564275 564292
					}

#########  OOB (...)

landunit = {
		name = "1st Indian Army"
		location = 1521
		id = { type = 12700 id = 21 }
		division = {
			id = { type = 12700 id = 22 }
			name = "1st (Peshawar) Division"
			type = infantry
			model = 6
			strength = 100 }
	}

landunit = {
		name = "2nd Indian Army"
		location = 1480
		id = { type = 12700 id = 27 }
		division = {
			id = { type = 12700 id = 28 }
			name = "2nd (Rawalpindi) Division"
			type = infantry
			model = 6
			strength = 100 }
	}


	landunit = {
		name = "5th Indian Army"
		location = 1481
		id = { type = 12700 id = 29 }
		division = {
			id = { type = 12700 id = 30 }
			name = "5th (Mhow) Division"
			type = infantry
			model = 6
			extra = engineer
			brigade_model = 3
			strength = 100 }
	}

        landunit = {
		name = "4th Indian Army"
		location = 1479
		id = { type = 12702 id = 31 }
		division = {
			id = { type = 12702 id = 32 }
			name = "6th (Poona) Division"
			type = infantry
			model = 6
			strength = 100 }
	}
        landunit = {
		name = "3rd Indian Army"
		location = 1466
		id = { type = 12702 id = 33 }
		division = {
			id = { type = 12702 id = 34 }
			name = "4th (Quetta) Division"
			type = infantry
			model = 6
			strength = 100 }
	}

       landunit = {
		name = "6th Indian Army"
		location = 1483
		id = { type = 12702 id = 35 }
		division = {
			id = { type = 12702 id = 36 }
			name = "3rd (Lahore) Division"
			type = infantry
			model = 6
			strength = 100 }
	}

       landunit = {
		name = "7th Indian Army"
		location = 1539
		id = { type = 12702 id = 37 }
		division = {
			id = { type = 12702 id = 38 }
			name = "7th (Meerut) Division"
			type = infantry
			model = 6
	                extra  = artillery 
	                brigade_model = 3
	                experience = 2
			strength = 100 }
	}
       landunit = {
		name = "8th Indian Army"
		location = 1538
		id = { type = 12702 id = 39 }
		division = {
			id = { type = 12702 id = 40 }
			name = "8th (Lucknow) Division"
			type = infantry
			model = 6
			strength = 100 }
	}
       landunit = {
		name = "Bikaner State Forces"
		location = 1527
		id = { type = 12702 id = 41 }
		division = {
			id = { type = 12702 id = 42 }
			name = "Bikaner Camel Corps"
			type = cavalry
			model = 7
		        locked = yes
                        max_strength = 50
			strength = 50 }
		division = {
			id = { type = 12703 id = 55 }
			name = "Dungar Lancers"
			type = cavalry
			model = 7
		        locked = yes
                        max_strength = 10
			strength = 10 }
		division = {
			id = { type = 12703 id = 56 }
			name = "Sadul Light Infantry"
			type = d_01
			model = 6
		        locked = yes
                        max_strength = 10
			strength = 10 }
	}
       landunit = {
		name = "Jammu and Kashmir State Forces"
		location = 1540
		id = { type = 12702 id = 43 }
		division = {
			id = { type = 12702 id = 44 }
			name = "1st Jammu and Kashmir Infantry"
			type = infantry
			model = 5
		        locked = yes
                        max_strength = 50
			strength = 30 }
	}
       landunit = {
		name = "Delhi Independent Brigade"
		location = 1459
		id = { type = 12702 id = 45 }
		division = {
			id = { type = 12702 id = 46 }
			name = "Alwar Mangal Lancers"
			type = cavalry
			model = 7
			strength = 50 }
	}
       landunit = {
		name = "Bahawalpar State Forces"
		location = 1536
		id = { type = 12703 id = 53 }
		division = {
			id = { type = 12703 id = 54 }
			name = "1st Bahawalpar Infantry"
			type = infantry
			model = 6
		        locked = yes
	                extra  = light_armor_brigade 
	                brigade_model = 2
                        max_strength = 20
			strength = 20 }
		division = {
			id = { type = 12703 id = 61 }
			name = "2nd Bahawalpar Light Infantry"
			type = d_01
			model = 6
		        locked = yes
                        max_strength = 10
			strength = 10 }
	}

       landunit = {
		name = "Gwalior State Forces"
		location = 1523
		id = { type = 12702 id = 57 }
		division = {
			id = { type = 12703 id = 58 }
			name = "1st Gwalior Jayaji Lancers"
			type = cavalry
			model = 7
		        locked = yes
	                extra  = artillery 
	                brigade_model = 3
	                experience = 2
                        max_strength = 20
			strength = 20 }
		division = {
			id = { type = 12703 id = 59 }
			name = "1st Gwalior Maharani Sakhya Raja's Own Battalion"
			type = infantry
			model = 6
		        locked = yes
	                extra  = artillery 
	                brigade_model = 3
	                experience = 2
                        max_strength = 10
			strength = 10 }
		division = {
			id = { type = 12703 id = 60 }
			name = "2nd Gwalior Maharaja Jajaji Rao's Battalion"
			type = infantry
			model = 6
		        locked = yes
                        max_strength = 10
			strength = 10 }

	}

       landunit = {
		name = "Kapurthala State Forces"
		location = 1530
		id = { type = 12702 id = 62 }
		division = {
			id = { type = 12703 id = 63 }
			name = "Kapurthala Jagatjit Infantry"
			type = infantry
			model = 6
		        locked = yes
                        max_strength = 10
			strength = 10 }
		division = {
			id = { type = 12703 id = 64 }
			name = "Kapurthala Paramjit Infantry"
			type = infantry
			model = 6
		        locked = yes
                        max_strength = 10
			strength = 10 }
			

	}

	    landunit = {
		name = "North-Western Frontier Force"
		location = 1534
		id = { type = 12702 id = 65 }
		division = {
			id = { type = 12703 id = 66 }
			name = "8th Gorkha Rifles"
			type = bergsjaeger
			model = 8
			strength = 60 }
	}
	
	    landunit = {
		name = "Karachi Harbour Division"
		location = 1533
		id = { type = 12702 id = 67 }
		division = {
			id = { type = 12703 id = 68 }
			name = "11th Sindh Rifles"
			type = garrison
			model = 3
			locked = yes
			strength = 50 }
	}	
	
########## Indian Marine


navalunit = {
name = "Royal Indian Navy"
id = { type = 12703  id = 47 }
location = 1533
base = 1533
division = { id = { type = 12703 id = 48 } name = "HMIS Dufferin" type = light_cruiser model = 1 }
division = { id = { type = 12703 id = 49 } name = "HMIS Morthbrook" type = light_cruiser model = 1 }
division = { id = { type = 12703 id = 50 } name = "HMIS Minto " type = light_cruiser model = 1 }
division = { id = { type = 12703 id = 51 } name = "HMIS Hardinge" type = light_cruiser model = 1 }
division = { id = { type = 12703 id = 52 } name = "HMIS El Hind" type = transport model = 1 }
}

}

