


country = {
    tag = FRA

ai = "kaiserreich\France.ai"

	policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 3
        political_left = 9
        free_market = 1
        freedom = 4
        professional_army = 3
        defense_lobby = 6
        interventionism = 5
    }


	headofstate = { type = 9 id = 2216 }
	headofgovernment = { type = 9 id = 2217 }
 	foreignminister = { type = 9 id = 2218 }
 	armamentminister = { type = 9 id = 2219 }
 	ministerofsecurity = { type = 9 id = 2220  }
 	ministerofintelligence = { type = 9 id = 2221  }
 	chiefofstaff = { type = 9 id = 2007 }
 	chiefofarmy = { type = 9 id = 2223 }
 	chiefofnavy = { type = 9 id = 2224 }        
 	chiefofair = { type = 9 id = 2225 }

#### Resource Reserves
	capital = 55

SpyInfo  = {  country = "FRA" NumberOfSpies = 5  } 

	# Resource Reserves
	energy	=	1000   metal	= 1000		rare_materials =	2500	oil =	500	supplies =	500
	money = 50      transports = 60

	manpower = 560
        free = { ic = 10 }


    ownedprovinces =      {
		37 38 39 40 78 41 42 43 44 45 46 47 48 55 53 50 49 51 52 56 101 103 100 102 99 54 95 97
                98 88 64 63 66 60 58 59 57 62 70 69 68 67 83 84 75 73 72 61 65 90 86 89 93 82 79 80 76 77
                71 81 92 85 74
    
		
		
	 }
    controlledprovinces = {
		37 38 39 40 78 41 42 43 44 45 46 47 48 55 53 50 49 51 52 56 101 103 100 102 99 54 95 97
                98 88 64 63 66 60 58 59 57 62 70 69 68 67 83 84 75 73 72 61 65 90 86 89 93 82 79 80 76 77
                71 81 92 85 74
		
	  }
    nationalprovinces =   {
		37 38 39 40 78 41 42 43 44 45 46 47 48 55 53 50 49 51 52 56 101 103 100 102 99 54 95 97
                98 88 64 63 66 60 58 59 57 62 70 69 68 67 83 84 75 73 72 61 65 90 86 89 93 82 79 80 76 77
                71 81 92 85 74
                 91 87 94 106 96
	
	}
    claimedprovinces = { 
                391 104 105 107
                 }

diplomacy = {
relation = {   tag =    BEL	value = 		-120	   }  
relation = {   tag =  	BLR	 value =		-60	   }  
relation = {   tag =  	BUL	value = 		-60	   }  
relation = {   tag =  	GER	 value =		-180	   }  
relation = {   tag =  	LAT	value = 		-50	   }  
relation = {   tag =  	LIT	 value =		-50	   }  
relation = {   tag =  	POL	value = 		-20	   }  
relation = {   tag =  	UKR	 value =		-50	   }  
relation = {   tag =  	AUS	value = 		-120	   }  
relation = {   tag =  	BOS	value = 		-50	   }  
relation = {   tag =  	CRO	 value =		-60	   }  
relation = {   tag =  	CZE	value = 		-70	   }  
relation = {   tag =  	GLD	value = 		-40	   }  
relation = {   tag =  	HUN	 value =		-150	   }  
relation = {   tag =  	DEN	 value =		-30	   }  
relation = {   tag =  	HOL	 value =		-40	   }  
relation = {   tag =  	IRE	value = 		10	   }  
relation = {   tag =  	ITA	value = 		-120	   }  
relation = {   tag =  	POR	value = 		-40	   }  
relation = {   tag =  	ROM	value = 		40	   }  
relation = {   tag =  	SER	value = 		20	   }  
relation = {   tag =  	SPA	value = 		-120	   }  
relation = {   tag =  	ENG	value = 		120	   }  
relation = {   tag =  	RSI	 value =		150	   }  
relation = {   tag =  	AST	value = 		-40	   }  
relation = {   tag =  	CAN	value = 		-100	   }  
relation = {   tag =  	GUY	value = 		-30	   }  
relation = {   tag =  	NZL	 value =		-50	   }  
relation = {   tag =  	VIC	value = 		-180	   }  
relation = {   tag =  	RUS	 value =		20	   }  
relation = {   tag =  	OTT	 value =		-60	   }  
relation = {   tag =  	CON	value = 		-60	   }  
relation = {   tag =  	SAF	value = 		-20	   }  
relation = {   tag =   	USA	value = 		-40	   }
relation = {   tag =  	JAP	value = 		-60	   }  
relation = {   tag =  	GEO	value = 		100	   }  
relation = {   tag =  	PRK	value = 		100	   } 
relation = {   tag =  	MEX	value = 		100	   } 
}


	
	techapps = {

# FRA 1936 techs
#######################
#Armour & Artillery
2860 2870 2880 2020 2150 #Basic Armoured Car 
7600 7610 2620 2010 2630 2640 2646 2650 #Early Tank 
2290 2300 2310 2900 2910 2920 # Field Artillery 
2800 2450 21180 21190 #Early Static Anti-Air Artillery
2810 2820 2510 #Basic Anti-Air Artillery Brigade 
2400 #Early Anti-Tank Artillery

#Infantry
1010  1020 1030 1040 1050 1060 1070 1080 1090 #Early Infantry Division 
13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 #1930 Cavalry Division  
1160  1170 1180 1190 1200 1210 1220 1230 1240 #Early Mountain Division 
1396 #Motorised Inf
1560 1570 #Naval Infantry
1830 1840 1850 1860 #Engineers
1910 1920 1930 1940 1950 1960 1970 1980 #Interbellum 1930 Supply 

#Industrial
5700 5710 5010 #Modern Agriculture 
5810 5820 5050 5830 5060 #Basic Machine Tools 
5800 5080 5090  #Improved Construction Engineering 
5310 54010 54020 54030 #Computers 
5316 5326 #cryptografi
5470 5480 #Faculty of Atomic Research 
5600 5610 5620 5630 #Medicine
5560 #Exp. Rocket

#Naval
3010 3020 3030 3040 3050 3060 #Improved Destroyer 
3110 3120 3130 3140 3150 3160 #Basic Light Cruiser 
3210 3220 3230 3240 3250 3260 #Improved Heavy Cruiser 
3410 3420 3430 3440 3450 3456 3460 3470 #Early Battleship 
3510 #Great War Air Carrier 
12100 12110 12120 #Improved Light carrier
3610 3620 3630 3640 #Short Range Submarine 
3310 3320 3330 3340 # Battle Cruiser
3720 3730 3736 3740 3750 3900 #Torpedo & ASW 18
3810 3820 #Troopships

#Aircraft
4500 4510 4520 4530 4540 4550 4010 4020 #Early Fighter  
4600 4610 4620 4630 4120 4130 #Early Bomber 
4300 4310 4320 4330 #Multirole fighter
4740 4750 4760 4770 #SEAPLANES
7290 7300 7310 7320 #CAS
4800 4810 4820 #ww1 strategic bomber
4700 4710 #ww1 navalbomber
4900 4910 #CAG 30

# Great War Land Doctrines (entente)
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6680 6540 6910
14000 14010 14020 #Great War Hospital System 

#Naval Doctrines
8010 8020 8030 8040 8050 8060 8070 8080 # Theories
82300 # Amphibious Warfare
82500 # Naval Logistics
8500 8510 8550 8600 # Naval Interdiction
8900 8910 8920 8930 8940 # Engagement Tactic (Fleet-in-Being)
8100 8110 8120 8150 8160 8200 8210 # Naval Supremacy

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9040


	}

deactivate = { 6010 6210 6570 6560 6390 } 

###################
####### L'Armée Populaire de la Commune de France
###################

landunit = {
location =  55  #### Paris
name = "Grand Quartier Général de l'Armée Populaire"
        id = { type = 13507 id = 1 }
  division = {
  id = { type = 31871 id = 2 }
  name = "Grand Quartier Général de l'Armée Populaire"
  type = hq
  model = 2
  strength = 100
  }
}


landunit = {
location = 55  #### Paris
name = "Réserve de GQG"
      id = { type = 31871 id = 3  }
  division = {
  id = { type = 31871 id = 4 }
  name = "1ère Division Motorisé de Réserve"
  type = motorized
  model = 0
  extra = light_armor_brigade
  brigade_model = 4
  strength = 100
  }

  division = {
  id = { type = 31871 id = 5 }
  name = "2ème Division Motorisé de Réserve"
  type = motorized
  model = 0
  extra = light_armor_brigade
  brigade_model = 4
  strength = 100
  }

  division = {
  id = { type = 31871 id = 7  }
  name = "3ème Division Motorisé de Réserve"
  type = motorized
  model = 0
  extra = light_armor_brigade
  brigade_model = 4
  strength = 100
  }

  division = {
  id = { type = 31871 id = 91  }
  name = "10ème Division d'Infanterie"
  type = infantry
  model = 8
  strength = 100
  }

  division = {
  id = { type = 31871 id = 92  }
  name = "11ème Division d'Infanterie"
  type = infantry
  model = 8
  strength = 100
  }

  division = {
  id = { type = 31871 id = 95  }
  name = "12ème Division d'Infanterie"
  type = infantry
  model = 8
  strength = 100
  }

  division = {
  id = { type = 31871 id = 96  }
  name = "13ème Division d'Infanterie"
  type = infantry
  model = 8
  strength = 100
  }
}



landunit = {
location = 50    #### Amiens
name = "Ier Corps d'Armée"
      id = { type = 31871 id = 6 }
  division = {
  id = { type = 31871 id = 277  }
  name = "1ère Div. Légère de Cavalerie"
  type = cavalry
  model = 9
  strength = 100
  extra = anti_tank
  brigade_model = 2
  }

  division = {
  id = { type = 31871 id = 8  }
  name = "2ème Div. Légère de Cavalerie"
  type = cavalry
  model = 9
  strength = 100
  extra = anti_tank
  brigade_model = 2
  }

  division = {
  id = { type = 31871 id = 9  }
  name = "3ème Div. Légère de Cavalerie"
  type = cavalry
  model = 9
  strength = 100
  extra = anti_tank
  brigade_model = 2
  }
}



landunit = {
location = 63  #### Auxerre
name = "IIe Corps d'Armée"
      id = { type = 31871 id = 10  }
	division = {
  id = { type = 31871 id = 12 }
  name = "1ère Division Légère Mécanisée"
  type = cavalry
  model = 9
  strength = 100
  extra = light_armor_brigade
  brigade_model = 3
  }

  division = {
  id = { type = 31871 id = 13  }
  name = "2ème Division Légère Mécanisée"
  type = cavalry
  model = 9
  strength = 100
  extra = light_armor_brigade
  brigade_model = 3
  }

  division = {
  id = { type = 31871 id = 86  }
  name = "3ème Division Légère Mécanisée"
  type = cavalry
  model = 9
  strength = 100
  extra = light_armor_brigade
  brigade_model = 3
  }

  division = {
  id = { type = 31871 id = 90  }
  name = "4ème Division Légère Mécanisée"
  type = cavalry
  model = 9
  strength = 100
  extra = light_armor_brigade
  brigade_model = 3
  }
}



landunit = {
location = 63  #### Auxerre
name = "IIIe Corps d'Armée"
      id = { type = 31871 id = 14 }
	division = {
  id = { type = 31871 id = 16  }
  name = "5ème Division Légère Mécanique"
  type = motorized
  model = 0 
  extra = light_armor_brigade
  brigade_model = 3
  strength = 100
  }

  division = {
  id = { type = 31871 id = 17 }
  name = "6ème Division Légère Mécanique"
  type = motorized
  model = 0 
  extra = light_armor_brigade
  brigade_model = 3
  strength = 100
  }

  division = {
  id = { type = 31871 id = 88 }
  name = "9ème Division Légère Mécanique"
  type = motorized
  model = 0 
  extra = light_armor_brigade
  brigade_model = 3
  strength = 100
  }
}



landunit = {
location = 101  #### Laon
name = "VIe Corps d'Armée"
  id = { type = 31871 id = 18  }
  division = {
  id = { type = 31871 id = 20  }
  name = "7ème Division Légère Mécanique"
  type = cavalry
  model = 9
  extra = light_armor_brigade
  brigade_model = 4
  strength = 100
  }

  division = {
  id = { type = 31871 id = 21  }
  name = "8ème Division Légère Mécanique"
  type = cavalry
  model = 9
  extra = light_armor_brigade
  brigade_model = 3
  strength = 100
  }

  division = {
  id = { type = 31871 id = 85  }
  name = "10ème Division Légère Mécanique"
  type = cavalry
  model = 9
  extra = light_armor_brigade
  brigade_model = 3
  strength = 100
  }
}



landunit = {
location = 78  #### Cholet
name = "IIIe Corps d'Armée"
      id = { type = 31871 id = 22  }

  division = {
  id = { type = 31871 id = 23  }
  name = "1ère Division d'Infanterie"
  type = infantry
  model = 8
  strength = 100
  extra = super_heavy_artillery
  brigade_model = 1
  }

  division = {
  id = { type = 31871 id = 24  }
  name = "2ème  Division d'Infanterie"
  type = infantry
  model = 8
  strength = 100
  extra = super_heavy_artillery
  brigade_model = 1
  }

  division = {
  id = { type = 31871 id = 276  }
  name = "9ème Division d'Infanterie"
  type = infantry
  model = 8
  strength = 100
  }
}



landunit = {
location = 89  #### Marseilles
name = "IVème Corps d'Armée"
      id = { type = 31871 id = 25  }

  division = {
  id = { type = 31871 id = 26  }
  name = "3ème Division d'Infanterie"
  type = infantry
  model = 8
  strength = 100
  extra = artillery
  brigade_model = 6
  }

  division = {
  id = { type = 31871 id = 27  }
  name = "5ème Division d'Infanterie"
  type = infantry
  model = 8
  strength = 100
  extra = artillery
  brigade_model = 6
  }

  division = {
  id = { type = 31871 id = 275  }
  name = "8ème Division d'Infanterie"
  type = infantry
  model = 8
  strength = 100
  extra = artillery
  brigade_model = 6
  }
}



landunit = {
location = 74  #### Vichy
name = "Vème Corps d'Armée"
      id = { type = 31871 id = 28  }

  division = {
  id = { type = 31871 id = 29  }
  name = "4ème Division d'Infanterie"
  type = infantry
  model = 8
  strength = 100
  extra = artillery
  brigade_model = 6
  }

  division = {
  id = { type = 31871 id = 30  }
  name = "6ème Division d'Infanterie"
  type = infantry
  model = 8
  strength = 100
  extra = artillery
  brigade_model = 6
  }

  division = {
  id = { type = 31871 id = 274  }
  name = "7ème Division d'Infanterie"
  type = infantry
  model = 8
  strength = 100
  extra = artillery
  brigade_model = 6
  }
}



landunit = {
location = 68  #### Bordeaux
name = "VIIème Corps d'Armée"
      id = { type = 31871 id = 31  }

  division = {
  id = { type = 31871 id = 32  }
  name = "1ère Div. d'Infanterie de Marine"
  type = marine
  model = 1
  strength = 70
  }

  division = {
  id = { type = 31871 id = 33 }
  name = "2ème Div. d'Infanterie de Marine"
  type = marine
  model = 1
  strength = 70
  }

  division = {
  id = { type = 31871 id = 34  }
  name = "3ème Div. d'Infanterie de Marine"
  type = marine
  model = 1
  strength = 70
  }
}



landunit = {
location = 73  #### Chalon
name = "VIIIe Corps d'Armée"
      id = { type = 31871 id = 35  }

  division = {
  id = { type = 31871 id = 36  }
  name = "1ère Division Légère de Chasseurs"
  type = bergsjaeger 
  model = 8
  strength = 100
  extra = artillery
  brigade_model = 6
  }

  division = {
  id = { type = 31871 id = 37  }
  name = "2ème Division Légère de Chasseurs"
  type = bergsjaeger 
  model = 8
  strength = 100
  extra = artillery
  brigade_model = 6
  }

  division = {
  id = { type = 31871 id = 87  }
  name = "3ème Division Légère de Chasseurs"
  type = bergsjaeger 
  model = 8
  strength = 100
  extra = artillery
  brigade_model = 6
  }
}


##################################
#########  LA GARDE NATIONALE (mobilisée déjà pour la defense de la patrie!)
##################################

#########################


landunit = {
location = 97
name = "Ière Division de la Garde Nationale"
      id = { type = 31871 id = 38  }

  division = {
  id = { type = 31871 id = 39  }
  name = "1ère Division d'Infanterie Prolétarienne"
  type = infantry
  model = 6
  strength = 60
  }

  division = {
  id = { type = 31871 id = 40  }
  name = "2ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 50
  }

  division = {
  id = { type = 31871 id = 41  }
  name = "3ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 50
  }
}


landunit = {
location = 88
name = "IIème Division de la Garde Nationale"
      id = { type = 31871 id = 42 }

  division = {
  id = { type = 31871 id = 43  }
  name = "4ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 6
  strength = 60
  }
  division = {
  id = { type = 31871 id = 44 }
  name = "5ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 50
  }
  division = {
  id = { type = 31871 id = 45 }
  name = "6ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 50
  }
}


landunit = {
location = 95
name = "IIIème Division de la Garde Nationale"
      id = { type = 31871 id = 46  }

  division = {
  id = { type = 31871 id = 47  }
  name = "7ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 6
  strength = 60
  }
  division = {
  id = { type = 31871 id = 48 }
  name = "8ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 50
  }
  division = {
  id = { type = 31871 id = 49  }
  name = "9ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 50
  }
}


landunit = {
location = 99
name = "IVème Division de la Garde Nationale"
      id = { type = 31871 id = 50 }

  division = {
  id = { type = 31871 id = 51  }
  name = "10ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 6
  strength = 60
  }
  division = {
  id = { type = 31871 id = 52  }
  name = "11ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 50
  }
  division = {
  id = { type = 31871 id = 53 }
  name = "12ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 50
  }
}


landunit = {
location = 51
name = "Vème Division de la Garde Nationale"
      id = { type = 31871 id = 54 }

  division = {
  id = { type = 31871 id = 55 }
  name = "13ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 6
  strength = 60
  }
  division = {
  id = { type = 31871 id = 56 }
  name = "14ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 50
  }
  division = {
  id = { type = 31871 id = 57  }
  name = "15ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 50
  }
}


landunit = {
location = 103
name = "VIème Division de la Garde Nationale"
      id = { type = 31871 id = 58  }

  division = {
  id = { type = 31871 id = 59  }
  name = "16ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 6
  strength = 60
  }
  division = {
  id = { type = 31871 id = 60  }
  name = "17ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 50
  }
  division = {
  id = { type = 31871 id = 61  }
  name = "18ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 50
  }
}


landunit = {
location = 102
name = "VIIème Division de la Garde Nationale"
      id = { type = 31871 id = 62  }

  division = {
  id = { type = 31871 id = 63 }
  name = "19ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 6
  strength = 60
  }
  division = {
  id = { type = 31871 id = 64 }
  name = "20ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 50
  }
  division = {
  id = { type = 31871 id = 65 }
  name = "21ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 50
  }
}



landunit = {
location = 100
name = "VIIIème Division de la Garde Nationale"
      id = { type = 31871 id = 81  }

  division = {
  id = { type = 31871 id = 82  }
  name = "22ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 85
  }

  division = {
  id = { type = 31871 id = 83  }
  name = "23ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 85
  }

  division = {
  id = { type = 31871 id = 84  }
  name = "24ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 85
  }

}


landunit = {
location = 90
name = "VIIIème Division de la Garde Nationale"
      id = { type = 31871 id = 97  }

  division = {
  id = { type = 31871 id = 93  }
  name = "25ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 85
  }

  division = {
  id = { type = 31871 id = 94  }
  name = "26ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 85
  }

  division = {
  id = { type = 31871 id = 98  }
  name = "27ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 6
  strength = 85
  }

}


landunit = {
location = 52
name = "IXème Division de la Garde Nationale"
      id = { type = 31871 id = 99  }

  division = {
  id = { type = 31871 id = 100  }
  name = "28ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 85
  }

  division = {
  id = { type = 31871 id = 101  }
  name = "29ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 7
  strength = 85
  }

  division = {
  id = { type = 31871 id = 102  }
  name = "30ème Division d'Infanterie Prolétarienne"
  type = infantry
  model = 6
  strength = 85
  }

}


####################################################


airunit = {
id = { type = 13500 id = 206 }
name = "1ère Groupe de Bombardement"
location = 55
base = 55

division = { id = { type = 13500 id = 207 } name = "Groupe de Bombardement Tactique 1" strength = 100 type = tactical_bomber model = 6 }
division = { id = { type = 13500 id = 211 } name = "Groupe de Bombardement Tactique 2" strength = 100 type = tactical_bomber model = 6 }
division = { id = { type = 13500 id = 215 } name = "Groupe de Bombardement Tactique 3" strength = 100 type = tactical_bomber model = 6 }
}


airunit = {
location = 89
base = 89
id = { type = 13500 id = 222 }
name = "2ème Groupe de Bombardement"
division = { id = { type = 13500 id = 280 } name = "Groupe de Bombardement Tactique 4" strength = 100 type = tactical_bomber model = 6 }
division = { id = { type = 13500 id = 281 } name = "Groupe de Bombardement Tactique 5" strength = 100 type = tactical_bomber model = 6 }
division = { id = { type = 13500 id = 223 } name = "Groupe de Bombardement Tactique 6" strength = 100 type = tactical_bomber model = 6 }
}

airunit = {
location = 55
base = 55
id = { type = 13500 id = 226 }
name = "1ère Groupe de Chasse"

  division = {
  id = { type = 13500 id = 227 }
  name = "Groupe de Chasse 1"
  strength = 100
  type = interceptor
  model = 7
  }

  division = {
  id = { type = 13500 id = 231 }
  name = "Groupe de Chasse 3"
  strength = 100
  type = interceptor
  model = 7
  }
  division = {
  id = { type = 13500 id = 278 }
  name = "Groupe de Chasse 4"
  strength = 100
  type = interceptor
  model = 7
  }
  division = {
  id = { type = 13500 id = 288 }
  name = "Groupe de Chasse 7"
  strength = 100
  type = interceptor
  model = 7
  }
  }

airunit = {
location = 89
base = 89
id = { type = 13500 id = 234 }
name = "2ème Groupe de Chasse"

division = {
id = { type = 13500 id = 235 }
name = "Groupe de Chasse 2"
strength = 100
type = interceptor
model = 7
}
division = {
id = { type = 13500 id = 279 }
name = "Groupe de Chasse 5"
strength = 100
type = interceptor
model = 7
}
division = {
id = { type = 13500 id = 282 }
name = "Groupe de Chasse 6"
strength = 100
type = interceptor
model = 7
}
}

navalunit = {
 name = "Flotte de la Commune"
 id = { type = 13862 id = 250 }
 location = 86 #### [Toulon] [Fleet of the Homeland]
 base = 86

 division = { id = { type = 13862 id = 252 } name = "Robespierre" type = battleship model = 6 }
 division = { id = { type = 13862 id = 1007 } name = "Marat" type = battleship model = 6 } 
 division = { id = { type = 13862 id = 1015 } name = "Normandie" type = battleship model = 4 } # change the name
 division = { id = { type = 13862 id = 1016 } name = "Flandre" type = battleship model = 4 } # change the name
 division = { id = { type = 13862 id = 1017 } name = "Gascogne" type = battleship model = 4 } # change the name
 division = { id = { type = 13862 id = 1018 } name = "Languedoc" type = battleship model = 4 } # change the name
 division = { id = { type = 13862 id = 1019 } name = "Bearn" type = battleship model = 4 } # change the name
 division = { id = { type = 13862 id = 1020 } name = "Lyon" type = battleship model = 4 } # change the name 
 division = { id = { type = 13862 id = 1021 } name = "Duquesne" type = battleship model = 4 } # change the name
 division = { id = { type = 13862 id = 1022 } name = "Lille" type = battleship model = 4 } # change the name
 division = { id = { type = 13862 id = 1023 } name = "Tourville" type = battleship model = 4 } # change the name
 division = { id = { type = 13862 id = 253 } name = "Georges Sorel" type = battleship model = 3 }
 division = { id = { type = 13501 id = 1024 } name = "Commandant Teste" type = escort_carrier model = 0 } # change the name
 division = { id = { type = 13862 id = 256 } name = "Paris" type = light_cruiser model = 3 }
 division = { id = { type = 13862 id = 257 } name = "Marseille" type = light_cruiser model = 3 }
 division = { id = { type = 13862 id = 258 } name = "Lyon" type = light_cruiser model = 3 }
 division = { id = { type = 13862 id = 1000 } name = "Toulon" type = light_cruiser model = 3 }
 division = { id = { type = 13862 id = 1001 } name = "Toulouse" type = light_cruiser model = 3 }
 division = { id = { type = 13862 id = 260 } name = "2ème Flotille des Contre-Torpilleurs" type = destroyer model = 4 }
 division = { id = { type = 13862 id = 261 } name = "3ème Flotille des Contre-Torpilleurs" type = destroyer model = 4 }
 division = { id = { type = 13862 id = 262 } name = "4ème Flotille des Contre-Torpilleurs" type = destroyer model = 4 }
 }

 navalunit = {
 name = "1ere Flotte de Sous-Marins"
 id = { type = 13862 id = 263 }
 location = 86 ####
 base = 86

 division = { id = { type = 13862 id = 264 } name = "1ère Flotille des Sous-Marins" type = submarine model = 3 }
 division = { id = { type = 13862 id = 265 } name = "2ème Flotille des Sous-Marins" type = submarine model = 3 }
 division = { id = { type = 13862 id = 272 } name = "3ème Flotille des Sous-Marins" type = submarine model = 3 }
 division = { id = { type = 13862 id = 1013 } name = "4ème Flotille des Sous-Marins" type = submarine model = 3 }
 division = { id = { type = 13862 id = 1014 } name = "5ème Flotille des Sous-Marins" type = submarine model = 3 }
 }

 navalunit = {
 name = "Flotte de la Fédération"
 id = { type = 13862 id = 266 }
 location = 37 #### Flotte de la Normandie [Brest]
 base = 37 

 division = { id = { type = 13862 id = 255 } name = "Internationale" type = battleship model = 4 }
 division = { id = { type = 13862 id = 271 } name = "Charles Fourier" type = battlecruiser model = 3 }
 division = { id = { type = 13862 id = 273 } name = "Jean-Sylvain Bailly" type = heavy_cruiser model = 3 }
 division = { id = { type = 13862 id = 267 } name = "Jean-Louis Pindy" type = heavy_cruiser model = 3 }
 division = { id = { type = 13862 id = 268 } name = "Saint-Etienne" type = light_cruiser model = 3 }
 division = { id = { type = 13862 id = 1004 } name = "Rennes" type = light_cruiser model = 3 }
 division = { id = { type = 13862 id = 1005 } name = "Saint-Nazaire" type = light_cruiser model = 4 }
 division = { id = { type = 13862 id = 269 } name = "1ère Flotille des Contre-Torpilleurs" type = destroyer model = 3 }
 division = { id = { type = 13862 id = 270 } name = "5ème Flotille des Contre-Torpilleurs" type = destroyer model = 3 }
 division = { id = { type = 13862 id = 1008 } name = "6ème Flotille des Contre-Torpilleurs" type = destroyer model = 3 }
 division = { id = { type = 13862 id = 1009 } name = "7ème Flotille des Contre-Torpilleurs" type = destroyer model = 3 }
 division = { id = { type = 13862 id = 1010 } name = "8ème Flotille des Contre-Torpilleurs" type = destroyer model = 3 }


 }

 navalunit = {
 name = "Flotte de Transports"
 id = { type = 13862 id = 300 }
 location = 37
 base = 37
 division = { id = { type = 13862 id = 301 } name = "1ère Flotille de Convoi" type = transport model = 1 }
 division = { id = { type = 13862 id = 302 } name = "2ème Flotille de Convoi" type = transport model = 1 }
 division = { id = { type = 13862 id = 303 } name = "3ème Flotille de Convoi" type = transport model = 1 }
 division = { id = { type = 13862 id = 1011 } name = "4ème Flotille de Convoi" type = transport model = 1 }
 division = { id = { type = 13862 id = 1012 } name = "5ème Flotille de Convoi" type = transport model = 1 }



 }

 }