


country = {
tag = GER

ai = "kaiserreich\Germany.ai"
policy = {
date = { year = 0 month = january day = 0 }
democratic = 4
political_left = 3
free_market = 5
freedom = 6
professional_army = 6
defense_lobby = 7
interventionism = 6
}

peacetime_ic_mod = 0.75

headofstate = { type = 9 id = 36 }
headofgovernment = { type = 9 id = 386 }
foreignminister = { type = 9 id = 68 }
armamentminister = { type = 9 id = 77 }
ministerofsecurity = { type = 9 id = 121 }
ministerofintelligence = { type = 9 id = 12 }
chiefofstaff = { type = 9 id = 257 }
chiefofarmy = { type = 9 id = 255 }
chiefofnavy = { type = 9 id = 9 }
chiefofair = { type = 9 id = 273 }


#### Resource Reserves

	SpyInfo = { country = "GER" NumberOfSpies = 7 }

	capital = 163

	manpower = 850

	energy	= 1000
	metal = 1000
	rare_materials = 500
	oil = 500
	supplies = 500
	money =	70


ownedprovinces =      {
96 106 105 107 111 108 104 109 110 132 133 135 178 179 176 175 177 134 136 130 127 174 180 139 138 140
143 128 129 126 131 142 145 141 144 147 148 149 146 137 171 170 173 172 157 169 156 153 162 151 154 152
150 216 160 163 158 159 165 164 166 167 168 221 224 225 161 155 226 181 183 222 185 182 184 261

719 720 722 718 717 721 723 725 726 724  #Morocco

429 #Malta
833 #Djibouti
900 1007 # Suez
964 #Sierra Leone
1421 1746 1732 1741 1742

# MISC
993 #Ascension island
896 #St.Helena
1611 1612 #Seychelles
998 999 1000 997 1613 1614
1053

# PACIFIC
1670 1671 1668 1669 1234 1684 1685 1748 1686 1667 1676 1665 1666 1674 1675 1681 1677 1678 1679 1680 1682 1687 1602 1605 1610 1603 1724 1725 1726 1727 1587 1589 1588 1591 1590 1593 1582 1592 1581 1583 1584 1585 1586  1730 1749 1731 1750 1744 1743 1740


#SOUTHEAST ASIA
1432 1437 1438  #Malay States
1624 1625 1626 #Sarawak-Borneo

#INDIAN OCEAN AREA
1001 1003 1002 # Madagascar
996 #Reunion
#ASIA
1399 1403 1397 1398 1394 1396 1405 1395 1391 1404 1392 1393#Indochine

1328 1331 1241 1245 1365 1367 ## China
1509 1510 1511 ## Sri Lanka

}
controlledprovinces = {
96 106 105 107 111 108 104 109 110 132 133 135 178 179 176 175 177 134 136 130 127 174 180 139 138 140
143 128 129 126 131 142 145 141 144 147 148 149 146 137 171 170 173 172 157 169 156 153 162 151 154 152
150 216 160 163 158 159 165 164 166 167 168 221 224 225 161 155 226 181 183 222 185 182 184 261

719 720 722 718 717 721 723 725 726 724  #Morocco

429 #Malta
833 #Djibouti
900 1007 # Suez
964 #Sierra Leone
1421 1746 1732 1741 1742

# MISC
993 #Ascension island
896 #St.Helena
1611 1612 #Seychelles
998 999 1000 997 1613 1614
1053

# PACIFIC
1670 1671 1748 1668 1669 1234 1684 1685 1686 1667 1676 1665 1666 1674 1675 1681 1677 1678 1679
1680 1682 1687 1602 1605 1610 1603 1724 1725 1726 1727 1587 1589 1588 1591 1590 1593 1582 1592
1581 1583 1584 1585 1586  1730 1749 1731 1750 1744 1743 1740


#SOUTHEAST ASIA
1432 1437 1438   #Malay States
1624 1625 1626 #Sarawak-Borneo

#INDIAN OCEAN AREA
1001 1003 1002 # Madagascar
996 #Reunion
#ASIA
1399 1403 1397 1398 1394 1396 1405 1395 1391 1404 1392 1393#Indochine

1328 1331 1241 1245 1365 1367 ## China
1509 1510 1511 ## Sri Lanka

}
nationalprovinces =   {
105 107 104 109 110 132 133 135 178 179 176 175 177 134 136 130 127 174 180
139 138 140 143 128 129 126 131 142 145 141 147 148 149 146 144 137 171 170 173 172
157 169 156 153 162 151 154 152 150 216 160 163 158 159 165 164 166 167 168 222 224
225 161 155 226 181 183 185 182 184 261 221

}
claimedprovinces = {
108 111 #Wallonia
96 106 #french dominant Lorraine
429 #Malta
1432 #Singapore
900 1007 #Suez
1602 1605 1610 1603 1234 #Papua
1328 1331 1241 1245 1365 1367 ## China
}

diplomacy = {
relation = { tag = 	BEL   value = 199	access = yes   guaranteed = { day = 29 month = december year = 1933   } 	   }
relation = { tag = 	BLR   value = 193	access = yes   guaranteed = { day = 29 month = december year = 1933   } 	   }
relation = { tag = 	BUL   value = 143	access = yes   guaranteed = { day = 29 month = december year = 1933   } 	   }
relation = { tag = 	LAT   value = 178	access = yes   guaranteed = { day = 29 month = december year = 1933   } 	   }
relation = { tag = 	LIT   value = 171	access = yes   guaranteed = { day = 29 month = december year = 1933   } 	   }
relation = { tag = 	POL   value = 119	access = yes   guaranteed = { day = 29 month = december year = 1933   } 	   }
relation = { tag = 	UKR   value = 200	access = yes   guaranteed = { day = 29 month = december year = 1933   } 	   }
relation = { tag = 	AUS   value = 169	guaranteed = { day = 29 month = december year = 1933   } 	   }
relation = { tag = 	BOS   value = 69	   }
relation = { tag = 	CRO   value = 119		   }
relation = { tag = 	CZE   value = 91		   }
relation = { tag = 	GLD   value = 79		   }
relation = { tag = 	HUN   value = 124	guaranteed = { day = 29 month = december year = 1933   }    }
relation = { tag = 	ALB   value = 83	guaranteed = { day = 29 month = december year = 1933   } 	   }
relation = { tag = 	DEN   value = 87	guaranteed = { day = 29 month = december year = 1935   }	   }
relation = { tag = 	FIN   value = 114	guaranteed = { day = 29 month = december year = 1933   } 	   }
relation = { tag = 	GRE   value = -37		   }
relation = { tag = 	HOL   value = 148	guaranteed = { day = 29 month = december year = 1933   } 	   }
relation = { tag = 	IRE   value = 63		   }
relation = { tag = 	ITA   value = 83	guaranteed = { day = 29 month = december year = 1933   } 	   }
relation = { tag = 	NOR   value = 39		   }
relation = { tag = 	POR   value = 39		   }
relation = { tag = 	ROM   value = -109		   }
relation = { tag = 	SCH   value = 34	guaranteed = { day = 16 month = may year = 1935 	}	   }
relation = { tag = 	SER   value = -60		   }
relation = { tag = 	SPA   value = 90		   }
relation = { tag = 	SWE   value = 60		   }
relation = { tag = 	ENG   value = -129		   }
relation = { tag = 	FRA   value = -169		   }
relation = { tag = 	RSI   value = -88		   }
relation = { tag = 	AST   value = -30	           }
relation = { tag = 	CAN   value = -50		   }
relation = { tag = 	GUY   value = -10		   }
relation = { tag = 	NZL   value = -70		   }
relation = { tag = 	VIC   value = -30	           }
relation = { tag = 	ARM   value = -40		   }
relation = { tag = 	AZB   value = 50		   }
relation = { tag = 	GEO   value = -40		   }
relation = { tag = 	KAZ   value = 40		   }
relation = { tag = 	KYG   value = -90		   }
relation = { tag = 	PRI   value = -100		   }
relation = { tag = 	RUS   value = 50	   }
relation = { tag = 	TRA   value = 80	guaranteed = { day = 29 month = december year = 1933   } 	   }
relation = { tag = 	AFG   value = 60		   }
relation = { tag = 	CYN   value = 30		   }
relation = { tag = 	EGY   value = 100	 	   }
relation = { tag = 	LBY   value = 50	 	   }
relation = { tag = 	OMN   value = 120		   }
relation = { tag = 	OTT   value = 120	 	   }
relation = { tag = 	PER   value = 25	           }
relation = { tag = 	SAU   value = -60		   }
relation = { tag = 	YEM   value = 120		   }
relation = { tag = 	CON   value = 200	guaranteed = { day = 29 month = december year = 1933   } 	   }
relation = { tag = 	ETH   value = 20		   }
relation = { tag = 	LIB   value = -50		   }
relation = { tag = 	SAF   value = -40		   }
relation = { tag = 	BUR   value = 40		   }
relation = { tag = 	IND   value = -30		   }
relation = { tag = 	PAK   value = -20		   }
relation = { tag = 	PHI   value = -40		   }
relation = { tag = 	SIA   value = -20	           }
relation = { tag = 	EAF   value = 60        guaranteed = { day = 29 month = december year = 1935   } 	   }
relation = { tag = 	ARG   value = 100	           }
relation = { tag = 	BOL   value = -40		   }
relation = { tag = 	BRA   value = -20		   }
relation = { tag = 	CHL   value = -40		   }
relation = { tag = 	COL   value = -40		   }
relation = { tag = 	CUB   value = -40		   }
relation = { tag = 	DOM   value = 60		   }
relation = { tag = 	ECU   value = -20		   }
relation = { tag = 	MEX   value = 60		   }
relation = { tag = 	PAN   value = -80		   }
relation = { tag = 	PRU   value = 50		   }
relation = { tag = 	URU   value = 20		   }
relation = { tag = 	VEN   value = 10		   }
relation = { tag = 	USA   value = -40		 }
relation = { tag = 	CGX   value = 150	access = yes   guaranteed = { day = 29 month = december year = 1933   } 	   }
relation = { tag = 	CHC   value = -90		   }
relation = { tag = 	CSX   value = 120	access = yes   guaranteed = { day = 29 month = december year = 1933   } 	   }
relation = { tag = 	CXB   value = 50		   }
relation = { tag = 	JAP   value = -80		   }
relation = { tag = 	MAN   value = -40		   }
relation = { tag = 	MON   value = -80		   }

}


techapps = {

# Germany 1936 techs
#######################
#Infantry
1010 1020 1030 1040 1050 1060 1070 1080 1090 #Early Infantry Division
13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380 #SEMI-MOTORIZED CAVALRY
1396 # Motorized Infantry
1160  1170 1180 1190 1200 1210 1220 1230 1240 #Early Mountain Division
1830 1840 1850 1860 #Engineers
1910 1920 1930 1940 1950 1960 1970 1980 #Interbellum 1930 Supply
1560 1570 1580 #Marine Divisions

#Armour & Artillery
2860 2870 2880 2020 2150 #Basic Armoured Car
7600 7610 2620 2010 2630 2640 2646 2650 2030 #Early Tank
2290 2300 2310 2900 2910 2920 2930 #Early Field Artillery
2800 2450 21180 21190 21200 #Early Static Anti-Air Artillery
2810 2820 2510 #Basic Anti-Air Artillery Brigade

#Naval
3010 3020 3030 3040 3050 3060 #Improved Destroyer
3110 3120 3130 3140 3150 3160 #Basic Light Cruiser
3210 3220 3230 3240 3250 3260 #Improved Heavy Cruiser
3310 3320 3330 3340 #Early Battlecruiser
3410 3420 3430 3440 3450 3456 3460 3470 #Early Battleship
3610 3620 3630 3640 3650 #Improved Submarine
3510 3520 3530 #Early Air Carrier (Graff Zeppelin)
12100 12110 12120 12130 #(Constructing Stuttgart-class)
3720 3730 3736 3740 3750 3900 #Torpedo & ASW 18
3810 3820 #Troopships 1926

#Aircrafts
4290 4250 #Basic Air Transport
4300 4310 4320 4330 4340 #Multirole fighter
7290 7300 7310 7320 4400 #CAS
4800 4810 4820 #ww1 strategic bomber
4700 4710 #ww1 navalbomber
4500 4510 4520 4530 4540 4550 4010 4020 #Early Fighter
4600 4610 4620 4630 4120 4130 #Early Bomber
4740 4750 4760 4770 #SEAPLANES
4900 4910 #CAG

#Industrial
5810 5820 5050 5830 5060 #Manufacturing
5800 5080 5090 #Improved Construction Engineering
5190 5200 #Basic Oil Refining
5310 54010 54020 54030 5316 5326 #Computers & cryptografi
5470 5480 #Faculty of Atomic Research
5560 #Exp. Rocket
5700 5710 5010 5020 #Mechanized Agriculture
5600 5610 5620 5630 #Medicine

# Great War Land Doctrines (central powers)
6500 6510 6530 6550 6590 6600 6610 6620 6650 6670 6680 6690 6700 6710 6910
14000 14010 14020 #Great War Hospital System

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9040 9050 9090

#Naval Doctrines
8010 8020 8030 8040 8050 8060 8070 8080
8500 8510 8520 8550 8560 # Naval Interdiction
82300 # Amphib
82500 # Naval Logistics
8900 8910 8920 8930 8940 8950 # Fleet in being
8600 8610 # Trade Interdiction Submarine
8100 8110 8120 8150 8160 8170 8200 8210 # Naval Supremacy
81650 # Subsidiary carrier role
}


deactivate = { 6010 6210 6570 6560 6390 }

dormant_teams = { 44
				19 28 #Steyr-Puch, Skoda
				68 72 73 74 75 76 #Land doctrine teams
				56 57 58 59 } #Bomber doctrine teams

dormant_ministers = { 385 214 219 }

dormant_leaders = { #AUS
				  1200 1201 1202 1203 1204 1205 1206 1207 1208 1209 1210 1211 1212 1213 1214 1215 1216 1217 1218 1219
				  1220 1221 1222 1223 1224 1225 1226 1227 1228 1229
				  #LAT - United Baltic Duchy
				  1240 1241 1242 1243 1244 1245
				  1239 #CZE
				  285 #CON - Mittelafrika
				  }

##########

transports = 700
escorts = 45     #### Limited to reflect over-reliance on Hochseeflotte



#########  OOB (14500 for air and navy)  (14502 for land  )


########################################################################
############
#######Das Kaiserliche Deutsche Heer - 1936
#################

landunit = {
location = 163 ### (Berlin)
name = "Oberste Heeres Leitung"
id = { type = 14502 id = 1 }
division = {
id = { type = 14502 id = 2 }
name = "Oberste Heeres Leitung"
type = hq
model = 2
strength = 100
}
}

landunit = {
location = 138  ### (Frankfurt)
name = "OHL Hauptquartier West"
id = { type = 14502 id = 3 }
division = {
id = { type = 14502 id = 4 }
name = "Hauptquartier West"
type = hq
model = 2
strength = 100
}
}


landunit = {
location = 184  ### (Königsberg)
name = "OHL Hauptquartier Ost"
id = { type = 14502 id = 5 }
division = {
id = { type = 14502 id = 6 }
name = "Hauptquartier Ost"
type = hq
model = 2
strength = 100
}

}

landunit = {
location = 1432  ### (Singapore)
name = "OHL Hauptquartier Asien"
id = { type = 14502 id = 136 }
division = {
id = { type = 14502 id = 137 }
name = "Hauptquartier Asien"
type = hq
model = 2
strength = 100
}
}

landunit = {
location = 138 ### (Frankfurt)
name = "Motorisiertes-Kavallerie Kommando I"
id = { type = 14502 id = 7  }
division = {
id = { type = 14502 id = 8 }
name = "1. Motorisierte Garde Kavallerie Division"
type = cavalry
model = 8
extra = armored_car
brigade_model = 3
strength = 100
}
division = {
id = { type = 14502 id = 9  }
name = "1. Motoriserte-Kavallerie Division"
type = cavalry
model = 8
extra = armored_car
brigade_model = 3
strength = 100
}
division = {
id = { type = 14502 id = 10   }
name = "2. Motoriserte-Kavallerie Division"
type = cavalry
model = 8
extra = armored_car
brigade_model = 3
strength = 100
}
}

landunit = {
location = 177  ### (Nürnberg)
name = "Motorisiertes-Kavallerie Kommando II"
division = {
id = { type = 14502 id = 11 }
name = "1. Bayerische Kavallerie Division"
type = cavalry
model = 8
extra = armored_car
brigade_model = 3
strength = 100
}

division = {
id = { type = 14502 id = 140 }
name = "2. Bayerische Kavallerie Division"
type = cavalry
model = 8
extra = armored_car
brigade_model = 3
strength = 100
}

division = {
id = { type = 14502 id = 12 }
name = "1. Sächsische Kavallerie Division"
type = cavalry
model = 8
extra = armored_car
brigade_model = 3
strength = 100
}
}


landunit = {
location = 163  ### (Berlin)
name = "I. Panzerkampfwagen Kommando"
id = { type = 14502 id = 13  }
division = {
id = { type = 14502 id = 14  }
name = "1. Motorisierte-Infanterie Division"
type = motorized
model = 0
extra = light_armor_brigade
brigade_model = 4
strength = 100
}

division = {
id = { type = 14502 id = 15 }
name = "2. Motorisierte-Infanterie Division"
type = motorized
model = 0
strength = 100
extra = anti_tank
brigade_model = 2
}

division = {
id = { type = 14502 id = 138 }
name = "3. Motorisierte-Infanterie Division"
type = motorized
model = 0
strength = 100
extra = anti_tank
brigade_model = 2
}
}


landunit = {
location = 163   ### (Berlin)
name = "I. Garde Armee Korps"
id = { type = 14502 id = 16 }
division = {
id = { type = 14502 id = 17  }
name = "1. Garde Infanterie-Division"
type = infantry
model = 8
strength = 100
extra = engineer
brigade_model = 3
}

division = {
id = { type = 14502 id = 18 }
name = "2. Garde Infanterie-Division"
type = infantry
model = 8
strength = 100
extra = engineer
brigade_model = 3
}

division = {
id = { type = 14502 id = 139 }
name = "3. Garde Infanterie-Division"
type = infantry
model = 8
strength = 100
extra = engineer
brigade_model = 3
}
}

landunit = {
location = 184  ### (Königsberg)
name = "I. Armeekorps"
id = { type = 14502 id = 19 }
division = {
id = { type = 14502 id = 20  }
name = "1. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 24 }
name = "2. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = light_armor_brigade
brigade_model = 4
}

division = {
id = { type = 14502 id = 141 }
name = "32. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = light_armor_brigade
brigade_model = 4
}
}


landunit = {
location = 158  ### (Stettin)
name = "II. Armeekorps"
id = { type = 14502 id = 22 }
division = {
id = { type = 14502 id = 23 }
name = "3. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 25  }
name = "4. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = light_armor_brigade
brigade_model = 4
}

division = {
id = { type = 14502 id = 142  }
name = "33. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}
}


landunit = {
location = 163  ### (Berlin)
name = "III. Armeekorps"
id = { type = 14502 id = 26 }
division = {
id = { type = 14502 id = 27  }
name = "5. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 28 }
name = "6. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = anti_tank
brigade_model = 2
}

division = {
id = { type = 14502 id = 143 }
name = "34. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = anti_tank
brigade_model = 2
}
}

landunit = {
location = 169  ### (Magdeburg)
name = "IV. Armeekorps"
id = { type = 14502 id = 29 }
division = {
id = { type = 14502 id = 30  }
name = "7. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 32 }
name = "8. Infanterie-Division"
type = infantry
model = 8
strength = 50
}

division = {
id = { type = 14502 id = 144 }
name = "35. Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}


landunit = {
location = 224   ### (Posen/Poznan)
name = "V. Armeekorps"
id = { type = 14502 id = 33 }
division = {
id = { type = 14502 id = 34 }
name = "9. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 35 }
name = "10. Infanterie-Division"
type = infantry
model = 8
strength = 50
}

division = {
id = { type = 14502 id = 145 }
name = "36. Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}



landunit = {
location = 167  ###  (Breslau)
name = "VI. Armeekorps"
id = { type = 14502 id = 36}
division = {
id = { type = 14502 id = 37 }
name = "11. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 38 }
name = "12. Infanterie-Division"
type = infantry
model = 8
strength = 50
}

division = {
id = { type = 14502 id = 146 }
name = "37. Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}

landunit = {
location = 141   ### (Münster)
name = "VII. Armeekorps"
id = { type = 14502 id = 39 }
division = {
id = { type = 14502 id = 40 }
name = "13. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 41 }
name = "14. Infanterie-Division"
type = infantry
model = 8
strength = 50
}

division = {
id = { type = 14502 id = 147 }
name = "38. Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}


landunit = {
location = 126   ### (Aachen)
name = "VIII. Armeekorps"
id = { type = 14502 id = 42  }
division = {
id = { type = 14502 id = 43 }
name = "15. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 44 }
name = "16. Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}




landunit = {
location = 152   ### (Kiel)
name = "IX. Armeekorps"
id = { type = 14502 id = 45 }
division = {
id = { type = 14502 id = 46  }
name = "1. Mecklenburgische Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 47 }
name = "17. Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}

landunit = {
location = 146   ### (Hannover)
name = "X. Armeekorps"
id = { type = 14502 id = 48 }
division = {
id = { type = 14502 id = 49 }
name = "18. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 50 }
name = "19. Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}

landunit = {
location = 171   ### (Erfurt)
name = "XI. Armeekorps"
id = { type = 14502 id = 51 }
division = {
id = { type = 14502 id = 52 }
name = "20. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 53 }
name = "21. Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}



landunit = {
location = 173  ### (Dresden)
name = "I. Königlich Sächsisches Armeekorps"
id = { type = 14502 id = 54 }
division = {
id = { type = 14502 id = 55 }
name = "1. Königlich Sächsische Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 56  }
name = "2. Königlich Sächsische Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}


landunit = {
location = 134  ### (Stuttgart)
name = "I. Würtembergisches Armeekorps"
id = { type = 14502 id = 57  }
division = {
id = { type = 14502 id = 58  }
name = "1. Würtembergische Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 59 }
name = "2. Würtembergische Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}


landunit = {
location = 132   ### (Freiburg)
name = "I. Rheinisches Armeekorps"
id = { type = 14502 id = 60 }
division = {
id = { type = 14502 id = 61 }
name = "1. Rheinische Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 62  }
name = "2. Rheinische Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}


landunit = {
location = 106   ### (Nancy)
name = "XII. Armeekorps"
id = { type = 14502 id = 63  }
division = {
id = { type = 14502 id = 65 }
name = "22. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 64  }
name = "23. Infanterie-Division"
type = infantry
model = 8
strength = 50
}

division = {
id = { type = 14502 id = 149  }
name = "39. Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}


landunit = {
location = 96   ### (Longwy)
name = "XIII. Armeekorps"
id = { type = 14502 id = 66 }
division = {
id = { type = 14502 id = 67 }
name = "24. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 68 }
name = "25. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = super_heavy_artillery
brigade_model = 1
}

division = {
id = { type = 14502 id = 150  }
name = "40. Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}


landunit = {
location = 226  ### (Danzig)
name = "I. Ostpreußisches Armeekorps"
id = { type = 14502 id = 69 }
division = {
id = { type = 14502 id = 70 }
name = "1. Preußische Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 71 }
name = "2. Preußische Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}

landunit = {
location = 105 ### For Miggel, as Close to Baden as I could get!
name = "XIV. Armeekorps"
id = { type = 14502 id = 72 }
division = {
id = { type = 14502 id = 73 }
name = "Feld-Artillerie-Regiment 'Großherzog'"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 74 }
name = "1. Badisches Leib-Grenadier-Regiment"
type = infantry
model = 8
strength = 50
}

division = {
id = { type = 14502 id = 151  }
name = "41. Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}


landunit = {
location = 170   ### (Leipzig)
name = "II. Königlich Sächsisches Armeekorps"
id = { type = 14502 id = 75  }
division = {
id = { type = 14502 id = 76 }
name = "3. Königlich Sächsische Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 77 }
name = "4. Königlich Sächsische Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}



landunit = {
location = 185  ### (Allenstein)
name = "XVI. Armeekorps"
id = { type = 14502 id = 78  }
division = {
id = { type = 14502 id = 79 }
name = "27. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}
#id = { type = 14502 id = 80  }
division = {
id = { type = 14502 id = 81  }
name = "28. Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}


landunit = {
location = 127   ### (Saarbrücken)
name = "XVII. Armeekorps"
id = { type = 14502 id = 82 }
division = {
id = { type = 14502 id = 83 }
name = "29. Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 84 }
name = "30. Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}


landunit = {
location = 108 ### (Liege)
name = "XVIII. Armeekorps"
id = { type = 14502 id = 85 }
division = {
id = { type = 14502 id =  86 }
name = "1. Wallonische Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 87 }
name = "31. Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}


landunit = {
location = 111  ###  (Arlon)
name = "I. Bayerisches Armeekorps"
id = { type = 14502 id = 88 }
division = {
id = { type = 14502 id = 89 }
name = "1. Bayerische Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 91 }
name = "2. Bayerische Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = super_heavy_artillery
brigade_model = 1
}

division = {
id = { type = 14502 id = 152  }
name = "3. Bayerische Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}


landunit = {
location = 178  ###  (München)
name = "II. Bayerisches Armeekorps"
id = { type = 14502 id = 92   }
division = {
id = { type = 14502 id = 93  }
name = "3. Bayerische Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 94 }
name = "4. Bayerische Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}


landunit = {
location = 179  ###  (München)
name = "III. Bayerisches Armeekorps"
id = { type = 14502 id = 95  }
division = {
id = { type = 14502 id = 96  }
name = "5. Bayerische Infanterie-Division"
type = infantry
model = 8
strength = 50
extra = artillery
brigade_model = 6
}

division = {
id = { type = 14502 id = 97  }
name = "6. Bayerische Infanterie-Division"
type = infantry
model = 8
strength = 50
}
}

###################
#####  SCHUTZTRUPPEN UND AUSLANDS-ABTEILUNGEN
#################
### Schutztruppen - Elite colonial/marine units, usually stationed in small numbers to complement local native units and garrison
###  Auslands Kommando - Colonial garrison and native troops


landunit = {
location = 850  ### [Mittelafrika]
name = "1. Schutztruppen Division"
id = { type = 14502 id = 98 }
division = {
id = { type = 14502 id = 100 }
name = "1. Schutztruppen Division"
type = marine
model = 2
strength = 100
}
}

landunit = {
location = 1432    ### [Indochina]
name = "2. Schutztruppen Division"
id = { type = 14502 id = 99 }
division = {
id = { type = 14502 id = 101 }
name = "2. Schutztruppen Division"
type = marine
model = 2
strength = 100
}
}


landunit = {
location = 1395   ### [Hanoi]
name = "3. Schutztruppen Division"
id = { type = 14502 id = 102  }
division = {
id = { type = 14502 id = 103  }
name = "3. Schutztruppen Division"
type = marine
model = 2
strength = 100
}
}



landunit = {
location = 1667  ### [Truk]
name = "4. Schutztruppen Division"
id = { type = 14502 id = 104 }
division = {
id = { type = 14502 id = 105 }
name = "4. Schutztruppen Division"
type = marine
model = 2
strength = 100
}
}


landunit = {
location = 1399  ### [Saigon]
name = "Auslands Kommando Südostasien"
id = { type = 14502 id = 107  }
division = {
id = { type = 14502 id = 106  }
name = "Auslands Kommando Südostasien"
type = d_01
model = 7
strength = 100
}
}

landunit = {
location = 1328 ###   [German Asian Puppet]

name = "Auslands Kommando China"
id = { type = 14502 id = 108  }
division = {
id = { type = 14502 id = 109 }
name = "Auslands Kommando China"
type = d_01
model = 7
strength = 100
}
}


landunit = {
location = 1365 ###    [Hainan]

name = "Auslands Kommando Hainan"
id = { type = 14502 id = 110 }
division = {
id = { type = 14502 id = 111 }
name = "Auslands Festungs Kommando Hainan"
type = d_01
model = 7
strength = 50
}
}


landunit = {
location = 964 ###    [Freetown]

name = "Auslands Festungs Kommando Freistadt"
id = { type = 14502 id = 112 }
division = {
id = { type = 14502 id = 113 }
name = "Auslands Festungs Kommando Freistadt"
type = garrison
model = 4
strength = 50
}
}

landunit = {
location = 429  ###    Malta

name = "Auslands Festungs Kommando Malta"
id = { type = 14502 id = 114 }
division = {
id = { type = 14502 id = 115 }
name = "Auslands Festungs Kommando Malta"
type = garrison
model = 4
strength = 50
}
}


landunit = {
location = 382  ###    Crete

name = "Auslands Festungs Kommando Crete"
id = { type = 14502 id = 1000 }
division = {
id = { type = 14502 id = 1001 }
name = "Auslands Festungs Kommando Crete"
type = garrison
model = 4
strength = 50
}
}

landunit = {
location = 900  ###    Suez

name = "Auslands Festungs Kommando Suez"
id = { type = 14502 id = 116 }
division = {
id = { type = 14502 id = 117 }
name = "Auslands Festungs Kommando Suez"
type = garrison
model = 4
strength = 100
}
}


landunit = {
location = 1602   ###    Neuguinea

name = "Auslands Kommando Neuguinea"
id = { type = 14502 id = 118 }
division = {
id = { type = 14502 id = 119 }
name = "Auslands Kommando Neuguinea"
type = d_01
model = 7
strength = 50
}
}


landunit = {
location =   833 ###    Somalia

name = "Auslands Kommando Äthiopien"
id = { type = 14502 id = 120 }
division = {
id = { type = 14502 id = 121 }
name = "Auslands Kommando Äthiopien"
type = d_01
model = 7
strength = 100
}
}



landunit = {
name = "Auslands Festungs Kommando Singapore"
location = 1432
id = { type = 14502 id = 122 }
division = {
id = { type = 14502 id = 123 }
name = "Auslands Festungs Kommando Singapore"
type = garrison
model = 4
strength = 50  }
}
landunit = {
name = "Auslands Festungs Kommando Ceylon"
location = 1511
id = { type = 14502 id = 124  }
division = {
id = { type = 14502 id = 125 }
name = "Auslands Festungs Kommando Ceylon"
type = garrison
model = 4
strength = 50 }
}


landunit = {
name = "Auslands Festungs Kommando Marokko"
location = 722
id = { type = 14502 id = 126  }
division = {
id = { type = 14502 id = 127 }
name = "Auslands Festungs Kommando Marokko"
type = garrison
model = 4
strength = 50 }
}

########## Luftwaffe ##############

airunit = { location = 163 id = { type = 14500 id = 151 } name = "Luftflotte II"
base = 163
division = { id = { type = 14500 id = 152 } name = "KG 2 'Holzhammer'" strength = 100 type = tactical_bomber model = 5 }
division = { id = { type = 14500 id = 154 } name = "KG 3 'Blitz'" strength = 100 type = tactical_bomber model = 5 }
division = { id = { type = 14500 id = 153 } name = "Sturzkampfgeschwader 51" strength = 100 type = tactical_bomber model = 5 }
division = { id = { type = 14500 id = 155 } name = "JG 2 'Richthofen'" strength = 100 type = interceptor model = 7 }
division = { id = { type = 14500 id = 156 } name = "JG 26 'Schlageter'" strength = 100 type = interceptor model = 7 }
}


airunit = { location = 167 id = { type = 14500 id = 157 } name = "Luftflotte III"
base = 167
division = { id = { type = 14500 id = 158 } name = "KG 53 'Ludendorff'" strength = 100 type = tactical_bomber model = 5 }
division = { id = { type = 14500 id = 159 } name = "Kampfgeschwader 25" strength = 100 type = tactical_bomber model = 5 }
division = { id = { type = 14500 id = 160 } name = "KG 30 'Adler'" strength = 100 type = tactical_bomber model = 5 }
}

airunit = { location = 137 id = { type = 14500 id = 161 } name = "Luftflotte IV"
base = 137
division = { id = { type = 14500 id = 162 } name = "KG 1 'Hindenburg'" strength = 100 type = tactical_bomber model = 5 }
division = { id = { type = 14500 id = 163 } name = "JG 3 'Udet'" strength = 100 type = interceptor model = 7 }
}

airunit = { location = 179 id = { type = 14500 id = 164 } name = "Luftflotte V"
base = 179
division = { id = { type = 14500 id = 165 } name = "KG 4 'General Wever'" strength = 100 type = tactical_bomber model = 5 }
}


airunit = {
id = { type = 14500 id = 320 }
name = "Luftflotte VI"
location = 1432
home = 1432
base = 1432

division = {
id = { type = 14500 id = 321 }
name = "Kampfgeschwader 26"
model = 4
brigade_model = 0
type = tactical_bomber

}
division = {
id = { type = 14500 id = 322  }
name = "Seeaufklärungsgruppe 125"
model = 1
brigade_model = 0
type = naval_bomber

}
division = {
id = { type = 14500 id = 323  }
name = "Jagdgeschwader 7"
model = 6
brigade_model = 0
type = interceptor

}
}




airunit = {
location = 900
base = 900
id = { type = 14500 id = 166 }
name = "Luftflotte VII"

division = {
id = { type = 14500 id = 167 }
name = "Kampfgeschwader 27"
type = tactical_bomber
model = 4
strength = 100
}
}


airunit = {
id = { type = 14500 id = 131 }
name = "Luftflotte VIII"
location = 599
base = 599

division = {
id = { type = 14500 id = 132 }
name = "Kampfgeschwader 28"
strength = 100
type = tactical_bomber
model = 5
}

division = {
id = { type = 14500 id = 133 }
name = "Kampfgeschwader 29"
strength = 100
type = tactical_bomber
model = 5
}

division = {
id = { type = 14500 id = 134 }
name = "Jagdgeschwader 5"
strength = 100
type = interceptor
model = 7
}

division = {
id = { type = 14500 id = 135 }
name = "Jagdgeschwader 6"
strength = 100
type = interceptor
model = 7
}
}

airunit = {
id = { type = 14500 id = 138 }
name = "Luftflotte IX"
location = 1667
home = 1667
base = 1667

division = {
id = { type = 14500 id = 139  }
name = "Seeaufklärungsgruppe 126"
model = 1
strength  = 30
type = naval_bomber
}

division = {
id = { type = 14500 id = 140  }
name = "Jagdgeschwader 8"
model = 6
strength  = 30
type = interceptor

}
}


##### #####Das Kaiserliche Marine auf 1936 " The Imperial Navy of 1936
#### by Berchlingen
###############
######Deustchlands Hochseeflotte " German High Seas Fleet
############




navalunit = {
name = "I. Schlachtschwadron"
id = { type = 14500 id = 168 }
location = 147
base = 147

division = { id = { type = 14500 id = 169 } name =  "SMS Wittelsbach" type = battleship  model = 6 }
division = { id = { type = 14500 id = 170 } name =  "SMS Zähringen" type = battleship  model = 6 }
division = { id = { type = 14500 id = 171 } name =  "SMS Wettin" type = battleship  model = 6 }
division = { id = { type = 14500 id = 172 } name =  "SMS Kaiser Wilhelm der Große" type = battleship  model = 5 }
division = { id = { type = 14500 id = 173 } name =  "SMS Kaiser Wilhelm II" type = battleship  model = 5 }

}

navalunit = {
name = "II. Schlachtschwadron"
id = { type = 14500 id = 175 }
location = 147  ### [Wilhelmshaven]
base = 147

division = { id = { type = 14500 id = 176 } name =  "SMS Königin Victoria" type = battleship  model = 5  }
division = { id = { type = 14500 id = 177 } name =  "SMS Kaiser Friedrich III" type = battleship   model = 5 }
division = { id = { type = 14500 id = 178 } name =  "SMS Dennewitz" type = battleship model = 4   }
division = { id = { type = 14500 id = 179 } name =  "SMS Kulm" type = battleship  model = 4  }
division = { id = { type = 14500 id = 180 } name =  "SMS Katzbach" type = battleship  model = 4  }

}

navalunit = {
name = "III. Schlachtschwadron"
id = { type = 14500 id = 181 }
location = 147  #### [Wilhelmshaven]
base = 147

division = { id = { type = 14500 id = 182 } name =  "SMS Bayern" type = battleship  model = 4  }
division = { id = { type = 14500 id = 183 } name =  "SMS Baden" type = battleship   model = 4 }
division = { id = { type = 14500 id = 184 } name =  "SMS Württemberg" type = battleship model = 4   }
division = { id = { type = 14500 id = 185 } name =  "SMS Sachsen" type = battleship model = 4   }

}

navalunit = {
name = "Reserven Schlachtswadron"
id = { type = 14500 id = 187 }
location = 152 #### Kiel
base = 152
division = { id = { type = 14500 id = 188 } name =  "SMS Kaiser" type = battleship  model = 3  }
division = { id = { type = 14500 id = 189 } name =  "SMS Kaiserin" type = battleship  model = 3  }
division = { id = { type = 14500 id = 190 } name =  "SMS König Albert" type = battleship   model = 3 }
division = { id = { type = 14500 id = 191 } name =  "SMS Prinzregent Luitpold" type = battleship  model = 3  }
division = { id = { type = 14500 id = 186 } name =  "SMS Friedrich der Große" type = battleship  model = 3  }
division = { id = { type = 14500 id = 192 } name =  "SMS Stralsund" type = light_cruiser model = 2  }
division = { id = { type = 14500 id = 193 } name =  "SMS Straßburg" type = light_cruiser  model = 2 }
division = { id = { type = 14500 id = 194 } name =  "11. Zerstörergeschwader" type = destroyer   model = 2   }
division = { id = { type = 14500 id = 195 } name =  "12. Zerstörergeschwader" type = destroyer  model = 2    }

}

navalunit = {
name = "I. Aufklärungsschwadron"
id = { type = 14500 id = 196 }
location = 152
base = 152
division = { id = { type = 14500 id = 197 } name =  "SMS Alte Dessau" type = battlecruiser  model = 2  }
division = { id = { type = 14500 id = 198 } name =  "SMS Zieten" type = battlecruiser  model = 2  }
division = { id = { type = 14500 id = 199 } name =  "SMS Hutier" type = battlecruiser  model = 2  }
division = { id = { type = 14500 id = 201 } name =  "SMS Gneisenau" type = battlecruiser model = 2   }
division = { id = { type = 14500 id = 202 } name =  "SMS Mülhausen" type = light_cruiser model = 3  }
division = { id = { type = 14500 id = 200 } name =  "SMS Erfurt" type = light_cruiser model = 3  }
division = { id = { type = 14500 id = 203 } name =  "SMS Aachen"  type = light_cruiser model = 3 }
division = { id = { type = 14500 id = 222 } name =  "SMS Albatross"  type = light_cruiser model = 3 }

}

navalunit = {
name = "II. Aufklärungsschwadron"
id = { type = 14500 id = 204 }
location = 148  ####  [Wilhelmshaven]
base = 148
division = { id = { type = 14500 id = 205 } name =  "SMS Graf Schwerin" type = battlecruiser  model = 2  }
division = { id = { type = 14500 id = 206 } name =  "SMS Prinz Eitel Friedrich" type = battlecruiser  model = 2   }
division = { id = { type = 14500 id = 208 } name =  "SMS Seydlitz" type = battlecruiser  model = 0 }
division = { id = { type = 14500 id = 209 } name =  "SMS Luxemburg" type = light_cruiser  model = 3 }
division = { id = { type = 14500 id = 210 } name =  "SMS Koblenz" type = light_cruiser model = 3 }
division = { id = { type = 14500 id = 211 } name =  "SMS Darmstadt" type = light_cruiser model = 3 }
division = { id = { type = 14500 id = 223 } name =  "SMS Nautilus"  type = light_cruiser model = 3 }

}

navalunit = {
name = "III. Aufklärungsschwadron"
id = { type = 14500 id = 337 }
location = 152  ####  [Kiel]
base = 152
division = { id = { type = 14500 id = 338 } name =  "SMS Kaiserin Augusta" type = heavy_cruiser  model = 4  }
division = { id = { type = 14500 id = 339 } name =  "SMS Victoria Louise" type = heavy_cruiser  model = 4  }
division = { id = { type = 14500 id = 340 } name =  "SMS Victoria Adelaide" type = heavy_cruiser  model = 4  }
division = { id = { type = 14500 id = 341 } name =  "SMS Hermine Reuß" type = heavy_cruiser  model = 4  }
division = { id = { type = 14500 id = 342 } name =  "SMS Prinz Eugen" type = heavy_cruiser  model = 3  }
division = { id = { type = 14500 id = 343 } name =  "SMS Prinz Adalbert" type = heavy_cruiser  model = 3  }
division = { id = { type = 14500 id = 344 } name =  "SMS Prinz Heinrich" type = heavy_cruiser  model = 3  }

}

navalunit = {
name = "Reserve Aufklärungsschwadron"
id = { type = 14500 id = 212 }
location = 152 ### [Kiel]
base = 152
division = { id = { type = 14500 id = 213 } name =  "SMS Boelcke" type = carrier   model = 0  extra = cag brigade_model = 1 }
division = { id = { type = 14500 id = 332 } name =  "SMS Mainz" type = escort_carrier   model = 1  }
division = { id = { type = 14500 id = 334 } name =  "SMS Rhein" type = escort_carrier   model = 1  }
division = { id = { type = 14500 id = 335 } name =  "SMS Lützow" type = heavy_cruiser   model = 3  }
division = { id = { type = 14500 id = 336 } name =  "SMS Deutschland" type = heavy_cruiser   model = 3  }
division = { id = { type = 14500 id = 214 } name =  "SMS Königsberg" type = light_cruiser model = 2  }
division = { id = { type = 14500 id = 215 } name =  "SMS Emden" type = light_cruiser model = 2  }
division = { id = { type = 14500 id = 216 } name =  "SMS Karlsruhe" type = light_cruiser  model = 2 }
division = { id = { type = 14500 id = 217 } name =  "SMS Nürnberg" type = light_cruiser model = 2  }
division = { id = { type = 14500 id = 218 } name =  "17. Zerstörergeschwader" type = destroyer   model = 3 }

}

navalunit = {
name = "Küstenschutzverband Ostsee"
id = { type = 14500 id = 219 }
location = 153 #### [Rostock]
base = 153
division = { id = { type = 14500 id = 220 } name =  "SMS Oldenburg" type = battleship  model = 2 }
division = { id = { type = 14500 id = 221 } name =  "SMS Thüringen" type = battleship   model = 2  }
division = { id = { type = 14500 id = 229 } name =  "SMS Regensburg" type = light_cruiser model = 2  }
division = { id = { type = 14500 id = 230 } name =  "SMS Frankfurt" type = light_cruiser model = 2  }
division = { id = { type = 14500 id = 231 } name =  "1. Zerstörergeschwader" type = destroyer  model = 3    }
division = { id = { type = 14500 id = 232 } name =  "2. Zerstörergeschwader" type = destroyer  model = 3    }

}

navalunit = {
name = "Zerstörerflotte"
id = { type = 14500 id = 233  }
location = 152
base = 152
division = { id = { type = 14500 id = 234 } name =  "3. Zerstörergeschwader" type = destroyer  model = 3   }
division = { id = { type = 14500 id = 235 } name =  "4. Zerstörergeschwader" type = destroyer     model = 3 }
division = { id = { type = 14500 id = 236 } name =  "5. Zerstörergeschwader" type = destroyer   model = 4   }
division = { id = { type = 14500 id = 237 } name =  "6. Zerstörergeschwader" type = destroyer   model = 4   }
division = { id = { type = 14500 id = 238 } name =  "15. Zerstörergeschwader" type = destroyer   model = 4   }
division = { id = { type = 14500 id = 239 } name =  "16. Zerstörergeschwader" type = destroyer    model = 4  }
division = { id = { type = 14500 id = 345 } name =  "24. Zerstörergeschwader" type = destroyer model = 2  }
division = { id = { type = 14500 id = 346 } name =  "25. Zerstörergeschwader" type = destroyer model = 2  }
division = { id = { type = 14500 id = 347 } name =  "26. Zerstörergeschwader" type = destroyer model = 2  }
division = { id = { type = 14500 id = 348 } name =  "27. Zerstörergeschwader" type = destroyer model = 2  }
division = { id = { type = 14500 id = 349 } name =  "28. Zerstörergeschwader" type = destroyer model = 2  }

}

navalunit = {
name = "Unterseebootsflotte "
id = { type = 14500 id = 240 }
location = 152  ### [Kiel]
base = 152
division = { id = { type = 14500 id = 241 } name =  "1. Unterseebootsflottille" type = submarine  model = 3 }
division = { id = { type = 14500 id = 242 } name =  "2. Unterseebootsflottille" type = submarine  model = 3 }
division = { id = { type = 14500 id = 243 } name =  "3. Unterseebootsflottille" type = submarine  model = 4 }
division = { id = { type = 14500 id = 244 } name =  "4. Unterseebootsflottille" type = submarine  model = 4 }
division = { id = { type = 14500 id = 245 } name =  "5. Unterseebootsflottille" type = submarine  model = 4 }

}

##################
#####Deustches Auslandflotte " German Over Seas Fleet
##################

navalunit = {
name = "Mittelmeerflotte"
id = { type = 14500 id = 246 }
location = 900 ### Port Said
base = 900
division = { id = { type = 14500 id = 247 } name =  "SMS Peter Strasser" type = carrier   model = 1 extra = cag brigade_model = 1  }
division = { id = { type = 14500 id = 248 } name =  "SMS Großer Kurfürst" type = battleship  model = 3   }
division = { id = { type = 14500 id = 249 } name =  "SMS König" type = battleship  model = 3  }
division = { id = { type = 14500 id = 250 } name =  "SMS Markgraf" type = battleship  model = 3  }
division = { id = { type = 14500 id = 251 } name =  "SMS Kronprinz Wilhelm" type = battleship   model = 3 }
division = { id = { type = 14500 id = 252 } name =  "SMS Yorck" type = battlecruiser   model = 2  }
division = { id = { type = 14500 id = 253 } name =  "SMS Scharnhorst" type = battlecruiser  model = 2   }
division = { id = { type = 14500 id = 255 } name =  "SMS Blücher" type = heavy_cruiser  model = 4   }
division = { id = { type = 14500 id = 256 } name =  "SMS Admiral Scheer" type = heavy_cruiser model = 4  }
division = { id = { type = 14500 id = 257 } name =  "SMS Admiral Hipper" type = heavy_cruiser  model = 4 }
division = { id = { type = 14500 id = 258 } name =  "SMS Köln" type = light_cruiser model = 2 }
division = { id = { type = 14500 id = 259 } name =  "SMS Dresden" type = light_cruiser  model = 2 }
division = { id = { type = 14500 id = 260 } name =  "SMS Madgeburg" type = light_cruiser  model = 2 }
division = { id = { type = 14500 id = 261 } name =  "SMS Leipzig" type = light_cruiser model = 2  }
division = { id = { type = 14500 id = 174 } name =  "SMS Ariadne"  type = light_cruiser model = 2 }
division = { id = { type = 14500 id = 224 } name =  "SMS Bremen"  type = light_cruiser model = 3 }
division = { id = { type = 14500 id = 262 } name =  "7. Zerstörergeschwader" type = destroyer    model = 4  }
division = { id = { type = 14500 id = 263 } name =  "8. Zerstörergeschwader" type = destroyer    model = 4  }
division = { id = { type = 14500 id = 350 } name =  "29. Zerstörergeschwader" type = destroyer model = 2  }
division = { id = { type = 14500 id = 351 } name =  "30. Zerstörergeschwader" type = destroyer model = 2  }

}

navalunit = {
name = "Ostasienschwadron"
id = { type = 14500 id = 264 }
location = 1432
base = 1432 ### Singapore
division = { id = { type = 14500 id = 265 } name =  "SMS Blumenthal" type = carrier  model = 1  extra = cag brigade_model = 1  }
division = { id = { type = 14500 id = 365 } name =  "SMS Roon" type = escort_carrier   model = 0  }
division = { id = { type = 14500 id = 358 } name =  "SMS Helgoland" type = battleship  model = 2  }
division = { id = { type = 14500 id = 359 } name =  "SMS Posen" type = battleship  model = 2  }
division = { id = { type = 14500 id = 360 } name =  "SMS Nassau" type = battleship   model = 2 }
division = { id = { type = 14500 id = 361 } name =  "SMS König Albert" type = battleship   model = 2 }
division = { id = { type = 14500 id = 364 } name =  "SMS Rheinland" type = battleship   model = 2 }
division = { id = { type = 14500 id = 266 } name =  "SMS Hindenburg" type = battlecruiser  model = 1 }
division = { id = { type = 14500 id = 362 } name =  "SMS Von der Tann" type = battlecruiser  model = 1 }
division = { id = { type = 14500 id = 267 } name =  "SMS Mackensen" type = battlecruiser  model = 2   }
division = { id = { type = 14500 id = 268 } name =  "SMS Derfflinger" type = battlecruiser  model = 1   }
division = { id = { type = 14500 id = 363 } name =  "SMS Fürst Bismarck" type = battlecruiser  model = 0 }
division = { id = { type = 14500 id = 269 } name =  "SMS Admiral Pohl" type = heavy_cruiser model = 4 }
division = { id = { type = 14500 id = 270 } name =  "SMS Bonn" type = light_cruiser  model = 4 }
division = { id = { type = 14500 id = 271 } name =  "SMS Bamberg" type = light_cruiser  model = 4 }
division = { id = { type = 14500 id = 272 } name =  "SMS Bayreuth" type = light_cruiser  model = 4 }
division = { id = { type = 14500 id = 373 } name =  "SMS Bayreuth" type = light_cruiser  model = 2 }
division = { id = { type = 14500 id = 371 } name =  "SMS Stuttgart"  type = light_cruiser model = 2 }
division = { id = { type = 14500 id = 372 } name =  "SMS Niobe"  type = light_cruiser model = 2 }
division = { id = { type = 14500 id = 273 } name =  "9. Zerstörergeschwader" type = destroyer   model = 5   }
division = { id = { type = 14500 id = 274 } name =  "18. Zerstörergeschwader" type = destroyer    model = 4  }
division = { id = { type = 14500 id = 275 } name =  "19. Zerstörergeschwader" type = destroyer    model = 4  }

}

navalunit = {
name = "Unterseebootsflotte Asien "
id = { type = 14500 id = 276 }
location = 1432 #### Singapore
base = 1432
division = { id = { type = 14500 id = 277 } name =  "6. Unterseebootsflottille" type = submarine  model = 3 }
division = { id = { type = 14500 id = 278 } name =  "7. Unterseebootsflottille" type = submarine model = 3  }
division = { id = { type = 14500 id = 279 } name =  "8. Unterseebootsflottille" type = submarine model = 3  }

}

navalunit = {
name = "Karolinenflotte "
id = { type = 14500 id = 280 }
location = 1667 #### Truk
base = 1667
division = { id = { type = 14500 id = 281 } name =  "SMS Freiherr von Sanders" type = battlecruiser  model = 2  }
division = { id = { type = 14500 id = 366 } name =  "SMS Prinz Heinrich" type = battlecruiser  model = 0 }
division = { id = { type = 14500 id = 282 } name =  "SMS Metz" type = light_cruiser  model = 3 }
division = { id = { type = 14500 id = 368 } name =  "SMS Strassburg" type = light_cruiser  model = 2 }
division = { id = { type = 14500 id = 369 } name =  "SMS Augsburg" type = light_cruiser  model = 2 }
division = { id = { type = 14500 id = 283 } name =  "10. Zerstörergeschwader" type = destroyer   model = 3   }

}

navalunit = {
name = "Sudseeflotte"
id = { type = 14500 id = 284 }
location = 1511  #### Colombo
base = 1511
division = { id = { type = 14500 id = 285 } name =  "SMS Ludendorff" type = battlecruiser  model = 2  }
division = { id = { type = 14500 id = 286 } name =  "SMS Rostock" type = light_cruiser model = 2  }
division = { id = { type = 14500 id = 287 } name =  "SMS Frauenlob" type = light_cruiser model = 2  }
division = { id = { type = 14500 id = 288 } name =  "20. Zerstörergeschwader" type = destroyer    model = 3  }

}

navalunit = {
name = "Westafrikaschwadron"
id = { type = 14500 id = 289 }
location = 964
base = 964
division = { id = { type = 22006 id = 372 } name =  "SMS Carl Peters" type = battleship model = 2 }
division = { id = { type = 22006 id = 373 } name =  "SMS Lüderitz" type = battleship model = 2 }
division = { id = { type = 14500 id = 290 } name =  "SMS Schlieffen" type = battlecruiser  model = 2  }
division = { id = { type = 14500 id = 291 } name =  "SMS Brummer " type = light_cruiser model = 2  }
division = { id = { type = 14500 id = 292 } name =  "SMS Bremse" type = light_cruiser model = 2  }
division = { id = { type = 14500 id = 293 } name =  "14. Zerstörergeschwader" type = destroyer   model = 3   }

}

navalunit = {
name = "Unterseebootsflotte Afrika"
id = { type = 14500 id = 294 }
location = 964 ### Freetown
base = 964
division = { id = { type = 14500 id = 295 } name =  "9. Unterseebootsflottille" type = submarine  model = 2 }
division = { id = { type = 14500 id = 296 } name =  "10. Unterseebootsflottille" type = submarine model = 2  }

}

navalunit = {
name = "Ostafrikaschwadron"
id = { type = 14500 id = 297 }
location = 833 #### German Somaliland
base = 833
division = { id = { type = 22006 id = 370 } name =  "SMS Lettow-Vorbeck" type = battleship model = 2 }
division = { id = { type = 22006 id = 371 } name =  "SMS Ebermaier" type = battleship model = 2 }
division = { id = { type = 14500 id = 298 } name =  "SMS Moltke" type = battlecruiser  model = 0 }
division = { id = { type = 14500 id = 299 } name =  "SMS Pillau" type = light_cruiser  model = 2 }
division = { id = { type = 14500 id = 300 } name =  "SMS Graudenz" type = light_cruiser  model = 2 }
division = { id = { type = 14500 id = 301 } name =  "13. Zerstörergeschwader" type = destroyer model = 3  }

}

#### Naval Construction

navaldivision = {
dormant = yes
id = { type = 12027 id = 302 }
name = "SMS Bismarck"
type = battleship
model = 7
}

navaldivision = {
dormant = yes
id = { type = 12027 id = 303 }
name = "SMS Tirpitz"
type = battleship
model = 7
}

navaldivision = {
dormant = yes
id = { type = 12027 id = 304 }
name = "SMS Kleist"
type = heavy_cruiser
model = 5
}

navaldivision = {
dormant = yes
id = { type = 12027 id = 305 }
name = "SMS Bülow"
type = heavy_cruiser
model = 5
}

navaldivision = {
dormant = yes
id = { type = 12027 id = 325 }
name = "SMS Ägir"
type = escort_carrier
model = 3
}

navaldivision = {
dormant = yes
id = { type = 12027 id = 326 }
name = "SMS Beowulf"
type = escort_carrier
model = 3
}

navaldivision = {
dormant = yes
id = { type = 12027 id = 327 }
name = "30. Zerstörergeschwader"
type = destroyer
model = 5
}

navaldivision = {
dormant = yes
id = { type = 12027 id = 328 }
name = "31. Zerstörergeschwader"
type = destroyer
model = 5
}

navaldivision = {
dormant = yes
id = { type = 12027 id = 329 }
name = "32. Zerstörergeschwader"
type = destroyer
model = 5
}

navaldivision = {
dormant = yes
id = { type = 12027 id = 330 }
name = "11. Unterseebootsflottille"
type = submarine
model = 4
}

navaldivision = {
dormant = yes
id = { type = 12027 id = 331 }
name = "12. Unterseebootsflottille"
type = submarine
model = 4
}

#######################
######  German Naval Strength, 1936:
######  30 Battleships
######  19 Battlecruisers
######  3 Carriers
######  3 Light Carriers
######  13 Heavy Cruisers
######  27 Destroyer flotillas
######  33 Light Cruisers
######  10 UBoot Flotillas
######  Total: 129 Ships


###################
####  TRANSPORTS

navalunit = {
name = "I. Truppentransporterflottille"
id = { type = 14500 id = 306 }
location = 148
base = 148
division = { id = { type = 14500 id = 307 } name = "1. Truppentransporterflottille" type = transport model = 1 }
division = { id = { type = 14500 id = 308 } name = "2. Truppentransporterflottille" type = transport model = 1 }
division = { id = { type = 14500 id = 309 } name = "3. Truppentransporterflottille" type = transport model = 1 }
division = { id = { type = 14500 id = 310 } name = "4. Truppentransporterflottille" type = transport model = 1 }
division = { id = { type = 14500 id = 311 } name = "5. Truppentransporterflottille" type = transport model = 1 }
division = { id = { type = 14500 id = 312 } name = "6. Truppentransporterflottille" type = transport model = 1 }
}

navalunit = {
name = "II. Truppentransporterflottille"
id = { type = 14500 id = 367 }
location = 148
base = 148
division = { id = { type = 14500 id = 314 } name = "7. Truppentransporterflottille" type = transport model = 1 }
division = { id = { type = 14500 id = 315 } name = "8. Truppentransporterflottille" type = transport model = 1 }
division = { id = { type = 14500 id = 316 } name = "9. Truppentransporterflottille" type = transport model = 1 }
division = { id = { type = 14500 id = 318 } name = "10. Truppentransporterflottille" type = transport model = 1 }
division = { id = { type = 14500 id = 319 } name = "11. Truppentransporterflottille" type = transport model = 1 }
division = { id = { type = 14500 id = 324 } name = "12. Truppentransporterflottille" type = transport model = 1 }

}

navalunit = {
name = "III. Truppentransporterflottille"
id = { type = 14500 id = 313 }
location = 1432
base = 1432
division = { id = { type = 14500 id = 352 } name = "13. Truppentransporterflottille" type = transport model = 1 }
division = { id = { type = 14500 id = 353 } name = "14. Truppentransporterflottille" type = transport model = 1 }
division = { id = { type = 14500 id = 354 } name = "15. Truppentransporterflottille" type = transport model = 1 }

}

navalunit = {
name = "IV. Truppentransporterflottille"
id = { type = 14500 id = 317 }
location = 1511 # Colombo
base = 1511
division = { id = { type = 14500 id = 355 } name = "16. Truppentransporterflottille" type = transport model = 1 }
division = { id = { type = 14500 id = 356 } name = "17. Truppentransporterflottille" type = transport model = 1 }
division = { id = { type = 14500 id = 357 } name = "18. Truppentransporterflottille" type = transport model = 1 }
}

### If need, start again from 359 also...

### Ships under construction
division_development =
{  name  = "SMS Graf Zeppelin"
type  = carrier
model = 2
cost  = 0.1
id    = {  type = 14500 id = 500  }
date  = {  year = 1938 month = december day = 8  }
extra = cag
brigade_model = 2
}
}
