


country = {
    tag = HAI  


    policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 4
        political_left = 5
        free_market = 4
        freedom = 2
        professional_army = 1
        defense_lobby = 5
        interventionism = 3
    }

#### cabinet

#### Resource Reserves
	manpower = 27

	energy	=	1000   metal	= 1000		rare_materials =	500	oil =	500	supplies =	500
	money = 10

	capital = 	892



    ownedprovinces =      {
1781
	 }
    controlledprovinces = {
1781
	  }
    nationalprovinces =   {
1781 1780
	}

diplomacy = {
relation = { tag = CUB value = 30 }
relation = { tag = DOM value = -84 }
relation = { tag = USA value = 100 }
}


	
	techapps = {
#Aircrafts
4500 4510 4520 4530 #Interwar Fighter  

#Armour & Artillery
2860 #Interwar Armoured Car 
2290 #Light Field Artillery
7600 7610 #SW Tank 

#Infantry
1010  1020 1030 1040 1050 #1916 lgt. Infantry Division
1910 1920 1930 1940 1950 1960 #Interbellum 1930 Supply 
13060 13070 13080 1310 1320 1330 1340  #1916 Cavalry Division 

#Industrial
5700 #Early Agriculture
5600 #Medicine

# Great War Land Doctrines (entente)
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6680 6540 6910
#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470

	}

#########  OOB (...)

	landunit = {
	id = { type = 17500 id = 53 }
	name = "La Grandé Armée du Haiti"
	location = 1781
	
		division = {
		id = { type = 17500 id = 5301 }
		name = "1ère Brigade d'Infanterie Haitien"
		strength = 100
		type = infantry
		model = 4
		extra = artillery
		}
		division = {
		id = { type = 17500 id = 5302 }
		name = "2ère Brigade d'Infanterie Haitien"
		strength = 75
		type = infantry
		model = 4
		}
		}

}  