### AFG
province = { id = 2171 ic = 1 } #Kabul
province = { id = 2168 ic = 1 } #Kondoz
province = { id = 2169 ic = 3 } #Herat
province = { id = 2172 ic = 1 } #Kandahar
province = { id = 1529 ic = 1 } #Quetta
### ALB
province = { id = 359 ic = 4 } #Tirana
### ARG (URU, PAR)
province = { id = 2036 ic = 1 } #Rio Gallegos
province = { id = 2053 ic = 5 } #Mar del Plata
province = { id = 2048 ic = 10 } #La Plata
province = { id = 2050 ic = 4 } #Buenos Aires
province = { id = 2029 ic = 1 } #San Juan
province = { id = 2027 ic = 1 } #San Miguel del Tucuman
province = { id = 2054 ic = 2 } #Cordoba
province = { id = 2049 ic = 2 } #Corrientes
province = { id = 2056 ic = 1 } #Resistencia

province = { id = 2047 ic = 5 } #Nuestra Senora de la Asuncion
province = { id = 2046 ic = 1 } #Villa Hayes

province = { id = 2052 ic = 8 } #Montevideo
### ARM
province = { id = 711 ic = 2 } #Yeravan (Mar 2020 previously ic = 5)
### AST (NZL)
province = { id = 1710 ic = 1 } #Hobart
province = { id = 1709 ic = 2 } #Geelong
province = { id = 1708 ic = 2 } #Melbourne
province = { id = 1707 ic = 2 } #Canberra
province = { id = 1706 ic = 1 } #Wollongong
province = { id = 1705 ic = 2 } #Sydney
province = { id = 1704 ic = 7 } #Brisbane
province = { id = 1712 ic = 2 } #Adelaïde
province = { id = 1713 ic = 3 } #Robe
province = { id = 1694 ic = 1 } #Collk
province = { id = 1697 ic = 1 } #Darwin

province = { id = 1721 ic = 6 } #Wellington
province = { id = 1720 ic = 1 } #Auckland
### AUS (montenegro, slovenia)
province = { id = 186 ic = 2 } #Freistadt
province = { id = 187 ic = 4 } #Linz
province = { id = 189 ic = 1 } #Innsbruck
province = { id = 190 ic = 6 } #Graz
province = { id = 191 ic = 2 } #Klagenfurt
province = { id = 192 ic = 4 } #Salzburg
province = { id = 193 ic = 2 } #Sankt Poelten
province = { id = 194 ic = 3 } #Hollabrun
province = { id = 195 ic = 6 } #Vienna

province = { id = 349 ic = 2 } #Ljubljana
province = { id = 346 ic = 3 } #Maribor
province = { id = 406 ic = 2 } #Pola

province = { id = 332 ic = 1 } #Cetinje

province = { id = 404 ic = 3 } #Trieste
province = { id = 405 ic = 3 } #Udine
province = { id = 400 ic = 1 } #Venice
province = { id = 401 ic = 2 } #Trento
province = { id = 402 ic = 2 } #Bolzano
province = { id = 394 ic = 1 } #Belluno

### AZB
province = { id = 713 ic = 6 } #Baku(previously ic = 7)
### BEL
province = { id = 112 ic = 4 } #Mons
province = { id = 113 ic = 2 } #Namur
province = { id = 114 ic = 5 } #Bruges
province = { id = 115 ic = 5 } #Antwerpen
province = { id = 116 ic = 7 } #Brussels
province = { id = 117 ic = 4 } #Hasselt
### BHU
province = { id = 1456 ic = 3 } #Punakha
### BLR
province = { id = 251 ic = 2 } #Nowogrodek
province = { id = 248 ic = 1 } #Pinsk
province = { id = 595 ic = 1 } #Mozyr
province = { id = 599 ic = 6 } #Minsk
province = { id = 256 ic = 1 } #Vilejka
province = { id = 594 ic = 1 } #Sobruisk
### BOL
province = { id = 2020 ic = 4 } #Nuestra Senora de la Paz
province = { id = 2021 ic = 2 } #Sucre
### BOS
province = { id = 355 ic = 3 } #Sarajevo
province = { id = 353 ic = 2 } #Banja Luka
### BRA
province = { id = 2057 ic = 2 } #Curitiba
province = { id = 2058 ic = 2 } #Porto Alegre
province = { id = 2059 ic = 5 } #Sao Paulo
province = { id = 2075 ic = 6 } #Rio de Janeiro
province = { id = 2066 ic = 3 } #Barreiras
province = { id = 2071 ic = 6 } #Recife
province = { id = 2070 ic = 5 } #Natal
province = { id = 2072 ic = 3 } #Fortaleza
province = { id = 2069 ic = 1 } #Sao Luis
province = { id = 2068 ic = 1 } #Belem
province = { id = 2060 ic = 1 } #Campo Grande
### BUL
province = { id = 307 ic = 1 } #Dobrich
province = { id = 317 ic = 3 } #Ruse
province = { id = 318 ic = 1 } #Vidin
province = { id = 319 ic = 1 } #Haskovo
province = { id = 321 ic = 7 } #Sofia
province = { id = 322 ic = 1 } #Gabrovo
province = { id = 324 ic = 3 } #Plovdiv
province = { id = 325 ic = 1 } #Burgas
province = { id = 326 ic = 4 } #Varna
province = { id = 323 ic = 1 } #Pleven

province = { id = 333 ic = 1 } #Skopje
province = { id = 331 ic = 2 } #Pirot
province = { id = 363 ic = 1 } #Xanthi
province = { id = 364 ic = 1 } #Kavala
province = { id = 365 ic = 3 } #Thessaloniki
### BUR
province = { id = 1415 ic = 2 } #Rangoon
province = { id = 1410 ic = 3 } #Mandalay
province = { id = 1411 ic = 1 } #Pakokdu/Sarak
### CAN
province = { id = 2132 ic = 3 } #Halifax
province = { id = 2134 ic = 1 } #Glace Bay
province = { id = 2126 ic = 2 } #Trois Rivieres
province = { id = 2137 ic = 2 } #St John's
province = { id = 2117 ic = 3 } #Quebec
province = { id = 2119 ic = 7 } #Montreal
province = { id = 2108 ic = 2 } #Ottawa
province = { id = 2113 ic = 4 } #Pembroke
province = { id = 2111 ic = 6 } #Toronto
province = { id = 2109 ic = 3 } #Hamilton
province = { id = 2114 ic = 1 } #Subbury
province = { id = 2127 ic = 1 } #Roberval
province = { id = 2129 ic = 2 } #Sault Sainte Marie
province = { id = 2115 ic = 1 } #Fort Severn
province = { id = 2110 ic = 3 } #Fort William
province = { id = 2107 ic = 1 } #Flin Flon
province = { id = 2106 ic = 2 } #Winnipeg
province = { id = 2100 ic = 1 } #Saskatoon
province = { id = 2101 ic = 2 } #Regina
province = { id = 2103 ic = 1 } #Edmonton
province = { id = 2104 ic = 1 } #Calgary
province = { id = 2099 ic = 1 } #Fort Resolution
province = { id = 2089 ic = 3 } #Vancouver
province = { id = 2090 ic = 1 } #Victoria
province = { id = 2118 ic = 2 } #Sherbrooke
province = { id = 2130 ic = 2 } #Saint John
province = { id = 2131 ic = 1 } #Moncton
### CGX (german protectorate)
province = { id = 1373 ic = 5 } #Jiangmen
province = { id = 1380 ic = 3 } #Liuzhou
province = { id = 1369 ic = 3 } #Guangzhou
province = { id = 1305 ic = 1 } #Guiyang
province = { id = 1309 ic = 2 } #Xianghan
province = { id = 1354 ic = 1 } #Ganghou
province = { id = 1318 ic = 1 } #Huangshi
province = { id = 1307 ic = 2 } #Huaihua
province = { id = 1308 ic = 2 } #Changsha
province = { id = 1351 ic = 2 } #Shangrao
province = { id = 1368 ic = 3 } #Shaoguan
province = { id = 1378 ic = 5 } #Guilin
### CHC (shanqging tianguo)
province = { id = 1257 ic = 1 } #Tongguan
### CHL
province = { id = 2024 ic = 1 } #Iquique
province = { id = 2025 ic = 2 } #Antofogasta
province = { id = 2022 ic = 2 } #Valparaiso
province = { id = 2023 ic = 7 } #Santiago de Chile

### COL
province = { id = 1990 ic = 2 } #Cucuta
province = { id = 1986 ic = 2 } #Barranquilla
province = { id = 1987 ic = 7 } #Medellin
### CON (mittelafrika)
province = { id = 934 ic = 1 } #Oshogbo
province = { id = 935 ic = 1 } #Benin City
province = { id = 930 ic = 1 } #Port Harcourt
province = { id = 939 ic = 1 } #Kaduna
province = { id = 907 ic = 1 } #Brazzaville
province = { id = 897 ic = 1 } #Kolwezi
province = { id = 844 ic = 1 } #Kampala
province = { id = 850 ic = 5 } #Dar es Salaam
province = { id = 863 ic = 1 } #Lusaka
province = { id = 884 ic = 1 } #Windhoek
province = { id = 842 ic = 1 } #Mombasa
province = { id = 929 ic = 1 } #Lagos
province = { id = 915 ic = 1 } #Libreville
province = { id = 956 ic = 1 } #Accra

### CRO
province = { id = 352 ic = 4 } #Zagreb
province = { id = 350 ic = 1 } #Split
province = { id = 337 ic = 1 } #Ruma
province = { id = 343 ic = 1 } #Dubrovnik
province = { id = 344 ic = 1 } #Osijek
province = { id = 347 ic = 2 } #Karlovac
### CSX (qing)
province = { id = 1345 ic = 5 } #Hangzhou
province = { id = 1337 ic = 11 } #Nanjing
province = { id = 1340 ic = 2 } #Hefei
province = { id = 1317 ic = 1 } #Wuhan
province = { id = 1252 ic = 1 } #Taiyuan
province = { id = 1247 ic = 3 } #Beijing
province = { id = 1250 ic = 2 } #Lingqiu
province = { id = 1330 ic = 2 } #Jinan
province = { id = 1334 ic = 2 } #Nantong
province = { id = 1343 ic = 2 } #Huainan
### CUB
province = { id = 1776 ic = 3 } #Havana
province = { id = 1779 ic = 3 } #Santa Clara
province = { id = 1775 ic = 2 } #Camaguey
### CXB (san ma clique)
province = { id = 1264 ic = 1 } #Lanzhou
province = { id = 1283 ic = 1 } #Ge'ermu
province = { id = 1281 ic = 1 } #Urumqi
### CZE
province = { id = 205 ic = 1 } #Karlovy Vary
province = { id = 199 ic = 9 } #Plzen
province = { id = 207 ic = 7 } #Prague
province = { id = 198 ic = 4 } #Harlec Kralov
province = { id = 196 ic = 3 } #Brno
province = { id = 201 ic = 2 } #Ostrava
province = { id = 202 ic = 4 } #Ceske Budejovice
province = { id = 203 ic = 2 } #Tesin
### DEN(+Iceland)
province = { id = 294 ic = 4 } #Copenhagen
province = { id = 219 ic = 1 } #Odense
province = { id = 220 ic = 2 } #Arhus
province = { id = 217 ic = 1 } #Aalborg
province = { id = 218 ic = 3 } #Frederikshavn
province = { id = 1 ic = 4 } #Reykjavik
### DOM
province = { id = 1780 ic = 6 } #Ciudad Trujillo
### EAF (legation cities)
province = { id = 1371 ic = 3 } #Hong Kong
province = { id = 1358 ic = 2 } #Fuzhou
province = { id = 1338 ic = 6 } #Shanghai
province = { id = 1346 ic = 1 } #Ningbo
### ECU
province = { id = 2040 ic = 5 } #Santiago de Guayaquil
province = { id = 2042 ic = 1 } #San Francisco de Quito
### EGY (SUD)
province = { id = 789 ic = 7 } #Alexandria (previously ic = 6)
province = { id = 790 ic = 1 } #Tanta
province = { id = 786 ic = 1 } #Dimyat
province = { id = 788 ic = 1 } #Giza/Ishim
province = { id = 792 ic = 1 } #El Faiyun
province = { id = 787 ic = 10 } #Cairo (previously ic = 8)

province = { id = 810 ic = 2 } #Khartoum
province = { id = 813 ic = 1 } #Port Sudan(previously ic = 4)
### ENG
province = { id = 20 ic = 4 } #Exeter
province = { id = 27 ic = 7 } #Portsmouth
province = { id = 26 ic = 4 } #Dover
province = { id = 19 ic = 7 } #Bristol
province = { id = 29 ic = 15 } #London
province = { id = 25 ic = 5 } #Norwich
province = { id = 22 ic = 4 } #Cardiff
province = { id = 24 ic = 15 } #Birmingham
province = { id = 17 ic = 14 } #Manchester
province = { id = 18 ic = 10 } #Sheffield
province = { id = 15 ic = 4 } #Hull
province = { id = 13 ic = 8 } #Sutherland
province = { id = 10 ic = 1 } #Dumfries
province = { id = 12 ic = 4 } #Edinburgh
province = { id = 11 ic = 6 } #Glasgow
province = { id = 7 ic = 3 } #Aberdeen
province = { id = 14 ic = 3 } #Carlisle
province = { id = 16 ic = 2 } #Lincoln
province = { id = 21 ic = 1 } #Caernarfon
province = { id = 28 ic = 2 } #Oxford
### ETH
province = { id = 830 ic = 1 } #Arba Minch
province = { id = 831 ic = 1 } #Awasa
province = { id = 815 ic = 1 } #Massawa
province = { id = 818 ic = 1 } #Dire Dawa
province = { id = 820 ic = 1 } #Dessie
province = { id = 825 ic = 2 } #Addis Abeba
province = { id = 828 ic = 3 } #Harer
### FIN
province = { id = 525 ic = 5 } #Helsinki
province = { id = 531 ic = 3 } #Viipuri
province = { id = 528 ic = 1 } #Mikkeli
province = { id = 527 ic = 2 } #Tampere
province = { id = 524 ic = 1 } #Turku
province = { id = 512 ic = 1 } #Pori
province = { id = 521 ic = 1 } #Vaasa
province = { id = 520 ic = 1 } #Oulu
### FRA
province = { id = 49 ic = 1 } #Calais
province = { id = 51 ic = 1 } #Dunkirk
province = { id = 52 ic = 9 } #Lille
province = { id = 54 ic = 4 } #Troyes
province = { id = 55 ic = 19 } #Paris
province = { id = 45 ic = 4 } #le Havre
province = { id = 44 ic = 4 } #Caen
province = { id = 51 ic = 4 } #Saint Brieuc
province = { id = 38 ic = 4 } #Rennes
province = { id = 66 ic = 3 } #Orleans
province = { id = 64 ic = 3 } #le Creusot
province = { id = 72 ic = 1 } #Chateauroux
province = { id = 69 ic = 3 } #La Rochelle
province = { id = 70 ic = 3 } #Angouleme
province = { id = 68 ic = 5 } #Bordeaux
province = { id = 73 ic = 1 } #Limoges
province = { id = 71 ic = 3 } #Clermont Ferrand
province = { id = 77 ic = 6 } #Toulouse
province = { id = 82 ic = 3 } #Montpellier
province = { id = 89 ic = 4 } #Marseille
province = { id = 93 ic = 1 } #Avignon
province = { id = 86 ic = 1 } #Toulon
province = { id = 90 ic = 3 } #Grenoble
province = { id = 85 ic = 8 } #Lyon
province = { id = 97 ic = 1 } #Belfort
province = { id = 37 ic = 1 } #Brest
province = { id = 39 ic = 3 } #Lorient
province = { id = 40 ic = 2 } #Saint-Nazaire
province = { id = 63 ic = 1 } #Auxerre
province = { id = 74 ic = 2 } #Vichy
province = { id = 78 ic = 1 } #Saint Etienne
### GEO
province = { id = 709 ic = 7 } #Tbilisi
province = { id = 708 ic = 2 } #Kutaisi
province = { id = 710 ic = 1 } #Sukhumi
### GER
province = { id = 104 ic = 6 } #Metz
province = { id = 107 ic = 2 } #Strasbourg
province = { id = 96 ic = 2 } #Longwy

province = { id = 108 ic = 5 } #Liege
province = { id = 109 ic = 5 } #Luxembourg

province = { id = 110 ic = 1 } #Eupen
province = { id = 127 ic = 6 } #Saarbrucken
province = { id = 131 ic = 7 } #Cologne/Koln
province = { id = 147 ic = 2 } #Wilhelmshaven
province = { id = 141 ic = 4 } #Muenster
province = { id = 142 ic = 4 } #Dusseldorf
province = { id = 145 ic = 11 } #Essen
province = { id = 144 ic = 2 } #Bielefield
province = { id = 137 ic = 2 } #Kassel
province = { id = 143 ic = 2 } #Neuewied
province = { id = 138 ic = 5 } #Frankfurt am Main
province = { id = 132 ic = 1 } #Freiburg
province = { id = 135 ic = 7 } #Tubingen
province = { id = 133 ic = 1 } #Konstanz
province = { id = 134 ic = 10 } #Stuttgart
province = { id = 177 ic = 7 } #Nuremberg
province = { id = 179 ic = 4 } #Munich
province = { id = 146 ic = 5 } #Hannover
province = { id = 148 ic = 3 } #Bremen
province = { id = 154 ic = 3 } #Hambourg
province = { id = 151 ic = 2 } #Lubeck
province = { id = 152 ic = 5 } #Kiel
province = { id = 150 ic = 5 } #Flenburg
province = { id = 170 ic = 3 } #Leipzig
province = { id = 173 ic = 2 } #Dresden
province = { id = 163 ic = 13 } #Berlin
province = { id = 160 ic = 6 } #Frankfurt am der Oder
province = { id = 157 ic = 4 } #Potsdam
province = { id = 153 ic = 3 } #Rostock
province = { id = 162 ic = 1 } #Stralsund
province = { id = 159 ic = 1 } #Meseritz
province = { id = 224 ic = 3 } #Poznan
province = { id = 158 ic = 4 } #Stettin
province = { id = 226 ic = 1 } #Gdynia
province = { id = 222 ic = 1 } #Torun
province = { id = 183 ic = 1 } #Elbing
province = { id = 184 ic = 6 } #Konigsberg
province = { id = 128 ic = 1 } #Trier
province = { id = 130 ic = 1 } #Mainz
province = { id = 164 ic = 2 } #Oppeln
province = { id = 167 ic = 6 } #Breslau
province = { id = 168 ic = 2 } #Gleiwitz
province = { id = 181 ic = 2 } #Gdansk/Danzig
province = { id = 221 ic = 2 } #Katowice

province = { id = 717 ic = 1 } #Rabat
province = { id = 718 ic = 1 } #Csablanca
province = { id = 964 ic = 1 } #Freetown
province = { id = 1053 ic = 1 } #Aden

province = { id = 1511 ic = 1 } #Colombo
province = { id = 1432 ic = 1 } #Singapore
province = { id = 1399 ic = 1 } #Saigon
province = { id = 1395 ic = 2 } #Hanoi
province = { id = 1393 ic = 3 } #Hoa Binh
### GLD (galicia londomeria)
province = { id = 235 ic = 2 } #Krakow
province = { id = 242 ic = 2 } #Lwow
province = { id = 240 ic = 1 } #Tarnopol
province = { id = 300 ic = 1 } #Cernauti
### GRE
province = { id = 368 ic = 2 } #Larissa
province = { id = 369 ic = 2 } #Metsovo
province = { id = 374 ic = 1 } #Chalcis
province = { id = 377 ic = 7 } #Athens
province = { id = 373 ic = 1 } #Corinth
province = { id = 372 ic = 1 } #Patra
province = { id = 375 ic = 1 } #Levadhia
### GUA (centroamerica)
province = { id = 2087 ic = 1 } #Puerto Barios
province = { id = 2088 ic = 3 } #Ciudad de Guatemala
province = { id = 2079 ic = 2 } #San Salvador
### GUY (caribbean federation)
province = { id = 1758 ic = 1 } #Trinidad
province = { id = 1782 ic = 2 } #Jamaica
province = { id = 1997 ic = 2 } #Georgetown
province = { id = 2000 ic = 2 } #Cayenne
### HAI
province = { id = 1781 ic = 4 } #Port au Prince
### HOL
province = { id = 118 ic = 3 } #Eindhoven
province = { id = 119 ic = 4 } #Arnhem
province = { id = 122 ic = 8 } #Amsterdam
province = { id = 123 ic = 1 } #Middleburg
province = { id = 124 ic = 1 } #Gronigen
province = { id = 125 ic = 5 } #Rotterdam
province = { id = 121 ic = 1 } #Maastricht

province = { id = 1651 ic = 1 } #Bandoeng
province = { id = 1650 ic = 1 } #Semarang
province = { id = 1653 ic = 4 } #Soerabaja
province = { id = 1636 ic = 1 } #Palembang
province = { id = 1640 ic = 1 } #Koeata-Radja
province = { id = 1632 ic = 1 } #Balikpapan
province = { id = 1637 ic = 1 } #Padang
province = { id = 1646 ic = 1 } #Tjilatjap
province = { id = 1647 ic = 2 } #Batavia
province = { id = 1649 ic = 1 } #Tjirebon
province = { id = 1654 ic = 1 } #Jogjakarta
### HON
province = { id = 2085 ic = 2 } #Tegucigalpa
### HUN(+slovakia)
province = { id = 279 ic = 2 } #Gyor
province = { id = 278 ic = 4 } #Szekesferhvar
province = { id = 277 ic = 5 } #Pecs
province = { id = 284 ic = 6 } #Budapest
province = { id = 282 ic = 1 } #Miskolc
province = { id = 280 ic = 2 } #Szeged
province = { id = 281 ic = 2 } #Debrecen

province = { id = 208 ic = 4 } #Bratislava
province = { id = 209 ic = 3 } #Kosice
province = { id = 211 ic = 2 } #Banka Bistrica
province = { id = 214 ic = 1 } #Presov
province = { id = 212 ic = 3 } #Zilina

province = { id = 296 ic = 1 } #Oradea
province = { id = 288 ic = 2 } #Cluj
province = { id = 292 ic = 1 } #Bictrita
province = { id = 291 ic = 1 } #Sibiu
province = { id = 286 ic = 1 } #Arad
province = { id = 285 ic = 1 } #Timisora
province = { id = 295 ic = 2 } #Resita

province = { id = 341 ic = 2 } #Novi Sad
### IND (Princely states)
province = { id = 1520 ic = 1 } #Surat
province = { id = 1514 ic = 1 } #Nasik
province = { id = 1478 ic = 1 } #Burhanpur
province = { id = 1486 ic = 1 } #Aurangabad
province = { id = 1517 ic = 3 } #Bombay/Mumbai
province = { id = 1489 ic = 1 } #Nizamabad
province = { id = 1498 ic = 1 } #Vijaywada
province = { id = 1487 ic = 3 } #Hyderabad
province = { id = 1496 ic = 1 } #Guntaru
province = { id = 1501 ic = 1 } #Anantapur
province = { id = 1503 ic = 1 } #Mangalore
province = { id = 1507 ic = 2 } #Matsuru
province = { id = 1497 ic = 2 } #Kochi
province = { id = 1495 ic = 2 } #Thiravana-thapuran
province = { id = 1516 ic = 2 } #Poona/Puna
### ITA
province = { id = 87 ic = 3 } #Nice
province = { id = 94 ic = 1 } #Corsica

province = { id = 398 ic = 3 } #Turin
province = { id = 396 ic = 3 } #Genoa
province = { id = 407 ic = 8 } #Milan
province = { id = 395 ic = 3 } #Bergamo
province = { id = 393 ic = 4 } #Brescia
province = { id = 408 ic = 1 } #Parma
province = { id = 411 ic = 4 } #Bologna
province = { id = 410 ic = 4 } #Florence
province = { id = 414 ic = 2 } #Livorno
province = { id = 419 ic = 4 } #Rome
province = { id = 416 ic = 1 } #Anzio
province = { id = 434 ic = 1 } #Cagliari
### IRE
province = { id = 36 ic = 4 } #Belfast
province = { id = 35 ic = 1 } #Londonderry
province = { id = 34 ic = 4 } #Dublin
province = { id = 31 ic = 6 } #Cork
### JAP (KOR)
province = { id = 1544 ic = 1 } #Kushiro
province = { id = 1551 ic = 4 } #Niigata
province = { id = 1549 ic = 1 } #Sendai
province = { id = 1552 ic = 12 } #Tokyo
province = { id = 1550 ic = 8 } #Yokohama
province = { id = 1556 ic = 3 } #Kanazawa
province = { id = 1557 ic = 6 } #Nagoya
province = { id = 1558 ic = 6 } #Kyoto
province = { id = 1553 ic = 10 } #Osaka
province = { id = 1559 ic = 3 } #Matsuyama
province = { id = 1554 ic = 6 } #Hiroshima
province = { id = 1560 ic = 9 } #Nagasaki
province = { id = 1531 ic = 6 } #Kagoshima
province = { id = 1549 ic = 2 } #Sendai
province = { id = 1555 ic = 4 } #Kobe

province = { id = 1361 ic = 2 } #Ganguong
province = { id = 1362 ic = 2 } #Taipei

province = { id = 1231 ic = 1 } #Daegu
province = { id = 1232 ic = 2 } #Busan
province = { id = 1228 ic = 3 } #Seoul
province = { id = 1227 ic = 2 } #Hamheung
province = { id = 1225 ic = 1 } #Cheongjin
province = { id = 1221 ic = 3 } #Pyeongyang
province = { id = 1222 ic = 2 } #Sariwon
province = { id = 1223 ic = 2 } #Wonsan
province = { id = 1219 ic = 2 } #Port Arthur
province = { id = 1216 ic = 1 } #Jinzhou
### KAZ (alash orda/alash autonomy)
province = { id = 706 ic = 4 } #Astrakhan
province = { id = 1107 ic = 1 } #Frunze
province = { id = 506 ic = 1 } #Taldy-Kurgan
province = { id = 500 ic = 2 } #Balkash
province = { id = 503 ic = 1 } #Karaganda
province = { id = 504 ic = 5 } #Alma ata
province = { id = 507 ic = 1 } #Ust-Kamenogorsk
province = { id = 1110 ic = 1 } #Kyzyl-Orda
province = { id = 1113 ic = 1 } #Uralsk
province = { id = 1114 ic = 1 } #Aktyubinsk
province = { id = 1116 ic = 1 } #Derzhavinsk
province = { id = 1117 ic = 1 } #Chelkar
province = { id = 1118 ic = 1 } #Fort Alexandrovsky
### KYG(turkestan)
province = { id = 1097 ic = 3 } #Ashkabad
province = { id = 1105 ic = 2 } #Stalinabad
province = { id = 1103 ic = 7 } #Tashkent
province = { id = 1098 ic = 1 } #Merv
province = { id = 1099 ic = 7 } #Samarkand
province = { id = 1100 ic = 2 } #Bukhara
province = { id = 1106 ic = 1 } #Osh
### LAT (EST)
province = { id = 270 ic = 6 } #Tallin
province = { id = 272 ic = 1 } #Tartu
province = { id = 274 ic = 1 } #Narva

province = { id = 268 ic = 2 } #Liepaja
### LBY
province = { id = 750 ic = 4 } #Tripoli
province = { id = 761 ic = 2 } #Benghazi
province = { id = 765 ic = 1 } #Tobruk
### LIB
province = { id = 969 ic = 2 } #Monrovia
### LIT
province = { id = 262 ic = 7 } #Kaunas
province = { id = 258 ic = 5 } #Wilno/Vilnius
province = { id = 263 ic = 1 } #Alytus
province = { id = 252 ic = 2 } #Suwalki
province = { id = 255 ic = 1 } #Grodno
### MAN
province = { id = 1218 ic = 1 } #Panjin
province = { id = 1215 ic = 1 } #Fushun
province = { id = 1207 ic = 1 } #Jilin
province = { id = 1199 ic = 3 } #Harbin
province = { id = 1203 ic = 1 } #Qiqihaer
province = { id = 1208 ic = 2 } #Changchun
province = { id = 1214 ic = 5 } #Shenyang
province = { id = 1217 ic = 2 } #Anshan
### MEX
province = { id = 1980 ic = 1 } #Culiacan Rosales
province = { id = 1975 ic = 1 } #Monterrey
province = { id = 1973 ic = 1 } #Leon de los Aldama
province = { id = 1971 ic = 3 } #Morelia
province = { id = 1974 ic = 7 } #Mexico City
province = { id = 1968 ic = 3 } #Veracruz
province = { id = 1972 ic = 5 } #Acapulco de Juarez
province = { id = 1970 ic = 1 } #Oaxaca de Juarez
province = { id = 1966 ic = 1 } #Merida
province = { id = 1965 ic = 1 } #Tuxtla Gutierrez
province = { id = 1967 ic = 3 } #Matamoros
### MON
province = { id = 1124 ic = 7 } #Ulaanhaatar
province = { id = 1119 ic = 3 } #Kyzyl
province = { id = 1168 ic = 2 } #Boryza
province = { id = 1158 ic = 2 } #Minusinsk
province = { id = 1147 ic = 2 } #Abakan (was 3)
province = { id = 1146 ic = 2 } #Oyrot-Tura
province = { id = 1167 ic = 2 } #Ulan Ude
province = { id = 1169 ic = 1 } #Chita
### NEP
province = { id = 1457 ic = 4 } #Katmundu
province = { id = 1467 ic = 4 } #Gorakhpur
### NIC (united provinces)
province = { id = 2080 ic = 2 } #Managua
province = { id = 2081 ic = 2 } #San Jose
### NOR
province = { id = 483 ic = 7 } #Oslo
province = { id = 485 ic = 1 } #Kristiansand
province = { id = 488 ic = 1 } #Bergen
province = { id = 493 ic = 1 } #Trondheim
### YEM
province = { id = 1050 ic = 2 } #Sanaa (Mar2020 reduced ic, was 4)
### OMN
province = { id = 1052 ic = 2 } #Masqat (Mar2020 reduced ic, was 4)
### OTT
province = { id = 409 ic = 10 } #Istanbul
province = { id = 1076 ic = 2 } #Izmit
province = { id = 1078 ic = 6 } #Bursa
province = { id = 1077 ic = 4 } #Izmir
province = { id = 1079 ic = 1 } #Denizli
province = { id = 1075 ic = 6 } #Ankara
province = { id = 1074 ic = 2 } #Konya
province = { id = 1073 ic = 1 } #Kayseri
province = { id = 1072 ic = 2 } #Kirikkale
province = { id = 1058 ic = 2 } #Tarsus
province = { id = 1067 ic = 2 } #Trabzon
province = { id = 1065 ic = 2 } #Karabuk

province = { id = 1019 ic = 3 } #Beirut
province = { id = 1108 ic = 1 } #Tel Aviv
province = { id = 1016 ic = 1 } #Damascus
province = { id = 1021 ic = 2 } #Aleppo

province = { id = 1029 ic = 3 } #Mosul
province = { id = 1034 ic = 2 } #Baghdad
province = { id = 1032 ic = 1 } #Basra

province = { id = 387 ic = 2 } #Famagusta
### PAK (delhi india)
province = { id = 1533 ic = 3 } #Karachi
province = { id = 1532 ic = 2 } #Nawabshah
province = { id = 1534 ic = 1 } #Islamabad
province = { id = 1526 ic = 1 } #Udaypur
province = { id = 1519 ic = 1 } #Mandvi
province = { id = 1518 ic = 2 } #Amdavad
province = { id = 1521 ic = 1 } #Baroda
province = { id = 1524 ic = 1 } #Jaypur
province = { id = 1459 ic = 5 } #Delhi
province = { id = 1479 ic = 1 } #Jabalpur
### PAN
province = { id = 2078 ic = 2 } #Ciudad de Panama
### PER
province = { id = 1092 ic = 2 } #Mashad
province = { id = 1095 ic = 1 } #Birjand
province = { id = 1094 ic = 1 } #Kerman
province = { id = 1093 ic = 2 } #Zuhedan
province = { id = 1086 ic = 2 } #Esfahan
province = { id = 1089 ic = 3 } #Ahvaz
### PER(socialist)
province = { id = 1085 ic = 5 } #Tehran
province = { id = 1080 ic = 1 } #Sari
province = { id = 1083 ic = 2 } #Tabriz
### PHI
province = { id = 1567 ic = 1 } #Baguio
province = { id = 1565 ic = 4 } #Manillla
province = { id = 1568 ic = 1 } #Logazpi
province = { id = 1576 ic = 1 } #Panay
province = { id = 1574 ic = 1 } #Bacolod
### POL
province = { id = 232 ic = 8 } #Warsaw
province = { id = 223 ic = 6 } #Lodz
province = { id = 233 ic = 3 } #Sosnowiec
province = { id = 234 ic = 1 } #Radom
province = { id = 243 ic = 2 } #Lublin
province = { id = 227 ic = 1 } #Czestochowa
province = { id = 228 ic = 1 } #Siedlce
### POR
province = { id = 481 ic = 3 } #Porto
province = { id = 479 ic = 1 } #Coimbra
province = { id = 476 ic = 9 } #Lisbon
province = { id = 480 ic = 1 } #Evora

province = { id = 1513 ic = 2 } #Panaji

province = { id = 854 ic = 1 } #Nampula
### PRI
province = { id = 1190 ic = 2 } #Khabarovsk
province = { id = 1191 ic = 9 } #Vladivostock
province = { id = 1185 ic = 1 } #Gavan
province = { id = 1192 ic = 4 } #Semyonovka
province = { id = 1194 ic = 1 } #Lesozavodsk
### PRK (bhartiya commune)
province = { id = 1493 ic = 3 } #Vishakhapatnam
province = { id = 1475 ic = 1 } #Bastar
province = { id = 1473 ic = 1 } #Kataka
province = { id = 1469 ic = 2 } #Raigarh
province = { id = 1472 ic = 1 } #Jamsedpur
province = { id = 1476 ic = 1 } #Ranchi
province = { id = 1448 ic = 1 } #Khasagpur
province = { id = 1447 ic = 10 } #Calcutta/kolkatta
province = { id = 1444 ic = 6 } #Khulna
province = { id = 1445 ic = 1 } #Dhaka
### PRU
province = { id = 2014 ic = 1 } #Trujillo
province = { id = 2016 ic = 7 } #Lima
province = { id = 2015 ic = 1 } #Cuzco
province = { id = 2017 ic = 1 } #Arequipa
### ROM
province = { id = 315 ic = 2 } #Craiova
province = { id = 311 ic = 2 } #Ploesti
province = { id = 316 ic = 7 } #Bucharest
province = { id = 309 ic = 1 } #Braila
province = { id = 297 ic = 3 } #Iasi
province = { id = 306 ic = 1 } #Ismail
province = { id = 304 ic = 2 } #Chisinau
province = { id = 310 ic = 2 } #Constanta
### RSI (socialist italy)
province = { id = 415 ic = 2 } #Pescara
province = { id = 421 ic = 2 } #Naples
province = { id = 420 ic = 1 } #Foggia
province = { id = 425 ic = 1 } #Reggio Calabria
province = { id = 430 ic = 2 } #Palermo
province = { id = 417 ic = 2 } #Cassino
province = { id = 422 ic = 3 } #Taranto
province = { id = 424 ic = 2 } #Potenza
province = { id = 427 ic = 3 } #Salerno
### RUS (SIB)
province = { id = 1164 ic = 1 } #Ust-Kut
province = { id = 1144 ic = 1 } #Kemerovo
province = { id = 1145 ic = 1 } #Stalinsk/Kuznezk
province = { id = 1143 ic = 2 } #Biysk
province = { id = 1142 ic = 4 } #Novosibirisk
province = { id = 501 ic = 1 } #Kokchetav
province = { id = 1138 ic = 3 } #Omsk
province = { id = 1136 ic = 1 } #Tyumen
province = { id = 1151 ic = 1 } #Sverdlovsk
province = { id = 1162 ic = 2 } #Irkutsk
province = { id = 1179 ic = 2 } #Yakutsk

province = { id = 553 ic = 5 } #Petrograd/St Petersburg
province = { id = 566 ic = 1 } #Pskov
province = { id = 590 ic = 1 } #Vitebsk
province = { id = 589 ic = 2 } #Smolensk
province = { id = 567 ic = 1 } #Serpukhov
province = { id = 570 ic = 1 } #Zagorsk
province = { id = 572 ic = 11 } #Moscow
province = { id = 678 ic = 1 } #Vladimir
province = { id = 569 ic = 1 } #Kalinin/Tver
province = { id = 539 ic = 1 } #Petrozavodsk
province = { id = 558 ic = 1 } #Rzhev
province = { id = 560 ic = 1 } #Novgorod

province = { id = 266 ic = 1 } #Daugavpils

province = { id = 1128 ic = 1 } #Nizhny Tagil
province = { id = 1133 ic = 1 } #Orsk
province = { id = 1132 ic = 2 } #Chelyabinsk
province = { id = 1127 ic = 1 } #Pervouralsk
province = { id = 1126 ic = 1 } #Kungur
province = { id = 1131 ic = 2 } #Ufa
province = { id = 687 ic = 1 } #Perm
province = { id = 667 ic = 1 } #Tolyatti
province = { id = 664 ic = 1 } #Neberezhnye Chelny
province = { id = 672 ic = 1 } #Kazan
province = { id = 671 ic = 3 } #Izhevsk
province = { id = 680 ic = 3 } #Gorky
province = { id = 542 ic = 1 } #Arkhangelsk
province = { id = 663 ic = 4 } #Stalingrad/Volgograd/Tsaritsyn
province = { id = 669 ic = 2 } #Saratov
province = { id = 654 ic = 2 } #Voronezh
province = { id = 652 ic = 1 } #Lipetsk
province = { id = 650 ic = 1 } #Tambov
province = { id = 665 ic = 2 } #Volsk
province = { id = 668 ic = 2 } #Kyubyshev
province = { id = 675 ic = 1 } #Cheboksary
province = { id = 670 ic = 1 } #Saransk
province = { id = 682 ic = 1 } #Ivanovo
province = { id = 677 ic = 1 } #Yaroslavl
province = { id = 603 ic = 1 } #Belgorod
province = { id = 604 ic = 1 } #Kursk
province = { id = 580 ic = 1 } #Yelets
province = { id = 579 ic = 1 } #Ryazan
province = { id = 584 ic = 2 } #Tula
province = { id = 581 ic = 1 } #Oryol
province = { id = 588 ic = 2 } #Bryansk

### SAF
province = { id = 880 ic = 1 } #Cape Town
province = { id = 872 ic = 1 } #Durban
province = { id = 874 ic = 1 } #Maseru
province = { id = 875 ic = 1 } #Bloemfontein
province = { id = 876 ic = 2 } #Johannesburg
province = { id = 873 ic = 6 } #Pretoria
### SAU
province = { id = 1049 ic = 1 } #Mecca
province = { id = 1045 ic = 5 } #Riyadh
### SCH
province = { id = 391 ic = 3 } #Geneva
province = { id = 392 ic = 7 } #Bern
province = { id = 389 ic = 4 } #Zurich
### SER
province = { id = 338 ic = 9 } #Belgrade
province = { id = 329 ic = 2 } #Pristina
province = { id = 330 ic = 1 } #Nis
province = { id = 339 ic = 1 } #Bor
### SIA
province = { id = 1426 ic = 1 } #Phitsanulok
province = { id = 1427 ic = 1 } #khonkhen
province = { id = 1422 ic = 1 } #Chon Buri
province = { id = 1401 ic = 1 } #Siem Reap
province = { id = 1423 ic = 6 } #Bangkok
province = { id = 1435 ic = 1 } #Ipoh
### SOM
province = { id = 836 ic = 3 } #Mogadishu
### SPA
province = { id = 441 ic = 3 } #Coruna
province = { id = 444 ic = 2 } #Oviedo
province = { id = 451 ic = 1 } #Burgos
province = { id = 443 ic = 2 } #Bilbao
province = { id = 440 ic = 4 } #Barcelona
province = { id = 442 ic = 2 } #Zaragoza
province = { id = 460 ic = 5 } #Madrid
province = { id = 464 ic = 3 } #Valencia
province = { id = 454 ic = 3 } #Tarancon
province = { id = 457 ic = 2 } #Toledo
province = { id = 463 ic = 1 } #Murcia
province = { id = 458 ic = 2 } #Badajoz
province = { id = 472 ic = 2 } #Huelva
province = { id = 474 ic = 5 } #Sevilla
### SWE
province = { id = 2165 ic = 1 } #Umea
province = { id = 2162 ic = 1 } #Gaevle
province = { id = 2158 ic = 1 } #Uppsala
province = { id = 2159 ic = 10 } #Stockholm
province = { id = 2160 ic = 1 } #Oerebro
province = { id = 2161 ic = 2 } #Karlstad
province = { id = 2157 ic = 1 } #Linkoping
province = { id = 2155 ic = 1 } #Kalmar
province = { id = 2153 ic = 1 } #Gothenburg
province = { id = 2152 ic = 2 } #Malmo
province = { id = 2162 ic = 1 } #Lulea
### TIB
province = { id = 1289 ic = 1 } #Lhasa
### TRA (don kuban)
province = { id = 644 ic = 2 } #Rostov on Don
province = { id = 698 ic = 1 } #Voroshilovsk
province = { id = 691 ic = 6 } #Krasnodar
province = { id = 694 ic = 2 } #Novorossiysk
province = { id = 702 ic = 2 } #Grozny
province = { id = 703 ic = 2 } #Vladikavkaz
### U02 (cretan state)
province = { id = 382 ic = 1 } #Irakleion
### U35 (madras residency)
province = { id = 1500 ic = 5 } #Madras
### UKR
province = { id = 244 ic = 3 } #Rowne
province = { id = 626 ic = 2 } #Odessa
province = { id = 611 ic = 1 } #Zhitomir
province = { id = 612 ic = 2 } #Vinnitsa
province = { id = 617 ic = 3 } #Kiev
province = { id = 613 ic = 1 } #Cherky
province = { id = 627 ic = 1 } #Krkoy Rog
province = { id = 624 ic = 1 } #Kherson
province = { id = 601 ic = 1 } #Gomel
province = { id = 607 ic = 1 } #Chernigov
province = { id = 606 ic = 1 } #Sumy
province = { id = 629 ic = 1 } #Poltava
province = { id = 636 ic = 4 } #Kharkov
province = { id = 632 ic = 2 } #Dnepropetrovsk
province = { id = 635 ic = 5 } #Stalino
province = { id = 622 ic = 2 } #Nikolayev
province = { id = 641 ic = 1 } #Sevastopol
### USA
province = { id = 1784 ic = 1 } #Bangor
province = { id = 1785 ic = 2 } #Lewiston
province = { id = 1787 ic = 1 } #Concord
province = { id = 1789 ic = 10 } #Boston
province = { id = 1796 ic = 1 } #Providence
province = { id = 1788 ic = 4 } #Hartford
province = { id = 1790 ic = 2 } #Burlington
province = { id = 1793 ic = 4 } #Albany
province = { id = 1792 ic = 4 } #Syracuse
province = { id = 1791 ic = 2 } #Buffalo

province = { id = 1795 ic = 10 } #New York
province = { id = 1797 ic = 3 } #Newark
province = { id = 1805 ic = 6 } #Philadelphia
province = { id = 1801 ic = 3 } #Harrisburg
province = { id = 1804 ic = 2 } #Scranton
province = { id = 1803 ic = 3 } #Williamsport
province = { id = 1806 ic = 2 } #Pitsburgh
province = { id = 1825 ic = 2 } #Cleveland
province = { id = 1821 ic = 2 } #Colombus
province = { id = 1845 ic = 8 } #Detroit
province = { id = 1842 ic = 4 } #grand Rapids
province = { id = 1826 ic = 3 } #Fort Wayne
province = { id = 1832 ic = 13 } #Chicago
province = { id = 1830 ic = 1 } #Decatur
province = { id = 1829 ic = 1 } #Peoria
province = { id = 1839 ic = 2 } #Milwaukee
province = { id = 1841 ic = 2 } #Green Bay
province = { id = 1843 ic = 1 } #Marquette

province = { id = 1961 ic = 2 } #Raleigh
province = { id = 1962 ic = 2 } #Charlotte
province = { id = 1963 ic = 1 } #Wilmington
province = { id = 1957 ic = 1 } #Columbia
province = { id = 1958 ic = 2 } #Greenville
province = { id = 1960 ic = 2 } #Charleston
province = { id = 1942 ic = 1 } #Knoxville
province = { id = 1943 ic = 1 } #Nashville
province = { id = 1940 ic = 1 } #Memphis
province = { id = 1956 ic = 1 } #Savannah
province = { id = 1954 ic = 1 } #Macon
province = { id = 1955 ic = 3 } #Atlanta
province = { id = 1952 ic = 1 } #Jacksonville
province = { id = 1953 ic = 1 } #Miami
province = { id = 1948 ic = 1 } #Tampa
province = { id = 1945 ic = 1 } #Gadsen
province = { id = 1944 ic = 2 } #Mobile
province = { id = 1931 ic = 2 } #New Orleans
province = { id = 1934 ic = 2 } #Lafayette
province = { id = 1929 ic = 1 } #Monroe
province = { id = 1959 ic = 1 } #Augusta

province = { id = 1874 ic = 2 } #Seattle
province = { id = 1872 ic = 1 } #Spokane
province = { id = 1882 ic = 3 } #Benk
province = { id = 1878 ic = 4 } #Portland
province = { id = 1879 ic = 1 } #Eugene
province = { id = 1885 ic = 1 } #Redding
province = { id = 1889 ic = 7 } #San Francisco
province = { id = 1883 ic = 1 } #Fresno
province = { id = 1887 ic = 7 } #Los Angeles
province = { id = 1892 ic = 1 } #San Bernadino
province = { id = 1886 ic = 1 } #San Diego

province = { id = 1734 ic = 1 } #Pearl Harbor

province = { id = 1921 ic = 1 } #Amarillo
province = { id = 1920 ic = 1 } #Lubock
province = { id = 1924 ic = 3 } #Dallas
province = { id = 1928 ic = 4 } #Houston
province = { id = 1925 ic = 1 } #Austin
province = { id = 1926 ic = 1 } #San Antonia
province = { id = 1922 ic = 1 } #Corpus Christi

province = { id = 1802 ic = 2 } #Ancona
province = { id = 1808 ic = 2 } #Baltimore
province = { id = 1809 ic = 12 } #Washington DC
province = { id = 1814 ic = 3 } #Arlington
province = { id = 1810 ic = 2 } #Clarksburg
province = { id = 1813 ic = 3 } #Richmond
province = { id = 1812 ic = 3 } #Norfiolk
province = { id = 1811 ic = 1 } #Huntington
province = { id = 1820 ic = 2 } #Lexington
province = { id = 1819 ic = 2 } #Louisville
province = { id = 1828 ic = 3 } #Indianapolis
province = { id = 1831 ic = 1 } #Belleville
province = { id = 1833 ic = 1 } #Saint Louis
province = { id = 1836 ic = 1 } #Springfield
province = { id = 1837 ic = 2 } #Cedar Rapids
province = { id = 1838 ic = 2 } #Des Moines
province = { id = 1846 ic = 9 } #Rochester
province = { id = 1850 ic = 1 } #Saint Paul
province = { id = 1847 ic = 2 } #Minneapolis
province = { id = 1854 ic = 2 } #Grand Forks
province = { id = 1915 ic = 2 } #Jonesboro
province = { id = 1918 ic = 1 } #Little Rock
province = { id = 1913 ic = 2 } #Oklahoma City
province = { id = 1911 ic = 2 } #Lawton
province = { id = 1910 ic = 1 } #Wichita
province = { id = 1914 ic = 2 } #Kansas City
province = { id = 1908 ic = 2 } #Denver
province = { id = 1860 ic = 2 } #Omaha
province = { id = 1858 ic = 1 } #Rapid City
province = { id = 1855 ic = 2 } #Fargo
province = { id = 1856 ic = 2 } #Bismarck
province = { id = 1905 ic = 1 } #Roswell
province = { id = 1904 ic = 1 } #Albuquerque
province = { id = 1906 ic = 1 } #Santa Fe
province = { id = 1901 ic = 1 } #Tuscon
province = { id = 1902 ic = 1 } #Flagstaff
province = { id = 1900 ic = 1 } #Phoenix
province = { id = 1909 ic = 1 } #Colorado Springs
province = { id = 1897 ic = 1 } #Grand Junction
province = { id = 1896 ic = 1 } #Salt Lake City
province = { id = 1893 ic = 1 } #Las Vegas
province = { id = 1866 ic = 1 } #Casper
province = { id = 1868 ic = 1 } #Billings
province = { id = 1871 ic = 1 } #Bose
province = { id = 1863 ic = 2 } #Helena

### VEN
province = { id = 1988 ic = 1 } #Macaraibo
province = { id = 1996 ic = 1 } #Barinas
province = { id = 1995 ic = 1 } #Maturin
province = { id = 1989 ic = 1 } #Barquisimeto
province = { id = 1993 ic = 4 } #Caracas
### VIC (national france)
province = { id = 734 ic = 1 } #Constantine
province = { id = 746 ic = 1 } #El Kef
province = { id = 747 ic = 5 } #Tunis
province = { id = 978 ic = 4 } #Dakar
province = { id = 966 ic = 2 } #Conakry
province = { id = 962 ic = 3 } #Abidjan
province = { id = 970 ic = 2 } #San Pedro
province = { id = 728 ic = 3 } #Oran
province = { id = 727 ic = 8 } #Algiers
province = { id = 729 ic = 2 } #Tlemcen
province = { id = 731 ic = 1 } #Batna
province = { id = 734 ic = 1 } #Constantine
province = { id = 735 ic = 2 } #Bona
province = { id = 736 ic = 3 } #Bougie
province = { id = 749 ic = 2 } #Beja
province = { id = 957 ic = 1 } #Ouagadougou
### YUN
province = { id = 1390 ic = 5 } #Kunming
province = { id = 1299 ic = 1 } #Chongqing