

country = {
    tag = JAP  

ai = "kaiserreich\Japan.ai"

	policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 6
        political_left = 3
        freedom = 6
        free_market = 5
        professional_army = 3
        defense_lobby = 6
        interventionism = 6

    }

#### cabinet

headofstate = { type = 9 id = 55601 }
headofgovernment = { type = 9 id = 55602 }
  foreignminister = { type = 9 id = 55603 }
  armamentminister = { type = 9 id = 55604 }
  ministerofsecurity = { type = 9 id = 55605 }
  ministerofintelligence = { type = 9 id = 55606 }
  chiefofstaff = { type = 9 id = 55607 }
  chiefofarmy = { type = 9 id = 55608 }
  chiefofnavy = { type = 9 id = 55609 }        
  chiefofair = { type = 9 id = 55610 }

#### Resource Reserves

	manpower = 735

        SpyInfo  = {  country = "JAP" NumberOfSpies = 5  } 

	# Resource Reserves
	energy	=		1000 
	metal	= 		1000	
	rare_materials =	500	
	oil =			500	
	supplies =		500
	money = 		100

	capital = 1552




    ownedprovinces =      {
     1543 1564 1544 1545 1549 1551 1550 1556 1552 1557 1558 1553 1554 1559 1560 1561 1662 1661 1562 1563 1672 1362 1361 1364 1225 1226 
     1227 1223 1221 1228 1233 1232 1231 1230 1224 1219 1542 1555 1547 1548 1546 1664 1663 1541 
     # Sakhalin 
     1363 1229 1222 
     #Japan in China    
     1216 1235 1236 1240  
}



controlledprovinces = {
1543 1564 1544 1545   1549 1551 1550 1556 1552 1557 1558 1553 1554 1559 1560 1561 1662 1661 1562 1563 1672 1362 1361 1364 1225 1226 
               1227 1223 1221 1228 1233 1232 1231 1230 1224 1219 1542 1555 
     1547 1548 1546 1664 1663 1541 
     # Sakhalin 
     1363 1229 1222 
 
     #Japan in China    
     1216 1235 1236 1240  

	  }
    nationalprovinces =   {
		1543 1544 1545 1549 1551 1550 1556 1552 1557 1558 1553 1554 1559 1560 1561 1662 1661 1562 1563 1672 1555 1542  
               1664 1564 1663 
     1547 1548 1546 1541
 
	}

claimedprovinces = {
 1228 1233 1232 1231 1230  1229 # South Korea 
 1223 1221 1222 1226 1227 1224 1225    # North Korea 
		1219 1363 1362 1361 1364
	}

diplomacy = {

relation = {   tag =    BEL	value = 		-50	   }  
relation = {   tag =  	BLR	 value =		-20	   }  
relation = {   tag =  	BUL	value = 		-30	   }  
relation = {   tag =  	GER	 value =		-80	   }  
relation = {   tag =  	LAT	value = 		-40	   }  
relation = {   tag =  	LIT	 value =		-20	   }  
relation = {   tag =  	POL	value = 		-10	   }  
relation = {   tag =  	UKR	 value =		-40	   }  
relation = {   tag =  	AUS	value = 		-50	   }  
relation = {   tag =  	BOS	value = 		-20	   }  
relation = {   tag =  	CRO	 value =		-10	   }  
relation = {   tag =  	CZE	value = 		-10	   }  
relation = {   tag =  	GLD	value = 		-10	   }  
relation = {   tag =  	HUN	 value =		-50	   }  
relation = {   tag =  	HOL	 value =		40	   }  
relation = {   tag =  	ITA	value = 		-20	   }  
relation = {   tag =  	POR	value = 		20	   }  
relation = {   tag =  	SPA	value = 		-10	   }  
relation = {   tag =  	ENG	value = 		-50	   }  
relation = {   tag =  	FRA	value = 		-60	   }  
relation = {   tag =  	RSI	 value =		-20	   }  
relation = {   tag =  	AST	value = 		-50	   }  
relation = {   tag =  	CAN	value = 		80	   }  
relation = {   tag =  	GUY	value = 		40	   }  
relation = {   tag =  	NZL	 value =		-40	   }  
relation = {   tag =  	VIC	value = 		50	   }  
relation = {   tag =  	KAZ	 value =		30	   }  
relation = {   tag =  	KYG	value = 		40	   }  
relation = {   tag =  	PRI	value = 		120	 access = yes   }  
relation = {   tag =  	RUS	 value =		-50	   }  
relation = {   tag =  	AFG	 value =		20	   }  
relation = {   tag =  	OTT	 value =		-30	   }  
relation = {   tag =  	PER	value = 		20	   }  
relation = {   tag =  	CON	value = 		-40	   }  
relation = {   tag =  	IND	value = 		50	   }  
relation = {   tag =  	CHL	value = 		40	   }  
relation = {   tag =  	PRU	value = 		40	   }  
relation = {  tag =   	USA	value = 		30	   }
relation = {   tag =  	CHC	value = 		-50	   }  
relation = {   tag =  	CSX	value = 		-80	   }  
relation = {   tag =  	CXB	value = 		-30	   }  
relation = {   tag =  	MAN	 value =		160	access = yes    }  
relation = {   tag =  	MON	value = 		100	   }  
relation = {   tag =  	SIK	value = 		90	   }  

		relation = { tag = EAF value = 60 guaranteed = { day = 29 month = december year = 1935   } 	   } 
}

dormant_ministers = { 55973 55984 55985 }

	techapps = {

# JAP 1936 techs
#######################
#Infantry
1010  1020 1030 1040 1050 1060 1070 1080 1090 #Early Infantry Division 
1160 1170 1180 1190 1200 1210 1220 1230 1240 #1930 Mountain
13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 #1930 Cavalry Division 
1560 1570 1580 1590 #Naval Infantry
1830 1840 1850 1860 #Engineers
1910 1920 1930 1940 1950 1960 1970 1980 #Interbellum 1930 Supply 

#Armour & Artillery
7600 7610 2620 2010 2630 2640 2646 2650 #Tanks
2860 2870 2880 2020 #Basic Armoured Car 
2290 2300 2310 2900 2910 2920 #Great War Heavy Field Artillery
2800 2450 21180 21190 #Early Static Anti-Air Artillery 
2810 2820 2510 #Basic Anti-Air Artillery Brigade

#Naval
3010 3020 3030 3040 3050 3060 #Improved Destroyer 
3110 3120 3130 3140 3150 3160 #Basic Light Cruiser
3210 3220 3230 3240 3250 3260 #Improved Heavy Cruiser
3310 3320 3330 3340 # Battle Cruiser
3410 3420 3430 3440 3450 3456 3460 3470 #Early Battleship
3510 3520 3530 #Great War Air Carrier
12100 12110 12120 12130 #Improved Light carrier
3610 3620 3630 3640 3650 #Short Range Submarine
3720 3730 3736 3740 3750 3760 3900 #Torpedo & ASW 18
3810 3820 #Troopships

#Aircrafts
7290 7300 7310 7320 4400 #CAS 
4500 4510 4520 4530 4540 4550 4010 4020 #Early Fighter
4600 4610 4620 4630 4120 4130 #Early Bomber 
4700 4710 4190 #Basic Naval Bomber
4290 # Transports
4300 4310 4320 4330 4340 #Multirole fighter
4740 4750 4760 4770 4780 #SEAPLANES
4800 4810 4820 #ww1 strategic bomber
4900 4910 4920 #CAG 34

#Industrial
5700 5710 5010 #Modern Agriculture
5810 5820 5050 5830 #manufactoring
5800 5080 5090 #Improved Construction Engineering 
5190 #Basic Oil Refining 
5310 54010 54020 54030 #Computers & cryptografi
5316 5326 5327
5600 5610 5620 #Medicine
5560 #Exp. Rocket

#Land Doctrines
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6680 6540 6910 # Great War Land Doctrines (entente)
14000 14010 #Improved Great War Hospital System

#Naval Doctrines
8010 8020 8030 8040 8050 8060 8070 8080 # Engagement Theories
8100 8110 8120 8150 # Naval Supremacy
8500 8510 8520 8550 8560 8600 8610 # Naval Interdiction
8900 8910 8920 8930 8940 8950 # Engagement Tactics - Fleet-in-Being column
81650 # Subsidiary Carrier Role
81700 81710 # Aerial Supremacy column
81850 81860 # Scouting Focus column
82300 82310 # Amphibious Warfare
82500 # Logistic Support

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9040 
}

deactivate = { 6210 6570 6010 6560 6390 }

######### Land OOB, 1936 (13016 - 500) #########

	landunit = {
	id = { type = 13016 id = 500 }
	name = "Dai-1 'Tokyo' Shidan"
	location = 1552

		division = {
		id = { type = 13016 id = 501 }
		name = "1. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = artillery
		brigade_model = 5
		}
  }

	landunit = {
	id = { type = 13016 id = 502 }
	name = "Konoegun"
	location = 1552

		division = {
		id = { type = 13016 id = 503 }
		name = "1. Konoeshidan"
		strength = 100
		type = infantry
		model = 8
		extra = artillery
		brigade_model = 5
		}
  }

	landunit = {
	id = { type = 13016 id = 504 }
	name = "Daihonei" #Tokyo
	location = 1552

		division = {
		id = { type = 13016 id = 505 }
		name = "Daihonei"
		strength = 100
		type = hq
		model = 2
		}
	}

	landunit = {
	id = { type = 13016 id = 506 }
	name = "Dai-2 'Sendai' Shidan"
	location = 1236

		division = {
		id = { type = 13016 id = 507 }
		name = "2. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = artillery
		brigade_model = 5
		}
  }

	landunit = {
	id = { type = 13016 id = 508 }
	name = "Dai-3 'Nagoya' Shidan"
	location = 1557

		division = {
		id = { type = 13016 id = 509 }
		name = "3. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = anti_tank
		brigade_model = 2
		}
  }


	landunit = {
	id = { type = 13016 id = 510 }
	name = "Dai-4 'Osaka' Shidan" 
	location = 1240

		division = {
		id = { type = 13016 id = 511 }
		name = "4. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = armored_car
		brigade_model = 3
		}
  }

	landunit = {
	id = { type = 13016 id = 512 }
	name = "Dai-5 'Hiroshima' Shidan"
	location = 1554

		division = {
		id = { type = 13016 id = 513 }
		name = "5. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = artillery
		brigade_model = 5
		}
	}

	landunit = {
	id = { type = 13016 id = 514 }
	name = "Dai-6 'Kumamoto' Shidan"
	location = 1561

		division = {
		id = { type = 13016 id = 515 }
		name = "6. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = artillery
		brigade_model = 5
		}
		}

	landunit = {
	id = { type = 13016 id = 516 }
	name = "Dai-7 'Sapporo' Shidan"
	location = 1545

		division = {
		id = { type = 13016 id = 517 }
		name = "7. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = anti_air
		brigade_model = 2
		}
  }

	landunit = {
	id = { type = 13016 id = 518 }
	name = "Dai-8 'Hirosaki' Shidan"
	location = 1216

		division = {
		id = { type = 13016 id = 519 }
		name = "8. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = artillery
		brigade_model = 5
		}
  }

	landunit = {
	id = { type = 13016 id = 520 }
	name = "Dai-9 'Kanazawa' Shidan"
	location = 1200

		division = {
		id = { type = 13016 id = 521 }
		name = "9. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = anti_air
		brigade_model = 2
		}
	}

	landunit = {
	id = { type = 13016 id = 522 }
	name = "Dai-11 'Zentsuji' Shidan" 
	location = 1559

		division = {
		id = { type = 13016 id = 523 }
		name = "11. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = artillery
		brigade_model = 5
		}
	}

	landunit = {
	id = { type = 13016 id = 524 }
	name = "Dai-13 'Takada' Shidan" 
	location = 1551

		division = {
		id = { type = 13016 id = 525 }
		name = "13. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = engineer
		brigade_model = 3
		}
  }

	landunit = {
	id = { type = 13016 id = 526 }
	name = "Dai-14 'Utsunomiya' Shidan"
	location = 1201

		division = {
		id = { type = 13016 id = 527 }
		name = "14. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = artillery
		brigade_model = 5
		}
  }

	landunit = {
	id = { type = 13016 id = 528 }
	name = "Dai-16 'Kyoto' Shidan"
	location = 1558

		division = {
		id = { type = 13016 id = 529 }
		name = "16. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = armored_car
		brigade_model = 3
		}
	}

	landunit = {
	id = { type = 13016 id = 530 }
	name = "Dai-17 'Okayama' Shidan"
	location = 1209

		division = {
		id = { type = 13016 id = 531 }
		name = "17. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = anti_air
		brigade_model = 2
		}
		}

	landunit = {
	id = { type = 13016 id = 532 }
	name = "Dai-19 'Ranan' Shidan"
	location = 1225

		division = {
		id = { type = 13016 id = 533 }
		name = "19. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = artillery
		brigade_model = 5
		}
	}

	landunit = {
	id = { type = 13016 id = 534 }
	name = "Dai-20 'Keijo' Shidan"
	location = 1228

		division = {
		id = { type = 13016 id = 535 }
		name = "20. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = anti_air
		brigade_model = 2
		}
	}


#Armies in the oversea

	landunit = {
	id = { type = 13016 id = 536 }
	name = "Kantogun"
	location = 1208

		division = {
		id = { type = 13016 id = 537 }
		name = "Kantogun"
		strength = 100
		type = hq
		model = 2
		extra = police
		brigade_model = 1
		}

		division = {
		id = { type = 13016 id = 538 }
		name = "1. Kiheishudan"
		strength = 100
		type = cavalry
		model = 9
		extra = armored_car
		brigade_model = 3
		}

		division = {
		id = { type = 13016 id = 539 }
		name = "10. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = light_armor_brigade
		brigade_model = 3
		}

		division = {
		id = { type = 13016 id = 540 }
		name = "12. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = artillery
		brigade_model = 5
		}
  }

	landunit = {
	id = { type = 13016 id = 541 }
	name = "Kanto Chuton Hoheiryodan"
	location = 1219
		division = {
		id = { type = 13016 id = 542 }
		name = "Kanto Chuton Hoheiryodan"
		strength = 100
		type = garrison
		model = 4
		locked = yes
		}
  }

	landunit = {
	id = { type = 13016 id = 543 }
	name = "Kokuryukogun"
	location = 1190

		division = {
		id = { type = 13016 id = 544 }
		name = "15. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = armored_car
		brigade_model = 3
		}

		division = {
		id = { type = 13016 id = 545 }
		name = "18. Hoheishidan"
		strength = 100
		type = infantry
		model = 8
		extra = engineer
		brigade_model = 3
		}
  }

landunit = {
	id = { type = 13016 id = 546 }
	name = "Taiwangun" 
	location = 1362

	division = {
		id = { type = 13016 id = 547 }
		name = "48. Hoheishidan"
		strength = 60
		type = infantry
		model = 8
		}
		division = {
		id = { type = 13016 id = 548 }
		name = "Kiirun Yosai Shirebu"
		strength = 50
		type = garrison
		model = 4
		locked = yes
		}
	}

landunit = {
	id = { type = 13016 id = 549 }
	name = "Yokosuka Chinjufu" 
	location = 1552

		division = {
		id = { type = 13016 id = 550 } 
		name = "Yokosuka Tokubetsu Rikusentai" 
		strength = 25
		type = marine
		model = 3
		}
  }

landunit = {
	id = { type = 13016 id = 551 }
	name = "Kure Chinjufu" 
	location = 1554

		division = {
		id = { type = 13016 id = 552 } 
		name = "Kure Tokubetsu Rikusentai" 
		strength = 25
		type = marine
		model = 3
		}
  }

landunit = {
	id = { type = 13016 id = 553 }
	name = "Sasebo Chinjufu" 
	location = 1560

		division = {
		id = { type = 13016 id = 554 } 
		name = "Sasebo Tokubetsu Rikusentai" 
		strength = 25
		type = marine
		model = 3
		}
  }

landunit = {
	id = { type = 13016 id = 555 }
	name = "Maizuru Chinjufu" 
	location = 1558

		division = {
		id = { type = 13016 id = 556 } 
		name = "Maizuru Tokubetsu Rikusentai" 
		strength = 25
		type = marine
		model= 3
		}
  }

landunit = {
	id = { type = 13016 id = 557 }
	name = "Dai-1/Dai-2 Kokkyo Shubitai" 
	location = 1202

		division = {
		id = { type = 13016 id = 558 }
		name = "1. Kokkyo Shubitai"
		strength = 100
		type = garrison
		model = 4
		}

		division = {
		id = { type = 13016 id = 559 }
		name = "2. Kokkyo Shubitai"
		strength = 100
		type = garrison
		model = 4
		}
  }

landunit = {
	id = { type = 13016 id = 560 }
	name = "Dai-3 Kokkyo Shubitai" 
	location = 1197

		division = {
		id = { type = 13016 id = 561 }
		name = "3. Kokkyo Shubitai"
		strength = 100
		type = garrison
		model = 4
		}
  }

landunit = {
	id = { type = 13016 id = 562 }
	name = "Dai-4/Dai-5 Kokkyo Shubitai" 
	location = 1201

		division = {
		id = { type = 13016 id = 563 }
		name = "4. Kokkyo Shubitai"
		strength = 100
		type = garrison
		model = 4
		}

		division = {
		id = { type = 13016 id = 564 }
		name = "5. Kokkyo Shubitai"
		strength = 100
		type = garrison
		model = 4
		}
  }

landunit = {
	id = { type = 13016 id = 565 }
	name = "Dai-6/Dai-7 Kokkyo Shubitai" 
	location = 1200

		division = {
		id = { type = 13016 id = 566 }
		name = "6. Kokkyo Shubitai"
		strength = 100
		type = garrison
		model = 4
		}

		division = {
		id = { type = 13016 id = 567 }
		name = "7. Kokkyo Shubitai"
		strength = 100
		type = garrison
		model = 4
		}
  }

	landunit = {
	id = { type = 13016 id = 568 }
	name = "Karafutogun"
	location = 1542

		division = {
		id = { type = 13016 id = 569 }
		name = "Karafuto Konseiryodan"
		strength = 100
		type = garrison
		model = 4
		locked = yes
		}
  }

	landunit = {
	id = { type = 13016 id = 570 }
	name = "Dai-1 Dokuritsu Shubitai"
	location = 1214

		division = {
		id = { type = 13016 id = 571 }
		name = "1. Dokuritsu Shubitai"
		strength = 100
		type = garrison
		model = 4
		}
  }

	landunit = {
	id = { type = 13016 id = 572 }
	name = "Dai-2 Dokuritsu Shubitai"
	location = 1208

		division = {
		id = { type = 13016 id = 573 }
		name = "2. Dokuritsu Shubitai"
		strength = 100
		type = garrison
		model = 4
		}
  }

	landunit = {
	id = { type = 13016 id = 574 }
	name = "Dai-3 Dokuritsu Shubitai"
	location = 1203

		division = {
		id = { type = 13016 id = 575 }
		name = "3. Dokuritsu Shubitai"
		strength = 100
		type = garrison
		model = 4
		}
  }

	landunit = {
	id = { type = 13016 id = 576 }
	name = "Dai-4 Dokuritsu Shubitai"
	location = 1205

		division = {
		id = { type = 13016 id = 577 }
		name = "4. Dokuritsu Shubitai"
		strength = 100
		type = garrison
		model = 4
		}
  }

	landunit = {
	id = { type = 13016 id = 578 }
	name = "Dai-5 Dokuritsu Shubitai"
	location = 1199

		division = {
		id = { type = 13016 id = 579 }
		name = "5. Dokuritsu Shubitai"
		strength = 100
		type = garrison
		model = 4
		}
  }

######### Air OOB, 1936 (13016 - 1400) #########
######  This fictional air OOB is partially based on datas from lab4.jp.apan.net/nishiko/murakawa

	airunit = {
		location = 1557 #Gifu
		base = 1557
		id = { type = 13016 id = 1400 }
		name = "Dai-1 Hikodan"
		division = { id = { type = 13016 id = 1401 } name = "1. Hikorentai" strength = 60 type = interceptor model = 7 }
		division = { id = { type = 13016 id = 1402 } name = "2. Hikorentai" strength = 30 type = cas model = 4 }
	}

	airunit = {
		location = 1219 #Yokaichi
		base = 1219
		id = { type = 13016 id = 1403 }
		name = "Hiko Dai-3 Rentai"
		division = { id = { type = 13016 id = 1404 } name = "3. Hikorentai" strength = 45 type = cas model = 4 }
	}

	airunit = {
		location = 1560 #Tachiarai
		base = 1560
		id = { type = 13016 id = 1405 }
		name = "Hiko Dai-4 Rentai"
		division = { id = { type = 13016 id = 1406 } name = "4. Hikorentai" strength = 60 type = interceptor model = 7 }
	}

	airunit = {
		location = 1552 #Tachikawa
		base = 1552
		id = { type = 13016 id = 1407 }
		name = "Hiko Dai-5 Rentai"
		division = { id = { type = 13016 id = 1408 } name = "5. Hikorentai" strength = 60 type = interceptor model = 7 }
	}

	airunit = {
		location = 1221 #Heijo
		base = 1221
		id = { type = 13016 id = 1409 }
		name = "Hiko Dai-6 Rentai"
		division = { id = { type = 13016 id = 1410 } name = "6. Hikorentai" strength = 45 type = cas model = 4 }
	}

	airunit = {
		location = 1546 #Hamamatsu
		base = 1546
		id = { type = 13016 id = 1411 }
		name = "Hiko Dai-7 Rentai"
		division = { id = { type = 13016 id = 1412 } name = "7. Hikorentai" strength = 75 type = tactical_bomber model = 5 }
	}

	airunit = {
		location = 1361 #Heito
		base = 1361
		id = { type = 13016 id = 1413 }
		name = "Hiko Dai-8 Rentai"
		division = { id = { type = 13016 id = 1414 } name = "8. Hikorentai" strength = 45 type = interceptor model = 7 }
	}

	airunit = {
		location = 1541 #Kainei
		base = 1541
		id = { type = 13016 id = 1415 }
		name = "Hiko Dai-9 Rentai"
		division = { id = { type = 13016 id = 1416 } name = "9. Hikorentai" strength = 60 type = interceptor model = 7 }
	}

	airunit = {
		location = 1203 #Chichiharu
		base = 1203
		id = { type = 13016 id = 1417 }
		name = "Hiko Dai-10 Rentai"
		division = { id = { type = 13016 id = 1418 } name = "10. Hikorentai" strength = 60 type = tactical_bomber model = 4 }
	}

	airunit = {
		location = 1199 #Harupin
		base = 1199
		id = { type = 13016 id = 1419 }
		name = "Hiko Dai-11 Rentai"
		division = { id = { type = 13016 id = 1420 } name = "11. Hikorentai" strength = 60 type = interceptor model = 6 }
	}

	airunit = {
		location = 1208 #Koshurei
		base = 1208
		id = { type = 13016 id = 1421 }
		name = "Hiko Dai-12 Rentai"
		division = { id = { type = 13016 id = 1422 } name = "12. Hikorentai" strength = 60 type = tactical_bomber model = 5 }
	}

	airunit = {
		location = 1555 #Kakogawa
		base = 1555
		id = { type = 13016 id = 1423 }
		name = "Hiko Dai-13 Rentai"
		division = { id = { type = 13016 id = 1424 } name = "13. Hikorentai" strength = 5 type = interceptor model = 7 }
	}

	airunit = {
		location = 1361 #Kagi
		base = 1361
		id = { type = 13016 id = 1425 }
		name = "Hiko Dai-14 Rentai"
		division = { id = { type = 13016 id = 1426 } name = "14. Hikorentai" strength = 30 type = tactical_bomber model = 5 }
	}

	airunit = {
		location = 1208 #Shinkyo
		base = 1208
		id = { type = 13016 id = 1427 }
		name = "Hiko Dai-15 Rentai"
		division = { id = { type = 13016 id = 1428 } name = "15. Hikorentai" strength = 30 type = cas model = 4 }
	}

	airunit = {
		location = 1205 #Botanko
		base = 1205
		id = { type = 13016 id = 1429 }
		name = "Hiko Dai-16 Rentai"
		division = { id = { type = 13016 id = 1430 } name = "16. Hikorentai" strength = 60 type = interceptor model = 6 }
	}

	airunit = {
		location = 1547 #Ominato
		base = 1547
		id = { type = 13016 id = 1431 }
		name = "Ominato Kokutai"
		division = { id = { type = 13016 id = 1432 }	name = "Ominato Kokutai" strength = 80 type = naval_bomber model = 1 }
	}

	airunit = {
		location = 1552 #Tateyama
		base = 1552
		id = { type = 13016 id = 1433 }
		name = "Tateyama Kokutai"
		division = { id = { type = 13016 id = 1434 }	name = "Tateyama Kokutai" strength = 80 type = naval_bomber model = 1 }
	}

	airunit = {
		location = 1560 #Saiki
		base = 1560
		id = { type = 13016 id = 1435 }
		name = "Saiki Kokutai"
		division = { id = { type = 13016 id = 1436 }	name = "Saiki Kokutai" strength = 80 type = naval_bomber model = 1 }
	}

######### Naval OOB, 1936 (13016 - 1000) #########
######    Battleship :
######    3 Old ships
######    4 Fuso/Ise class Battleships
######    2 Nagato class Battleships
######    2 Tosa class Battleships
######    2 Kii class Battleships      - Ordered in October 1921 - Halted in November 1921 with the Peace with Honour - Cancelled in January 1924 - Reordered in 1931 and completed
######    2 Kii class Battleships under construction
######
###### = 15 Battleships in total (2 ships in construction)

######    Battlecruiser :
######    4 Kongo class Battlecruisers
######    0 Amagi class Battlecruiser  - Construction of Atago and Takao halted in November 1921 with the Peace with Honour
######                                 - Amagi, Atago, Takao all cancelled in January 1924 with the Great Kanto Earthquake
######                                 - Akagi converted into the Aircraft Carrier
###### =  4 Battlecruisers in total

######    Aircraft Carrier :
######    1 Hosho class Carrier
######    2 Seaplane Carriers
######    2 Shokaku class Carriers     - Two Aircraft Carriers from the 8-8 Fleet Programme
######    1 Akagi class Carrier        - Converted into Aircraft Carrier
######    1 Ryujo class Carrier
######
###### =  7 Aircraft Carriers in total (4 Fleet Carriers)

######    Heavy Cruiser :
######    4 Old ships (CA2)
######    2 Furutaka class Heavy Cruisers (CA4)
######    2 Aoba class Heavy Cruisers (CA4)
######    4 Myoko class Heavy Cruisers (CA5)
######    4 Takao class Heavy Cruisers (CA5)
######    All other ships were either scrapped or converted for training purposes due to financial shortage.
######
###### = 16 Heavy Cruisers in total

######    Light Cruiser :
######    2 Chikuma class Light Cruisers (CL2)
######    2 Tenryu class Light Cruisers (CL3)
######    5 Kuma class Light Cruisers (CL4)
######    6 Nagara class Light Cruisers (CL4)
######    8 Sendai class Light Cruisers (CL4)
######    1 Yubari class Light Cruiser (CL4)
######    4 Mogami class Light Cruisers under construction (CL6)
######
###### = 28 Light Cruisers in total (4 ships in construction)

######    Destroyer :
######   20 Momi class Destroyers (4 DD4 Destroyer units)
######    8 Wakatake class Destroyers (2 DD4 Destroyer units)
######   15 Minekaze class Destroyers (3 DD5 Destroyer units)
######    9 Kamikaze class Destroyers (2 DD5 Destroyer units)
######   12 Mutsuki class Destroyers (2 DD5 Destroyer units)
######   20 Fubuki class Destroyers (4 DD6 Destroyer units)
######    4 Akatsuki class Destroyers (1 DD6 Destroyer unit)
######    6 Hatsuharu class Destroyers (1 DD6 Destroyer unit)
######   10 Shiratsuyu class Destroyers under construction (2 DD6 Destroyer units)
######    3 Asashio class Destroyers under construction (1 DD7 Destroyer unit)
######
###### = 107 Destroyers (22 Destroyer units) in total (3 Destroyer units in construction)

######    Submarine :
######    2 L1/4 L2/3 L3/4 K3/3 K4/5 K5 class Submarines (4 SS2 Submarine units)
######    9 L4/1 KD1/1 KD2/4 KD3a/3 KD3b/3 KD4 class Submarines (4 SS3 Submarine units)
######    1 K6/5 J1/3 KD5/4 KD6a class Submarines (3 SS4 Submarine unit)
######    1 J2/1 K6/2 KD6a/2 KD6b class Submarines under construction (1 SS4 Submarine unit)
######    2 J3 class Submarines under construction (1 SS5 Submarine unit)
######
###### = 63 Submarines (13 Submarine units) in total (2 Submarine units in construction)

######   15 Battleships (2 ships in construction)
######    4 Battlecruisers
######    4 Fleet Carriers
######    3 Light Carriers
######   16 Heavy Cruisers
######   22 Destroyer flotillas (3 flotillas in construction)
######   28 Light Cruisers (4 ships in construction)
######   13 Submarine flotillas (2 flotillas in construction)
######   19 Transport flotillas

######  Below fictional naval OOB is partially based on datas from www.geocities.jp/boat_sparrowhawk

######  The First Fleet

	navalunit = {
        id = { type = 13016 id = 1001 }
        name = "Dai-1 Sentai"
        location = 1558
        base = 1558
        division = { id = { type = 13016 id = 1002 } name = "Nagato" type = battleship model = 5 }
        division = { id = { type = 13016 id = 1003 } name = "Mutsu" type = battleship model = 5 }
        }

	navalunit = {
        id = { type = 13016 id = 1004 }
        name = "Dai-2 Sentai"
        location = 1558
        base = 1558
        division = { id = { type = 13016 id = 1005 } name = "Kii" type = battleship model = 7 }
        division = { id = { type = 13016 id = 1006 } name = "Owari" type = battleship model = 7 }
        division = { id = { type = 13016 id = 1007 } name = "Tosa" type = battleship model = 6 }
        division = { id = { type = 13016 id = 1008 } name = "Kaga" type = battleship model = 6 }
        }

	navalunit = {
        id = { type = 13016 id = 1009 }
        name = "Dai-3 Sentai"
        location = 1558
        base = 1558
        division = { id = { type = 13016 id = 1010 } name = "Kongo" type = battlecruiser model = 1 }
        division = { id = { type = 13016 id = 1011 } name = "Hiei" type = battlecruiser model = 1 }
        division = { id = { type = 13016 id = 1012 } name = "Haruna" type = battlecruiser model = 1 }
        division = { id = { type = 13016 id = 1013 } name = "Kirishima" type = battlecruiser model = 1 }
        }

	navalunit = {
        id = { type = 13016 id = 1014 }
        name = "Dai-6 Sentai"
        location = 1558
        base = 1558
        division = { id = { type = 13016 id = 1015 } name = "Fuso" type = battleship model = 3 }
        division = { id = { type = 13016 id = 1016 } name = "Yamashiro" type = battleship model = 3 }
        division = { id = { type = 13016 id = 1017 } name = "Ise" type = battleship model = 3 }
        division = { id = { type = 13016 id = 1018 } name = "Hyuga" type = battleship model = 3 }
        }

	navalunit = {
        id = { type = 13016 id = 1019 }
        name = "Dai-8 Sentai"
        location = 1558
        base = 1558
        division = { id = { type = 13016 id = 1020 } name = "Kako" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1021 } name = "Ayase" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1022 } name = "Minase" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1023 } name = "Otonase" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1024 } name = "Kano" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1120 } name = "1. Yusosentai" type = transport model = 1 }
        division = { id = { type = 13016 id = 1121 } name = "2. Yusosentai" type = transport model = 1 }
        division = { id = { type = 13016 id = 1122 } name = "3. Yusosentai" type = transport model = 1 }
        division = { id = { type = 13016 id = 1123 } name = "4. Yusosentai" type = transport model = 1 }
        }

	navalunit = {
        id = { type = 13016 id = 1025 }
        name = "Dai-11 Sentai"
        location = 1558
        base = 1558
        division = { id = { type = 13016 id = 1026 } name = "Kuma" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1027 } name = "Nagara" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1028 } name = "Abukuma" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1124 } name = "5. Yusosentai" type = transport model = 1 }
        division = { id = { type = 13016 id = 1125 } name = "6. Yusosentai" type = transport model = 1 }
        }

	navalunit = {
        id = { type = 13016 id = 1029 }
        name = "Dai-1 Suiraisentai"
        location = 1558
        base = 1558
        division = { id = { type = 13016 id = 1030 } name = "Sendai" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1031 } name = "9. Kuchikutai" type = destroyer model = 5 }
        division = { id = { type = 13016 id = 1032 } name = "21. Kuchikutai" type = destroyer model = 5 }
        }

	navalunit = {
        id = { type = 13016 id = 1033 }
        name = "Dai-1 Sensuisentai"
        location = 1558
        base = 1558
        division = { id = { type = 13016 id = 1034 } name = "Isuzu" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1035 } name = "7. Sensuitai" type = submarine model = 3 }
        division = { id = { type = 13016 id = 1036 } name = "8. Sensuitai" type = submarine model = 3 }
        }

	navalunit = {
        id = { type = 13016 id = 1037 }
        name = "Dai-1 Kokusentai"
        location = 1558
        base = 1558
        division = { id = { type = 13016 id = 1038 } name = "Akagi" type = carrier model = 0 extra = cag brigade_model = 2 }
        division = { id = { type = 13016 id = 1039 } name = "Ryujo" type = light_carrier model = 0 extra = light_cag brigade_model = 2 }
        division = { id = { type = 13016 id = 1040 } name = "Hosho" type = escort_carrier model = 2 }
        division = { id = { type = 13016 id = 1041 } name = "30. Kuchikutai" type = destroyer model = 4 }
        division = { id = { type = 13016 id = 1042 } name = "31. Kuchikutai" type = destroyer model = 4 }
        }

######  The Second Fleet

	navalunit = {
        id = { type = 13016 id = 1043 }
        name = "Dai-4 Sentai"
        location = 1560
        base = 1560
        division = { id = { type = 13016 id = 1044 } name = "Takao" type = heavy_cruiser model = 4 }
        division = { id = { type = 13016 id = 1045 } name = "Atago" type = heavy_cruiser model = 4 }
        division = { id = { type = 13016 id = 1126 } name = "7. Yusosentai" type = transport model = 1 }
        division = { id = { type = 13016 id = 1127 } name = "8. Yusosentai" type = transport model = 1 }
        }

	navalunit = {
        id = { type = 13016 id = 1046 }
        name = "Dai-5 Sentai"
        location = 1560
        base = 1560
        division = { id = { type = 13016 id = 1047 } name = "Myoko" type = heavy_cruiser model = 4 }
        division = { id = { type = 13016 id = 1048 } name = "Haguro" type = heavy_cruiser model = 4 }
        division = { id = { type = 13016 id = 1049 } name = "Nachi" type = heavy_cruiser model = 4 }
        division = { id = { type = 13016 id = 1050 } name = "Ashigara" type = heavy_cruiser model = 4 }
        division = { id = { type = 13016 id = 1128 } name = "9. Yusosentai" type = transport model = 1 }
        division = { id = { type = 13016 id = 1129 } name = "10. Yusosentai" type = transport model = 1 }
        division = { id = { type = 13016 id = 1130 } name = "11. Yusosentai" type = transport model = 1 }
        division = { id = { type = 13016 id = 1131 } name = "12. Yusosentai" type = transport model = 1 }
        }

	navalunit = {
        id = { type = 13016 id = 1051 }
        name = "Dai-7 Sentai"
        location = 1560
        base = 1560
        division = { id = { type = 13016 id = 1052 } name = "Aoba" type = heavy_cruiser model = 3 }
        division = { id = { type = 13016 id = 1053 } name = "Kinugasa" type = heavy_cruiser model = 3 }
        division = { id = { type = 13016 id = 1132 } name = "13. Yusosentai" type = transport model = 1 }
        division = { id = { type = 13016 id = 1133 } name = "14. Yusosentai" type = transport model = 1 }
        }

	navalunit = {
        id = { type = 13016 id = 1054 }
        name = "Dai-9 Sentai"
        location = 1560
        base = 1560
        division = { id = { type = 13016 id = 1055 } name = "Maya" type = heavy_cruiser model = 4 }
        division = { id = { type = 13016 id = 1056 } name = "Chokai" type = heavy_cruiser model = 4 }
        division = { id = { type = 13016 id = 1134 } name = "15. Yusosentai" type = transport model = 1 }
        division = { id = { type = 13016 id = 1135 } name = "16. Yusosentai" type = transport model = 1 }
        }

	navalunit = {
        id = { type = 13016 id = 1057 }
        name = "Dai-2 Suiraisentai"
        location = 1560
        base = 1560
        division = { id = { type = 13016 id = 1058 } name = "Jintsu" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1059 } name = "7. Kuchikutai" type = destroyer model = 5 }
        division = { id = { type = 13016 id = 1060 } name = "8. Kuchikutai" type = destroyer model = 5 }
        division = { id = { type = 13016 id = 1061 } name = "19. Kuchikutai" type = destroyer model = 5 }
        division = { id = { type = 13016 id = 1062 } name = "20. Kuchikutai" type = destroyer model = 5 }
        }

	navalunit = {
        id = { type = 13016 id = 1063 }
        name = "Dai-2 Sensuisentai"
        location = 1560
        base = 1560
        division = { id = { type = 13016 id = 1064 } name = "Tama" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1065 } name = "12. Sensuitai" type = submarine model = 2 }
        division = { id = { type = 13016 id = 1066 } name = "29. Sensuitai" type = submarine model = 3 }
        division = { id = { type = 13016 id = 1067 } name = "30. Sensuitai" type = submarine model = 2 }
        }

	navalunit = {
        id = { type = 13016 id = 1068 }
        name = "Dai-2 Kokusentai"
        location = 1560
        base = 1560
        division = { id = { type = 13016 id = 1069 } name = "Shokaku" type = carrier model = 1 extra = cag brigade_model = 2 }
        division = { id = { type = 13016 id = 1070 } name = "Zuikaku" type = carrier model = 1 extra = cag brigade_model = 2 }
        division = { id = { type = 13016 id = 1071 } name = "22. Kuchikutai" type = destroyer model = 4 }
        division = { id = { type = 13016 id = 1072 } name = "24. Kuchikutai" type = destroyer model = 4 }
        }

	navalunit = {
        id = { type = 13016 id = 1073 }
        name = "Dai-3 Suiraisentai"
        location = 1558 #Maizuru
        base = 1558
        division = { id = { type = 13016 id = 1074 } name = "Kitakami" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1075 } name = "11. Kuchikutai" type = destroyer model = 3 }
        division = { id = { type = 13016 id = 1076 } name = "23. Kuchikutai" type = destroyer model = 3 }
        }

######  The Third Fleet

	navalunit = {
        id = { type = 13016 id = 1077 }
        name = "Dai-10 Sentai"
        location = 1361
        base = 1361
        division = { id = { type = 13016 id = 1078 } name = "Furutaka" type = heavy_cruiser model = 3 }
        division = { id = { type = 13016 id = 1079 } name = "Tate" type = heavy_cruiser model = 3 }
        division = { id = { type = 13016 id = 1136 } name = "17. Yusosentai" type = transport model = 1 }
        }

	navalunit = {
        id = { type = 13016 id = 1080 }
        name = "Dai-12 Sentai"
        location = 1361
        base = 1361
        division = { id = { type = 13016 id = 1081 } name = "Kamoi" type = escort_carrier model = 0 }
        division = { id = { type = 13016 id = 1082 } name = "14. Kuchikutai" type = destroyer model = 3 }
        }

	navalunit = {
        id = { type = 13016 id = 1083 }
        name = "Dai-13 Sentai"
        location = 1361
        base = 1361
        division = { id = { type = 13016 id = 1084 } name = "Natori" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1085 } name = "Kinu" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1086 } name = "Yura" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1137 } name = "18. Yusosentai" type = transport model = 1 }
        division = { id = { type = 13016 id = 1138 } name = "19. Yusosentai" type = transport model = 1 }
        }

	navalunit = {
        id = { type = 13016 id = 1087 }
        name = "Dai-3 Kokusentai"
        location = 1361
        base = 1361
        division = { id = { type = 13016 id = 1088 } name = "Notoro" type = escort_carrier model = 0 }
        division = { id = { type = 13016 id = 1089 } name = "28. Kuchikutai" type = destroyer model = 3 }
        }

	navalunit = {
        id = { type = 13016 id = 1090 }
        name = "Dai-3 Sensuisentai"
        location = 1361
        base = 1361
        division = { id = { type = 13016 id = 1091 } name = "Oi" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1092 } name = "2. Sensuitai" type = submarine model = 2 }
        division = { id = { type = 13016 id = 1093 } name = "9. Sensuitai" type = submarine model = 2 }
        division = { id = { type = 13016 id = 1094 } name = "10. Sensuitai" type = submarine model = 1 }
        }

	navalunit = {
        id = { type = 13016 id = 1095 }
        name = "Dai-4 Sensuisentai"
        location = 1361
        base = 1361
        division = { id = { type = 13016 id = 1096 } name = "Naka" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1097 } name = "17. Sensuitai" type = submarine model = 1 }
        division = { id = { type = 13016 id = 1098 } name = "20. Sensuitai" type = submarine model = 1 }
        division = { id = { type = 13016 id = 1099 } name = "32. Sensuitai" type = submarine model = 1 }
        }

	navalunit = {
        id = { type = 13016 id = 1100 }
        name = "Dai-4 Suiraisentai"
        location = 1361
        base = 1361
        division = { id = { type = 13016 id = 1101 } name = "Kiso" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1102 } name = "6. Kuchikutai" type = destroyer model = 4 }
        division = { id = { type = 13016 id = 1103 } name = "10. Kuchikutai" type = destroyer model = 4 }
        division = { id = { type = 13016 id = 1104 } name = "12. Kuchikutai" type = destroyer model = 4 }
        }

	navalunit = {
        id = { type = 13016 id = 1105 }
        name = "Dai-5 Suiraisentai"
        location = 1361
        base = 1361
        division = { id = { type = 13016 id = 1106 } name = "Yubari" type = light_cruiser model = 3 }
        division = { id = { type = 13016 id = 1107 } name = "13. Kuchikutai" type = destroyer model = 3 }
        division = { id = { type = 13016 id = 1108 } name = "16. Kuchikutai" type = destroyer model = 3 }
        }

######  The Reserve/Training Fleet

	navalunit = {
        id = { type = 13016 id = 1139 }
        name = "Renshukantai"
        location = 1552
        base = 1552
        division = { id = { type = 13016 id = 1109 } name = "Settsu" type = battleship model = 2 }
        division = { id = { type = 13016 id = 1110 } name = "Satsuma" type = battleship model = 1 }
        division = { id = { type = 13016 id = 1111 } name = "Aki" type = battleship model = 1 }
        division = { id = { type = 13016 id = 1112 } name = "Yakumo" type = heavy_cruiser model = 1 }
        division = { id = { type = 13016 id = 1113 } name = "Izumo" type = heavy_cruiser model = 1 }
        division = { id = { type = 13016 id = 1114 } name = "Asama" type = heavy_cruiser model = 1 }
        division = { id = { type = 13016 id = 1115 } name = "Iwate" type = heavy_cruiser model = 1 }
        division = { id = { type = 13016 id = 1116 } name = "Hirado" type = light_cruiser model = 1 }
        division = { id = { type = 13016 id = 1117 } name = "Yahagi" type = light_cruiser model = 1 }
        division = { id = { type = 13016 id = 1118 } name = "Tenryu" type = light_cruiser model = 2 }
        division = { id = { type = 13016 id = 1119 } name = "Tatsuta" type = light_cruiser model = 2 }
        }

#### Under division_development

    division_development = {  
        name  = "Omi" 
        type  = battleship
        model = 7 
        cost  = 0.1
        id    = {  type = 13016 id = 1140  } 
        date  = {  year = 1936 month = may day = 7  } 
        new_model = no
    }
    division_development = {  
        name  = "Suruga" 
        type  = battleship
        model = 7 
        cost  = 0.1
        id    = {  type = 13016 id = 1141  } 
        date  = {  year = 1936 month = september day = 20  } 
        new_model = no
    }
    division_development = {  
        name  = "Mogami"
        type  = light_cruiser
        model = 5
        cost  = 0.1
        id    = { type = 13016 id = 1142 }
        date  = { year = 1937 month = october day = 1 }
        new_model = no
    }
    division_development = {  
        name  = "Mikuma"
        type  = light_cruiser
        model = 5
        cost  = 0.1
        id    = { type = 13016 id = 1143 }
        date  = { year = 1937 month = october day = 30 }
        new_model = no
    }
    division_development = {  
        name  = "Suzuya"
        type  = light_cruiser
        model = 5
        cost  = 0.1
        id    = { type = 13016 id = 1144 }
        date  = { year = 1937 month = november day = 20 }
        new_model = no
    }
    division_development = {  
        name  = "Kumano"
        type  = light_cruiser
        model = 5
        cost  = 0.1
        id    = { type = 13016 id = 1145 }
        date  = { year = 1938 month = may day = 20 }
        new_model = no
    }
    division_development = {
        name  = "3. Kuchikutai" 
        type  = destroyer 
        model = 5
        cost  = 0.1
        id    = {  type = 13016 id = 1146  } 
        date  = {  year = 1936 month = august day = 20  } 
        new_model = no
    }
    division_development = {
        name  = "4. Kuchikutai" 
        type  = destroyer 
        model = 5
        cost  = 0.1
        id    = {  type = 13016 id = 1147  } 
        date  = {  year = 1937 month = january day = 7  } 
        new_model = no
    }
    division_development = {
        name  = "15. Kuchikutai" 
        type  = destroyer 
        model = 6
        cost  = 0.1
        id    = {  type = 13016 id = 1148  } 
        date  = {  year = 1937 month = april day = 1  } 
        new_model = no
    }
    division_development = {
        name  = "11. Sensuitai" 
        type  = submarine
        model = 3
        cost  = 0.1
        id    = {  type = 13016 id = 1149  } 
        date  = {  year = 1936 month = august day = 1  } 
        new_model = no
    }
    division_development = {
        name  = "13. Sensuitai" 
        type  = submarine
        model = 4
        cost  = 0.1
        id    = {  type = 13016 id = 1150  } 
        date  = {  year = 1936 month = november day = 1  } 
        new_model = no
    }
    division_development = {
        name  = "Kisarazu Kokutai" 
        type  = naval_bomber
        model = 2
        cost  = 0.1
        id    = {  type = 13016 id = 1151 } 
        date  = {  year = 1936 month = april day = 1  } 
        new_model = no
    }

	transports = 560
	escorts = 140

}