country = {
    tag = UPE
	#ai = "kaiserreich\Yunnan.ai"


	policy = {
		date = { year = 0 month = january day = 0 }
		democratic = 3
		political_left = 3
		freedom = 3
		free_market = 6
		professional_army = 4
		defense_lobby = 7
		interventionism = 5
		}

#### cabinet (starting Sun Chuanfang)
headofstate = { type = 9 id = 100030 } #Sun Chuanfang
headofgovernment = { type = 9 id = 100066 } #Yang Wenkai
foreignminister = { type = 9 id = 100106 } #Wei Daofeng
armamentminister = { type = 9 id = 100184 } #Yu Dawei
ministerofsecurity = { type = 9 id = 100217 } #Chen Taoyi
ministerofintelligence = { type = 9 id = 100263 } #Xiang Xiongxiao
chiefofstaff = { type = 9 id = 100293 } #Wang Geng
chiefofarmy = { type = 9 id = 100031 } #Sun Chuanfang
chiefofnavy = { type = 9 id = 100351 } #Yang Shuzhuang
chiefofair = { type = 9 id = 100301 } #Xu Peigen
	#possible successor warlord gov (anti-concessionist)
	#headofstate = { type = 9 id = 100032 } #Chen Tiaoyuan
	#headofgovernment = { type = 9 id = 100056 } #Wang Pu
	#foreignminister = { type = 9 id = 100091 } #Jiang Zuobin
	#armamentminister = { type = 9 id = 100184 } #Yu Dawei
	#ministerofsecurity = { type = 9 id = 100217 } #Chen Taoyi
	#ministerofintelligence = { type = 9 id = 100168 } #Cheng Xiaogang (Zhao Zhiyao [100180] also an option)
	#chiefofstaff = { type = 9 id = 100293 } #Wang Geng
	#chiefofarmy = { type = 9 id = 100033 } #Chen Tiaoyuan
	#chiefofnavy = { type = 9 id = 100347 } #Li Shijia
	#chiefofair = { type = 9 id = 100301 } #Xu Peigen
	#possible successor warlord gov (pro-japanese)
	#headofstate = { type = 9 id = 100034 } #Qi Xieyuan
	#headofgovernment = { type = 9 id = 100061 } #Chen Yi
	#foreignminister = { type = 9 id = 100093 } #Xu Shiying (Jiang Hongjie [100356] also an option)
	#armamentminister = { type = 9 id = 100177 } #Chen Wei
	#ministerofsecurity = { type = 9 id = 100243 } #Ren Yuandao (Wang Tianmu [100244] also an option)
	#ministerofintelligence = { type = 9 id = 100263 } #Xiang Xiongxiao
	#chiefofstaff = { type = 9 id = 100289 } #Ge Jingen (Lin Wei [100295] also an option)
	#chiefofarmy = { type = 9 id = 100063 } #Chen Yi (Tang Enbo [100334] also an option)
	#chiefofnavy = { type = 9 id = 100356 } #Jiang Hongjie
	#chiefofair = { type = 9 id = 100301 } #Xu Peigen
	#possible successor Socdem gov (CDL + CDNCA figures)
	#headofstate = { type = 9 id = 502001 } #
	#headofgovernment = { type = 9 id = 502002 } #
	#foreignminister = { type = 9 id = 579004 } #
	#armamentminister = { type = 9 id = 579008 } #
	#ministerofsecurity = { type = 9 id = 579011 } #
	#ministerofintelligence = { type = 9 id = 579012 } #
	#chiefofstaff = { type = 9 id = 579015 } #
	#chiefofarmy = { type = 9 id = 579018 } #
	#chiefofnavy = { type = 9 id = 100341 } #Wang Shouting
	#chiefofair = { type = 9 id = 100364 } #Chen Yibai (Li Mingyang [100334] also an option)
	#possible successor Lib-dem gov
	#headofstate = { type = 9 id = 100020 } #Guo Bingwen 
	#headofgovernment = { type = 9 id = 100051 } #Wu Yifang
	#foreignminister = { type = 9 id = 100086 } #Jin Wensi (Wu Yifang [100052] also an option)
	#armamentminister = { type = 9 id = 100160 } #Li Ming (Zhou Yichun [100143] also an option)
	#ministerofsecurity = { type = 9 id = 100212 } #Jiang Menglin (Tao Xingzhi [100211] also an option)
	#ministerofintelligence = { type = 9 id = 100258 } #Pan Xulun
	#chiefofstaff = { type = 9 id = 100281 } #Li Erkang
	#chiefofarmy = { type = 9 id = 100277 } #Li Mingyang (Fan Songfu [100311] also an option)
	#chiefofnavy = { type = 9 id = 100341 } #Wang Shouting
	#chiefofair = { type = 9 id = 100366 } #Zhu Lin
	#possible successor RKMT gov (CC Clique + Sun Wenist officers)
	#headofstate = { type = 9 id = 100022 } #Lin Sen (Tao Xingzhi [100211] also an option), maybe Dai Jitao [100036] for a far-right version
	#headofgovernment = { type = 9 id = 100057 } #Chen Guofu, another possibility is Wu Zhongxin [100059]
	#foreignminister = { type = 9 id = 100083 } #Guo Taiqi, another possibility is Wu Zhongxin [100060], maybe Miao Bin [100101] for a far-right version
	#armamentminister = { type = 9 id = 100141 } #Zhao Dihua, other possibilities are Chen Qicai [100157] or Fu Rulin [100164]
	#ministerofsecurity = { type = 9 id = 100219 } #Ju Zheng, other possibilities are Ye Chucang [100227] or Li Shizhen [100230], maybe Ding Mocun [100245] for a far-right version
	#ministerofintelligence = { type = 9 id = 100026 } #Chen Lifu, other possibilities are Hu Jingan [100097] or Xu Enzeng [100265], maybe Ding Mocun [100245] for a far-right version
	#chiefofstaff = { type = 9 id = 100299 } #Liu Zhi
	#chiefofarmy = { type = 9 id = 100326 } #Hu Zongnan
	#chiefofnavy = { type = 9 id = 100352 } #Chen Zhaoying
	#chiefofair = { type = 9 id = 100368 } #Huang Bingheng
#### Resource Reserves
	energy = 200
	metal = 200
	rare_materials = 100
	oil = 100
	supplies = 100
	money = 50
	capital = 1337 #Nanjing
	manpower = 200

	free = { ic = 10 }

SpyInfo  = { country = "UPE" NumberOfSpies = 5 }

    ownedprovinces =      {
 1337 1347 1348 1345 1340 1343 1344 1350 1342 1318 1353 1354 1355 1349 1352 1351
	 }
    controlledprovinces = {
 1337 1347 1348 1345 1340 1343 1344 1350 1342 1318 1353 1354 1355 1349 1352 1351
	  }
    nationalprovinces =   {
 1337 1347 1348 1345 1340 1343 1344 1350 1342 1318 1353 1354 1355 1349 1352 1351 1346
	}

diplomacy = {
relation = { tag = EAF value = -100  } 
relation = { tag = GER value = 50 }
relation = { tag = CGX value = 50 }
relation = { tag = JAP value = -75 }
relation = { tag = MAN value = -75 }
relation = { tag = MEN value = -75 }
relation = { tag = CYN value = 25 }
relation = { tag = CSX value =  25 }
relation = { tag = UCH value = -100 }
relation = { tag = UCS value = -50 }
relation = { tag = UGS value = 50 }
}

dormant_teams = { 4739 } #Kuang Yumin (CCP artillery team)

	techapps = {

# Group E 1936 techs
#######################

#Armor and Artillery
7600 7610 2620 #SW Tank
2860 2870 2880 #1921 Armored Car
2290 2300 2310 2900 2910 2920 #1924 Artillery
2800 2450 21180 #1924 Static Anti-Air Artillery
2810 2820 #AA Brigade 1924

#Infantry
1010 1020 1030 1040 1050 1060 1070 1080 #1926 Infantry
1160 1170 1180 1190 1200 1210 1220 #1921 Mountain Infantry
1830 1840 1850 #1921 Engineering Brigade
13060 13070 13080 1310 1320 1330 1340 1350 #1924 Cavalry
1910 1920 1930 1940 1950 1960 1970 #1924 Logistics

#Industrial 
5810 5820 5050 #Production 1920
5800 5080 #Construction 1910
5310 54010 #Automatic feed tabulator
5316 #Ciphering Machine
5700 5710 5010 #Modern Agriculture
5190 #Basic Oil Refining
5600 5610 #Indirect Blood transfusions

#Aircrafts
4500 4510 4520 4530 4540 #Interceptor 1917
4300 4310 #Multi-Role 1917
7290 7300 #CAS 1917
4600 4610 4620 4630 #Tactical Bomber 1918
4700 #Naval Bomber 1918
4740 4750 #Seaplane 1914

# Land Doctrines WWI - Entente line
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6680 6540 6910

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470

#Naval
3010 3020 3030 3040 #Weltkrieg Destroyer
3110 3120 3130 #Early Light Cruiser
3810 3820 #Troopship 25
3720 3730 #Basic Torpedo

#Naval Doctrines
8010 8020 8050 8060 8070 8080 8100 8110 #Coastal Defense
	}
}