


country = {
    tag = VIC
ai = "kaiserreich\Nationalist France.ai"
	policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 4
        political_left = 2
        freedom = 3
        free_market = 6
        professional_army = 7
        defense_lobby = 7
        interventionism = 6
    }


#### cabinet
	headofstate = { type = 9 id = 57001 } #Phillipe Petain
	headofgovernment = { type = 9 id = 57242 } #Louis Franchet d'Esperey
	foreignminister = { type = 9 id = 57147 } #Edouard de Castelnau
	armamentminister = { type = 9 id = 57023 } #Paul Painleve
	ministerofsecurity = { type = 9 id = 57080 } #Theodore Steeg
	ministerofintelligence = { type = 9 id = 57212 } #Louis Rivet
	chiefofstaff = { type = 9 id = 57223 } #Alphonse Georges
	chiefofarmy = { type = 9 id = 57232 } #Henri Giraud
	chiefofnavy = { type = 9 id = 57093 } #Georges Durand-Viel
	chiefofair = { type = 9 id = 57050 } #Jean Mermoz

#### Resource Reserves

SpyInfo  = {  country = "VIC" NumberOfSpies = 4  } 

	capital = 727 
manpower = 28
energy	=	1000  
metal	= 1000		
rare_materials =	500	
oil =	500	
supplies =	500
money = 10
transports = 40


    ownedprovinces =      {
			729 733 728 730 727 732 736 731 734 735 743 740 741 742 744 745 747 748 746 749 739 737 986 985 738 984
                        943 946 921 922 944 947 981 982 978 983 977 979 980 966 975 965 971 976 942 945 957 958 974 967 972 973
                        962 968 970 960 961 959
	 }
    controlledprovinces = {
			729 733 728 730 727 732 736 731 734 735 743 740 741 742 744 745 747 748 746 749 739 737 986 985 738 984
                        943 946 921 922 944 947 981 982 978 983 977 979 980 966 975 965 971 976 942 945 957 958 974 967 972 973
                        962 968 970 960 961 959
	  }
    nationalprovinces =   {
			729 733 728 730 727 732 736 731 734 735 743 740 741 742 744 745 747 748 746 749 739 737 986 985 738 984
                        943 946 921 922 944 947 981 982 978 983 977 979 980 966 975 965 971 976 942 945 957 958 974 967 972 973
                        962 968 970 960 961 959
	}
    claimedprovinces = {  37 38 39 40 78 41 42 43 44 45 46 47 48 55 53 50 49 51 52 56 101 103 100 102 99 54 95 97
                98 88 64 63 66 60 58 59 57 62 70 69 68 67 83 84 75 73 72 61 65 90 86 89 93 82 79 80 76 77
                71 81 92 85 74   }

diplomacy = {
relation = {   tag =    BEL	value = 		-20	   }  
relation = {   tag =  	BLR	 value =		-30	   }  
relation = {   tag =  	BUL	value = 		-20	   }  
relation = {   tag =  	GER	 value =		-100	   }  
relation = {   tag =  	LAT	value = 		-40	   }  
relation = {   tag =  	LIT	 value =		-20	   }  
relation = {   tag =  	POL	value = 		30	   }  
relation = {   tag =  	UKR	 value =		-10	   }  
relation = {   tag =  	AUS	value = 		-90	   }  
relation = {   tag =  	BOS	value = 		-40	   }  
relation = {   tag =  	CZE	value = 		-30	   }  
relation = {   tag =  	HUN	 value =		-30	   }  
relation = {   tag =  	ALB	value = 		-20	   }  
relation = {   tag =  	DEN	 value =		20	   }  
relation = {   tag =  	GRE	value = 		-10	   }  
relation = {   tag =  	HOL	 value =		50	   }  
relation = {   tag =  	IRE	value = 		-30	   }  
relation = {   tag =  	ITA	value = 		80	   }  
relation = {   tag =  	POR	value = 		90	   }  
relation = {   tag =  	ROM	value = 		40	   }  
relation = {   tag =  	SER	value = 		40	   }  
relation = {   tag =  	SPA	value = 		80	   }  
relation = {   tag =  	ENG	value = 		-100	   }  
relation = {   tag =  	FRA	value = 		-180	   }  
relation = {   tag =  	RSI	 value =		-120	   }  
relation = {   tag =  	AST	value = 		170	   }  
relation = {   tag =  	CAN	value = 		170	   }  
relation = {   tag =  	PAK	value = 		170	   }  
relation = {   tag =  	GUY	value = 		170	   }  
relation = {   tag =  	RUS	 value =		50	   }  
relation = {   tag =  	EGY	 value =		30	   }  
relation = {   tag =  	LBY	value = 		50	   }  
relation = {   tag =  	OTT	 value =		-90	   }  
relation = {   tag =  	PER	value = 		50	   }  
relation = {   tag =  	SAU	value = 		30	   }  
relation = {   tag =  	YEM	value = 		30	   }  
relation = {   tag =  	CON	value = 		-40	   }  
relation = {   tag =  	ETH	value = 		10	   }  
relation = {   tag =  	LIB	 value =		20	   }  
relation = {   tag =  	SAF	value = 		60	   }  
relation = {  tag =   	USA	value = 		45	 }
relation = {   tag =  	JAP	value = 		50	   }  
}


	
	techapps = {
# FRA 1936 techs
#######################

#Infantry
1010 1020 1030 1040 1050 1060 1070 1080 1090 #interwar Infantry Division
13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380 #1936 Cavalry
1160 1170 1180 1190 1200 1210 1220 1230 1240 #Early Mountain Division
1910 1920 1930 1940 1950 1960 1970 1980 #Up to IW Supply 1930
1830 1840 1850 #Engineers
1396 #Motorized Divisions
1560 # Naval infantry

#Aircrafts
4500 4510 4520 4530 4540 4550 4010 4020 #Interceptor 1930
4300 4310 4320 4330 #Multi-Role 1926
4600 4610 4620 4630 4120 4130 #Tac Bomber 1932
4700 4710 #Nav Bomber 1924
4800 4810 4820 #Strat Bomber 1930
7290 7300 7310 7320 #CAS 1922
4740 4750 4760 4770 4780 4790 #Seaplane 1932
4900 4910 #CAG 1930
4290 #Trans Plane 1926

#Armour & Artillery
2860 2870 2880 2020 #Armd Cars 1929
2620 2010 2630 2640 2646 #Tank 1928
2290 2300 2310 2900 2910 2920 2930 #Artillery 1930
2800 2450 21180 21190 21200 #Anti-Air 1935
2810 2820 2510 #AA Brigade 1930
2400 #Anti-Tank 1935

#Secret Weapons (for tanks only)
7600 7610 #Tank experiments

#Industrial
5810 5820 5050 5830 #Production 1925
5700 5710 5010 5020 #Mechanized Agriculture
5600 5610 5620 5630 #Medicine
5800 5080 5090 #Improved Construction Engineering
5190 #Basic Oil Refining
5310 54010 54020 54030 5316 5326 #Computers & cryptography

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010

# Great War Land Doctrines
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6680 6540 6910
6390 6400 6420 #Light Infantry (French colonial army)
14000 14010 #Improved Great War Hospital System

#Naval Doctrines
8010 8020 8040 8050 8030 8060 8070 8080 #Basic Theories
8100 8110 8120 8150 8160 8170 8200 8210 #Naval supremacy
8500 8510 8520 8550 8560 8570 #Naval Interdiction
81300 81310 81320 81330 81340 81350 #Indirect Approach
82500 #Fuel Oil Logistics
82300 #Basic Amphib Warfare

#Naval
3010 3020 3030 3040 3050 #1923 DD
3110 3120 3130 3140 #1922 Light Cruiser
3210 3220 3230 3240 #1922 Heavy Cruiser
3310 3320 3330 3340 #Interwar Battlecruiser
3410 3420 3430 3440 3450 3456 #Early Battleship
3610 3620 3630 3640 #Interwar Submarine
12100 12110 12120 #Early Light Carrier
3720 3730 3736 3740 3750 3900 #Torpedo & ASW 18
3810 3820 #Troopships


	}

dormant_teams = { 6641 6652 6657 6659 6662 }

#########  OOB (...)



landunit = {
		id = { type = 13500 id = 8 }
		name = "1ère Armée"
		location = 727

			division = {
			id = { type = 13500 id = 9 }
			name = "1ère Div. Légère Motorisée"
			type = infantry
			model = 8
			extra = armored_car
			brigade_model = 2
			}

			division = {
			id = { type = 13500 id = 10 }
			name = "1ère Division d'Infanterie"
			type = infantry
			model = 7
			extra = anti_tank
			brigade_model = 2
			}

			division = {
			id = { type = 13500 id = 11 }
			name = "2ème Division motorizee de Réserve"
			type = motorized
			model = 0
			extra = anti_tank
			brigade_model = 2
			}

			division = {
			id = { type = 13500 id = 15 }
			name = "12ème Div. d'Infanterie Motorisée"
			type = infantry
			model = 7
			extra = armored_car
			brigade_model = 2
			}

			division = {
			id = { type = 13500 id = 17 }
			name = "2ème Div. d'Infanterie Nord-Africaine"
			type = infantry
			model = 7
			extra = anti_tank
			brigade_model = 2
			}
			}

landunit = {
		id = { type = 13500 id = 20 }
		name = "Légion étrangère"
		location = 747 #Tunisia, to not having them all concentrated at Algiers

			division = {
			id = { type = 13500 id = 21 }
			name = "1er RE"
			type = d_01
			model = 7
			}
	}
landunit = {
		id = { type = 13500 id = 22 }
		name = "Garnison d'Algiers"
		location = 727
			division = {
			id = { type = 13500 id = 23 }
			name = "Garnison d'Algiers"
			type = garrison
			model = 3
			strength = 30
			max_strength = 30
			locked = yes
			}
	}
landunit = {
		id = { type = 13500 id = 24 }
		name = "Garnison d'Tunisia"
		location = 747
			division = {
			id = { type = 13500 id = 25 }
			name = "Garnison d'Tunisia"
			type = garrison
			model = 3
			strength = 30
			max_strength = 30
			locked = yes
			}
	}
landunit = {
		id = { type = 13500 id = 26 }
		name = "Garnison d'Dakar"
		location = 978
			division = {
			id = { type = 13500 id = 27 }
			name = "Garnison d'Dakar"
			type = garrison
			model = 3
			strength = 30
			max_strength = 30
			locked = yes
			}
	}
landunit = {
		id = { type = 13500 id = 28 }
		name = "Garnison d'Abidjan"
		location = 962
			division = {
			id = { type = 13500 id = 29 }
			name = "Garnison d'Abidjan"
			type = garrison
			model = 3
			strength = 30
			max_strength = 30
			locked = yes
			}
	}
landunit = {
		id = { type = 13500 id = 30 }
		name = "Garnison d'Oran"
		location = 728
			division = {
			id = { type = 13500 id = 31 }
			name = "Garnison d'Oran"
			type = garrison
			model = 3
			strength = 30
			max_strength = 30
			locked = yes
			}
	}

landunit = {
location = 747  #### Tunis
name = "Ième Corps d'Armée"
      id = { type = 13500 id = 32  }

  division = {
  id = { type = 13500 id = 33  }
  name = "1ère Div. d'Infanterie de Marine"
  type = marine
  model = 0
  strength = 60
  }
}

airunit = {
	location = 727
	base = 727
	id = { type = 13500 id = 218 }
	name = "4ème Groupe de Bombardement"

	division = { id = { type = 13500 id = 219 } name = "Groupe de Bombardement Tactique 6" strength = 100 type = tactical_bomber model = 5 }
	}
airunit = {
	location = 747
	base = 747
	id = { type = 13500 id = 220 }
	name = "1éme Groupe de chasse"
	division = {
		id = { type = 13500 id = 221 }
		name = "Groupe de chasse 1"
		strength = 100
		type = interceptor
		model = 7
		}
	}
airunit = {
	location = 736
	base = 736
	id = { type = 13500 id = 228 }
	name = "2éme Groupe de chasse"
	division = {
		id = { type = 13500 id = 229 }
		name = "Groupe de chasse 2"
		strength = 100
		type = interceptor
		model = 7
		}
	}

navalunit = {
 name = "1ere Flotte, Capital"
 id = { type = 13501 id = 300 }
 location = 727 #### [Algerie]
 base = 727

 division = { id = { type = 13501 id = 301 } name = "Bretagne" type = battleship model = 3 }
 division = { id = { type = 13501 id = 302 } name = "Provence" type = battleship model = 3 }
 division = { id = { type = 13501 id = 303 } name = "Lorraine" type = battleship model = 3 }
 division = { id = { type = 13501 id = 304 } name = "Foudre" type = escort_carrier model = 0 }
 division = { id = { type = 13501 id = 305 } name = "Courbet" type = battleship model = 2 }
 division = { id = { type = 13501 id = 306 } name = "Jean Bart" type = battleship model = 2 }
 division = { id = { type = 13501 id = 307 } name = "Paris" type = battleship model = 2 }
 division = { id = { type = 13501 id = 308 } name = "Condorcet" type = battleship model = 2 }
 division = { id = { type = 13501 id = 309 } name = "Diderot" type = battleship model = 2 }
 division = { id = { type = 13501 id = 310 } name = "Mirabeau" type = battleship model = 2 }
 division = { id = { type = 13501 id = 311 } name = "Vergniaud" type = battleship model = 2 }
 division = { id = { type = 13501 id = 312 } name = "Voltaire" type = battleship model = 2 }
 division = { id = { type = 13501 id = 313 } name = "France" type = battleship model = 2 }
 division = { id = { type = 13862 id = 427 } name = "Diderot" type = heavy_cruiser model = 2 }
 division = { id = { type = 13501 id = 316 } name = "DD. 1" type = destroyer model = 3 }
 division = { id = { type = 13501 id = 321 } name = "DD. 2" type = destroyer model = 3 }
 division = { id = { type = 13501 id = 326 } name = "DD. 3" type = destroyer model = 3 }
 division = { id = { type = 13501 id = 347 } name = "DD. 4" type = destroyer model = 3 }
 division = { id = { type = 13501 id = 352 } name = "DD. 5" type = destroyer model = 2 }
 division = { id = { type = 13501 id = 357 } name = "DD. 6" type = destroyer model = 2 }
 division = { id = { type = 13501 id = 368 } name = "DD. 7" type = destroyer model = 2 }
 division = { id = { type = 13501 id = 375 } name = "DD. 8" type = destroyer model = 2 }
 division = { id = { type = 13501 id = 381 } name = "DD. 9" type = destroyer model = 2 }
 division = { id = { type = 13501 id = 387 } name = "DD. 10" type = destroyer model = 2 }
 division = { id = { type = 13501 id = 393 } name = "DD. 11" type = destroyer model = 2 }
 division = { id = { type = 13501 id = 399 } name = "DD. 12" type = destroyer model = 2 }
 }

 navalunit = {
 name = "10eme Flotte, Transport du Réserve"
 id = { type = 13501 id = 405 }
 location = 728 #### [Oran]
 base = 728
 division = { id = { type = 13501 id = 406 } name = "TP. 1" type = transport model = 1 }
 division = { id = { type = 13501 id = 407 } name = "TP. 2" type = transport model = 1 }
 division = { id = { type = 13501 id = 408 } name = "TP. 3" type = transport model = 1 }
 division = { id = { type = 13501 id = 409 } name = "TP. 4" type = transport model = 1 }
 division = { id = { type = 13501 id = 410 } name = "TP. 5" type = transport model = 1 }
 division = { id = { type = 13501 id = 411 } name = "TP. 6" type = transport model = 1 }
 division = { id = { type = 13501 id = 412 } name = "TP. 7" type = transport model = 1 }
 }


 navalunit = {
 name = "11eme Sub Flotte"
 id = { type = 13501 id = 413 }
 location = 978 #### [Dakar]
 base = 978

 division = { id = { type = 13501 id = 417 } name = "S. 1." type = submarine model = 1 }
 division = { id = { type = 13501 id = 418 } name = "S. 2." type = submarine model = 1 }
 division = { id = { type = 13501 id = 425 } name = "S. 3." type = submarine model = 1 }
 }

 navalunit = {
 name = "2ere Flotte, Cruiser Reserve"
 id = { type = 13501 id = 426 }
 location = 727 #### [Algerie]
 base = 727


 division = { id = { type = 13862 id = 428 } name = "Bergerac" type = light_cruiser model = 2 }
 division = { id = { type = 13862 id = 429 } name = "Nantes" type = light_cruiser model = 2 }
 division = { id = { type = 13501 id = 370 } name = "Jurien de la Graviere" type = light_cruiser model = 1 }

 } 

# Gamelin's Armée de Libération

  landdivision = {
  dormant = yes
  id = { type = 13501 id = 434  }
  name = "10ème Division d'Infanterie"
  type = infantry
  model = 8
  strength = 100
  }

  landdivision = {
  dormant = yes
  id = { type = 13501 id = 427  }
  name = "11ème Division d'Infanterie"
  type = infantry
  model = 8
  strength = 100
  }

  landdivision = {
  dormant = yes
  id = { type = 13501 id = 428  }
  name = "12ème Division d'Infanterie"
  type = infantry
  model = 8
  strength = 100
  }

  landdivision = {
  dormant = yes
  id = { type = 13501 id = 429  }
  name = "13ème Division d'Infanterie"
  type = infantry
  model = 8
  strength = 100
  }

  landdivision = {
  dormant = yes
  id = { type = 13501 id = 430 }
  name = "1ère Division Légère Mécanisée"
  type = cavalry
  model = 9
  strength = 100
  extra = light_armor_brigade
  brigade_model = 3
  }

  landdivision = {
  dormant = yes
  id = { type = 13501 id = 431  }
  name = "2ème Division Légère Mécanisée"
  type = cavalry
  model = 9
  strength = 100
  extra = light_armor_brigade
  brigade_model = 3
  }

  landdivision = {
  dormant = yes
  id = { type = 13501 id = 432  }
  name = "3ème Division Légère Mécanisée"
  type = cavalry
  model = 9
  strength = 100
  extra = light_armor_brigade
  brigade_model = 3
  }

  landdivision = {
  dormant = yes
  id = { type = 13501 id = 433  }
  name = "4ème Division Légère Mécanisée"
  type = cavalry
  model = 9
  strength = 100
  extra = light_armor_brigade
  brigade_model = 3
  }






 }