


country = {
    tag = OTT  
ai = "kaiserreich\Ottoman.ai"

	policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 4
        political_left = 3
        freedom = 4
        free_market = 6
        professional_army = 5
        defense_lobby = 6
        interventionism = 4
    }

peacetime_ic_mod = 0.85

#### cabinet

headofstate = { type = 9 id = 549001 }

headofgovernment = { type = 9 id = 549082  }

#### Resource Reserves

	energy	=	1000   metal	= 1000		rare_materials =	500	oil =	500	supplies =	500
	money = 20      

        SpyInfo  = {  country = "OTT" NumberOfSpies = 4  } 

	manpower = 165
	capital = 409
        dissent = 23

    ownedprovinces =      {
	409 384 385 1076 1077 1078 1071 383 381 378 379 1057 1079 1068 1075 1074 1058 387 388 1065 1072 1073 1055 1056 1061
        1059  1066 1067 386 1063 1064 1062 1060 1015 1004 1005 1006 1008 1009 1010 1011 1172 1013 1014 1016 1017 1018 1019 1020
        1021 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031 1032 1033 1034 1035 1036 1037 1041 1046 1048 1044 1054
        
	 }


    controlledprovinces = {
	409 384 385 1076 1077 1078 1071 383 381 378 379 1057 1079 1068 1075 1074 1058 387 388 1065 1072 1073 1055 1056 1061
        1059 1066 1067 386 1063 1064 1062 1060 1015 1004 1005 1006 1008 1009 1010 1011 1172 1013 1014 1016 1017 1018 1019 1020
          1021 1022  1023 1024 1025 1026 1027 1028 1029 1030 1031 1032 1033 1034 1035 1036 1037 1041 1046 1048 1044 1054
	  }



    nationalprovinces =   {
	409 384 385 1076 1077 1078 1071 383 381 378 379 1057 1079 1068 1075 1074 1058 387 388 1065 1072 1073 1055 1056 1061
        1059 1066 1067 386 1063 1064 1062 1060 1015 1008 1009 1010 1011 1172 1013 1014 1016 1017 1018 1019 1020
          1021  1023 1024  1027 1028 1029  1033 1034 1035 1036 1037  1054
	}
	claimedprovinces = {
	1004 1005 1006 1022 1025 1026 1030 1031 1032 1041 1046 1048 1044 1049
	}

diplomacy = {
relation = {   tag =    	BEL	value = 		40	   }  
relation = {   tag =  	BLR	 value =		20	   }  
relation = {   tag =  	BUL	value = 		40	   }  
relation = {   tag =  	GER	 value =		120	   }  
relation = {   tag =  	LAT	value = 		20	   }  
relation = {   tag =  	LIT	 value =		20	   }  
relation = {   tag =  	POL	value = 		10	   }  
relation = {   tag =  	UKR	 value =		39	   }  
relation = {   tag =  	AUS	value = 		40	   }  
relation = {   tag =  	BOS	value = 		90	   }  
relation = {   tag =  	CRO	 value =		-50	   }  
relation = {   tag =  	CZE	value = 		30	   }  
relation = {   tag =  	GLD	value = 		40	   }  
relation = {   tag =  	HUN	 value =		80	   }  
relation = {   tag =  	ALB	value = 		150	   }  
relation = {   tag =  	GRE	value = 		-60	   }  
relation = {   tag =  	HOL	 value =		30	   }  
relation = {   tag =  	IRE	value = 		20	   }  
relation = {   tag =  	ITA	value = 		40	   }  
relation = {   tag =  	ROM	value = 		-50	   }  
relation = {   tag =  	SER	value = 		-80	   }  
relation = {   tag =  	SPA	value = 		40	   }  
relation = {   tag =  	ENG	value = 		-40	   }  
relation = {   tag =  	FRA	value = 		-60	   }  
relation = {   tag =  	RSI	 value =		-60	   }  
relation = {   tag =  	CAN	value = 		-50	   }  
relation = {   tag =  	VIC	value = 		-90	   }  
relation = {   tag =  	ARM	 value =		120	   }  
relation = {   tag =  	AZB	value = 		140	   }  
relation = {   tag =  	GEO	value = 		-50	   }  
relation = {   tag =  	KAZ	 value =		-40	   }  
relation = {   tag =  	KYG	value = 		60	   }  
relation = {   tag =  	RUS	 value =		-50	   }  
relation = {   tag =  	AFG	 value =		40	   }  
relation = {   tag =  	EGY	 value =		150	   }  
relation = {   tag =  	LBY	value = 		160	   }  
relation = {   tag =  	OMN	value = 		90	   }  
relation = {   tag =  	PER	value = 		40	   }  
relation = {   tag =  	SAU	value = 		-20	   }  
relation = {   tag =  	SUD	 value =		50	   }  
relation = {   tag =  	TUN	value = 		120	   }  
relation = {   tag =  	YEM	value = 		40	   }  
relation = {   tag =  	CON	value = 		50	   }  
relation = {   tag =  	ETH	value = 		-20	   }    
relation = {   tag =  	IND	value = 		-30	   }  
relation = {   tag =  	PAK	 value =		60	   }  
relation = {  tag =   	USA	value = 		-50	 }
relation = {   tag =  	JAP	value = 		-30	   }  
}


	
	techapps = {
# Group C 1936 techs
#######################

#Aircrafts
4500 4510 4520 4530 4540 4550 4010 4020 #Early Fighter 
4600 4610 4620 4630 4120 #Interwar Bomber 
4300 4310 4320 4330 #Multirole fighter
4800 4810 4820 #ww1 strategic bomber
4700 4710 #ww1 navalbomber
7290 7300 7310 #CAS

#Armour & Artillery
2860 2870 2880 2020 #Basic Armoured Car  
7600 7610 2620 2010 2630 2640 #Tankette 
2290 2300 2310 #Great War Heavy Field Artillery 
2800 2450 21180 21190 21200 #Early Static Anti-Air Artillery 
2810 2820 2510 #Basic Anti-Air Artillery Brigade 

#Infantry
1010  1020 1030 1040 1050 1060 1070 #Great War Infantry Division
13060 13070 13080 1310 1320 1330 1340 #Great War Cavalry Division
1160  1170 1180 1190 1200 1210 1220 1230 #Early Mountain Division 
1910 1920 1930 1940 1950 1960 1970 1980 #Interbellum 1930 Supply
1830 1840 1850 1860 #Engineers

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010

#Industrial
5700 5710 5010 #Agriculture 
5310 54010 54020 54030 5316 #Computers & cryptografi
5810 5820 5050 5830 #Manufactoring
5800 5080 5090 #Improved Construction Engineering 
5190 #Basic Oil Refining 
5600 5610 5620 5630 #Medicine

#Naval
3210 3220 3230 #Early Heavy Cruiser 
3010 3020 3030 3040 #Great War Destroyer 
3110 3120 3130 #Early Light Cruiser 
3410 3420 3430 3440 3450 3456 3460 #Great War Battleship 
3610 3620 3630 #Short Range Submarine 
3720 3730 3736 3740 3750 3900 #Torpedo & ASW 18
3810 #Troopships

#Land Doctrines
14000 14010 #Improved Great War Hospital System
6500 6510 6530 6550 6590 6600 6610 6620 6650 6670 6680 6690 6700 6710 6910 # Great War Land Doctrines (central powers)
6570 6300 # Human Wave, mobility

#Naval Doctrines
8010 8020 8040 8050


	}

#########  OOB (...)

################
###  By Afsin and Berchlingen
################
###### Ottoman Navy `36 ######

        navalunit = {
        location = 409
        base = 409
        name = "1. Devlet-i Aliye Deniz Kuvvetleri"
        id = { type = 11700 id = 1 }

                division = {
                id = { type = 11700 id = 2 }
                name = "Hüdavendigâr Sultan Murad"
                type = battleship
                model = 4
                }

                division = {
                id = { type = 11700 id = 3 }
                name = "Sultan Osman I"
                type = battleship
                model = 4
                }

                division = {
                id = { type = 11700 id = 4 }
                name = "Fatih Sultan Mehmed"
                type = battleship
                model = 3
                }

                division = {
                id = { type = 11700 id = 5 }
                name = "Xebec"
                type = heavy_cruiser
                model = 4
                }

                division = {
                id = { type = 11700 id = 6 }
                name = "Dhow"
                type = heavy_cruiser
                model = 4
                }

                division = {
                id = { type = 11700 id = 7 }
                name = "Izmit"
                type = light_cruiser
                model = 4
                }

                division = {
                id = { type = 11700 id = 8 }
                name = "Izmir"
                type = light_cruiser
                model = 4
                }

                division = {
                id = { type = 11700 id = 9 }
                name = "Edirne"
                type = light_cruiser
                model = 3
                }

                division = {
                id = { type = 11700 id = 10 }
                name = "Bursa"
                type = light_cruiser
                model = 3
                }

                division = {
                id = { type = 11700 id = 11 }
                name = "Ankara"
                type = light_cruiser
                model = 3
                }

                division = {
                id = { type = 11700 id = 12 }
                name = "1. Tahripçi Filotilla"
                type = destroyer
                model = 4
                }

                division = {
                id = { type = 11700 id = 13 }
                name = "1. Denizalti Filotilla"
                type = submarine
                model = 1
                }
          }

        navalunit = {
        location = 1019
        base = 1019
        name = "Al-Afriqiya Filosu"
        id = { type = 11700 id = 14 }

                division = {
                id = { type = 11700 id = 15 }
                name = "Yavuz Sultan Selim"
                type = battlecruiser
                model = 1
                }

                division = {
                id = { type = 11700 id = 16 }
                name = "Yildirim Sultan Bayezid"
                type = battleship
                model = 3
                }

                division = {
                id = { type = 11700 id = 17 }
                name = "Hamidiye"
                type = light_cruiser
                model = 3
                }

                division = {
                id = { type = 11700 id = 18 }
                name = "Mecidiye"
                type = light_cruiser
                model = 3
                }

                division = {
                id = { type = 11700 id = 19 }
                name = "2. Tahripçi Filotilla"
                type = destroyer
                model = 4
                }

                division = {
                id = { type = 11700 id = 20 }
                name = "4. Tahripçi Filotilla"
                type = destroyer
                model = 4
                }

                division = { 
		id = { type = 11700 id = 100 } 
		name = "Reschid Pasha Kücük Filotilla" 
		type = transport 
                model = 1
		} 
        }

        navalunit = {
        location = 1041
        base = 1041
        name = "Irak Filosu"
        id = { type = 11700 id = 21 }

                division = {
                id = { type = 11700 id = 22 }
                name = "Diyerbakir"
                type = light_cruiser
                model = 3
                }

                division = {
                id = { type = 11700 id = 23 }
                name = "3. Tahripçi Filotilla"
                type = destroyer
                model = 4
                }
  }

###### Ottoman Army `36 ######

        landunit = {
  location = 409
  name = "Istanbul Ordusu"
              id = { type = 11700 id = 24 }

  division = {
  id = { type = 11700 id = 25 }
  type = infantry
  model = 6
  strength  = 100
  organisation = 30
  name = "1. Piyade Firkasi"
  }

  division = {
  id = { type = 11700 id = 26 }
  type = infantry
  strength  = 100
  model = 6
  organisation = 30
  name = "2. Piyade Firkasi"
  }

  division = {
  id = { type = 11700 id = 27 }
  type = cavalry
  strength  = 50
  model = 6
  organisation = 30
  name = "1. Sipahi Tümeni"
  }
}

        landunit = {
  location = 385
  name = "Edirne Ordusu"
              id = { type = 11700 id = 28 }

                              division = {
                              id = { type = 11700 id = 29 }
  type = infantry
  strength  = 100
  model = 6
  organisation = 30
  name = "3. Piyade Firkasi"
  }
                              division = {
                              id = { type = 11700 id = 30 }
  type = infantry
  strength  = 100
  model = 6
  organisation = 30
  name = "7. Piyade Firkasi"
  }

                              division = {
                              id = { type = 11700 id = 31 }
  type = cavalry
  strength  = 50
  model = 6
  organisation = 30
  name = "3. Sipahi Tümeni"
  }
}

        landunit = {
  location = 1077
  name = "Izmir Ordusu"
              id = { type = 11700 id = 32 }

                              division = {
                              id = { type = 11700 id = 33 }
  type = infantry
  strength  = 100
  model = 6
  organisation = 30
  name = "12. Piyade Firkasi"
  }
                              division = {
                              id = { type = 11700 id = 34 }
  type = infantry
  strength  = 100
  model = 6
  organisation = 30
  name = "13. Piyade Firkasi"
  }
			         division = {
                              id = { type = 11700 id = 35 }
  type = cavalry
  strength  = 50
  model = 6
  organisation = 30
  name = "5. Sipahi Tümeni"
  }
}

        landunit = {
  location = 1063
  name = "Erzurum Ordusu"
              id = { type = 11700 id = 36 }

                              division = {
                              id = { type = 11700 id = 37 }
  type = infantry
  strength  = 100
  model = 6
  organisation = 30
  name = "4. Piyade Firkasi"
  }
                              division = {
                              id = { type = 11700 id = 38 }
  type = infantry
  strength  = 100
  model = 6
  organisation = 30
  name = "5. Piyade Firkasi"
  }

                              division = {
                              id = { type = 11700 id = 39 }
  type = cavalry
  strength  = 50
  model = 6
  organisation = 30
  name = "6. Sipahi Tümeni"
  }
}

        landunit = {
  location = 1004
  name = "El-Arish Ordusu"
              id = { type = 11700 id = 40 }

                              division = {
                              id = { type = 11700 id = 41 }
  type = infantry
  strength  = 100
  model = 6
  organisation = 30
  name = "8. Piyade Firkasi"
  }
                              division = {
                              id = { type = 11700 id = 42 }
  type = infantry
  strength  = 100
  model = 6
  organisation = 30
  name = "10. Piyade Firkasi"
  }
 
                              division = {
                              id = { type = 11700 id = 43 }
  type = cavalry
  strength  = 50
  model = 6
  organisation = 30
  name = "2. Sipahi Tümeni"
  }
}

        landunit = {
  location = 1034
  name = "Baghdad Ordusu"
              id = { type = 11700 id = 44 }

                              division = {
                              id = { type = 11700 id = 45 }
  type = infantry
  strength  = 100
  model = 6
  organisation = 30
  name = "6. Piyade Firkasi"
  }
                              division = {
                              id = { type = 11700 id = 46 }
  type = infantry
  strength  = 100
  model = 6
  organisation = 30
  name = "9. Piyade Firkasi"
  }

                              division = {
                              id = { type = 11700 id = 47 }
  type = cavalry
  strength  = 50
  model = 6
  organisation = 30
  name = "4. Sipahi Tümeni"
  }
}

             landunit = {
  location = 1032
  name = "Basra Ordusu"
              id = { type = 11700 id = 48 }

                              division = {
                              id = { type = 11700 id = 49 }
  type = infantry
  strength  = 100
  model = 6
  organisation = 30
  name = "11. Piyade Firkasi"
  }
                              division = {
                              id = { type = 11700 id = 50 }
  type = militia
  strength  = 50
  model = 3
  organisation = 30
  name = "1. Redif Piyade Firkasi"
  }
}

        landunit = {
  location = 1044
  name = "Hedjaz Ordusu"
              id = { type = 11700 id = 51 }

                              division = {
                              id = { type = 11700 id = 52 }
  type = infantry
  strength  = 100
  model = 6
  organisation = 30
  name = "14. Piyade Firkasi"
  }
                              division = {
                              id = { type = 11700 id = 53 }
  type = militia
  model = 3
  strength  = 50
  organisation = 30
  name = "2. Redif Piyade Firkasi"
  }
}


        landunit = {
  location = 1067
  name = "Kafkasya Ordusu"
              id = { type = 11700 id = 54 }

                              division = {
                              id = { type = 11700 id = 55 }
  type = bergsjaeger
  strength  = 50
  model = 6
  organisation = 30
  name = "1. Dagci Firkasi"
  }
                              division = {
                              id = { type = 11700 id = 56 }
  type = bergsjaeger
  strength  = 50
  model = 6
  organisation = 30
  name = "2. Dagci Firkasi"
  }
}

        landunit = {
  location = 386
  name = "Kars Ordusu"
              id = { type = 11700 id = 57 }

                              division = {
                              id = { type = 11700 id = 58 }
  type = bergsjaeger
  strength  = 50
  model = 6
  organisation = 30
  name = "3. Dagci Firkasi"
  }
}

landunit = {
location = 388
name = "Cyprusian Garrison"
id = { type = 11700 id = 63 }

division = {
id = { type = 11700 id = 64 }
type = garrison
model = 3
strength  = 100
extra = artillery
organisation = 30
name = "10. Mustahfiz Piyade Firkasi"
}
}

landunit = {
location = 379
name = "Rhodesian Garrison"
id = { type = 11700 id = 65 }

division = {
id = { type = 11700 id = 66 }
type = garrison
model = 3
strength  = 100
extra = artillery
organisation = 30
name = "11. Mustahfiz Piyade Firkasi"
}
}

landunit = {
location = 383
name = "Dodecanesian Garrison"
id = { type = 11700 id = 67 }

division = {
id = { type = 11700 id = 68 }
type = garrison
model = 3
strength  = 100
extra = artillery
organisation = 30
name = "12. Mustahfiz Piyade Firkasi"
}
}

landunit = {
location = 381
name = "Cycladesian Garrison"
id = { type = 11700 id = 69 }

division = {
name = "13. Mustahfiz Piyade Firkasi"
id = { type = 11700 id = 70 }
type = garrison
model = 3
strength  = 100
extra = artillery
brigade_model = 5
organisation = 30
}
}

landunit = {
location = 362
name = "Albanian Garrison"
id = { type = 11700 id = 71 }

division = {
name = "14. Mustahfiz Piyade Firkasi"
id = { type = 11700 id = 72 }
type = garrison
model = 3
strength  = 100
extra = artillery
brigade_model = 5
organisation = 30
locked = yes
}
}

        landunit = {
  location = 1048
  name = "Trablusgarb Ordusu"
              id = { type = 11700 id = 59 }


                              division = {
                              id = { type = 11700 id = 60 }
  type = cavalry
  model = 6
  strength  = 100
  organisation = 30
  name = "7. Sipahi Tümeni"
  }
                              division = {
                              id = { type = 11700 id = 61 }
  type = militia
  model = 4
  strength  = 50
  organisation = 30
  name = "3. Redif Piyade Firkasi"
  }
                              division = {
                              id = { type = 11700 id = 62 }
  type = militia
  model = 4
  strength  = 50
  organisation = 30
  name = "4. Redif Piyade Firkasi"
  }
}
#Air Force
airunit = {
	location = 409
	base = 409
	id = { type = 11700 id = 73 }
	name = "1 uçagi kanat"
	division = {
		id = { type = 11700 id = 74 }
		name = "1 uçagi filosu"
		strength = 100
		type = interceptor
		model = 6
		}
	}
airunit = {
	location = 1075
	base = 1075
	id = { type = 11700 id = 75 }
	name = "1 taktik bombardiman uçagi kanat"
	division = {
		id = { type = 11700 id = 76 }
		name = "1 taktik bombardiman filosu"
		strength = 100
		type = tactical_bomber
		model = 4
		}
	}
airunit = {
	location = 388
	base = 388
	id = { type = 11700 id = 77 }
	name = "1 deniz uçagi kanat"
	division = {
		id = { type = 11700 id = 78 }
		name = "1 deniz bombardiman filosu"
		strength = 100
		type = naval_bomber
		model = 1
		}
	}

transports = 50
escorts = 10


}  