


country = {
    tag = OTT  
ai = "kaiserreich\Ottoman.ai"

	policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 4
        political_left = 3
        freedom = 4
        free_market = 6
        professional_army = 5
        defense_lobby = 6
        interventionism = 4
    }

peacetime_ic_mod = 0.85

#### cabinet

headofstate = { type = 9 id = 549001 }
headofgovernment = { type = 9 id = 549002 }
foreignminister = { type = 9 id =  549003 }
armamentminister = { type = 9 id = 549023 }
ministerofsecurity = { type = 9 id = 549005 }
ministerofintelligence = { type = 9 id = 549006 }
chiefofstaff = { type = 9 id = 549159 } #Asim Gündüz Pasha
chiefofarmy = { type = 9 id = 549088 } #Fahrettin Altay
chiefofnavy = { type = 9 id = 549009 }
chiefofair = { type = 9 id = 549103 } #Mehmet Fazil Bey

#### Resource Reserves

	energy	=	1000   metal	= 1000		rare_materials =	500	oil =	500	supplies =	500
	money = 20      

        SpyInfo  = {  country = "OTT" NumberOfSpies = 4  } 

	manpower = 165
	capital = 409
        dissent = 5

    ownedprovinces =      {
	409 384 385 1076 1077 1078 1071 383 381 378 379 1057 1079 1068 1075 1074 1058 387 388 1065 1072 1073 1055 1056 1061
        1059  1066 1067 386 1063 1064 1062 1060 1015 1004 1005 1006 1008 1009 1010 1011 1172 1013 1014 1016 1017 1018 1019 1020
        1021 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031 1032 1033 1034 1035 1036 1037 1041 1046 1044 1054 1048
        
	 }


    controlledprovinces = {
	409 384 385 1076 1077 1078 1071 383 381 378 379 1057 1079 1068 1075 1074 1058 387 388 1065 1072 1073 1055 1056 1061
        1059 1066 1067 386 1063 1064 1062 1060 1015 1004 1005 1006 1008 1009 1010 1011 1172 1013 1014 1016 1017 1018 1019 1020
          1021 1022  1023 1024 1025 1026 1027 1028 1029 1030 1031 1032 1033 1034 1035 1036 1037 1041 1046 1044 1054 1048
	  }



    nationalprovinces =   {
	409 384 385 1076 1077 1078 1071 383 381 378 379 1057 1079 1068 1075 1074 1058 387 388 1065 1072 1073 1055 1056 1061
        1059 1066 1067 386 1063 1064 1062 1060 1015 1008 1009 1010 1011 1172 1013 1014 1016 1017 1018 1019 1020
          1021  1023 1024  1027 1028 1029  1033 1034 1035 1036 1037  1054
	}
	claimedprovinces = {
	1004 1005 1006 1022 1025 1026 1030 1031 1032 1041 1046 1048 1044 1049
	}

diplomacy = {
relation = {   tag =    	BEL	value = 		40	   }  
relation = {   tag =  	BLR	 value =		20	   }  
relation = {   tag =  	BUL	value = 		40	   }  
relation = {   tag =  	GER	 value =		-50	   }  
relation = {   tag =  	LAT	value = 		20	   }  
relation = {   tag =  	LIT	 value =		20	   }  
relation = {   tag =  	POL	value = 		10	   }  
relation = {   tag =  	UKR	 value =		39	   }  
relation = {   tag =  	AUS	value = 		40	   }  
relation = {   tag =  	BOS	value = 		90	   }  
relation = {   tag =  	CRO	 value =		-50	   }  
relation = {   tag =  	CZE	value = 		30	   }  
relation = {   tag =  	GLD	value = 		40	   }  
relation = {   tag =  	HUN	 value =		80	   }  
relation = {   tag =  	ALB	value = 		150	   }  
relation = {   tag =  	GRE	value = 		-60	   }  
relation = {   tag =  	HOL	 value =		30	   }  
relation = {   tag =  	IRE	value = 		20	   }  
relation = {   tag =  	ITA	value = 		40	   }  
relation = {   tag =  	ROM	value = 		-50	   }  
relation = {   tag =  	SER	value = 		-80	   }  
relation = {   tag =  	SPA	value = 		40	   }  
relation = {   tag =  	ENG	value = 		-40	   }  
relation = {   tag =  	FRA	value = 		-60	   }  
relation = {   tag =  	RSI	 value =		-60	   }  
relation = {   tag =  	CAN	value = 		-50	   }  
relation = {   tag =  	VIC	value = 		-90	   }  
relation = {   tag =  	ARM	 value =		120	   }  
relation = {   tag =  	AZB	value = 		140	   }  
relation = {   tag =  	GEO	value = 		-50	   }  
relation = {   tag =  	KAZ	 value =		-40	   }  
relation = {   tag =  	KYG	value = 		60	   }  
relation = {   tag =  	RUS	 value =		-50	   }  
relation = {   tag =  	AFG	 value =		40	   }  
relation = {   tag =  	EGY	 value =		150	   }  
relation = {   tag =  	LBY	value = 		160	   }  
relation = {   tag =  	OMN	value = 		90	   }  
relation = {   tag =  	PER	value = 		40	   }  
relation = {   tag =  	SAU	value = 		-20	   }  
relation = {   tag =  	SUD	 value =		50	   }  
relation = {   tag =  	TUN	value = 		120	   }  
relation = {   tag =  	YEM	value = 		40	   }  
relation = {   tag =  	CON	value = 		50	   }  
relation = {   tag =  	ETH	value = 		-20	   }    
relation = {   tag =  	IND	value = 		-30	   }  
relation = {   tag =  	PAK	 value =		60	   }  
relation = {  tag =   	USA	value = 		-50	 }
relation = {   tag =  	JAP	value = 		-30	   }  
}


	
	techapps = {
# Group C 1936 techs
#######################

#Aircrafts
4500 4510 4520 4530 4540 4550 4010 4020 #Early Fighter 
4600 4610 4620 4630 4120 #Interwar Bomber 
4300 4310 4320 4330 #Multirole fighter
4800 4810 4820 #ww1 strategic bomber
4700 4710 #ww1 navalbomber
7290 7300 7310 #CAS
4740 #Early Seaplane

#Armour & Artillery
2860 2870 2880 2020 #Basic Armoured Car  
7600 7610 2620 2010 2630 2640 #Tankette 
2290 2300 2310 #Great War Heavy Field Artillery 
2800 2450 21180 21190 21200 #Early Static Anti-Air Artillery 
2810 2820 2510 #Basic Anti-Air Artillery Brigade 

#Infantry
1010  1020 1030 1040 1050 1060 1070 #Great War Infantry Division
13060 13070 13080 1310 1320 1330 1340 #Great War Cavalry Division
1160  1170 1180 1190 1200 1210 1220 1230 #Early Mountain Division 
1910 1920 1930 1940 1950 1960 1970 1980 #Interbellum 1930 Supply
1830 1840 1850 1860 #Engineers

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010

#Industrial
5700 5710 5010 #Agriculture 
5310 54010 54020 54030 5316 #Computers & cryptografi
5810 5820 5050 5830 #Manufactoring
5800 5080 5090 #Improved Construction Engineering 
5190 #Basic Oil Refining 
5600 5610 5620 5630 #Medicine

#Naval
3210 3220 3230 #Early Heavy Cruiser 
3010 3020 3030 3040 #Great War Destroyer 
3110 3120 3130 #Early Light Cruiser 
3410 3420 3430 3440 3450 3456 3460 #Great War Battleship 
3610 3620 3630 #Short Range Submarine 
3720 3730 3736 3740 3750 3900 #Torpedo & ASW 18
3810 #Troopships

#Land Doctrines
14000 14010 #Improved Great War Hospital System
6500 6510 6530 6550 6590 6600 6610 6620 6650 6670 6680 6690 6700 6710 6910 # Great War Land Doctrines (central powers)

#Naval Doctrines
8010 8020 8040 8050 8060 8070 8080
8100
8500
	}

dormant_ministers = { 549008 #Tahsin Yazici
					}

dormant_teams = { 15736 15737 15738 15739 15742 15743 }

dormant_leaders = { #LEB
					549180 549181 549182 549183 549184 549185 549186
					#SYR
					549187 549188 549189 549190 549191 549192 549193 549194 549195
					#IRQ
					549196 549197 549198 549199 549200 549201 549202 549203 549204 549205 549206 549207
					}

deactivate = { 6010 6210 6570 6560 6390 }

#########  OOB (...)

################
###  By Afsin and Berchlingen
################
###### Ottoman Navy `36 ######

        navalunit = {
        location = 409
        base = 409
        name = "1. Devlet-i Aliye Deniz Kuvvetleri"
        id = { type = 11700 id = 1 }

                division = {
                id = { type = 11700 id = 2 }
                name = "Hüdavendigâr Sultan Murad"
                type = battleship
                model = 4
                }

                division = {
                id = { type = 11700 id = 3 }
                name = "Sultan Osman I"
                type = battleship
                model = 4
                }

                division = {
                id = { type = 11700 id = 4 }
                name = "Fatih Sultan Mehmed"
                type = battleship
                model = 3
                }

                division = {
                id = { type = 11700 id = 5 }
                name = "Xebec"
                type = heavy_cruiser
                model = 4
                }

                division = {
                id = { type = 11700 id = 6 }
                name = "Dhow"
                type = heavy_cruiser
                model = 4
                }

                division = {
                id = { type = 11700 id = 7 }
                name = "Izmit"
                type = light_cruiser
                model = 4
                }

                division = {
                id = { type = 11700 id = 8 }
                name = "Izmir"
                type = light_cruiser
                model = 4
                }

                division = {
                id = { type = 11700 id = 9 }
                name = "Edirne"
                type = light_cruiser
                model = 3
                }

                division = {
                id = { type = 11700 id = 10 }
                name = "Bursa"
                type = light_cruiser
                model = 3
                }

                division = {
                id = { type = 11700 id = 11 }
                name = "Ankara"
                type = light_cruiser
                model = 3
                }

                division = {
                id = { type = 11700 id = 12 }
                name = "1. Tahripçi Filotilla"
                type = destroyer
                model = 4
                }

                division = {
                id = { type = 11700 id = 13 }
                name = "1. Denizalti Filotilla"
                type = submarine
                model = 1
                }
          }

        navalunit = {
        location = 1019
        base = 1019
        name = "Al-Afriqiya Filosu"
        id = { type = 11700 id = 14 }

                division = {
                id = { type = 11700 id = 15 }
                name = "Yavuz Sultan Selim"
                type = battlecruiser
                model = 1
                }

                division = {
                id = { type = 11700 id = 16 }
                name = "Yildirim Sultan Bayezid"
                type = battleship
                model = 3
                }

                division = {
                id = { type = 11700 id = 17 }
                name = "Hamidiye"
                type = light_cruiser
                model = 3
                }

                division = {
                id = { type = 11700 id = 18 }
                name = "Mecidiye"
                type = light_cruiser
                model = 3
                }

                division = {
                id = { type = 11700 id = 19 }
                name = "2. Tahripçi Filotilla"
                type = destroyer
                model = 4
                }

                division = {
                id = { type = 11700 id = 20 }
                name = "4. Tahripçi Filotilla"
                type = destroyer
                model = 4
                }

                division = { 
		id = { type = 11700 id = 100 } 
		name = "Reschid Pasha Kücük Filotilla" 
		type = transport 
                model = 1
		} 
        }

        navalunit = {
        location = 1041
        base = 1041
        name = "Irak Filosu"
        id = { type = 11700 id = 21 }

                division = {
                id = { type = 11700 id = 22 }
                name = "Diyerbakir"
                type = light_cruiser
                model = 3
                }

                division = {
                id = { type = 11700 id = 23 }
                name = "3. Tahripçi Filotilla"
                type = destroyer
                model = 4
                }
  }

###### Ottoman Army `36 ######


#1st Army
landunit = {										
	id 	= { type = 11700 id = 24 }
		name = "I. Ordu" 
		location = 409 	#Istanbul 
		leader = 549124 #Kemal Pasha
	division = {
		id 	= { type = 11700 id = 25 }
		name 	= "Ordu Genel Merkez"
		type 	= hq
		model 	= 2
		strength = 75
		organisation = 30
		experience = 0
		}		
	division = {  
		id = {  type = 11700 id = 26  } 
		name = "1. Piyade Tümeni" 
		type = infantry
        model = 6
		strength = 100
		organisation = 30
		} 

	division = {
		id = {  type = 11700 id = 27  } 
		name = "2. Piyade Tümeni" 
		type = infantry 
        model = 6
		strength = 100
		organisation = 30
		} 

	division = {
		id = {  type = 11700 id = 28  } 
		name = "3. Piyade Tümeni" 
		type = infantry
        model = 6
		strength = 100
		organisation = 30
		} 
	}
	

#2nd Army
landunit = {										
	id 	= { type = 11700 id = 29 }
		name = "II. Ordu" 
		location = 1067 	#Trabzon 
		leader = 549083 #Berkok
	division = {
		id = { type = 11700 id = 30 }
        type = bergsjaeger
        strength  = 50
        model = 6
        organisation = 30
        name = "1. Dagci Firkasi"
  }
    division = {
    id = { type = 11700 id = 31 }
		type = bergsjaeger
		strength  = 50
		model = 6
		organisation = 30
		name = "2. Dagci Firkasi"
  }
  
	division = {
		id = {  type = 11700 id = 32  } 
		name = "23. Piyade Tümeni" 
		type = infantry
        model = 6
		strength = 40
		organisation = 30
		} 

	division = {
		id = {  type = 11700 id = 33  } 
		name = "41. Piyade Tümeni" 
		type = infantry
        model = 6
		strength = 40
		organisation = 30
		} 		
 
	division = {
		id = {  type = 11700 id = 34  } 
		name = "44. Piyade Tümeni" 
		type = infantry
        model = 6
		strength = 40
		organisation = 30
		}  
}		
		
#4th Army
landunit = {										
	id 	= { type = 11700 id = 35 }
		name = "IV. Ordu" 
		location = 1016 	#Damascus
        leader = 549117 #Karabikir
	division = {
		id = {  type = 11700 id = 36  } 
		name = "3. Suvari Tümeni" 
		type = cavalry
		model = 6
		strength = 100
		experience = 0
		} 	
 
	division = {
		id = {  type = 11700 id = 37  } 
		name = "62. Piyade Tümeni" 
		type = infantry
        model = 6
		strength = 40
		organisation = 30
		}

	division = {
		id = {  type = 11700 id = 38  } 
		name = "24. Piyade Tümeni" 
		type = infantry
        model = 6
		strength = 40
		organisation = 30
		}		

	division = {
		id = {  type = 11700 id = 39  } 
		name = "48. Piyade Tümeni" 
		type = infantry
        model = 6
		strength = 40
		organisation = 30
		}		
}		

#7th Army
landunit = {										
	id 	= { type = 11700 id = 40 }
		name = "VII. Ordu" 
		location = 1004 	#El Arish 
		leader = 549103 #Fevzi Pasha
	division = {
		id = {  type = 11700 id = 41  } 
		name = "11. Piyade Tümeni" 
		type = infantry
        model = 6
		extra = rocket_artillery
	    brigade_model = 8		
		strength = 100
		organisation = 30
		}		
	division = {
		id = {  type = 11700 id = 42  } 
		name = "43. Piyade Tümeni" 
		type = infantry
        model = 6
		extra = rocket_artillery
	    brigade_model = 8			
		strength = 100
		organisation = 30
		}	
	division = {
		id = {  type = 11700 id = 43  } 
		name = "16. Piyade Tümeni" 
		type = infantry
        model = 6
		extra = rocket_artillery
	    brigade_model = 8			
		strength = 100
		organisation = 30
		}			
} 

#6th Army
landunit = {										
	id 	= { type = 11700 id = 44 }
		name = "VI. Ordu" 
		location = 1034 	#Baghdad 
		leader = 549101 #Fahrettin Altay
	division = {
		id = {  type = 11700 id = 45  } 
		name = "2. Suvari Tümeni" 
		type = cavalry
		model = 6
		strength = 100
		experience = 0
		} 
		
	division = {
		id = {  type = 11700 id = 46  } 
		name = "6. Piyade Tümeni" 
		type = infantry
        model = 6			
		strength = 100
		organisation = 30
		}	
	division = {
		id = {  type = 11700 id = 47  } 
		name = "14. Piyade Tümeni" 
		type = infantry
        model = 6		
		strength = 100
		organisation = 30
		}
	division = {
		id = {  type = 11700 id = 48  } 
		name = "46. Piyade Tümeni" 
		type = infantry
        model = 6		
		strength = 100
		organisation = 30
		}		
}


#3rd Army
landunit = {										
	id 	= { type = 11700 id = 49 }
		name = "III. Ordu" 
		location = 1021 	#Aleppo 
		leader = 549143 #Osman Fuat Efendi
	division = {
		id = {  type = 11700 id = 50  } 
		name = "1. Suvari Tümeni" 
		type = cavalry
		model = 6
        extra  = artillery 
	    brigade_model = 3		
		strength = 50
		experience = 0
		} 
	division = {
		id = {  type = 11700 id = 51  } 
		name = "46. Piyade Tümeni" 
		type = infantry
        model = 6
		extra = rocket_artillery
	    brigade_model = 8			
		strength = 50
		organisation = 30
		}
	division = {
		id = {  type = 11700 id = 52  } 
		name = "46. Piyade Tümeni" 
		type = infantry
        model = 6		
		extra = rocket_artillery
	    brigade_model = 8			
		strength = 50
		organisation = 30
		}		
}

landunit = {
location = 388
name = "Cyprusian Garrison"
id = { type = 11700 id = 53 }

division = {
id = { type = 11700 id = 54 }
type = garrison
model = 3
strength  = 50
max_strength = 50
extra = artillery
organisation = 30
name = "10. Mustahfiz Piyade Firkasi"
}
}

landunit = {
location = 379
name = "Rhodesian Garrison"
id = { type = 11700 id = 55 }

division = {
id = { type = 11700 id = 56 }
type = garrison
model = 3
strength  = 50
max_strength = 50
extra = artillery
organisation = 30
name = "11. Mustahfiz Piyade Firkasi"
}
}

landunit = {
location = 383
name = "Dodecanesian Garrison"
id = { type = 11700 id = 57 }

division = {
id = { type = 11700 id = 58 }
type = garrison
model = 3
strength  = 50
max_strength = 50
extra = artillery
organisation = 30
name = "12. Mustahfiz Piyade Firkasi"
}
}

#5th Army
landunit = {										
	id 	= { type = 11700 id = 59 }
		name = "V. Ordu" 
		location = 1077 	#Izmir 
		leader = 549102 #Fahrettin Türkkan
	division = {
		id = {  type = 11700 id = 60  } 
		name = "4. Suvari Tümeni" 
		type = cavalry
		model = 6
        extra  = artillery 
	    brigade_model = 3		
		strength = 50
		experience = 0
		} 
	division = {
		id = {  type = 11700 id = 61  } 
		name = "55. Piyade Tümeni" 
		type = infantry
        model = 6
		extra = rocket_artillery
	    brigade_model = 8			
		strength = 50
		organisation = 30
		}
	division = {
		id = {  type = 11700 id = 62  } 
		name = "49. Piyade Tümeni" 
		type = infantry
        model = 6		
		extra = rocket_artillery
	    brigade_model = 8			
		strength = 50
		organisation = 30
		}		
}


#Air Force
airunit = {
	location = 409
	base = 409
	id = { type = 11700 id = 73 }
	name = "1 uçagi kanat"
	division = {
		id = { type = 11700 id = 74 }
		name = "1 uçagi filosu"
		strength = 100
		type = interceptor
		model = 6
		}
	}
airunit = {
	location = 1075
	base = 1075
	id = { type = 11700 id = 200 }
	name = "1 taktik bombardiman uçagi kanat"
	division = {
		id = { type = 11700 id = 201 }
		name = "1 taktik bombardiman filosu"
		strength = 100
		type = tactical_bomber
		model = 4
		}
	}
airunit = {
	location = 388
	base = 388
	id = { type = 11700 id = 203 }
	name = "1 deniz uçagi kanat"
	division = {
		id = { type = 11700 id = 204 }
		name = "1 deniz bombardiman filosu"
		strength = 100
		type = naval_bomber
		model = 1
		}
	}

transports = 50
escorts = 10


}  