country = {
tag = RUS

ai = "kaiserreich\Russia.ai"
policy = {
date = { year = 0 month = january day = 0 }
democratic = 7
political_left = 6
freedom = 6
free_market = 5
professional_army = 1
defense_lobby = 3
interventionism = 2
}





headofstate = { type = 9 id = 4092  }
headofgovernment = { type = 9 id = 4160 }
ministerofsecurity = { type = 9 id = 4242  }
ministerofintelligence = { type = 9 id = 4251  }
chiefofstaff = { type = 9 id = 4124  }
chiefofarmy = { type = 9 id = 4266   }
chiefofnavy = { type = 9 id = 4179 }


#### Resource Reserves

SpyInfo  = {  country = "RUS" NumberOfSpies = 5  }

capital = 553
energy	=	1000   metal	= 1000		rare_materials =	500	oil =	500	supplies =	500
money = 30   transports = 55 escorts = 20

manpower = 1600
dissent = 10


ownedprovinces =      {
550 552 566 564 593 573 589 586 581 582 580 654 653 655 659 663 660 666 667 1134 553 551
549 560 565 535 534 536 537 541 539 557 562 559 561 542 546 547 556 555 563 558 577 575 574 588
585 583 579 652 650 651 657 661 669 665 668 656 658 688 545 543 548 676 677 570 572 1132 1133
1136 1137 1138 1139 1141 1142 1143 1144 1145 1156 1157 1069 1070 1166 1161 1163 1170 1176 1174
1175 1187 1188 1189 1186 1181 1182 1183 1184 1178 1180 1177 1179 1164 1165 1148 1155 1171 1152
1154 1135 1149 1150 1153 1129 1151 1128 1130 689 1126 1127 1131 687 671 569 554 567 568 576 584
678 682 571 679 578 670 675 683 664 674 690 672 673 680 681 684 685 686 544 1162 600 590 647
602 604 1140 501 498 1115 499 502 538 540 266 603 646 648
}
controlledprovinces = {
550 552 566 564 593 573 589 586 581 582 580 654 653 655 659 663 660 666 667 1134 553 551
549 560 565 535 534 536 537 541 539 557 562 559 561 542 546 547 556 555 563 558 577 575 574 588
585 583 579 652 650 651 657 661 669 665 668 656 658 688 545 543 548 676 677 570 572 1132 1133
1136 1137 1138 1139 1141 1142 1143 1144 1145 1156 1157 1069 1070 1166 1161 1163 1170 1176 1174
1175 1187 1188 1189 1186 1181 1182 1183 1184 1178 1180 1177 1179 1164 1165 1148 1155 1171 1152
1154 1135 1149 1150 1153 1129 1151 1128 1130 689 1126 1127 1131 687 671 569 554 567 568 576 584
678 682 571 679 578 670 675 683 664 674 690 672 673 680 681 684 685 686 544 1162 600 590 647
602 604 1140 501 498 1115 499 502 538 540 266 603 646 648
}
nationalprovinces =   {
550 552 566 564 593 573 589 586 581 582 580 654 653 655 659 663 660 666 667 1134 553 551
549 560 565 535 534 536 537 541 539 557 562 559 561 542 546 547 556 555 563 558 577 575 574 588
585 583 579 652 650 651 657 661 669 665 668 656 658 688 545 543 548 676 677 570 572 1132 1133
1136 1137 1138 1139 1141 1142 1143 1144 1145 1156 1157 1069 1070 1166 1161 1163 1170 1176 1174
1175 1187 1188 1189 1186 1181 1182 1183 1184 1178 1180 1177 1179 1164 1165 1148 1155 1171 1152
1154 1135 1149 1150 1153 1129 1151 1128 1130 689 1126 1127 1131 687 671 569 554 567 568 576 584
678 682 571 679 578 670 675 683 664 674 690 672 673 680 681 684 685 686 544 1162 600 590 647
602 604 1140 501 498 1115 499 502 538 540 266 603 646 648
}

diplomacy = {
relation = {   tag =    	BEL	value = 		10	   }
relation = {   tag =  	BLR	 value =		40	   }
relation = {   tag =  	BUL	value = 		60	   }
relation = {   tag =  	GER	 value =		40	   }
relation = {   tag =  	LAT	value = 		20	   }
relation = {   tag =  	LIT	 value =		25	   }
relation = {   tag =  	POL	value = 		-40	   }
relation = {   tag =  	UKR	 value =		30	   }
relation = {   tag =  	AUS	value = 		20	   }
relation = {   tag =  	BOS	value = 		40	   }
relation = {   tag =  	CRO	 value =		50	   }
relation = {   tag =  	CZE	value = 		80	   }
relation = {   tag =  	GLD	value = 		10	   }
relation = {   tag =  	HUN	 value =		60	   }
relation = {   tag =  	ALB	value = 		40	   }
relation = {   tag =  	DEN	 value =		60	   }
relation = {   tag =  	FIN	value = 		-30	   }
relation = {   tag =  	GRE	value = 		50	   }
relation = {   tag =  	HOL	 value =		10	   }
relation = {   tag =  	ITA	value = 		40	   }
relation = {   tag =  	ROM	value = 		60	   }
relation = {   tag =  	SER	value = 		80	   }
relation = {   tag =  	SPA	value = 		50	   }
relation = {   tag =  	SWE	 value =		20	   }
relation = {   tag =  	ENG	value = 		50	   }
relation = {   tag =  	FRA	value = 		20	   }
relation = {   tag =  	RSI	 value =		50	   }
relation = {   tag =  	AST	value = 		20	   }
relation = {   tag =  	CAN	value = 		-30	   }
relation = {   tag =  	VIC	value = 		50	   }
relation = {   tag =  	ARM	 value =		30	   }
relation = {   tag =  	AZB	value = 		-20	   }
relation = {   tag =  	GEO	value = 		30	   }
relation = {   tag =  	KAZ	 value =		50	   }
relation = {   tag =  	KYG	value = 		-80	   }
relation = {   tag =  	PRI	value = 		-70	   }
relation = {   tag =  	TRA	value = 		40	   }
relation = {   tag =  	AFG	 value =		-40	   }
relation = {   tag =  	CSX	 value =		30	   }
relation = {   tag =  	OTT	 value =		-50	   }
relation = {   tag =  	PER	value = 		20	   }
relation = {   tag =   	USA	value = 		40	   }
relation = {   tag =  	CHI	value = 		-40	   }
relation = {   tag =  	JAP	value = 		-50	   }
relation = {   tag =  	MAN	 value =		-60	   }
relation = {   tag =  	MON	value = 		-100	   }
relation = {   tag =  	TAN	 value =		-70	   }
}



techapps = {

#Infantry
1010 1020 1030 1040 1050 1060 1070 1080 1090 #1931 Infantry Division
1160 1170 1180 1190 1200 1210 1220 1230 #1925 Mountain Division
13060 13070 13080 1310 1320 1330 1340 1350 1360 #1928 Cavalry Division
1830 1840 1850 #Engineers
1910 1920 1930 1940 1950 1960 1970 #Interbellum 1930 Supply

#Armour & Artillery
7600 7610 2620 2010 2630 2640 #Early Tank
2860 2870 2880 2020 #Basic Armoured Car
2290 2300 2310 2900 2910 2920 #Early Field Artillery
2800 2450 21180 #Early Static Anti-Air Artillery
2810 2820 #Basic Anti-Air Artillery Brigade

#Naval
3010 3020 3030 3040 3050 3060 #Improved Destroyer
3110 3120 3130 3140 3150 #GW Light Cruiser
3210 3220 3230 3240 3250  #Improved Heavy Cruiser
3310 3320 3330 #Great War Battlecruiser
3410 3420 3430 3440 3450 3456 3460 #Early Battleship
3610 3620 3630 3640 3650 #Short Range Submarine
3720 3730 3736 3740 3750 3900 #Torpedo & ASW 18
3810 3820 #Troopships

#Aircrafts
4500 4510 4520 4530 4540 4550 4010 4020 #Early Fighter
4600 4610 4620 4630 4120 #Early Bomber
4300 4310 4320 4330 4340 #Multirole fighter
4800 4810 4820 #ww1 strategic bomber
4700 4710 #ww1 navalbomber
4290 # Transports
4740 4750 4760 #SEAPLANES
7290 7300 7310 7320 #1922 CAS

#Industrial
5700 5710 5010 #Modern Agriculture
5310 54010 54020 54030 5316 5326 5327 #Computers & cryptografi
5810 5820 5050 #manufactoring
5800 5080 #Construction Engineering
5190 #Basic Oil Refining
5600 5610 5620 #Medicine
5560 #Exp. Rocket

# Great War Land Doctrines (central powers)
6500 6510 6530 6550 6590 6600 6610 6620 6650 6670 6680 6690 6700 6710 6910
14000 14010 #Great War Hospital System

# Naval Doctrines
8010 8020 8030 8040 8050 8060 8070 8080 # Theory
82300 # Amphib
82500 # Logistics
8500 8510 8550 8560 8600 8610 # Naval Interdiction
8900 8910 8920 8930 # Fleet in being
8100 8110 8120 8150 8160 8200 # Naval Supremacy

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9040
}

dormant_leaders        = {  500814 500815 500816 500817 500818 500819 500820 500464 500593 500597 500604 500611 500613
500615 500618 500619 500062
500624 500625 500622 500633 500634 500645 500646 500649 500642 500660 500465 500466 500832
500836 500837 500838 500839 500840 500841 500842 500843 500844
}

deactivate = { 6010 6210 6570 6560 6390 }
dormant_ministers = { 4141 4199 4198 4148 }


#########  RUSSIAN ARMED FORCES

#########  RUSSIAN GROUND FORCES

landunit = {
id = { type = 10848 id = 130 }
name = "Arkhangelskii Voyennii Okrug"
location = 542 # Arkhangelsk

division = {
id  = { type = 10848 id = 131 }
name = "88. Pekhotnaya  Diviziya"
strength = 60
type = infantry
model = 8
}

division = {
id = { type = 10848 id = 380 }
name = "76. Pekhotnaya  Diviziya"
type = infantry
model = 7
strength = 10
}

division = {
id = { type = 10848 id = 381 }
name     = "52. 'Kazanskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 10
}

division = {
id = { type = 10848 id = 382 }
name = "53. Pekhotnaya  Diviziya"
type = infantry
model = 7
strength = 10
}
}

landunit = {
id = { type = 10848 id = 485 }
name     = "STAVKA"
location = 553 # Petrograd

division = {
id = { type = 10848 id = 486 }
name = "STAVKA"
strength = 100
type = hq
model = 2
}
}

landunit = { id = { type = 10848 id = 132 }
name     = "Moskovskii Voyennii Okrug"
location = 572 # Moskva

division = {
id = { type = 10848 id = 133 }
name = "4. Pekhotnaya  Diviziya"
strength = 80
type = infantry
model = 8
extra = engineer
brigade_model = 2
}

division = {
id = { type = 10848 id = 294 }
name = "5. Pekhotnaya  Diviziya"
strength = 80
type = infantry
model = 8
extra = engineer
brigade_model = 2
}

division = {
id = { type = 10848 id = 487 }
name = "6. Pekhotnaya  Diviziya"
strength = 80
type  = infantry
model = 8
extra = engineer
brigade_model = 2
}
}

######################
###  GROUND FORCES - EUROPEAN RUSSIA
######################

landunit = {
id = { type = 10848 id = 7 }
name     = "1-y Korpus"
location = 560 # Novgorod

division = {
id  = { type = 10848 id = 8503 }
name     = "1. Pekhotnaya  Diviziya"
strength = 80
type     = infantry
model = 7
extra    = artillery
brigade_model = 5
}

division = {
id = { type = 10848 id = 237 }
name     = "2. Pekhotnaya  Diviziya"
strength = 80
type     = infantry
model = 7
extra = anti_tank
brigade_model = 2
}

division = {
id  = { type = 10848 id = 9 }
name     = "3. 'Krivorozhskaya' Pekhot. Div."
strength = 80
type     = infantry
model = 7
extra = light_armor_brigade
brigade_model = 2
}

division =
{ id       = { type = 10848 id = 301 }
name     = "7. 'Pskovskaya' Pekhot. Div."
type     = infantry
model    = 7
strength = 20
extra    = artillery
brigade_model = 5
}
division =
{ id       = { type = 10848 id = 302 }
name     = "8. 'Novgorodskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 303 }
name     = "16. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}

division =
{ id       = { type = 10848 id = 436 }
name     = "95. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 442 }
name     = "98. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 445 }
name     = "100. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
}


landunit =
{ location = 553 # Petrograd
name     = "Peterburgskii Voyennii Okrug"
id       = { type = 10848 id = 306 }
division =
{ id       = { type = 10848 id = 307 }
name     = "56. Pekhotnaya  Diviziya"
type     = infantry
model = 8
strength = 80
extra    = artillery
brigade_model = 5
}
division =
{ id       = { type = 10848 id = 308 }
name     = "9. 'Novgorodskaya' Pekhot. Div."
type     = infantry
model = 8
strength = 80
extra    = super_heavy_artillery
brigade_model = 1
}
division =
{ id       = { type = 10848 id = 309 }
name     = "10. 'Tulskaya' Pekhot. Div."
type     = infantry
model = 8
strength = 80
}
division =
{ id       = { type = 10848 id = 310 }
name     = "34. Pekhotnaya  Diviziya"
type     = infantry
model = 8
strength = 80
}
division =
{ id       = { type = 10848 id = 311 }
name     = "35. Pekhotnaya  Diviziya"
type     = infantry
model = 8
strength = 80
}
}
landunit =
{ location = 566
name     = "3-y Korpus" # Pskov
id       = { type = 10848 id = 312 }
division =
{ id       = { type = 10848 id = 313 }
name     = "24. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
extra    = artillery
brigade_model = 5
}
division =
{ id       = { type = 10848 id = 314 }
name     = "11. 'Ryazanskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 315 }
name     = "39. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}

division =
{ id       = { type = 10848 id = 319 }
name     = "36. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
extra    = artillery
brigade_model = 5
}
division =
{ id       = { type = 10848 id = 320 }
name     = "12. 'Moskovskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 321 }
name     = "33. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
}

landunit =
{ location = 589 # Smolensk
name     = "2-y Korpus"
id       = { type = 10848 id = 324 }
division =
{ id       = { type = 10848 id = 325 }
name     = "13. 'Pskovskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 20
extra    = artillery
brigade_model = 5
}
division =
{ id       = { type = 10848 id = 326 }
name     = "54. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 327 }
name     = "14. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 328 }
name     = "15. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}

division =
{ id       = { type = 10848 id = 331 }
name     = "20. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
extra    = artillery
brigade_model = 5
}
division =
{ id       = { type = 10848 id = 332 }
name     = "19. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 333 }
name     = "17. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 334 }
name     = "37. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
}


landunit =
{ location = 588 # Bryansk
name     = "4-y Korpus"
id       = { type = 10848 id = 336 }
division =
{ id       = { type = 10848 id = 337 }
name     = "18. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
extra    = artillery
brigade_model = 5
}
division =
{ id       = { type = 10848 id = 338 }
name     = "80. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 339 }
name     = "81. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 340 }
name     = "57. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}

division =
{ id       = { type = 10848 id = 343 }
name     = "20. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
extra    = artillery
brigade_model = 5
}
division =
{ id       = { type = 10848 id = 344 }
name     = "21. Pekhotnaya  Diviziya"
type     = infantry
model    = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 345 }
name     = "38. 'Smolenskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 346 }
name     = "43. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
}

landunit =
{ location = 581 # Oryol
name     = "8-y Korpus"
id       = { type = 10848 id = 506 }
division =
{ id       = { type = 10848 id = 507 }
name     = "118. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
extra    = artillery
brigade_model = 5
}
division =
{ id       = { type = 10848 id = 508 }
name     = "120. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 509 }
name     = "119. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 510 }
name     = "121. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}

division =
{ id       = { type = 10848 id = 356 }
name     = "25. 'Pskovskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 20
extra    = artillery
brigade_model = 5
}
division =
{ id       = { type = 10848 id = 357 }
name     = "26. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 358 }
name     = "28. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 359 }
name     = "46. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
}


landunit =
{ location = 535 # Murmansk
name     = "5-y Korpus"
id       = { type = 10848 id = 361 }
division =
{ id       = { type = 10848 id = 362 }
name     = "27. 'Murmanskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 20
extra    = artillery
brigade_model = 5
}
division =
{ id       = { type = 10848 id = 363 }
name     = "29. 'Murmanskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 364 }
name     = "44. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 365 }
name     = "41. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}

division =
{ id       = { type = 10848 id = 368 }
name     = "30. 'Kemskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 10
}
division =
{ id       = { type = 10848 id = 369 }
name     = "75. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}
division =
{ id       = { type = 10848 id = 370 }
name     = "42. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}
}



landunit =
{ location = 539 # Petrozavodsk
name     = "6-y Korpus"
id       = { type = 10848 id = 375 }
division =
{ id       = { type = 10848 id = 376 }
name     = "48. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}
division =
{ id       = { type = 10848 id = 377 }
name     = "50. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}
division =
{ id       = { type = 10848 id = 378 }
name     = "51. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}
division =
{ id       = { type = 10848 id = 372 }
name     = "47. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}
division =
{ id       = { type = 10848 id = 373 }
name     = "45. 'Petrovskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 10
}
}


landunit =
{ location = 654 #Voronezh
name     = "7-y Korpus"
id       = { type = 10848 id = 387 }
division =
{ id       = { type = 10848 id = 388 }
name     = "86. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}
division =
{ id       = { type = 10848 id = 389 }
name     = "61. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}
division =
{ id       = { type = 10848 id = 390 }
name     = "64. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}

division =
{ id       = { type = 10848 id = 392 }
name     = "63. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}
division =
{ id       = { type = 10848 id = 394 }
name     = "66. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}
division =
{ id       = { type = 10848 id = 393 }
name     = "84. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}

division =
{ id       = { type = 10848 id = 396 }
name     = "62. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}
division =
{ id       = { type = 10848 id = 397 }
name     = "59. 'Saratovskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 10
}
division =
{ id       = { type = 10848 id = 398 }
name     = "92. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}
}


landunit =
{ location = 669 # Saratov
name     = "9-y Korpus"
id       = { type = 10848 id = 399 }
division =
{ id       = { type = 10848 id = 400 }
name     = "60. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}
division =
{ id       = { type = 10848 id = 401 }
name     = "67. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}
division =
{ id       = { type = 10848 id = 402 }
name     = "68. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}

division =
{ id       = { type = 10848 id = 426 }
name     = "79. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 427 }
name     = "83. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 428 }
name     = "90. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
}

landunit = {
location = 663 # Tsarytsin
name = "Tsarytsinskii Voyennii Okrug"
id = { type = 10848 id = 407 }

division = {
id = { type = 10848 id = 408 }
name = "70. Pekhotnaya  Diviziya"
type = infantry
model = 7
strength = 10
}

division = {
id = { type = 10848 id = 409 }
name = "85. Pekhotnaya  Diviziya"
type = infantry
model = 7
strength = 10
}

division = {
id = { type = 10848 id = 410 }
name = "93. Pekhotnaya  Diviziya"
type = infantry
model = 7
strength = 10
}

division = {
id = { type = 10848 id = 404 }
name = "97. Pekhotnaya  Diviziya"
type = infantry
model = 7
strength = 10
}

division = {
id = { type = 10848 id = 405 }
name = "96. Pekhotnaya  Diviziya"
type = infantry
model = 7
strength = 10
}

division = {
id = { type = 10848 id = 406 }
name = "69. Pekhotnaya  Diviziya"
type = infantry
model = 7
strength = 10
}
}

landunit =
{ location = 661
name     = "1yi Kavaleriiski korpus"
id       = { type = 10848 id = 511 }

division = {
id = { type = 10848 id = 512 }
name = "1.Kavaleriiskaya Diviziya"
type = cavalry
model = 8
strength = 30
extra    = artillery
brigade_model = 5
}

division = {
id = { type = 10848 id = 513 }
name = "2.Kavaleriiskaya Diviziya"
type = cavalry
model = 8
strength = 30
}
}

######################
### GROUND FORCES - FAR EAST
######################
landunit =
{ location = 1187 # Sofiysk
name     = "10-y Korpus"
id       = { type = 10848 id = 411 }
division =
{ id       = { type = 10848 id = 412 }
name     = "71. Pekhotnaya  Diviziya"
type     = infantry
model = 8
strength = 50
extra    = artillery
brigade_model = 5
}
division =
{ id       = { type = 10848 id = 413 }
name     = "72. Pekhotnaya  Diviziya"
type     = infantry
model = 8
strength = 50
extra = light_armor_brigade
brigade_model = 2
}
division =
{ id       = { type = 10848 id = 414 }
name     = "77. Pekhotnaya  Diviziya"
type     = infantry
model = 8
strength = 50
}
division =
{ id       = { type = 10848 id = 415 }
name     = "82. Pekhotnaya  Diviziya"
type     = infantry
model = 8
strength = 50
}
}

landunit =
{ location = 1188 # Elban
name     = "11-y Korpus"
id       = { type = 10848 id = 417 }
division =
{ id       = { type = 10848 id = 418 }
name     = "73. 'Birobidzanskaya' Pekhot. Div."
type     = infantry
model = 8
strength = 50
extra    = artillery
brigade_model = 5
}
division =
{ id       = { type = 10848 id = 419 }
name     = "74. 'Sibirskaya' Pekhot. Div."
type     = infantry
model = 8
strength = 50
}
division =
{ id       = { type = 10848 id = 420 }
name     = "78. Pekhotnaya  Diviziya"
type     = infantry
model = 8
strength = 50
}
division =
{ id       = { type = 10848 id = 421 }
name     = "87. Pekhotnaya  Diviziya"
type     = infantry
model = 8
strength = 50
}
}

landunit =
{ location = 1175 # Birobidzhan
name     = "12-y Korpus"
id       = { type = 10848 id = 449 }
division =
{ id       = { type = 10848 id = 450 }
name     = "101. 'Novosibirskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 20
}

division =
{ id       = { type = 10848 id = 385 }
name     = "58. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}
division =
{ id       = { type = 10848 id = 386 }
name     = "89. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 10
}

}

landunit =
{ location = 1140
name     = "14-y Korpus"
id       = { type = 10848 id = 462 }
division =
{ id       = { type = 10848 id = 463 }
name     = "102. 'Irkutskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 20
}
}
landunit =
{ location = 1143
name     = "13-y Korpus"
id       = { type = 10848 id = 464 }
division =
{ id       = { type = 10848 id = 465 }
name     = "104. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
}
landunit =
{ location = 1145
name     = "15-y Korpus"
id       = { type = 10848 id = 466 }
division =
{ id       = { type = 10848 id = 467 }
name     = "106. 'Omskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 20
}
}
landunit =
{ location = 1144
name     = "18-y Korpus"
id       = { type = 10848 id = 468 }
division =
{ id       = { type = 10848 id = 469 }
name     = "107. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
}
landunit =
{ location = 1156
name     = "16-y Korpus"
id       = { type = 10848 id = 470 }
division =
{ id       = { type = 10848 id = 471 }
name     = "108. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
}
landunit =
{ location = 1157
name     = "17-y Korpus"
id       = { type = 10848 id = 473 }
division =
{ id       = { type = 10848 id = 472 }
name     = "109. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
}
landunit =
{ location = 1069
name     = "19-y Korpus"
id       = { type = 10848 id = 474 }
division =
{ id       = { type = 10848 id = 476 }
name     = "111. 'Orskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 20
}
}

landunit = { location = 1162
name     = "Irkutskii Voyennii Okrug"
id       = { type = 10848 id = 477 }
division = {
id       = { type = 10848 id = 478 }
name     = "115. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
division = {
id       = { type = 10848 id = 455 }
name     = "105. 'Orskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 20
}
division = {
id       = { type = 10848 id = 457 }
name     = "103. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}

division = {
id       = { type = 10848 id = 349 }
name     = "22. 'Smolenskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 20
extra    = artillery
brigade_model = 5
}
division = {
id       = { type = 10848 id = 350 }
name     = "40. 'Ryazanskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 20
}
division = {
id       = { type = 10848 id = 351 }
name     = "31. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
}

landunit =
{ location = 1166
name     = "20-y Korpus"
id       = { type = 10848 id = 479 }
division =
{ id       = { type = 10848 id = 480 }
name     = "112. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
}
landunit =
{ location = 1161
name     = "21-y Korpus"
id       = { type = 10848 id = 481 }
division =
{ id       = { type = 10848 id = 482 }
name     = "113. 'Novosibirskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 10
}
}
landunit =
{ location = 1176
name     = "22-y Korpus"
id       = { type = 10848 id = 500 }
division =
{ id       = { type = 10848 id = 501 }
name     = "115. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
}
landunit =
{ location = 1174
name     = "25-y Korpus"
id       = { type = 10848 id = 502 }
division =
{ id       = { type = 10848 id = 503 }
name     = "116. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
}
landunit =
{ location = 1189
name     = "23-y Korpus"
id       = { type = 10848 id = 504 }
division =
{ id       = { type = 10848 id = 505 }
name     = "117. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
division =
{ id       = { type = 10848 id = 384 }
name     = "55. 'Slobodskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 10
}

}



landunit =
{ location = 1170
name     = "24-y Korpus"
id       = { type = 10848 id = 484 }
division =
{ id       = { type = 10848 id = 483 }
name     = "114. 'Blagoveshchenskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 10
}
}
######################
### GROUND FORCES CENTRAL ASIA
######################

landunit = {
location = 1132 # Chelyabinsk
name = "26-y Korpus"
id = { type = 10848 id = 443 }

division = {
id = { type = 10848 id = 444 }
name = "99. Pekhotnaya  Diviziya"
type = infantry
model = 7
strength = 20
}

division = {
id = { type = 10848 id = 441 }
name = "94. Pekhotnaya  Diviziya"
type = infantry
model = 7
strength = 20
}

division = {
id = { type = 10848 id = 434 }
name = "93. Pekhotnaya  Diviziya"
type = infantry
model = 7
strength = 20
}

division = {
id = { type = 10848 id = 430 }
name = "91. Pekhotnaya  Diviziya"
type = infantry
model = 7
strength = 20
}
}



landunit = { location = 1138
name     = "Omskii Voyennii Okrug"
id       = { type = 10848 id = 460 }
division = {
id       = { type = 10848 id = 461 }
name     = "110. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}

division = {
id       = { type = 10848 id = 517 }
name     = "32. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}

division = {
id       = { type = 10848 id = 447 }
name     = "97. 'Kemerovskaya' Pekhot. Div."
type     = infantry
model = 7
strength = 20
}

division = {
id       = { type = 10848 id = 519 }
name     = "49. Pekhotnaya  Diviziya"
type     = infantry
model = 7
strength = 20
}
}




######################
### RUSSIAN NAVY
######################




navalunit =
{ id       = { type = 17351 id = 5113 }
name     = "Severniy Flot"
location = 535 # Murmansk
base     = 535
leader   = 599722

division =
{ id    = { type = 17351 id = 1200 }
name  = "2. Flotiliya Esmintsev"
type  = destroyer
model = 3
}
division =
{ id    = { type = 17351 id = 1201 }
name  = "3. Flotiliya Esmintsev"
type  = destroyer
model = 3
}
division =
{ id    = { type = 17351 id = 1202 }
name  = "1. Flotiliya Podlodok 'Mir'"
type  = submarine
model = 2
}
division =
{ id    = { type = 17351 id = 1203 }
name  = "2. Flotiliya Podlodok 'Rusalka'"
type  = submarine
model = 1
}
division =
{ id    = { type = 17351 id = 1254 }
name  = "9. Flotiliya Podlodok"
type  = submarine
model = 1
}
division =
{ id    = { type = 17351 id = 1255 }
name  = "10. Flotiliya Podlodok"
type  = submarine
model = 1
}
division =
{ id    = { type = 17351 id = 1256 }
name  = "11. Flotiliya Podlodok"
type  = submarine
model = 1
}
division =
{ id    = { type = 17351 id = 1257 }
name  = "Murmansk"
type  = light_cruiser
model = 2
}
}
navalunit =
{ id       = { type = 17351 id = 5114 }
name     = "Baltijskij Flot"
location = 553 # Leningrad
base     = 553
leader   = 500725
division =
{ id    = { type = 17351 id = 1204 }
name  = "Gangut"
type  = battleship
model = 2
}
division =
{ id    = { type = 17351 id = 1205 }
name  = "Poltava"
type  = battleship
model = 2
}
division =
{ id    = { type = 17351 id = 1270 }
name  = "Petropavlovsk"
type  = battleship
model = 2
}
division =
{ id    = { type = 17351 id = 1271 }
name  = "Sevastopol"
type  = battleship
model = 2
}
division =
{ id    = { type = 17351 id = 1272 }
name  = "Izmail"
type  = battlecruiser
model = 1
}
division =
{ id    = { type = 17351 id = 1207 }
name  = "1. Flotiliya Esmintsev"
type  = destroyer
model = 4
}
division =
{ id    = { type = 17351 id = 1262 }
name  = "6. Flotiliya Esmintsev"
type  = destroyer
model = 4
}
division =
{ id    = { type = 17351 id = 1208 }
name  = "3. Flotiliya Podlodok"
type  = submarine
model = 2
}
division =
{ id    = { type = 17351 id = 1209 }
name  = "4. Flotiliya Podlodok"
type  = submarine
model = 2
}
division =
{ id    = { type = 17351 id = 1210 }
name  = "5. Flotiliya Podlodok"
type  = submarine
model = 2
}
division =
{ id    = { type = 17351 id = 1211 }
name  = "6. Flotiliya Podlodok"
type  = submarine
model = 1
}
division =
{ id    = { type = 17351 id = 1212 }
name  = "7. Flotiliya Podlodok"
type  = submarine
model = 1
}
division =
{ id    = { type = 17351 id = 1213 }
name  = "8. Flotiliya Podlodok"
type  = submarine
model = 1
}
division =
{ id    = { type = 17351 id = 1214 }
name  = "Svoboda"
type  = heavy_cruiser
model = 2
}
division =
{ id    = { type = 17351 id = 1215 }
name  = "Rurik"
type  = light_cruiser
model = 2
}
division =
{ id    = { type = 17351 id = 1216 }
name  = "Admiral Nahimov"
type  = light_cruiser
model = 2
}
}
navalunit =
{ id       = { type = 17351 id = 1259 }
name     = "Sibirskoy Flot"
location = 1186 # Okhotsk
base     = 1186
leader   = 500713
division =
{ id    = { type = 17351 id = 1264 }
name  = "Rossiya"
type  = heavy_cruiser
model = 2
}
division =
{ id    = { type = 17351 id = 1263 }
name  = "Vostok"
type  = light_cruiser
model = 2
}
division =
{ id    = { type = 17351 id = 1260 }
name  = "4. Flotiliya Esmintsev"
type  = destroyer
model = 4
}
division =
{ id    = { type = 17351 id = 1261 }
name  = "5. Flotiliya Esmintsev"
type  = destroyer
model = 4
}

}

######################
### RUSSIAN AIR FORCE
######################
airunit =
{ id       = { type = 10848 id = 9961 }
name     = "Petrograd I. AD"
location = 553
base     = 553
division =
{ id       = { type = 10848 id = 9962 }
name     = "1-y Vozd. Otryad"
strength = 40
type     = interceptor
model    = 6
}
division =
{ id       = { type = 10848 id = 9963 }
name     = "2-y Vozd. Otryad"
strength = 100
type     = interceptor
model    = 6
}
}
airunit =
{ id       = { type = 10848 id = 9964 }
name     = "Pskov II. AD"
location = 566
base     = 566
division =
{ id       = { type = 10848 id = 9965 }
name     = "4-y Vozd. Otryad"
strength = 85
type     = interceptor
model = 6
}
}
airunit =
{ id       = { type = 10848 id = 9973 }
name     = "Moskva IV. AD"
location = 572
base     = 572
division =
{ id       = { type = 10848 id = 9974 }
name     = "3-y Vozd. Otryad"
strength = 40
type     = interceptor
model = 6
}
division =
{ id       = { type = 10848 id = 9975 }
name     = "1-y Bomb. Aviaotryad"
strength = 30
type     = tactical_bomber
model    = 4
}
}
airunit =
{ id       = { type = 10848 id = 9977 }
name     = "Amurskiy III. AD"
location = 1189
base     = 1189
division =
{ id       = { type = 10848 id = 9978 }
name     = "5-y Vozd. Otryad"
strength = 80
type     = interceptor
model = 6
}
division =
{ id       = { type = 10848 id = 9979 }
name     = "2-y Bomb. Aviaotryad"
strength = 40
type     = tactical_bomber
model    = 4
}
}

######################
### UNITS IN DEVELOPMENT
######################

division_development =
{ name  = "7. Flotiliya Esmintsev"
type  = destroyer
model = 5
cost  = 2
id    = { type = 17351 id = 8500 }
date  = { year = 1936 month = april day = 1 }
}

division_development =
{ name  = "12. Flotiliya Podlodok"
type  = submarine
model = 4
cost  = 1.9
id    = { type = 10848 id = 8501 }
date  = { year = 1936 month = february day = 1 }
}

division_development =
{ name  = "13. Flotiliya Podlodok"
type  = submarine
model = 4
cost  = 1.9
id    = { type = 10848 id = 8502 }
date  = { year = 1936 month = march day = 1 }
}
}