


country = {
    tag = SPA  
ai = "kaiserreich\Spain.ai"

	policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 6
        political_left = 2
        freedom = 6
        free_market = 4
        professional_army = 3
        defense_lobby = 4
        interventionism = 5
    }


#### cabinet
headofstate = { type = 9 id = 10039 }
	headofgovernment = { type = 9 id = 10054 }
 	ministerofintelligence = { type = 9 id = 10126  }
#### Resource Reserves

	manpower = 250
	energy	=	1000   metal	= 1000		rare_materials =	500	oil =	500	supplies =	500
	money = 20

        SpyInfo  = {  country = "SPA" NumberOfSpies = 3  } 

	dissent = 35
	capital = 460


    nationalprovinces   = {   444 451 441 453 466 456 460 457 458 472 474 471 470 467 463 468 464 461  
               348 440 438 436 442 443 475 437 439 452 447 990 991 469 
 455 448 449 446 462 445 459 473 465 454   450               } 
  
  ownedprovinces     = {   441 444 451 466 453 460 458 472 474 471 470 467 463 468 464 457 461 456 442 443 436 438 440 475  
               437 439 452 447 990 991  469  715   987 988 913 348
  446 
 449 448 455 454 465 473 
 462 459 445 450 
 989  716 916   
                 } 
 
  controlledprovinces  = {   441 444 451 466 453 460 458 472 474 471 470 467 463 468 464 457 461 456 442 443 436 438 440 475  
               437 439 452 447 990 991   715   987 988 913 348
  446 469 450 
 449 448 455 454 465 473 
 462 459 445  
 989  716 916  
                 } 

diplomacy = {
relation = {   tag =    	BEL	value = 		40	   }  
relation = {   tag =  	BLR	 value =		30	   }  
relation = {   tag =  	BUL	value = 		60	   }  
relation = {   tag =  	GER	 value =		90	   }  
relation = {   tag =  	LAT	value = 		20	   }  
relation = {   tag =  	LIT	 value =		20	   }  
relation = {   tag =  	POL	value = 		20	   }  
relation = {   tag =  	UKR	 value =		10	   }  
relation = {   tag =  	AUS	value = 		120	   }  
relation = {   tag =  	BOS	value = 		40	   }  
relation = {   tag =  	CRO	 value =		60	   }  
relation = {   tag =  	CZE	value = 		40	   }  
relation = {   tag =  	GLD	value = 		20	   }  
relation = {   tag =  	HUN	 value =		50	   }  
relation = {   tag =  	ALB	value = 		-30	   }  
relation = {   tag =  	DEN	 value =		40	   }  
relation = {   tag =  	FIN	value = 		20	   }  
relation = {   tag =  	GRE	value = 		-40	   }  
relation = {   tag =  	HOL	 value =		50	   }  
relation = {   tag =  	IRE	value = 		20	   }  
relation = {   tag =  	ITA	value = 		90	   }  
relation = {   tag =  	POR	value = 		120	   }  
relation = {   tag =  	ROM	value = 		40	   }  
relation = {   tag =  	ENG	value = 		-90	   }  
relation = {   tag =  	FRA	value = 		-120	   }  
relation = {   tag =  	RSI	 value =		-60	   }  
relation = {   tag =  	AST	value = 		20	   }  
relation = {   tag =  	CAN	value = 		90	   }  
relation = {   tag =  	GUY	value = 		40	   }  
relation = {   tag =  	NZL	 value =		10	   }  
relation = {   tag =  	VIC	value = 		80	   }  
relation = {   tag =  	RUS	 value =		50	   }  
relation = {   tag =  	OTT	 value =		40	   }  
relation = {   tag =  	CON	value = 		50	   }  
relation = {   tag =  	ARG	value = 		50	   }  
relation = {   tag =  	BOL	value = 		20	   }  
relation = {   tag =  	BRA	 value =		20	   }  
relation = {   tag =  	COL	value = 		40	   }  
relation = {   tag =  	COS	 value =		30	   }  
relation = {   tag =  	CUB	value = 		20	   }  
relation = {   tag =  	DOM	value = 		30	   }  
relation = {   tag =  	ECU	 value =		30	   }  
relation = {   tag =  	GUA	value = 		20	   }  
relation = {   tag =  	HAI	value = 		20	   }  
relation = {   tag =  	HON 	 value =		20	   }  
relation = {   tag =  	MEX	value = 		20	   }  
relation = {   tag =  	NIC	value = 		30	   }  
relation = {   tag =  	PAN	value = 		20	   }  
relation = {   tag =  	PAR	value = 		40	   }  
relation = {   tag =  	PRU	value = 		30	   }  
relation = {   tag =  	SAL	 value =		20	   }  
relation = {   tag =  	URU	value = 		20	   }  
relation = {   tag =  	VEN	value = 		20	   }  
relation = {  tag =   	USA	value = 		-40	 }
relation = {   tag =  	JAP	value = 		-10	   } 
}


	
	techapps = {
#Aircrafts
4500 4510 4520 4530 4540 4550 4010 4020 #Early Fighter
4600 4610 4620 4630 4120 #Interwar Bomber
4300 4310 4320 4330 #Multirole fighter
4800 4810 4820 #ww1 strategic bomber
4700 4710 #ww1 navalbomber

#Armour & Artillery
2860 2870 2880 2020 #Basic Armoured Car
7600 7610 2620 2010 2630 2640 #Tankette
2290 2300 2310 #Great War Heavy Field Artillery 
2800 2450 21180 21190 #Early Static Anti-Air Artillery 
2810 2820 2510 #Basic Anti-Air Artillery Brigade 

#Infantry
1910 1920 1930 1940 1950 1960 #Interbellum Supply 
1830 1840 1850 1860 #Engineers
1010  1020 1030 1040 1050 1060 1070 1080 #Great War Infantry Division
13060 13070 13080 1310 1320 1330 1340 #Great War Cavalry Division  
1160  1170 1180 1190 1200 1210 1220 1230 1240 #Early Mountain Division 

#Naval
3410 3420 3430 3440 #early ww1. It seems that they did not invest in BBs.
3210 3220 3230 3240 3250 #Improved Heavy Cruiser, just at the gates of the Canarias class
3610 3620 3630 3640 #1924 sub
3110 3120 3130 3140 #Interwar Light Cruiser 
3010 3020 3030 3040 3050 3060 #Improved Destroyer 
3720 3730 3736 3740 3750 3900 #Torpedo & ASW 18
12100 #Seaplane Tender Dédalo
3810 #Troopships

#Industrial
5700 5710 5010 #Modern Agriculture 
5310 54010 54020 54030 5316 5326 #Computers & cryptografi
5810 5820 5050 5830 #Manufactoring
5800 5080 5090 #Improved Construction Engineering 
5190 #Basic Oil Refining 
5600 5610 5620 #Medicine

#Land Doctrines

14000 14010 #Improved Great War Hospital System
6500 6510 6530 6580 6600 6610 6620 6630 6640 6650 6660 6670 6680 6540 6910
6010 6020 # Superior Firepower

#Naval Doctrines
8010 8020 8040 8050 

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010





	}

#########  OOB (...)



	landunit = {
	id = { type = 27600 id = 5 }
	location = 460
	name = "1a Cuerpo de Ejército"

		division = {
		id = { type = 27600 id = 6 }
		name = "1a División Orgánica"
		type = infantry
		model = 7
		}

		division = {
		id = { type = 27600 id = 7 }
		name = "2a División Orgánica"
		type = infantry
		model = 7
                extra = artillery
		}

		division = {
		id = { type = 27600 id = 8 }
		name = "1a División de Caballería"
		type = cavalry
		model = 7
		extra = light_armor_brigade
		brigade_model = 1
		}
		}


	landunit = {
	id = { type = 27600 id = 10 }
	location = 438
	name = "2o Cuerpo del Ejército"

		division = {
		id = { type = 27600 id = 11 }
		name = "3a División Orgánica"
		type = infantry
		model = 6
                extra = anti_tank
		brigade_model = 3
		}

		division = {
		id = { type = 27600 id = 12 }
		name = "4a División Orgánica"
		type = infantry
		model = 6
		}

		division = {
		id = { type = 27600 id = 13 }
		name = "5a División Orgánica"
		type = infantry
		model = 6
		}

		division = {
		id = { type = 27600 id = 14 }
		name = "Brigadas de Montaña"
		type = bergsjaeger
		model = 6
		}
		}

	landunit = {
		id = { type = 27600 id = 15 }
		location = 446
		name = "3er Cuerpo de Ejército"

		division = {
		id = { type = 27600 id = 16 }
		name = "6a División Orgánica"
		type = infantry
		model = 7
                extra = anti_air
		}

		division = {
		id = { type = 27600 id = 17 }
		name = "7a División Orgánica"
		type = infantry
		model = 7
		}

		division = {
		id = { type = 27600 id = 18 }
		name = "8a División Orgánica"
		type = infantry
		model = 7
		extra = artillery
                brigade_model = 3
		}
		}

	landunit = {
	id = { type = 27600 id = 19 }
	location = 475
	name = "Comandancia de Baleares"

		division = {
		id = { type = 27600 id = 20 }
		name = "Comandancia de Baleares"
		type = infantry
		model = 6
		strength = 30
		}
		}

	landunit = {
	id = { type = 27600 id = 21 }
	location = 991
	name = "Comandancia de Canarias"

		division = { id = { type = 27600 id = 22 }
		name = "Comandancia de Canarias"
		type = infantry
		model = 6
		strength = 30
		}
		}

	landunit = {
	id = { type = 27600 id = 23 }
	location = 715
	name = "Ejército de África"

		division = {
		id = { type = 27600 id = 24 }
		name = "Circunscripción Occidental"
		type = infantry
		model = 6
		}

		division = {
		id = { type = 27600 id = 25 }
		name = "Circunscripción Oriental"
		type = infantry
		model = 6
		}
		}

	landunit = {
	id = { type = 27600 id = 26 }
	location = 988
	name = "Fuerzas del Sahara"

		division = {
		id = { type = 27600 id = 27 }
		name = "Legión del Sahara"
		type = infantry
		model = 6
		strength = 30
		}
		}

	landunit = {
	id = { type = 27600 id = 28 }
	location = 988
	name = "Guardias Coloniales"

		division = {
		id = { type = 27600 id = 29 }
		name = "Guardias Coloniales"
		type = d_01
		model = 6
		strength = 30
		}
		}

	landunit = {
		name = "Fuerza de Gibraltar"
		location = 348
		id = { type = 12700 id = 12 }
		division = {
			id = { type = 12700 id = 13 }
			name = "Fuerza de Defensa de Gibraltar"
			type = garrison
			model = 4
			strength = 100 }
	}



	#Some naval units were clearly outdated or in bad fighting shape. Strength has been reduced in those cases.

	navalunit = {
     location = 473
     base = 473
     id = { type = 27600 id = 30 }
     name = "Base Naval Cádiz"

     division = { id = { type = 27600 id = 31 } name = "Reina Victoria Eugenia" strength = 60 type = light_cruiser model = 2 }
     division = { id = { type = 27600 id = 32 } name = "Flotilla de Escolta" strength = 100 type = destroyer model = 4 }
     }

     navalunit = {
     location = 473
     base = 473
     id = { type = 27600 id = 33 }
     name = "Flotilla Méndez Núnez"

     division = { id = { type = 27600 id = 34 } name = "Méndez Núnez" strength = 100 type = light_cruiser model = 2 }
     }

     navalunit = {
     location = 441
     base = 441
     id = { type = 27600 id = 35 }
     name = "Escuadrón de Batalla"
     division = { id = { type = 27600 id = 36 } name = "Jaime I" strength = 50 type = battleship model = 2 }
     division = { id = { type = 27600 id = 37 } name = "Alfonso XIII" strength = 100 type = battleship model = 2 }
     division = { id = { type = 27600 id = 38 } name = "Miguel de Cervantes" strength = 100 type = light_cruiser model = 3 }
     division = { id = { type = 27600 id = 39 } name = "Almirante Cervera" strength = 100 type = light_cruiser model = 3 }
     division = { id = { type = 27600 id = 40 } name = "Flotilla de Torpederas No. 1" strength = 100 type = destroyer model = 3 }
     division = { id = { type = 27600 id = 41 } name = "Flotilla de Torpederas No. 2" strength = 100 type = destroyer model = 4 }
     division = { id = { type = 27600 id = 42 } name = "1a Flotilla de Transporte Naval" strength = 100 type = transport model = 1 }
     division = { id = { type = 27600 id = 43 } name = "2a Flotilla de Transporte Naval" strength = 100 type = transport model = 1 }
     }

     navalunit = {
     location = 715
     base = 715
     id = { type = 27600 id = 44 }
     name = "Armada Colonial"

     division = { id = { type = 27600 id = 45 } name = "Flotilla de Torpederas No. 3" strength = 100 type = destroyer model = 4 }
     division = { id = { type = 27600 id = 47 } name = "3a Flotilla de Transporte Naval" strength = 100 type = transport model = 1 }
     division = { id = { type = 27600 id = 48 } name = "4a Flotilla de Transporte Naval" strength = 100 type = transport model = 1 }
     }

     navalunit = {
     location = 715
     base = 715
     id = { type = 27600 id = 49 }
     name = "Grupo C"

         division = { id = { type = 27600 id = 50 } name = "S101 Flotilla" strength = 100 type = submarine model = 1 }
     }

 navalunit = {
 location = 473
 base = 473
 id = { type = 27600 id = 51 }
 name = "Grupo B"
         division = { id = { type = 27600 id = 72 } name = "S103 Flotilla" strength = 75 type = submarine model = 1 }
     }

     navalunit = {
         id = { type = 27600 id = 73 }
         name = "Principe Alfonso"
         location = 473
         base = 473
         division = {
             id = { type = 27600 id = 74 }
             name = "Principe Alfonso"
             type = light_cruiser
                model = 3
                strength = 100
            }
        }

	navalunit = {
		id = { type = 27600 id = 75 }
		name = "ARE Libertad"
		location = 473
		base = 473
		division = {
			id = { type = 27600 id = 76 }
			name = "ARE Libertad"
			type = light_cruiser
	   		model = 3
	   		strength = 100
   		}
   	}

	airunit = { location = 460 base = 460 id = { type = 27600 id = 55 } name = "1a Escuadra Aérea"
		division = { id = { type = 27600 id = 56 } name = "1er Grupo Táctico" strength = 30 type = tactical_bomber model = 4 }
		division = { id = { type = 27600 id = 57 } name = "2o Grupo Táctico" strength = 30 type = tactical_bomber model = 4 }
	}

	airunit = { location = 348 base = 348 id = { type = 27600 id = 58 } name = "2a Escuadra Aérea"
		division = { id = { type = 27600 id = 59 } name = "1er Grupo de Caza" strength = 30 type = interceptor model = 6 }
		division = { id = { type = 27600 id = 60 } name = "3er Grupo de Caza" strength = 30 type = interceptor model = 6 }
	}

	airunit = { location = 440 base = 440 id = { type = 27600 id = 61 } name = "3a Escuadra Aérea"
		division = { id = { type = 27600 id = 62 } name = "1er Grupo Estratégico" strength = 30 type = strategic_bomber model = 2 }
		division = { id = { type = 27600 id = 63 } name = "2o Grupo Estratégico" strength = 30 type = strategic_bomber model = 2 }
	}

	airunit = {
		location = 715
		base = 715
		id = { type = 27600 id = 64 }
		name = "Fuerzas Aéreas del África"
		division = { id = { type = 27600 id = 65 } name = "1er Grupo de Bombardeo" strength = 30 type = tactical_bomber model = 4 }
		division = { id = { type = 27600 id = 66 } name = "2o Grupo de Caza" strength = 30 type = interceptor model = 6 }
	}

division_development = {
	name = "ARE Canarias"
	type = heavy_cruiser
	model = 3
	cost = 5
	id = { type = 27600 id = 500 }
	date = { year = 1936 month = march day = 1 }
	}

division_development = {
	name = "ARE Baleares"
	type = heavy_cruiser
	model = 3
	cost = 5
	id = { type = 27600 id = 501 }
	date = { year = 1936 month = june day = 1 }
	}



#########
###  FRENCH BORDER DEFENCE
########




	landunit = {
	location = 437
	name = "8o Cuerpo de Ejército"
        id = { type = 27600 id = 505  }
		division = { 
		id = { type = 27600 id = 506 } 
		name = "9a División Orgánica" 
		type = infantry
		model = 6
		strength = 70

		}

		division = { 
		id = { type = 27600 id = 507 } 
		name = "10a División Orgánica" 
		type = infantry
		model = 6
		strength = 70
		}  
 }


	landunit = {
	location = 443
	name = "9o Cuerpo de Ejército"
        id = { type = 27600 id = 508 }
		division = { 
		id = { type = 27600 id = 509 } 
		name = "11a División Orgánica" 
		type = infantry
		model = 6
		strength = 70

		}

		division = { 
		id = { type = 27600 id = 510 } 
		name = "12a División Orgánica" 
		type = infantry
		model = 6
		strength = 70
		}  
 }


	landunit = {
	location = 440
	name = "10mo Cuerpo de Ejército"
        id = { type = 27600 id = 511 }
		division = { 
		id = { type = 27600 id = 512  } 
		name = "13a División Orgánica" 
		type = infantry
		model = 6
		strength = 70

		}

		division = { 
		id = { type = 27600 id = 513  } 
		name = "14a División Orgánica" 
		type = infantry
		model = 6
		strength = 70
		}  
 }
transports = 100
escorts = 27
}  