


country = {
    tag = USA

ai = "kaiserreich\usa.ai"
	policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 10
        political_left = 6
        freedom = 10
        free_market = 10
        professional_army = 1
        defense_lobby = 1
        interventionism = 1
    }
	headofstate = { type = 9 id = 6229 }
	headofgovernment = { type = 9 id = 6230 }
 	foreignminister = { type = 9 id = 6061 }
 	armamentminister = { type = 9 id = 6231 }
 	ministerofsecurity = { type = 9 id = 6232 }
 	ministerofintelligence = { type = 9 id = 6130 }
 	chiefofstaff = { type = 9 id = 6233 }
 	chiefofarmy = { type = 9 id = 6182 }
 	chiefofnavy = { type = 9 id = 6183 }        
 	chiefofair = { type = 9 id = 6237  }




 	peacetime_ic_mod = 0.13

#### Resource Reserves
	energy	=	1000   metal	= 1000		rare_materials =	500	oil =	500	supplies =	500
	money = 100

        SpyInfo  = {  country = "USA" NumberOfSpies = 5  } 

	manpower = 0

	transports = 250
	escorts = 53
	dissent = 16

capital = 1809

    ownedprovinces =      {
		1953 1833 1949 1948 1952 1951 1950 1947 1956 1954  1955 1960 1958 1963  1961 1962 1964 1813 1812  1814 1818 1815 1816 1817 1809  
               1808 1807 1801 1797 1791 1795 1793  1792 1805 1803 1804  1790  1787 1788 1784 1785  1789 1796 1826 1806  
               1810 1811 1820 1819 1942 1943 1940  1939 1936 1937 1944 1931 1825 1821 1842 1845 1802 1957 1828 1934 1930 1929 1932 1918 1915   
               1925  1836 1830 1829 1832 1839 1838 1841 1843 1834 1837 2150 1846 1850 1855 1856 1858 1857 1859  
               1860  1914 1913  1919 1910 1911  1924 1928 1926 1920  1921 1922  1905 1906 1904 1900  1901  
               1902 1898 1896 1907 1908 1897 1909 1868 1866   1862    1869  1865  1871  1873 1875 1876 1874   
               1877 1878 1882  1879 1880  1895 1893  1892 1899 1886 1887 1883 1888 1889 1884 2141  2140 2142 2139   
                    1923   1765 889 1736 1737 1735  1739 1734 1738 1673 1683  
  1747 
 1733 1751 1745 
 1778 1831 
 1872 1863 1864 1847 1935 1945 1885 
           
 2151 2143 2144 2145 2146 2147 2174 1890 1891 1894 1881 
 1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800 
 1794 1824 1798 1799 1786 1938 
	 }
    controlledprovinces = {
		1953 1833 1949 1948 1952 1951 1950 1947 1956 1954  1955 1960 1958 1963  1961 1962 1964 1813 1812  1814 1818 1815 1816 1817 1809  
               1808 1807 1801 1797 1791 1795 1793  1792 1805 1803 1804  1790  1787 1788 1784 1785  1789 1796 1826 1806  
               1810 1811 1820 1819 1942 1943 1940  1939 1936 1937 1944 1931 1825 1821 1842 1845 1802 1957 1828 1934 1930 1929 1932 1918 1915   
               1925  1836 1830 1829 1832 1839 1838 1841 1843 1834 1837 2150 1846 1850 1855 1856 1858 1857 1859  
               1860  1914 1913  1919 1910 1911  1924 1928 1926 1920  1921 1922  1905 1906 1904 1900  1901  
               1902 1898 1896 1907 1908 1897 1909 1868 1866   1862    1869  1865  1871  1873 1875 1876 1874  
               1877 1878 1882  1879 1880  1895 1893  1892 1899 1886 1887 1883 1888 1889 1884 2141  2140 2142 2139   
                    1923   1765 889 1736 1737 1735  1739 1734 1738 1673 1683 1747 
  1733 1751 1745 
 1778 1831 
 1872 1863 1864 1847 1935 1945 1885 
            
 2151 2143 2144 2145 2146 2147 2174 1890 1891 1894 1881 
 1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800 
 1794 1824 1798 1799 1786 1938 
	  }
    nationalprovinces =   {
		1809 1953 1833 1949 1948 1952 1951 1950 1947 1956 1954 1955 1960 1958 1963 1961 
 1962 1964 1813 1812 1814 1818 1815 1816 1817 1808 1807 1801 1797 1791 1795 1793  
 1792 1805 1803 1804 1790 1787 1788 1784 1785 1789 1796 1826 1806 
 1810 1811 1820 1819 1942 1943 1940 1939 1936 1937 1944 1931 1825 1821 1842 1845 1802 
 1957 1828 1934 1930 1929 1932 1918 1915 1925 1836 1830 1829 1832 1839 
 1838 1841 1843 1834 1837 2150 1846 1850 1855 1856 1858 1857 1859 
 1860 1914 1913 1919 1910 1911 1924 1928 1926 1920 1921 1922 
 1905 1906 1904 1900 1901 1902 1898 1896 1907 1908 1897 1909 
 1868 1866 1862 1869 1865 1871 1873 1875 1876 1874 
 1877 1878 1882 1879 1880 1895 1893 1892 1899 1886 1887 1883 
 1888 1889 1884 2141 2140 2142 2139 
 1923 
 1831 1847 1935 1945 1885 1872 1863 1864 1778 
 2151 2143 2144 2145 2146 2147 2174 1890 1891 1894 1881 
 1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800 
 1794 1824 1798 1799 1786 1938
	}

diplomacy = {
relation = { tag = ARG value = 75 }
relation = { tag = AST value = 125 }
relation = { tag = BEL value = 75 }
relation = { tag = BHU value = 100 }
relation = { tag = BOL value = 85 }
relation = { tag = BRA value = 120 }
relation = { tag = CAN value = 75 }
relation = { tag = CHL value = 100 }
relation = { tag = COL value = 75 }
relation = { tag = COS value = 100 }
relation = { tag = CUB value = 200 }
relation = { tag = DEN value = 75 }
relation = { tag = DOM value = 125 }
relation = { tag = ECU value = 75 }
relation = { tag = ENG value = 150 }
relation = { tag = FIN value = -90 }
relation = { tag = FRA value = -65 }
relation = { tag = GER value = -60 }
relation = { tag = GUA value = 125 }
relation = { tag = HAI value = 100 }
relation = { tag = HOL value = 70 }
relation = { tag = HON value = 100 }
relation = { tag = IRE value = 75 }
relation = { tag = VIC value = 75 }
relation = { tag = IRQ value = 120 }
relation = { tag = JAP value = 15 }
relation = { tag = LIB value = 200 access = yes }
relation = { tag = MAN value = 1 }
relation = { tag = MEX value = 125 }
relation = { tag = NEP value = 100 }
relation = { tag = NIC value = 100 }
relation = { tag = NOR value = 75 }
relation = { tag = NZL value = 125 }
relation = { tag = OMN value = 100 }
relation = { tag = PAN value = 175 }
relation = { tag = PAR value = 75 }
relation = { tag = PHI value = 200 access = yes }
relation = { tag = PRU value = 75 }
relation = { tag = SAF value = 125 }
relation = { tag = SAL value = 100 }
relation = { tag = SOV value = 35 }
relation = { tag = SCH value = 1 }
relation = { tag = SWE value = 75 }
relation = { tag = VEN value = 125 }
relation = { tag = EAF value = 60 } 
}


	
	techapps = {
# USA 1936 techs
#######################

#Aircrafts
4500 4510 4520 4530 4540 4550 4010 4020 #Early Fighter  
4600 4610 4620 4630 4120 4130 #Early Bomber 
4290 4250 #Basic Air Transport 
4800 4810 4820 4220 #Basic Strategic Bomber
4300 4310 4320 4330 4340 #Multirole fighter 
4700 4710 #ww1 navalbomber	
4740 4750 4760 4770 #Seaplanes
4900 4910 4920 #CAG 34
7290 7300 7310 7320 4400 #CAS

#Armour & Artillery
2860 2870 2880 2020 #Armoured Cars 
7600 7610 2620 2010 2630 #Great War Tank 
2290 2300 2310 2900 2910 2920 #Great War Heavy Field Artillery 
2800 2450 21180 21190 21200 #Early Static Anti-Air Artillery
2810 2820 2510 #Basic Anti-Air Artillery Brigade

#Infantry
1010  1020 1030 1040 1050 1060 1070 1080 1090 #Great War Infantry Division 
13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 #1932 Cavalry Division 
1910 1920 1930 1940 1950 1960 1970 1980 #Interbellum 1930 Supply 
1560 1570 1580 #Naval Infantry
1160  1170  1180  1190 1200 1210 1220 1230 #Mountain
1830 1840 1850 1860 #Engineers

#Industrial
5700 5710 5010 5020 #Mechanized Agriculture
5810 5050 5830 5060 5070 #Basic Machine Tools 
5800 5080 5090 #Improved Construction Engineering 
5310 54010 54020 54030 5316 5326 5327 #Computers and cryptografi
5190 #Refining
5470 #Faculty of Atomic Research 
5600 5610 5620 5630 #Medicine
5560 #Exp. Rocket

#Naval
12100 12110 12120 #Improved Light carrier 
3720 3730 3736 3740 3750 3900 #Torpedo & ASW 18
3010 3020 3030 3040 3050 3060 #Improved Destroyer 
3110 3120 3130 3140 3150 3160 #Interwar Light Cruiser 
3210 3220 3230 3240 3250 3260 #Improved Heavy Cruiser 
3310 3320 3330 #Heavy Battlecruiser
3410 3420 3430 3440 3450 3456 3460 3470 #Early Battleship 
3510 3520 3530 #Fleet Carrier 
3610 3620 3630 3640 3650 #Short Range Submarine 
3810 5820 #Troopships





# WWI Land Doctrines - Entente: eng fra ita usa bel hol jap 
6500 6510  6530 6540 6580 6600 6610 6620 6630 6640 6650 6660 6670 6680 6910
# WWII Land Doctrines - Firepower Focus
6010 6020
14000 14010 14020 #Great War Hospital System 

#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9140

# Engagement Theories
8010 8020 8030 8040 8050 8060 8070 8080
# Naval Supremacy
8100 8110 8120 8150 8160 8200
# Naval Interdiction
8500 8510 8550 8600
# Engagement Tactics - Fleet-in-Being colum
8900 8910 8920 8930 8940 8950
# Subsidiary Carrier Role
81650
# Carrier - Scouting Focus
81850
# Logistic Support
82500  
# Amphibious Warfare
82300


	}

#########  OOB (14800)
	landunit = {
		location = 1809
		name = "1st US Army Corps"
        	id = { type = 14800 id = 3 }
		division = {  id = { type = 14800 id = 4 } name = "1st 'Big Red One' Division" model = 8 type = infantry extra = artillery brigade_model = 4 }
		}

	landunit = {
		location = 1889
		name = "2nd US Army Corps"
        	id = { type = 14800 id = 5 }
		division = {  id = { type = 14800 id = 6 } name = "2nd 'Indianhead' Division" model = 8	type = infantry	}
		}

	landunit = {
		location = 1908
		name = "3rd US Army Corps"
        	id = { type = 14800 id = 7 }
		division = {  id = { type = 14800 id = 8 } name = "3rd 'Rock of the Roanoke' Division"	model = 8 type = infantry	}
		}

	landunit = {
		location = 1903
		name = "United States Cavalry"
        	id = { type = 14800 id = 9 }
		division = {  id = { type = 14800 id = 10 } name = "1st Cavalry 'The 1st Team' Div."	model = 9 type = cavalry	}
		}





		airunit = {
		location = 1795
		base = 1795
        	id = { type = 14800 id = 13 }
		name = "1st USAAF Fighter Wing"
			division = {  id = { type = 14800 id = 14 } name = "6th USAAF Fighter Wing"	type = interceptor model = 7 }
			}

		airunit = {
		location = 1795
		base = 1795
        	id = { type = 14800 id = 15 }
		name = "2nd USAAF Bombardment Group"
			division = {
			id = { type = 14800 id = 16 }
			name = "2nd USAAF Strategic Bomb. Wing"
			type = strategic_bomber
			model = 3
			}
			}


		airunit = {
		location = 1887
		base = 1887
        	id = { type = 14800 id = 17 }
		name = "1st USAAF Bombardment Wing"
			division = {
			id = { type = 14800 id = 18 }
			name = "1st USAAF Dive Bomb. Wing"
			type = tactical_bomber
			model = 4
			}
			}



		airunit = {
		location = 1874
		base = 1874
        	id = { type = 14800 id = 19 }
		name = "5th USAAF Bombardment Wing"
			division = {
			id = { type = 14800 id = 20 }
			name = "5th USAAF Tactical Bomb. Wing"
			type = tactical_bomber
			model = 4
			}
			}


		airunit = {
		location = 1953
		base = 1953
        	id = { type = 14800 id = 21 }
		name = "7th USAAF Bombardment Wing"

			division = {
			id = { type = 14800 id = 22 }
			name = "1st USAAF Tactical Bomb. Wing"
			type = tactical_bomber
			model = 4
			}
			}

	airunit = {
	location = 1809
	base = 1809
        id = { type = 14800 id = 23 }
	name = "US Army Airforce"

			division = {
			id = { type = 14800 id = 24 }
			name = "9th USAAF Fighter Wing"
			type = interceptor
			model = 7
			}

			division = {
			id = { type = 14800 id = 25 }
			name = "2nd USAAF Tactical Bomb. Wing"
			type = tactical_bomber
			model = 4
			}
			}





#US PACIFIC FLEET-SAN DIEGO, CALIFORNIA
 #
 #Battleship Division 1
 #Nevada, Arizona, Pennsylvania, Constellation
     navalunit = {
         name = "USN Battleship Fleet 1"
         id = { type = 14800 id = 26 }
         location = 1886
         base = 1886
         division = {    id = { type = 14800 id = 28 }     name = "USS Nevada"    type = battleship model = 4 }
         division = {    id = { type = 14800 id = 29 }     name = "USS Arizona"    type = battleship model = 4 }
         division = {    id = { type = 14800 id = 30 }     name = "USS Pennsylvania"    type = battleship model = 4 }
         division = {    id = { type = 14800 id = 1018 } name = "USS Constellation"    type = battlecruiser model = 2 }
     }
 #
 #Battleship Division 2
 #Oklahoma, Tennessee, California, Constitution
     navalunit = {
         name = "USN Battleship Fleet 2"
         id = { type = 14800 id = 31 }
         location = 1812
         base = 1812
         division = {    id = { type = 14800 id = 33 }     name = "USS Oklahoma"    type = battleship model = 4 }
         division = {    id = { type = 14800 id = 34 }     name = "USS Tennessee"    type = battleship model = 5 }
         division = {    id = { type = 14800 id = 35 }     name = "USS California"    type = battleship model = 5 }
         division = {    id = { type = 14800 id = 1019 } name = "USS Constitution"    type = battlecruiser model = 2 }
     }

 #
 #Battleship Division 3
 #New Mexico, Mississippi, Idaho, Arkansas, Wyoming, New York, Texas
     navalunit = {
         name = "USN Battleship Fleet 3"
         id = { type = 14800 id = 1000 }
         location = 1886
         base = 1886
         division = {    id = { type = 14800 id = 1002 }     name = "USS New Mexico"    type = battleship model = 4 }
         division = {    id = { type = 14800 id = 1003 }     name = "USS Mississippi"    type = battleship model = 4 }
         division = {    id = { type = 14800 id = 1004 }     name = "USS Idaho"    type = battleship model = 4 }
         division = {    id = { type = 14800 id = 1005 }     name = "USS Arkansas"    type = battleship model = 2 }
         division = {    id = { type = 14800 id = 1006 }     name = "USS Wyoming"    type = battleship model = 2 }
         division = {    id = { type = 14800 id = 1007 }     name = "USS New York"    type = battleship model = 3 }
         division = {    id = { type = 14800 id = 1008 }     name = "USS Texas"    type = battleship model = 3 }
     }

 #
 #Battleship Division 4
 #Colorado, Maryland, Washington, West Virginia, Florida
     navalunit = {
         name = "USN Battleship Fleet 4"
         id = { type = 14800 id = 1009 }
         location = 1812
         base = 1812
         division = {    id = { type = 14800 id = 1011 }     name = "USS Colorado"    type = battleship model = 6 }
         division = {    id = { type = 14800 id = 1012 }     name = "USS Maryland"    type = battleship model = 6 }
         division = {    id = { type = 14800 id = 1013 }     name = "USS Washington"    type = battleship model = 6 }
         division = {    id = { type = 14800 id = 1014 }     name = "USS West Virginia"    type = battleship model = 6 }
         division = {    id = { type = 14800 id = 1017 }     name = "USS Florida"    type = battleship model = 2 }
     }

 #
 #Cruiser Division 3
 #New Orleans, Astoria, Minneapolis, Richmond, Trenton, Concord, Raleigh, Detroit
     navalunit = {
         name = "USN Cruiser Fleet 3"
         id = { type = 14800 id = 40 }
         location = 1886
         base = 1886
         division = {    id = { type = 14800 id = 1026 } name = "USS New Orleans"    type = heavy_cruiser model = 4 }
         division = {    id = { type = 14800 id = 1027 } name = "USS Astoria"        type = heavy_cruiser model = 4 }
         division = {    id = { type = 14800 id = 1028 } name = "USS Minneapolis"    type = heavy_cruiser model = 4 }
         division = {    id = { type = 14800 id = 41 }     name = "USS Richmond"    type = light_cruiser model = 3 }
         division = {    id = { type = 14800 id = 42 }     name = "USS Trenton"    type = light_cruiser model = 3 }
         division = {    id = { type = 14800 id = 43 }     name = "USS Concord"    type = light_cruiser model = 3 }
             division = {      id = { type = 14800 id = 44 }       name = "USS Raleigh"    type = light_cruiser model = 3 }
             division = {      id = { type = 14800 id = 45 }       name = "USS Detroit"    type = light_cruiser model = 3 }
         }

 #Cruiser Division 4
 #Pensacola, Salt Lake City, Chicago, San Francisco, Indianapolis
     navalunit = {
         name = "USN Cruiser Fleet 4"
         id = { type = 14800 id = 46 }
         location = 1886
         base = 1886
         division = {    id = { type = 14800 id = 47 }     name = "USS Pensacola"        type = heavy_cruiser model = 3 }
         division = {    id = { type = 14800 id = 48 }     name = "USS Salt Lake City"    type = heavy_cruiser model = 3 }
         division = {    id = { type = 14800 id = 49 }     name = "USS Chicago"        type = heavy_cruiser model = 3 }
         division = {    id = { type = 14800 id = 1029 } name = "USS San Francisco"    type = heavy_cruiser model = 4 }
         division = {    id = { type = 14800 id = 50 }     name = "USS Indianapolis"    type = heavy_cruiser model = 3 }
         division = {    id = { type = 14800 id = 1054 } name = "Destroyer Division 20"    type = destroyer model = 4 }
         division = {    id = { type = 14800 id = 1055 } name = "Destroyer Division 22"    type = destroyer model = 4 }
         division = {    id = { type = 14800 id = 1056 } name = "Destroyer Division 24"    type = destroyer model = 5 }
         division = {    id = { type = 14800 id = 1057 } name = "Destroyer Division 26"    type = destroyer model = 5 }
     }
 #
 #Cruiser Division 6
 #Northampton, Chester, Louisville, Portland
     navalunit = {
         name = "USN Cruiser Fleet 6"
         id = { type = 14800 id = 1020 }
         location = 1886
         base = 1886
         division = {    id = { type = 14800 id = 1021 } name = "USS Northampton"    type = heavy_cruiser model = 3 }
         division = {    id = { type = 14800 id = 1022 } name = "USS Chester"        type = heavy_cruiser model = 3 }
         division = {    id = { type = 14800 id = 1023 } name = "USS Louisville"        type = heavy_cruiser model = 3 }
         division = {    id = { type = 14800 id = 1024 } name = "USS Portland"        type = heavy_cruiser model = 3 }
         division = {    id = { type = 14800 id = 1051 } name = "Destroyer Division 21"    type = destroyer model = 5 }
         division = {    id = { type = 14800 id = 1052 } name = "Destroyer Division 23"    type = destroyer model = 5 }
         division = {    id = { type = 14800 id = 1053 } name = "Destroyer Division 25"    type = destroyer model = 4 }
     }
 #
 #Carrier Division 1
 #Lexington, Saratoga, Langley
     navalunit = {
         name = "USN Carrier Fleet 1"
         id = { type = 14800 id = 1025 }
         location = 1886
         base = 1886
         division = {     id = { type = 14800 id = 27 }   name = "USS Lexington"  type = carrier model = 0 extra = CAG brigade_model = 2 }
         division = {     id = { type = 14800 id = 32 }   name = "USS Saratoga"   type = carrier model = 0 extra = CAG brigade_model = 2 }
         division = {     id = { type = 14800 id = 1010 } name = "USS Langley"    type = escort_carrier model = 1 }
         division = {    id = { type = 14800 id = 1049 } name = "Destroyer Division 18"    type = destroyer model = 5 }
         division = {    id = { type = 14800 id = 1050 } name = "Destroyer Division 19"    type = destroyer model = 5 }
         }
 #
 #
     navalunit = {
         name = "Pacific Destroyer Fleet"
         id = { type = 14800 id = 61 }
         location = 1886
         base = 1886
         division = {    id = { type = 14800 id = 62 }     name = "Destroyer Division 1"    type = destroyer model = 4 }
         division = {    id = { type = 14800 id = 63 }     name = "Destroyer Division 2"    type = destroyer model = 4 }
         division = {    id = { type = 14800 id = 64 }     name = "Destroyer Division 3"    type = destroyer model = 4 }
         division = {    id = { type = 14800 id = 1039 } name = "Destroyer Division 4"    type = destroyer model = 3 }
         division = {    id = { type = 14800 id = 1040 } name = "Destroyer Division 5"    type = destroyer model = 3 }
         division = {    id = { type = 14800 id = 1041 } name = "Destroyer Division 6"    type = destroyer model = 4 }
         }

     navalunit = {
         name = "Atlantic Destroyer Fleet"
         id = { type = 14800 id = 1042 }
         location = 1812
         base = 1812
         division = {    id = { type = 14800 id = 1043 } name = "Destroyer Division 7"    type = destroyer model = 3 }
         division = {    id = { type = 14800 id = 1044 } name = "Destroyer Division 8"    type = destroyer model = 3 }
         division = {    id = { type = 14800 id = 1045 } name = "Destroyer Division 9"    type = destroyer model = 3 }
         division = {    id = { type = 14800 id = 1046 } name = "Destroyer Division 10"    type = destroyer model = 4 }
         division = {    id = { type = 14800 id = 1047 } name = "Destroyer Division 11"    type = destroyer model = 4 }
         division = {    id = { type = 14800 id = 1048 } name = "Destroyer Division 12"    type = destroyer model = 4 }
         }
 #
 #
     navalunit = {
         name = "Pacific Submarine Fleet"
         id = { type = 14800 id = 74 }
         location = 1886
         base = 1886
         division = {    id = { type = 14800 id = 75 }     name = "Submarine Division 1"    type = submarine model = 1 }
         division = {    id = { type = 14800 id = 76 }     name = "Submarine Division 2"    type = submarine model = 1 }
         division = {    id = { type = 14800 id = 77 }     name = "Submarine Division 3"    type = submarine model = 1 }
         division = {    id = { type = 14800 id = 78 }     name = "Submarine Division 4"    type = submarine model = 1 }
         division = {    id = { type = 14800 id = 79 }     name = "Submarine Division 5"    type = submarine model = 1 }
         division = {     id = { type = 14800 id = 80 }     name = "Submarine Division 6"      type = submarine model = 1 }
         }

     navalunit = {
         name = "USN Seattle Fleet"
         id = { type = 14800 id = 1030 }
         location = 1874
         base = 1874
         division = {    id = { type = 14800 id = 1031 } name = "USS Houston"        type = heavy_cruiser model = 3 }
         division = {    id = { type = 14800 id = 1032 } name = "USS Marblehead"        type = light_cruiser model = 3 }
         division = {     id = { type = 14800 id = 1033 } name = "Destroyer Division 16"     type = destroyer model = 3 } #
         division = {     id = { type = 14800 id = 1034 } name = "Destroyer Division 43"     type = destroyer model = 3 } #
         division = {     id = { type = 14800 id = 1035 } name = "Destroyer Division 47"     type = destroyer model = 3 } #
         }

     navalunit = { location = 1874 base = 1874 id = { type = 14800 id = 1036 } name = "3rd USN Submarine Fleet"
         division = {     id = { type = 14800 id = 1037 } name = "Submarine Division 10" type = submarine model = 3 } #
         }

     navalunit = { location = 1734 base = 1734 id = { type = 14800 id = 81 } name = "Asiatic Fleet"
         division = {     id = { type = 14800 id = 82 }     name = "Destroyer Division 13"     type = destroyer model = 3 } #
         division = {     id = { type = 14800 id = 83 }     name = "Destroyer Division 14"     type = destroyer model = 3 } #
         division = {     id = { type = 14800 id = 84 }     name = "Destroyer Division 15"     type = destroyer model = 3 } #
         division = {     id = { type = 14800 id = 179 }     name = "Destroyer Division 31"     type = destroyer model = 3 } #
         division = {     id = { type = 14800 id = 180 }     name = "Destroyer Division 32"     type = destroyer model = 3 } #
         division = {     id = { type = 14800 id = 85 }     name = "Submarine Division 7"     type = submarine model = 1 } #
         division = {     id = { type = 14800 id = 86 }     name = "Submarine Division 8"     type = submarine model = 1 } #
         }

     navalunit = { location = 1734 base = 1734 id = { type = 14800 id = 87 } name = "2nd USN Submarine Fleet"
         division = {     id = { type = 14800 id = 88 }     name = "Submarine Division 9"     type = submarine model = 1 } #
         }


     navalunit = { location = 889 base = 889  id = { type = 14800 id = 95 } name = "USN Carribean Fleet"
         division = {     id = { type = 14800 id = 96 }     name = "Destroyer Division 17"     type = destroyer model = 3 } #
         division = {     id = { type = 14800 id = 97 }     name = "Submarine Division 11"     type = submarine model = 1 } #
         division = {     id = { type = 14800 id = 190 }     name = "Destroyer Division 41"     type = destroyer model = 3 } #
         division = {     id = { type = 14800 id = 191 }     name = "Destroyer Division 42"     type = destroyer model = 3 } #
         }


     navalunit = { location = 1812 base = 1812  id = { type = 14800 id = 106 } name = "USN Cruiser Fleet 2"
         division = {    id = { type = 14800 id = 1038 } name = "USS Augusta"        type = heavy_cruiser model = 3 }
         division = {     id = { type = 14800 id = 107 }     name = "USS Omaha"         type = light_cruiser model = 3 } #
         division = {     id = { type = 14800 id = 108 }     name = "USS Milwaukee"         type = light_cruiser model = 3 } #
         division = {     id = { type = 14800 id = 109 }     name = "USS Cincinnati"     type = light_cruiser model = 3 } #
         division = {     id = { type = 14800 id = 110 }     name = "USS Memphis"         type = light_cruiser model = 3 } #
         }

     navalunit = { location = 1812  base = 1812 id = { type = 14800 id = 133 } name = "Atlantic Transport Fleet"
         division = {     id = { type = 14800 id = 134 }     name = "Abner Doubleday Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 135 }    name = "Brigham Young Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 136 }     name = "William B. Travis Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 137 }     name = "Peter Stuyvesant Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 138 }     name = "Henry L. Benning Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 139 }     name = "Casimir Pulaski Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 140 }     name = "Sam Houston Flotilla"         type = transport model = 1 }
         division = {     id = { type = 14800 id = 141 }     name = "Francis Scott Key Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 142 }     name = "Walter Reed Flotilla"         type = transport model = 1 }
         division = {     id = { type = 14800 id = 143 }     name = "Dolly Madison Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 144 }     name = "Frederick Douglass Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 145 }     name = "Clara Barton Flotilla"         type = transport model = 1 }
         }

     navalunit = { location = 1886 base = 1886 id = { type = 14800 id = 146 } name = "Pacific Transport Fleet"
         division = {     id = { type = 14800 id = 147 }     name = "Charles Goodyear Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 148 }    name = "Anthony Wayne Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 149 }     name = "John Hancock Flotilla"         type = transport model = 1 }
         division = {     id = { type = 14800 id = 150 }     name = "Samuel Dexter Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 151 }     name = "Stephen C. Crane Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 152 }     name = "William McKinley Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 153 }     name = "George A. Custer Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 154 }     name = "August Belmont Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 156 }     name = "Emily Dickinson Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 157 }     name = "Molly Pitcher Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 158 }     name = "Antonin Dvorak Flotilla"     type = transport model = 1 }
         division = {     id = { type = 14800 id = 159 }     name = "J. E. B. Stuart Flotilla"     type = transport model = 1 }
         }		 
	
    division_development = {  
        name  = "USS Ranger" 
        type  = carrier 
        model = 2 
        cost  = 3.2
	    id = { type = 14800 id = 500 }
	    date = { year = 1936 month = september day = 29 }
        extra = cag 
        brigade_model = 2 
        new_model = no
    }	

landunit = {
	id = { type = 14800 id = 160 }
	name = "Panama Canal Force"
	location = 889

	division = {
		id = { type = 14800 id = 161 }
		name = "Panama Canal Garrison"
		type = garrison
		model = 4
		locked = yes
		extra = artillery
		}
	}


}  