#
#
# Province Setup
#
#


#victory points..
province = {	id = 0	points = 20 }#


###############################################
# Germany
###############################################



province = { id = 163 points = 30 } #Berlin
province = { id = 154 points = 5   } #Hamburg
province = { id = 152 points = 5   } #Kiel
province = { id = 171 points = 5   } #Erfurt
province = { id = 145 points = 25  } #Essen
province = { id = 177 points = 5  } #Nürnberg
province = { id = 146 points = 5   } #Hannover
province = { id = 173 points = 5  } #Dresden
province = { id = 131 points = 10  } #Köln
province = { id = 170 points = 5  } #Leipzig
province = { id = 134 points = 5  } #Stuttgart
province = { id = 179 points = 10 } #München

province = {	id = 718	points = 5  }#Casablanca
province = {	id = 1399	points = 5	}#Saigon
province = {	id = 1395	points = 5  }#Hanoi
province = {	id = 900	points = 5	}#Suez
province = {	id = 348	points = 2	}#Gibraltar
province = {	id = 429	points = 1	}#Malta
province = {	id = 1432	points = 5	}#Singapore
province = {	id = 1328	points = 1	}# german Tsingtau
#province = { id = 1726 points = 1 } #Rabaul
#province = { id = 1587 points = 1 } #Bougainville


###############################################
# Union of Britain
###############################################

province = {	id = 29		points = 30	}#London
province = {	id = 15		points = 10	}#Newcastle
province = {	id = 24		points = 10	}#Birgmingham
province = {	id = 12		points = 15	}#Edinburgh
province = {	id = 19  	points = 5	}#Bistrol
province = {	id = 22 	points = 5	}#Cardiff
province = {	id = 17  	points = 5	}#Liverpool
province = {	id = 11		points = 5	}#Glasgow


province = {	id = 36		points = 5	}#Belfast
province = {	id = 787	points = 2      }#Cairo
province = {	id = 789	points = 5	}#Alexandria
province = {	id = 791	points = 5	}#Port Said
province = {	id = 1433	points = 2      }#Kota Baharu
province = {	id = 1371	points = 2	}#Hongkong
province = {	id = 1438	points = 1      }#Kualu Lumpur


###############################################
# Commune of France
###############################################
province = {	id = 55		points = 25	}#Paris
province = {	id = 74	        points = 5	}#Vichy
province = {	id = 107	points = 2	}#Strassbourg
province = {	id = 105	points = 7	}#Colmar
province = {	id = 89 	points = 10	}#Marseilles
province = {	id = 68 	points = 15	}#Bordeaux
province = {	id = 77 	points = 10	}#Toulouse
province = {	id = 44		points = 5	}#Caen
province = {	id = 50		points = 5	}#Amiens
province = {	id = 66		points = 5	}#Orleans
province = {	id = 37	        points = 10	}#Brest
province = {	id = 39	        points = 10	}#Lorient
province = {	id = 100	points = 10	}#Verdun
province = {	id = 85 	points = 10	}#Lyon


province = {	id = 915	points = 2      }#Libreville
province = {	id = 1016	points = 5	}#Damascus








###############################################
# Nationalist France
###############################################
province = {	id = 727	points = 10	}#Algiers
province = {	id = 747	points = 5	}#Tunis
province = {	id = 978	points = 10	}#Dakar
province = {	id = 728	points = 1	}#Oran
province = {	id = 962	points = 5	}#Abidjan
province = {	id = 957	points = 1	}#Ougadadougou
province = {	id = 732	points = 2	}#Djeffa
province = {	id = 735	points = 2	}#Bone
province = {	id = 742	points = 2	}#Medenine
province = {	id = 966	points = 1	}#Conakry


###############################################
# India
###############################################

province = {	id = 1517	points = 7	}#Bombay
province = {	id = 1447	points = 7	}#Calcutta
province = {	id = 1459	points = 7	}#Delhi
province = {	id = 1485	points = 1	}#Nagpur
province = {	id = 1504	points = 1	}#Madurai
province = {	id = 1487	points = 7	}#Hyderabad
province = {	id = 1442	points = 1	}#Imphal
province = {	id = 1533	points = 3	}#Karachi
province = {	id = 1530	points = 1	}#Lahore
province = {	id = 1540	points = 2	}#Srinagar



###############################################
# Italy
###############################################
province = {	id = 419	points = 15	}#Roma
province = {	id = 407	points = 7	}#Milano
province = {	id = 400	points = 7	}#Venezia
province = {	id = 396	points = 7	}#Genoa
province = {	id = 421	points = 6 }#Napoli
province = {	id = 430	points = 5 }#Palermo
province = {	id = 411	points = 5 }#Bologna
province = {	id = 422	points = 5 }#Tarento
province = {	id = 750	points = 3 }#Tripoli
province = {    id = 765        points = 1 }
province = {    id = 761        points = 3 }#Benghazi & Tobruk: North Africa hardly had VP



###############################################
# Russia
###############################################
province = {	id = 572	points = 10	}#Moscow
province = {	id = 553	points = 10	}#Leningrad
province = {	id = 663	points = 10	}#Stalingrad
province = {	id = 713	points = 5	}#Baku
province = {	id = 1191	points = 10	}#Vladivostok
province = {	id = 542	points = 5	}#Archangelsk
province = {	id = 693	points = 2	}#Maikop
province = {	id = 644	points = 2	}#Rostov
province = {	id = 641	points = 2	}#Sevestapol
province = {	id = 626	points = 2	}#Odessa
province = {	id = 636	points = 2	}#Kharkov
province = {	id = 617	points = 5	}#Kiev
province = {	id = 599	points = 5	}# Minsk
province = {	id = 589	points = 5	}#Smolensk
province = {	id = 590	points = 2	}#Vitebsk
province = {	id = 569	points = 2	}#Kalinin
province = {	id = 579	points = 2	}#Kaluga
province = {	id = 1162	points = 3	}#Irkutsk
province = {	id = 1151	points = 3	}#Sverdlovsk
province = {	id = 668	points = 1	}#Kujbysjev
province = {	id = 1103	points = 1	}#Tashkent
province = {	id = 504	points = 1	}#Alma-Ata
province = {	id = 1138	points = 1	}#Omsk
province = {	id = 1142	points = 1	}#Novosibirsk
province = {	id = 1186	points = 1	}#Okhotsk
province = {	id = 1179	points = 1	}#Yakutsk
province = {	id = 711	points = 2	}#Yerevan


###############################################
# USA
###############################################

province = {	id = 1809	points = 10	}#Washington
province = {	id = 1874	points = 1	}#Seattle
province = {	id = 1878	points = 1	}#Portland
province = {	id = 1872	points = 1	}#Spokane
province = {	id = 1889	points = 5	}#San Fransisco
province = {	id = 1888	points = 10	}#Sacramento
province = {	id = 1887	points = 1	}#Los Angeles
province = {	id = 1886	points = 1	}#San Diego
province = {	id = 1900	points = 1	}#Phoenix
province = {	id = 1904	points = 1	}#Albuquerque
province = {	id = 1908	points = 10	}#Denver
province = {	id = 1896	points = 1	}#Salt Lake City
province = {	id = 1856	points = 1	}#Bismarck
province = {	id = 1858	points = 1	}#Rapid City
province = {	id = 1860	points = 1	}#Omaha
province = {	id = 1914	points = 1	}#Kansas City
province = {	id = 1912	points = 1	}#Tulsa
province = {	id = 1924	points = 1	}#Dallas
province = {	id = 1926	points = 1	}#San Antonio
province = {	id = 1928	points = 1	}#Houston
province = {	id = 1931	points = 5	}#New Orleans
province = {	id = 1918	points = 1	}#Little Rock
province = {	id = 1836	points = 1	}#Springfield, MI
province = {	id = 1833	points = 5	}#St.Louis
province = {	id = 1838	points = 1	}#Des Moines
province = {	id = 1847	points = 1	}#Minneapolis
province = {	id = 1839	points = 1	}#Milwaukee
province = {	id = 1832	points = 10	}#Chicago
province = {	id = 1828	points = 1	}#Indianapolis
province = {	id = 1845	points = 5	}#Detroit
province = {	id = 1825	points = 1	}#Cleveland
province = {	id = 1819	points = 1	}#Louisville
province = {	id = 1934	points = 1	}#Nashville
province = {	id = 1925	points = 1	}#Jackson
province = {	id = 1944	points = 1	}#Mobile
province = {	id = 1953	points = 1	}#Miami
province = {	id = 1955	points = 10	}#Atlanta
province = {	id = 1957	points = 1	}#Columbia
province = {	id = 1962	points = 1	}#Charlotte
province = {	id = 1960	points = 1	}#Charleston
province = {	id = 1812	points = 1	}#Norfolk
province = {	id = 1805	points = 5	}#Philadelphia
province = {	id = 1806	points = 1	}#Pittsburgh
province = {	id = 1795	points = 10	}#New York
province = {	id = 1791	points = 1	}#Buffalo
province = {	id = 1789	points = 5	}#Boston
province = {	id = 1787	points = 1	}#Concord
province = {	id = 1907	points = 1	}#Cheyenne






###############################################
# Canada
###############################################

province = {	id = 2119	points = 5	}#Montreal
province = {	id = 2108	points = 20	}#Ottawa
province = {	id = 2106	points = 5	}#Winnipeg
province = {	id = 2111	points = 10	}#Toronto
province = {	id = 2089	points = 10	}#Vancouver
province = {	id = 2117	points = 5	}#Quebec 
province = {	id = 2132	points = 15	}#Halifax




###############################################
# Japan
###############################################

province = {	id = 1552	points = 10	}#Tokyo
province = {	id = 1557	points = 10	}#Nagoya
province = {	id = 1553	points = 10	}#Osaka
province = {	id = 1554	points = 10	}#Hiroshima
province = {	id = 1545	points = 2	}#Sapporo
province = {	id = 1547	points = 5	}#Akita
province = {	id = 1549	points = 5	}#Sendai
province = {	id = 1550	points = 5	}#Yokohama
province = {	id = 1551	points = 5	}#Niigata
province = {	id = 1556	points = 5	}#Kanazawa
province = {	id = 1559	points = 5	}#Matsuyama
province = {	id = 1558	points = 5	}#Kagashima
province = {	id = 1663	points = 1	}#Motoyama
province = {	id = 1542	points = 1	}#Toyohare
province = {	id = 1563	points = 5	}#Southern Okinawa
province = {	id = 1564	points = 5	}#Northern Okinawa



###############################################
# China
###############################################
province = {	id = 1337	points = 3	}#Nanjing
province = {	id = 1338	points = 2	}#Shanghai
province = {	id = 1247	points = 5	}#Beijing
province = {	id = 1241	points = 1	}#Tianjin
province = {	id = 1239	points = 1	}#Jining
province = {	id = 1243	points = 1	}#Baoding
province = {	id = 1340	points = 1	}#Hefei
province = {	id = 1322	points = 1	}#Luoyang
province = {	id = 1325	points = 1	}#Nanyang
province = {	id = 1318	points = 1	}#Huangshi
province = {	id = 1344	points = 1	}#Anquing
province = {	id = 1345	points = 1	}#Hangzhou
province = {	id = 1354	points = 1	}#Ganzhou
province = {	id = 1317	points = 1	}#Wuchan
province = {	id = 1312	points = 1	}#Hengyang
province = {	id = 1307	points = 1	}#Huaihua
province = {	id = 1254	points = 1	}#Hequ
province = {	id = 1299	points = 3	}#Chongqing
province = {	id = 1305	points = 1	}#Guiyang
province = {	id = 1263	points = 1	}#Tianshui
province = {	id = 1293	points = 1	}#Panzhihua
province = {	id = 1297	points = 1	}#Chengdu
province = {	id = 1303	points = 1	}#Anshun
province = {	id = 1390	points = 3	}#Kunming
province = {	id = 1292	points = 1	}#Ya'an

#Shanxi (CSX)
province = {	id = 1270	points = 1	}#Linhe

#Tibet
province = {	id = 1289	points = 2 }#Lhasa

#Mongolia
province = {	id = 1124	points = 1 }#Urga

#Manchuko
province = {	id = 1236	points = 2 }#Chengde
province = {	id = 1199	points = 4 }#Harbin
province = {	id = 1208	points = 2 }#Changchun



###############################################
# Central Europe
###############################################

#Hungary
province = {	id = 284	points = 2 }#Budapest
province = {	id = 277	points = 2 }#Pecs
province = {	id = 281	points = 1 }#Debrecen

#Bulgaria
province = {	id = 321	points = 1 }#Sofia
province = {	id = 324	points = 1 }#Plovdiv
province = {	id = 326	points = 1 }#Varna

#Greece
province = {	id = 377	points = 1 }#Athinai
province = {	id = 365	points = 1 }#Thessaloniki

#Czechoslovakia
province = { 	id = 207	points = 6 }#Prague
province = {    id = 199        points = 1 }#Plzen 
province = { 	id = 208	points = 4 }#Bratislava
province = { 	id = 209	points = 2 }#Kosice

#Schweiz
province = {	id = 392	points = 1 }#Bern
province = {	id = 389	points = 1 }#Zürich


#Austria
province = {	id = 195	points = 6 }#Vienna
province = {	id = 192	points = 2 }#Salzburg
province = {	id = 189	points = 2 }#Innsbruck
province = {	id = 190	points = 2 }#Graz


#Poland
province = {	id = 232	points = 4 }#Warsaw
province = {	id = 181	points = 2 }#Danzig
province = {	id = 223	points = 2 }#Lodz
province = {	id = 235	points = 2 }#Krakow
province = {	id = 242	points = 2 }#Lvov
province = {	id = 255	points = 2 }#Grodno


#Romania
province = {	id = 316	points = 4 }#Bucharest
province = {	id = 311	points = 2 }#Ploesti
province = {	id = 288	points = 2 }#Cluj-Napoca


#Albania
province = {	id = 359	points = 2 }#Tirane

#Yugoslavia
province = {	id = 338	points = 4 }#Belgrade
province = {	id = 352	points = 1 }#Zagreb
province = {	id = 349	points = 1 }#Ljubljana
province = {	id = 333	points = 1 }#Skopje
province = {	id = 355	points = 1 }#Sarajevo



################################
# Scandinavia
################################

#Sweden
province = { id = 2159 points = 4 }#Stockholm 
province = { id = 2153 points = 2 }#Göteborg
province = { id = 2152 points = 1 }#Malmö 
province = { id = 2161 points = 1 }#Karlstadt
province = { id = 2164 points = 1 }#Umea


#Denmark#
province = { id = 294 points = 1 }#Kopenhavn
province = { id = 220 points = 1 }#Aarhus
province = { id = 219 points = 1 }#Odense

#Norway#
province = { id = 483 points = 5 }#Oslo
province = { id = 495 points = 5 }#Narvik
province = { id = 493 points = 5 }#Trondheim

#Finland
province = { id = 525 points = 3 }#Helsinki
province = { id = 531 points = 1 }#Vipuri
province = { id = 524 points = 1 }#Turku
province = { id = 521 points = 1 }#Vaasa
province = { id = 517 points = 1 }#Petsamo
province = { id = 527 points = 1 }#Tampere

#Estonia
province = { id = 270 points = 2 }#Tallinn

#Latvia
province = { id = 264 points = 2 }#Riga

#Lithuania
province = { id = 258 points = 2 }#Vilnius


###############################################
# Western Europe
###############################################

#Netherlands
province = { id = 122 points = 5 }#Amsterdam
province = { id = 119 points = 5 }#Arnhem
province = { id = 1636 points = 2 }#Palembang
province = { id = 1647 points = 3 }#Batavia
province = { id = 1641 points = 2 }#Oosthaven
province = { id = 1642 points = 2 }#Medan
province = { id = 1632 points = 2 }#Balikpapan 
province = { id = 1596 points = 2 }#Hollandia

#Belgium
province = { id = 116 points = 3 }#Bruxelles
province = { id = 115 points = 2 }#Antwerpen
province = { id = 108 points = 1 }#Liege
province = { id = 898 points = 1 }#Leopoldville
province = { id = 899 points = 1 }#Elisabethville

#Spain
province = { id = 460 points = 3 }#Madrid
province = { id = 473 points = 0 }#Cadiz
province = { id = 464 points = 2 }#Valencia
province = { id = 440 points = 2 }#Barcelona
province = { id = 471 points = 1 }#Malaga
province = { id = 441 points = 1 }#Coruna
province = { id = 451 points = 1 }#Burgos
province = { id = 474 points = 1 }#Sevilla
province = { id = 442 points = 1 }#Zaragoza

#Portugal
province = { id = 476 points = 3 }#Lissabon
province = { id = 481 points = 2 }#Porto
province = { id = 895 points = 1 }#Luanda
province = { id = 1372 points = 1 }#Macao
province = { id = 855 points = 1 }#Lourenco Marques
province = { id = 2261 points = 1 }#Cap Verde


#Luxemburg
province = { id = 109 points = 1 }#Luxemburg

#Ireland
province = { id = 34 points = 2 }#Dublin

###############################################
# Middle East
###############################################


#Turkey
province = {	id = 409	points = 3 }#Istanbul
province = {	id = 1076	points = 1 }#Izmir
province = {	id = 1077	points = 1 }#Izmit
province = {	id = 1075	points = 2 }#Ankara
province = {	id = 1067	points = 1 }#Trebizon
province = {	id = 1056	points = 1 }#Gaziantep
province = {	id = 1063	points = 1 }#Erzurum
province = {	id = 1064	points = 1 }#Elazig

#Persia
province = {	id = 1085	points = 2 }#Teheran
province = {	id = 1089	points = 1 }#Ahvaz
province = {	id = 1088	points = 1 }#Shiraz
province = {	id = 1086	points = 1 }#Esfahan
province = {	id = 1091	points = 1 }#Gameroon
province = {	id = 1083	points = 1 }#Tabriz

#Iraq
province = {	id = 1034	points = 3 }#Bagdad
province = {	id = 1029	points = 2 }#Mosul
province = {	id = 1032	points = 1 }#Basra



###############################################
# Arabia
###############################################

#Oman
province = {	id = 1052	points = 2 }#Muscat


#Saudi Arabia
province = {	id = 1045	points = 1 }#Riyadh

#Palestine
province = {	id = 1012	points = 1 }#Jerusalem



###############################################
# Africa
###############################################
#Ethiopia
province = { id = 825 points = 2 }#Addis Abeba
province = { id = 827 points = 1 }#Gode
province = { id = 836 points = 1 }#Mogadishu
#Liberia
province = { id = 969 points = 1 }#Monorovia


#South africa
province = { id = 880 points = 3 }#Capetown
province = { id = 876 points = 3 }#Johannesburg
province = { id = 881 points = 2 }#Port Elizabeth
province = { id = 872 points = 2 }#Durban

#Mittelafrica
province = { id = 850 points = 10 }#Daresalam
province = { id = 841 points = 2  }#Nairobi
province = { id = 929 points = 2  }#Lagos
province = { id = 911 points = 2  }#Douala



###############################################
# Far East
###############################################

#Afghanistan
province = { id = 2171 points = 1 } #Kabul
province = { id = 2172 points = 1 } #Herat

#Siam
province = { id = 1423 points = 3 } #Bangkok
province = { id = 1426 points = 1 } #Phitsanulok
province = { id = 1431 points = 1 } #Songhla

#Philippines

province = { id = 1565 points = 3 } #Manila
province = { id = 1569 points = 1 } #Olongapo
province = { id = 1567 points = 1 } #Baguio
province = { id = 1571 points = 1 } #Mindoro
province = { id = 1573 points = 1 } #Leyte
province = { id = 1578 points = 1 } #Cagayan
province = { id = 1579 points = 1 } #Davao

#Australia

province = { id = 1707 points = 2 } #Canberra
province = { id = 1705 points = 3 } #Sydney
province = { id = 1704 points = 2 } #Brisbane
province = { id = 1690 points = 1 } #Perth
province = { id = 1708 points = 2 } #Melbourne
province = { id = 1697 points = 2 } #Darwin
province = { id = 1712 points = 1 } #Adelaide
province = { id = 1703 points = 1 } #Newcastle
province = { id = 1699 points = 1 } #Townsville

#Australian Colonies

province = { id = 1607 points = 2 } #Port Moresby

#New Zealand
province = { id = 1721 points = 1 } #Wellington
province = { id = 1720 points = 2 } #Auckland
province = { id = 1722 points = 1 } #Christchurch

#Burma

province = { id = 1415 points = 2 } #Rangoon
province = { id = 1410 points = 1 } #Manta LE

#The Pacific

#province = { id = 1661 points = 1 } #Iwo Jima
#province = { id = 1683 points = 2 } #Guam
#province = { id = 1680 points = 2 } #Tarawa
#province = { id = 1685 points = 2 } #Saipan
#province = { id = 1670 points = 1 } #Palau
#province = { id = 1669 points = 1 } #Yap
#province = { id = 1667 points = 2 } #Truk
#province = { id = 1590 points = 2 } #Guadalcanal
#province = { id = 1586 points = 1 } #Noumea
#province = { id = 1728 points = 1 } #Fiji
#province = { id = 1682 points = 1 } #Nauru
#province = { id = 1676 points = 1 } #Kwajalein
#province = { id = 1675 points = 1 } #Eniwetok
#province = { id = 1673 points = 1 } #Wake Island
#province = { id = 1739 points = 1 } #Midway Island
#province = { id = 2150 points = 1 } #Unalaska Island

###############################################
# Americas
###############################################
#Uruguay
province = { id = 2052 points = 1 }#Montevideo

#Paraguay
province = { id = 2047 points = 1 }#Asunción

#Argentine
province = { id = 2050 points = 6 }#Buenos Aires
province = { id = 2053 points = 2 }#Mar del Plata
province = { id = 2049 points = 2 }#Corrientes
province = { id = 2054 points = 2 }#Córdoba
province = { id = 2027 points = 1 }#San Miguel de Tucumán

#Chile
province = { id = 2023 points = 4 }#Santiago
province = { id = 2025 points = 2 }#Antofagasta

#Peru
province = { id = 2016 points = 2 }#Lima
province = { id = 2017 points = 2 }#Arequipa

#Brazil
province = { id = 2075 points = 3 }#Rio de Janeiro
province = { id = 2071 points = 2 }#Recife
province = { id = 2073 points = 2 }#Salvador
province = { id = 2068 points = 2 }#Belém
province = { id = 2074 points = 2 }#Vitória
province = { id = 2059 points = 2 }#São Paulo
province = { id = 2057 points = 2 }#Curitiba
province = { id = 2067 points = 2 }#Goiás

#Bolivia
province = { id = 2020 points = 2 }#La Paz

#Ecuador
province = { id = 2042 points = 2 }#Quito

#Venezuela
province = { id = 1993 points = 2 }#Caracas
province = { id = 1988 points = 2 }#Maracaibo

#Colombia
province = { id = 1991 points = 2 }#Bogotá
province = { id = 1990 points = 2 }#Cascuta
province = { id = 1985 points = 2 }#Cali

#Panama
province = { id = 2078 points = 1 }#Panama
province = { id = 889 points = 5 }#Colon (Channel Zone)

#Costa Rica
province = { id = 2081 points = 1 }#San José

#Nicaragua
province = { id = 2080 points = 1 }#Managua

#Honduras
province = { id = 2085 points = 1 }#Tegucigalpa

#El Salvador
province = { id = 2079 points = 1 }#San Salvado

#Guatemala
province = { id = 2088 points = 1 }#Guatemala

#Port au Prince
province = { id = 1781 points = 1 }#Port-au-Prince

#Santo Domingo
province = { id = 1780 points = 1 }#Santo Domingo

#Cuba
province = { id = 1776 points = 2 }#La Habana

#Mexico
province = { id = 1977 points = 2 }#Ciudad de Juarez
province = { id = 1968 points = 1 }#Veracruz
province = { id = 1980 points = 1 }#Culican
province = { id = 1975 points = 1 }#Monterrey
province = { id = 1972 points = 1 }#Acapulco

#WIF/Caribbean Federation
province = { id = 1782 points = 1 }#Jamaica, oh I want to take ya
province = { id = 1733 points = 1 }#Beruda, Bahama, come on pretty mama
province = { id = 1997 points = 2 }#Georgetown
province = { id = 2000 points = 1 }#Culican




province = { id = 1252 points = 2 }
province = { id = 1330 points = 1 } #(Shanxi: had too few VP) 
province = { id = 1378 points = 1 }
province = { id = 1277 points = 1 }# (Xibei San Ma: had no VP)

province = { id = 2030 points = 1 }
province = { id = 2023 points = 2 } #more evenly distributed Chile
province = { id = 1456 points = 1 } #Bhutan: had no VP
province = { id = 1457 points = 1 } #Nepal: had no VP



province = { id = 443 points = 2 }
province = { id = 451 points = 1 }
province = { id = 1982 points = 1 } 
province = { id = 436 points = 1 }
province = { id = 463 points = 1 } 

province = {	id =  327 	points =  1   } 
province = {	id =  330 	points =  1   } 
province = {	id =  372 	points =  1   } 
province = {	id =  310 	points =  1   } 
province = {	id =  315 	points =  1   } 
province = {	id =  306 	points =  1   } 
province = {	id =  196 	points =  1   } 

province = {	id =  247 	points = 1 } 
province = {	id =  244 	points = 1 } 
province = {	id =  590 	points = 1 } 
province = {	id =  594 	points = 1 } 
province = {	id =  251 	points = 1 } 
province = {	id =  600 	points = 1 } 
province = {	id =  706 	points = 1 } 
province = {	id =  702 	points = 1 } 
province = {	id =  694 	points = 1 } 


####add warlord vps
province = { id = 1381 points = 1 }
province = { id = 1380 points = 1 }
province = { id = 1259 points = 1 }
province = { id = 1321 points = 1 }
province = { id = 1284 points = 1 }
province = { id = 1281 points = 1 }

#Korean VP

province = { id = 1228 points = 1 }
province = { id = 1221 points = 1 }
province = { id = 1232 points = 1 }
province = { id = 1222 points = 1 }

#Extra Egyptian VP

province = { id = 810 points = 1 } #Khartoum

province = { id = 350 points = 1 }
province = { id = 1405 points = 1 }
province = { id = 1361 points = 1 }
province = { id = 1362 points = 1 }
province = { id = 1363 points = 1 }
province = { id = 353 points = 1 }
province = { id = 1190 points = 1 }


province = { id = 1369 points = 1 }
province = { id = 1049 points = 1 }
province = { id = 854 points = 1 }


province = { id = 1838 points = 2} 
province = { id = 1581 points = 2 } 
province = { id = 1550 points = 2 } 
province = { id = 1586  points = 1 } 
