
###############################
# Victory points distribution #
###############################

province = { id = 0 points = 20 } # (Embarked)
province = { id = 11 points = 5 } # Glasgow
province = { id = 12 points = 15 } # Edinburgh
province = { id = 15 points = 10 } # Hull
province = { id = 17 points = 5 } # Manchester
province = { id = 19 points = 5 } # Bristol
province = { id = 22 points = 5 } # Cardiff
province = { id = 24 points = 10 } # Birmingham
province = { id = 29 points = 30 } # London
province = { id = 34 points = 2 } # Dublin
province = { id = 36 points = 5 } # Belfast
province = { id = 37 points = 10 } # Brest
province = { id = 39 points = 10 } # Lorient
province = { id = 44 points = 5 } # Caen
province = { id = 50 points = 5 } # Amiens
province = { id = 55 points = 25 } # Paris
province = { id = 66 points = 5 } # Orleans
province = { id = 68 points = 15 } # Bordeaux
province = { id = 74 points = 5 } # Vichy
province = { id = 77 points = 10 } # Toulouse
province = { id = 85 points = 10 } # Lyon
province = { id = 89 points = 10 } # Marseille
province = { id = 100 points = 10 } # Verdun
province = { id = 105 points = 7 } # Colmar
province = { id = 107 points = 2 } # Strasbourg
province = { id = 108 points = 1 } # Liege
province = { id = 109 points = 1 } # Luxembourg
province = { id = 115 points = 2 } # Antwerpen
province = { id = 116 points = 3 } # Brussels
province = { id = 119 points = 5 } # Arnhem
province = { id = 122 points = 5 } # Amsterdam
province = { id = 131 points = 10 } # Cologne
province = { id = 134 points = 5 } # Stuttgart
province = { id = 145 points = 25 } # Essen
province = { id = 146 points = 5 } # Hannover
province = { id = 152 points = 5 } # Kiel
province = { id = 154 points = 5 } # Hamburg
province = { id = 163 points = 30 } # Berlin
province = { id = 170 points = 5 } # Leipzig
province = { id = 171 points = 5 } # Erfurt
province = { id = 173 points = 5 } # Dresden
province = { id = 177 points = 5 } # Nuremberg
province = { id = 179 points = 10 } # Munich
province = { id = 181 points = 2 } # Danzig
province = { id = 189 points = 2 } # Innsbruck
province = { id = 190 points = 2 } # Graz
province = { id = 192 points = 2 } # Salzburg
province = { id = 195 points = 6 } # Vienna
province = { id = 196 points = 1 } # Brno
province = { id = 199 points = 1 } # Plzen
province = { id = 207 points = 6 } # Prague
province = { id = 208 points = 4 } # Pressburg
province = { id = 209 points = 2 } # Kosice
province = { id = 219 points = 1 } # Odense
province = { id = 220 points = 1 } # Arhus
province = { id = 223 points = 2 } # Lodz
province = { id = 232 points = 4 } # Warsaw
province = { id = 235 points = 2 } # Krakow
province = { id = 242 points = 2 } # Lwow
province = { id = 244 points = 1 } # Rowne
province = { id = 247 points = 1 } # Brest-Litovsk
province = { id = 251 points = 1 } # Nowogrodek
province = { id = 255 points = 2 } # Grodno
province = { id = 258 points = 2 } # Wilno
province = { id = 264 points = 2 } # Riga
province = { id = 270 points = 2 } # Tallinn
province = { id = 277 points = 2 } # Pecs
province = { id = 281 points = 1 } # Debrecen
province = { id = 284 points = 2 } # Budapest
province = { id = 288 points = 2 } # Cluj
province = { id = 294 points = 1 } # Copenhagen
province = { id = 306 points = 1 } # Ismail
province = { id = 310 points = 1 } # Constantza
province = { id = 311 points = 2 } # Ploesti
province = { id = 315 points = 1 } # Craiova
province = { id = 316 points = 4 } # Bucharest
province = { id = 321 points = 1 } # Sofia
province = { id = 324 points = 1 } # Plovdiv
province = { id = 326 points = 1 } # Varna
province = { id = 327 points = 1 } # Krusevac
province = { id = 330 points = 1 } # Nis
province = { id = 333 points = 1 } # Skopje
province = { id = 338 points = 4 } # Belgrade
province = { id = 348 points = 2 } # Gibraltar
province = { id = 349 points = 1 } # Ljubljana
province = { id = 350 points = 1 } # Split
province = { id = 352 points = 1 } # Zagreb
province = { id = 353 points = 1 } # Banja Luka
province = { id = 355 points = 1 } # Sarajevo
province = { id = 359 points = 2 } # Tirana
province = { id = 365 points = 1 } # Thessaloniki
province = { id = 372 points = 1 } # Patra
province = { id = 377 points = 1 } # Athens
province = { id = 389 points = 1 } # Zurich
province = { id = 392 points = 1 } # Bern
province = { id = 396 points = 7 } # Genoa
province = { id = 400 points = 7 } # Venice
province = { id = 407 points = 7 } # Milan
province = { id = 409 points = 3 } # Istanbul
province = { id = 411 points = 5 } # Bologna
province = { id = 419 points = 15 } # Rome
province = { id = 421 points = 6 } # Naples
province = { id = 422 points = 5 } # Taranto
province = { id = 429 points = 1 } # Malta
province = { id = 430 points = 5 } # Palermo
province = { id = 436 points = 1 } # Tarragona
province = { id = 440 points = 2 } # Barcelona
province = { id = 441 points = 1 } # Coruna
province = { id = 442 points = 1 } # Zaragoza
province = { id = 443 points = 2 } # Bilbao
province = { id = 451 points = 1 } # Burgos
province = { id = 460 points = 3 } # Madrid
province = { id = 463 points = 1 } # Murcia
province = { id = 464 points = 2 } # Valencia
province = { id = 471 points = 1 } # Malaga
province = { id = 474 points = 1 } # Sevilla
province = { id = 476 points = 3 } # Lisbon
province = { id = 481 points = 2 } # Porto
province = { id = 483 points = 5 } # Oslo
province = { id = 493 points = 5 } # Trondheim
province = { id = 495 points = 5 } # Narvik
province = { id = 504 points = 1 } # Alma-Ata
province = { id = 517 points = 1 } # Petsamo
province = { id = 521 points = 1 } # Vaasa
province = { id = 524 points = 1 } # Turku
province = { id = 525 points = 3 } # Helsinki
province = { id = 527 points = 1 } # Tampere
province = { id = 531 points = 1 } # Viipuri
province = { id = 542 points = 5 } # Arkhangelsk
province = { id = 553 points = 10 } # Petrograd
province = { id = 569 points = 2 } # Tver
province = { id = 572 points = 10 } # Moscow
province = { id = 579 points = 2 } # Ryazan
province = { id = 589 points = 5 } # Smolensk
province = { id = 590 points = 1 } # Vitebsk
province = { id = 594 points = 1 } # Bobruisk
province = { id = 599 points = 5 } # Minsk
province = { id = 600 points = 1 } # Mogilev
province = { id = 617 points = 5 } # Kiev
province = { id = 626 points = 2 } # Odessa
province = { id = 636 points = 2 } # Kharkov
province = { id = 641 points = 2 } # Sevastopol
province = { id = 644 points = 2 } # Rostov-on-Don
province = { id = 663 points = 10 } # Tsaritsyn
province = { id = 668 points = 1 } # Kuybyshev
province = { id = 693 points = 2 } # Maykop
province = { id = 694 points = 1 } # Novorossiysk
province = { id = 702 points = 1 } # Grozny
province = { id = 706 points = 1 } # Astrakhan
province = { id = 708 points = 1 } # Kutaisi
province = { id = 709 points = 2 } # Tbilisi
province = { id = 711 points = 2 } # Yerevan
province = { id = 713 points = 5 } # Baku
province = { id = 718 points = 5 } # Casablanca
province = { id = 727 points = 10 } # Algiers
province = { id = 728 points = 1 } # Oran
province = { id = 732 points = 2 } # Djelfa
province = { id = 735 points = 2 } # Bona
province = { id = 742 points = 2 } # Medenine
province = { id = 747 points = 5 } # Tunis
province = { id = 750 points = 3 } # Tripoli
province = { id = 761 points = 3 } # Benghazi
province = { id = 765 points = 1 } # Tobruk
province = { id = 787 points = 2 } # Cairo
province = { id = 789 points = 5 } # Alexandria
province = { id = 791 points = 5 } # Port Said
province = { id = 810 points = 1 } # Khartoum
province = { id = 825 points = 2 } # Addis Abeba
province = { id = 827 points = 1 } # Gode
province = { id = 836 points = 1 } # Mogadishu
province = { id = 841 points = 2 } # Nairobi
province = { id = 850 points = 10 } # Dar es Salaam
province = { id = 854 points = 1 } # Nampula
province = { id = 855 points = 1 } # Lourenco Marques
province = { id = 872 points = 2 } # Durban
province = { id = 876 points = 3 } # Johannesburg
province = { id = 880 points = 3 } # Cape Town
province = { id = 881 points = 2 } # Port Elizabeth
province = { id = 889 points = 5 } # Balboa
province = { id = 895 points = 1 } # Luanda
province = { id = 898 points = 1 } # Elisabethville
province = { id = 899 points = 1 } # Leopoldville
province = { id = 900 points = 5 } # Suez
province = { id = 911 points = 2 } # Douala
province = { id = 915 points = 2 } # Libreville
province = { id = 929 points = 2 } # Lagos
province = { id = 957 points = 1 } # Ouagadougou
province = { id = 962 points = 5 } # Abidjan
province = { id = 966 points = 1 } # Conakry
province = { id = 969 points = 1 } # Monrovia
province = { id = 978 points = 10 } # Dakar
province = { id = 1012 points = 1 } # free
province = { id = 1016 points = 5 } # Damascus
province = { id = 1029 points = 2 } # Mosul
province = { id = 1032 points = 1 } # Basrah
province = { id = 1034 points = 3 } # Baghdad
province = { id = 1045 points = 1 } # Riyadh
province = { id = 1049 points = 1 } # Mecca
province = { id = 1052 points = 2 } # Masqat
province = { id = 1056 points = 1 } # Gaziantep
province = { id = 1063 points = 1 } # Erzurum
province = { id = 1064 points = 1 } # Elazig
province = { id = 1067 points = 1 } # Trabzon
province = { id = 1075 points = 2 } # Ankara
province = { id = 1076 points = 1 } # Izmit
province = { id = 1077 points = 1 } # Smyrna
province = { id = 1083 points = 1 } # Tabriz
province = { id = 1085 points = 2 } # Teheran
province = { id = 1086 points = 1 } # Esfahan
province = { id = 1088 points = 1 } # Shiraz
province = { id = 1089 points = 1 } # Ahvaz
province = { id = 1091 points = 1 } # Gameroon
province = { id = 1103 points = 1 } # Tashkent
province = { id = 1124 points = 1 } # Urga
province = { id = 1138 points = 1 } # Omsk
province = { id = 1142 points = 1 } # Novosibirsk
province = { id = 1151 points = 3 } # Sverdlovsk
province = { id = 1162 points = 3 } # Irkutsk
province = { id = 1179 points = 1 } # Yakutsk
province = { id = 1186 points = 1 } # Okhotsk
province = { id = 1190 points = 1 } # Khabarovsk
province = { id = 1191 points = 10 } # Vladivostok
province = { id = 1199 points = 4 } # Harbin
province = { id = 1208 points = 2 } # Changchun
province = { id = 1221 points = 1 } # Pyeongyang
province = { id = 1222 points = 1 } # Sariwon
province = { id = 1228 points = 1 } # Seoul
province = { id = 1232 points = 1 } # Busan
province = { id = 1236 points = 2 } # Chengde
province = { id = 1239 points = 1 } # Jining
province = { id = 1241 points = 1 } # Tianjin
province = { id = 1243 points = 1 } # Baoding
province = { id = 1247 points = 5 } # Beijing
province = { id = 1252 points = 2 } # Taiyuan
province = { id = 1254 points = 1 } # Hequ
province = { id = 1259 points = 1 } # Yan'an
province = { id = 1263 points = 1 } # Tianshoui
province = { id = 1270 points = 1 } # Linhe
province = { id = 1277 points = 1 } # Qumul
province = { id = 1281 points = 1 } # Urumqi
province = { id = 1284 points = 1 } # Xining
province = { id = 1289 points = 2 } # Lhasa
province = { id = 1292 points = 1 } # Ya'an
province = { id = 1293 points = 1 } # Panzhihua
province = { id = 1297 points = 1 } # Chengdu
province = { id = 1299 points = 3 } # Chongqing
province = { id = 1303 points = 1 } # Anshun
province = { id = 1305 points = 1 } # Guiyang
province = { id = 1307 points = 1 } # Huaihua
province = { id = 1312 points = 1 } # Hengyang
province = { id = 1317 points = 1 } # Wuhan
province = { id = 1318 points = 1 } # Huangshi
province = { id = 1321 points = 1 } # Xinxiang
province = { id = 1322 points = 1 } # Luoyang
province = { id = 1325 points = 1 } # Nanyang
province = { id = 1328 points = 1 } # Qingdao
province = { id = 1330 points = 1 } # Jinan
province = { id = 1337 points = 3 } # Nanjing
province = { id = 1338 points = 2 } # Shanghai
province = { id = 1340 points = 1 } # Hefei
province = { id = 1344 points = 1 } # Anqing
province = { id = 1345 points = 1 } # Hangzhou
province = { id = 1354 points = 1 } # Ganzhou
province = { id = 1361 points = 1 } # Gaoxiong
province = { id = 1362 points = 1 } # Taipei
province = { id = 1363 points = 1 } # Taizhong
province = { id = 1369 points = 1 } # Guangzhou
province = { id = 1371 points = 2 } # Hong Kong
province = { id = 1378 points = 1 } # Guilin
province = { id = 1380 points = 1 } # Liuzhou
province = { id = 1381 points = 1 } # Bose
province = { id = 1390 points = 3 } # Kunming
province = { id = 1395 points = 5 } # Hanoi
province = { id = 1399 points = 5 } # Saigon
province = { id = 1405 points = 1 } # Vientiane
province = { id = 1410 points = 1 } # Mandalay
province = { id = 1415 points = 2 } # Rangoon
province = { id = 1423 points = 3 } # Bangkok
province = { id = 1426 points = 1 } # Phitsanulok
province = { id = 1431 points = 1 } # Songhla
province = { id = 1432 points = 5 } # Singapore
province = { id = 1433 points = 2 } # Kota Bahru
province = { id = 1438 points = 1 } # Kuala Lumpur
province = { id = 1442 points = 1 } # Imphal
province = { id = 1447 points = 7 } # Calcutta
province = { id = 1456 points = 1 } # Punakha
province = { id = 1457 points = 1 } # Kathmandu
province = { id = 1459 points = 7 } # Delhi
province = { id = 1485 points = 1 } # Nagpur
province = { id = 1487 points = 7 } # Hyderabad
province = { id = 1504 points = 1 } # Madurai
province = { id = 1517 points = 7 } # Bombay
province = { id = 1530 points = 1 } # Lahore
province = { id = 1533 points = 3 } # Karachi
province = { id = 1540 points = 2 } # Srinagar
province = { id = 1542 points = 1 } # Toyohara
province = { id = 1545 points = 2 } # Sapporo
province = { id = 1547 points = 5 } # Akita
province = { id = 1549 points = 5 } # Sendai
province = { id = 1550 points = 2 } # Yokohama
province = { id = 1551 points = 5 } # Niigata
province = { id = 1552 points = 10 } # Tokyo
province = { id = 1553 points = 10 } # Osaka
province = { id = 1554 points = 10 } # Hiroshima
province = { id = 1556 points = 5 } # Kanazawa
province = { id = 1557 points = 10 } # Nagoya
province = { id = 1558 points = 5 } # Kyoto
province = { id = 1559 points = 5 } # Matsuyama
province = { id = 1563 points = 5 } # Southern Okinawa
province = { id = 1564 points = 5 } # Northern Okinawa
province = { id = 1565 points = 3 } # Manila
province = { id = 1567 points = 1 } # Baguio
province = { id = 1569 points = 1 } # Olongapo
province = { id = 1571 points = 1 } # Mindoro
province = { id = 1573 points = 1 } # Leyte
province = { id = 1578 points = 1 } # Cagayan de Oro
province = { id = 1579 points = 1 } # Davao
province = { id = 1581 points = 2 } # Efate
province = { id = 1586 points = 1 } # Nouvelle-Caledonie
province = { id = 1596 points = 2 } # Hollandia
province = { id = 1607 points = 2 } # Port Moresby
province = { id = 1632 points = 2 } # Balikpapan
province = { id = 1636 points = 2 } # Palembang
province = { id = 1641 points = 2 } # Oosthaven
province = { id = 1642 points = 2 } # Medan
province = { id = 1647 points = 3 } # Batavia
province = { id = 1663 points = 1 } # Motoyama
province = { id = 1690 points = 1 } # Perth
province = { id = 1697 points = 2 } # Darwin
province = { id = 1699 points = 1 } # Townsville
province = { id = 1703 points = 1 } # Newcastle
province = { id = 1704 points = 2 } # Brisbane
province = { id = 1705 points = 3 } # Sydney
province = { id = 1707 points = 2 } # Canberra
province = { id = 1708 points = 2 } # Melbourne
province = { id = 1712 points = 1 } # Adelaide
province = { id = 1720 points = 2 } # Auckland
province = { id = 1721 points = 1 } # Wellington
province = { id = 1722 points = 1 } # Christchurch
province = { id = 1773 points = 1 } # The Bermudas
province = { id = 1776 points = 2 } # Havana
province = { id = 1780 points = 1 } # Ciudad Trujillo
province = { id = 1781 points = 1 } # Port-au-Prince
province = { id = 1782 points = 1 } # Jamaica
province = { id = 1787 points = 1 } # Concord
province = { id = 1789 points = 5 } # Boston
province = { id = 1791 points = 1 } # Buffalo
province = { id = 1795 points = 10 } # New York
province = { id = 1805 points = 5 } # Philadelphia
province = { id = 1806 points = 1 } # Pittsburgh
province = { id = 1809 points = 10 } # Washington
province = { id = 1812 points = 1 } # Norfolk
province = { id = 1819 points = 1 } # Louisville
province = { id = 1825 points = 1 } # Cleveland
province = { id = 1828 points = 1 } # Indianapolis
province = { id = 1832 points = 10 } # Chicago
province = { id = 1833 points = 5 } # Saint Louis
province = { id = 1836 points = 1 } # Springfield
province = { id = 1838 points = 2 } # Des Moines
province = { id = 1839 points = 1 } # Milwaukee
province = { id = 1845 points = 5 } # Detroit
province = { id = 1847 points = 1 } # Minneapolis
province = { id = 1856 points = 1 } # Bismarck
province = { id = 1858 points = 1 } # Rapid City
province = { id = 1860 points = 1 } # Omaha
province = { id = 1872 points = 1 } # Spokane
province = { id = 1874 points = 1 } # Seattle
province = { id = 1878 points = 1 } # Portland
province = { id = 1886 points = 1 } # San Diego
province = { id = 1887 points = 1 } # Los Angeles
province = { id = 1888 points = 10 } # Sacramento
province = { id = 1889 points = 5 } # San Francisco
province = { id = 1896 points = 1 } # Salt Lake City
province = { id = 1900 points = 1 } # Phoenix
province = { id = 1904 points = 1 } # Albuquerque
province = { id = 1907 points = 1 } # Cheyenne
province = { id = 1908 points = 10 } # Denver
province = { id = 1912 points = 1 } # Tulsa
province = { id = 1914 points = 1 } # Kansas City
province = { id = 1918 points = 1 } # Little Rock
province = { id = 1924 points = 1 } # Dallas
province = { id = 1925 points = 1 } # Austin
province = { id = 1926 points = 1 } # San Antonio
province = { id = 1928 points = 1 } # Houston
province = { id = 1931 points = 5 } # New Orleans
province = { id = 1934 points = 1 } # Lafayette
province = { id = 1944 points = 1 } # Mobile
province = { id = 1953 points = 1 } # Miami
province = { id = 1955 points = 10 } # Atlanta
province = { id = 1957 points = 1 } # Columbia
province = { id = 1960 points = 1 } # Charleston
province = { id = 1962 points = 1 } # Charlotte
province = { id = 1968 points = 1 } # Veracruz
province = { id = 1972 points = 1 } # Acapulco de Juarez
province = { id = 1974 points = 5 } # Mexico City
province = { id = 1975 points = 1 } # Monterrey
province = { id = 1977 points = 2 } # Ciudad Juarez
province = { id = 1980 points = 1 } # Culiacan Rosales
province = { id = 1982 points = 1 } # Guadalajara
province = { id = 1985 points = 2 } # Cali
province = { id = 1988 points = 2 } # Maracaibo
province = { id = 1990 points = 2 } # Cucuta
province = { id = 1991 points = 2 } # Santa Fe de Bogota
province = { id = 1993 points = 2 } # Caracas
province = { id = 1997 points = 2 } # Georgetown
province = { id = 2000 points = 1 } # Cayenne
province = { id = 2016 points = 2 } # Lima
province = { id = 2017 points = 2 } # Arequipa
province = { id = 2020 points = 2 } # Nuestra Senora de La Paz
province = { id = 2023 points = 2 } # Santiago de Chile
province = { id = 2025 points = 2 } # Antofagasta
province = { id = 2027 points = 1 } # San Miguel de Tucuman
province = { id = 2030 points = 1 } # Punta Arenas
province = { id = 2042 points = 2 } # San Francisco de Quito
province = { id = 2047 points = 1 } # Nuestra Senora de la Asuncion
province = { id = 2049 points = 2 } # Corrientes
province = { id = 2050 points = 6 } # Buenos Aires
province = { id = 2052 points = 1 } # Montevideo
province = { id = 2053 points = 2 } # Mar del Plata
province = { id = 2054 points = 2 } # Cordoba
province = { id = 2057 points = 2 } # Curitiba
province = { id = 2059 points = 2 } # Sao Paulo
province = { id = 2067 points = 2 } # Goiania
province = { id = 2068 points = 2 } # Belem
province = { id = 2071 points = 2 } # Recife
province = { id = 2073 points = 2 } # Salvador
province = { id = 2074 points = 2 } # Vitoria
province = { id = 2075 points = 3 } # Rio de Janeiro
province = { id = 2078 points = 1 } # Ciudad de Panama
province = { id = 2079 points = 1 } # San Salvador
province = { id = 2080 points = 1 } # Managua
province = { id = 2081 points = 1 } # San Jose
province = { id = 2085 points = 1 } # Tegucigalpa
province = { id = 2088 points = 1 } # Ciudad de Guatemala
province = { id = 2089 points = 10 } # Vancouver
province = { id = 2106 points = 5 } # Winnipeg
province = { id = 2108 points = 20 } # Ottawa
province = { id = 2111 points = 10 } # Toronto
province = { id = 2117 points = 5 } # Quebec
province = { id = 2119 points = 5 } # Montreal
province = { id = 2132 points = 15 } # Halifax
province = { id = 2152 points = 1 } # Malmo
province = { id = 2153 points = 2 } # Gothenburg
province = { id = 2159 points = 4 } # Stockholm
province = { id = 2161 points = 1 } # Karlstad
province = { id = 2164 points = 1 } # Oestersund
province = { id = 2171 points = 1 } # Kabul
province = { id = 2172 points = 1 } # Herat
province = { id = 2261 points = 1 } # Cape Verde Islands 
