  #.#.#   United Kingdom 

province = { 
	id = 34 #Dublin
	supplypool = 2
}

 province = { id = 36   # Belfast - Northern Ireland
   naval_base = { size = 5 current_size = 5 }
 }
 
 province = { id = 5   #  Scapa Flow - North Scotland - Scotland
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 13   #  Sunderland - North England - England
   ic = -3 } 
 
 province = { id = 17   #  Manchester - North England - England
   naval_base = { size = 8 current_size = 8 } 
   ic = -5 
 } 
 
 province = { id = 18   #  Sheffield - North England - England
   ic = -10 } 
 province = { id = 22   #  Cardiff - West England - England
   ic = -8 } 
 
 province = { id = 23   #  Plymouth - West England - England
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 24   #  Birmingham - West England - England
   ic = -4 } 
 
 province = { id = 25   #  Norwich - East England - England
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 26   #  Dover - East England - England
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 3 
 } 
 
 province = { id = 27   #  Portsmouth - East England - England
   naval_base = { size = 10 current_size = 10 } 
   coastalfort = 2
 } 
 
 province = { id = 29   #  London - East England - England
   air_base = { size = 2 current_size = 2 } 
   ic = -10 
 } 