############################
#Victory points distribution
############################

province = { id = 29 points = 20 } #London
province = { id = 12 points = 10 } #Edinburgh
province = { id = 17 points = 10 } #Manchester
province = { id = 34 points = 10 } #Dublin
province = { id = 11 points = 5 } #Glasgow
province = { id = 13 points = 5 } #Sunderland
province = { id = 18 points = 5 } #Sheffield
province = { id = 22 points = 5 } #Cardiff
province = { id = 24 points = 5 } #Birmingham
province = { id = 7 points = 2 } #Aberdeen
province = { id = 19 points = 2 } #Bristol
province = { id = 23 points = 2 } #Plymouth
province = { id = 25 points = 2 } #Norwich
province = { id = 26 points = 2 } #Dover
province = { id = 36 points = 2 } #Belfast
province = { id = 5 points = 1 } #Scara Flow
province = { id = 15 points = 1 } #Hull
province = { id = 31 points = 1 } #Cork